#!/bin/sh
mountpoint="/mnt/gentoo"
# mount proc
[ ! -d "${mountpoint%/}/proc" ] && mkdir "${mountpoint%/}/proc"; done
mount --types proc proc "${mountpoint%/}/proc"
# bind-mount sys, dev, and run
for x in sys dev run; do
    [ ! -d "${mountpoint%/}/${x}" ] && mkdir "${mountpoint%/}/${x}"
    mount --rbind "/${x}" "${mountpoint%/}/${x}"
    mount --make-rslave "${mountpoint%/}/${x}"
done
# maybe mkdir /dev/shm
test -L /dev/shm && rm -f /dev/shm && mkdir /dev/shm
mount --types tmpfs --options nosuid,nodev,noexec shm /dev/shm
chmod 1777 /dev/shm
