#!/bin/bash
# collect-system-files_template.conf  joe brendler 8/22/2025
#

# verbosity - iaw RFC 5424 severity
[ -z $verbosity ] && verbosity=${notice}  # don't load unless null; allow calling program to set

# user - primary user of the app, who will need write privileges on logs, config files, and status files
user=joe

# logFile - generated each time the app runs, three copies rotated
#logFile="/var/log/${PN}.log"
logFile="/var/log/${PN}.log"

# confit_dir - files resident here and ending .conf (like THIS one) are sourced to override defaults
#config_dir="/etc/${PN}"

# status_file - holds an integer representing the NEXT step after the last successfully completed step
#   RESUME action is to read this file and set starting_step equal to this value (if it is in range)
#status_file="${HOME}/.config/${PN}.status"

#export QUIET=$FALSE
#export DEBUG=$FALSE

# interactive (supervised mode)
export INTERACTIVE=$TRUE
export LOGGING=$TRUE
[ -z "$loglevel" ] && export loglevel=5  # $notice

SOURCED_CONFIG=yes
varlist="${varlist} yn.SOURCED_CONFIG"

#sync_root - directory in which to create collection_directory e.g. "/home/${user}"
# (and to which it will be transferred on any remote host)
sync_root="/home/${user}"

# ssh key - (path to user's private key)
#SSH_KEY=""
SSH_KEY="/home/${user}/.ssh/id_ecdsa"

# collection_directory -- directory in /home/${user} into which we collect
collection_directory="content_for_mkimg_$(hostname)"

# remotehosts - array of hostnames to which to trasfer content
remotehosts=(
'yorsqui'
'nuthuvia'
'gmki92'
)

# source_dirs - directories the entire content of which we collect
source_dirs=(
'/etc/openvpn'
'/etc/sddm'
'/etc/sddm.conf.d'
"/home/${user}/.ssh"
)

# source_files - individual file names we collect (can contian wildcards)
source_files=(
'/etc/apache2/ssl/*.key'
'/etc/apache2/ssl/*.crt'
'/etc/apache2/ssl/*.pem'
'/etc/apache2/vhosts.d/00_default_ssl_vhost.conf'
'/etc/apache2/vhosts.d/00_default_vhost.conf'
'/etc/fstab'
'/etc/hostname'
'/etc/conf.d/hostname'
'/etc/conf.d/net'
'/etc/conf.d/modules'
'/etc/sddm.conf'
'/etc/conf.d/display-manager'
'/etc/wpa_supplicant/wpa_supplicant.conf'
'/root/.bash_profile'
"/home/${user}/.bashrc"
"/home/${user}/.bash_profile"
)

# note: don't collect root/.bashrc - it will overwrite the copy provided
# by the crossbuild-tools package, which is needed to trigger the
# execution of finalize-chroot scripts

# note: don't collect make.conf, package.use, or package.accept_keywords;
# these are now provided by joetoo-base/joetoo-platform-meta on a
# board-specific basis

