#!/bin/bash

#-----[ variables ]-------------------------------------
PN=$(basename $0)
CSI="\033["
BRon="${CSI}01;31m"
BGon="${CSI}01;32m"
BYon="${CSI}01;33m"
BBon="${CSI}01;34m"
BMon="${CSI}01;35m"
LBon="${CSI}01;36m"
BWon="${CSI}01;39m"
Won="${CSI}01;37m"
Boff="${CSI}00m"

#-----[ functions ]-------------------------------------
testcolors() {
    for x in ${BRon} ${BGon} ${BYon} ${BBon} ${BMon} ${LBon} ${BWon} ${Won}; do
        echo -e "${x}color ${Boff}"
    done
}

usage() {
    E_message "usage: ${PN} /path/to/imagefile"
    exit 1
}

E_message() {
    echo -e "${BRon}*${Boff} $@"
}

message() {
    echo -e "${BGon}*${Boff} $@"
}

message_n() {
    echo -e -n "${BGon}*${Boff} $@"
}

checkroot() {
    ROOT_UID=0
    if [ "$UID" -ne "$ROOT_UID" ] ; then
        E_message "user must be root but is not"
        exit 1
    else
        return 0
    fi
}

die() {
    E_message "$@"
    exit 1
}

#-----[ main script ]-----------------------------------
checkroot
message "completed checkroot and still running"
#testcolors

[ $# -ne 1 ] && E_message "Error: path to image file not specified" && usage
imagefile="$1"
message "imagefile: $imagefile"

img_loopdev=$(losetup --find --show --partscan ${imagefile})
message "img_loopdev: $img_loopdev"

#message "These loop devices are active"
#losetup -a
message "This loop device is active for your imagefile"
losetup -a | grep ${imagefile} | sed 's|^|  |'

message "This is imagefile's fdisk -l layout"
fdisk -l ${img_loopdev} | sed 's|^|  |'

message_n "checking mountpoint /mnt/armbian ..."
if [ ! -d /mnt/armbian ] ; then
    echo -en " (creating)"
    mkdir -p /mnt/armbian || die "failed to create mountpoint"
    echo -e " ${BGon}(OK)${Boff}"
else
    echo -e " (exists) ${BGon}(OK)${Boff}"
fi

message_n "counting partitions in image file"
dbn=$(basename ${img_loopdev})
echo -e -n " $dbn"
p_count=$(lsblk -n -o NAME $img_loopdev | grep -c "${dbn}p[0-9]")
echo -e " p_count: $p_count"

case $p_count in
    1 )
        message_n "mounting root partition ..."
        mount ${img_loopdev}p1 /mnt/armbian/ || die "failed to mount root partition"
        echo -e " ${BGon}(OK)${Boff}"
        ;;
    2 )
        message_n "mounting root partition ..."
        mount ${img_loopdev}p2 /mnt/armbian/ || die "failed to mount root partition"
        echo -e " ${BGon}(OK)${Boff}"
        message_n "mounting boot partition ..."
        mount ${img_loopdev}p1 /mnt/armbian/boot/ || die "failed to mount boot partition"
        echo -e " ${BGon}(OK)${Boff}"
        ;;
    * ) E_message "invalid partition count"; exit 1;;
esac

message "This is what I mounted"
mount | grep armbian | sed 's|^|  |'

echo -e "${BYon}Done${Boff}"
