#!/bin/bash
script_header_installed_dir=/usr/sbin/

u_echo() {      # in UTF-8 env, echo -e -n one or more unicode chars $@
LC_CTYPE=en_US.UTF-8 echo -e -n $@ ; }

emoji() {       # use u_echo() to display one unicode char $1
[ ! $# -eq 1 ] && die "one arg allowed/required"
u_echo "\U${1}" ; }

bremoji() {     # use emoji()/uecho() to display one unicode char $1 in brackets
[ ! $# -eq 1 ] && die "one arg allowed/required"
echo -n "["; emoji "${1}"; echo -n "]" ; }

bremojis() {    # use emoji()/uecho() to display chars $@ in brackets
echo -n "["; for each in $@; do emoji "${each}"; done; echo -n "]" ; }

bremojis2() {   # use emoji()/uecho() to display chars $@ in brackets
payload=""; echo -n "["; for each in $@; do payload+="\U${each}"; done;
u_echo ${payload}; echo -n "]" ; }

u_message() {   # use bremoji() and message() to prefix message() with unicode char $1
[ ! $# -ge 2 ] && die "usage: <unicodeprefix> <message>"
prefix=$1 ; shift ; bremoji $prefix ; message "$@" ; }

uE_message() {   # use bremojis() and E_message() to prefix message() with unicode char $1
[ ! $# -ge 2 ] && die "usage: <unicodeprefix> <error_message>"
prefix=$1 ; shift ; bremojis $prefix ; E_message "$@" ; }

uEx_message() {   # use bremojis() and E_message() to prefix message() with unicode explosion
[ ! $# -ge 1 ] && die "usage: <error_message>"
prefix=${explosion} ; bremojis ${prefix} ; E_message "$@" ; }

summarize_my_unicode() { # list and demo functions in header ("source" to employ)
grep --color=auto "()" ${script_header_installed_dir%/}/script_header_joetoo_unicode | \
    grep --color=auto -v "grep" | sed 's|^|  |'; 
# demonstrate u_message
echo ; message "running ${BGon}u_message ${BMon}"'${hammer}'"${Boff} hello, world"
u_message ${hammer} "hello, world"
# demonsgrate bremojis
echo; msg="running ${BGon} bremojis ${BMon}"' ${explosion} ${face_grimace}'
msg+=" ; ${BGon}E_message ${Boff}\"I think we have a problem here\""
message "${msg}"
bremojis ${explosion} ${face_grimace} ; E_message "I think we have a problem here"
# demonstrate uE_message
echo; msg="running ${BGon} uE_message ${BMon}\${cross_mark} ${Boff}\"testing uEx_error_message\""
message "${msg}"
uE_message ${cross_mark} "testing uE_error_message"
# demonstrate uEx_message
echo; msg="running ${BGon} uEx_message ${Boff}\"testing uEx_error_message\""
message "${msg}"
uEx_message "testing uEx_error_message"
# demonstrate emoji
echo; message "running ${BGon}emoji${Boff} '1F427' ; ${LBon}echo${Boff}"
emoji "1F427" ; echo
# demonsgrate u_echo
msg="running ${BGon}u_echo${Boff} \""
msg+='\U2550\U2550\U2550\U2550 \U${biohazard} \U${no_entry} \U2550\U2550\U2550\U2550'
msg+="\" ; ${LBon}echo${Boff}"
message "${msg}"
u_echo "\U2550\U2550\U2550\U2550 \U${biohazard} \U${no_entry} \U2550\U2550\U2550\U2550" ; echo
echo; message "${BYon}Run ${BGon}emoji_demo ${BYon}to see available unicode emoticons (emojis)${Boff}"
}

light="1F3FB"
mediumlight="1F3FC"
medium="1F3FD"
mediumdark="1F3FE"
dark="1F3FF"


bat="1F987"
penguin="1F427"
mouseface="1F42D"
mouse="1F401"

hand="270B"
hand_ok="1F44C"
thumb_up="1F44D"
thumb_down="1F44E"

face_grin="1F600"
face_beam="1F601"
face_hearts="1F970"
face_thinking="1F914"
face_grimace="1F62C"
face_rolleyes="1F644"
face_confused="1F615"
face_frown1="1F641"
face_frown2="2639"
face_tearsofjoy="1F602"
face_hearteyes="1F60D"
face_blowkiss="1F618"
face_cowboy="1F920"
face_sunglasses="1F60E"

heart_red="2764"
heart_pink="1FA77"
heart_orange="1F9E1"
heart_yellow="1F49B"
heart_green="1F49A"
heart_blue="1F499"
heart_lightblue="1FA75"
heart_purple="1F49C"
heart_brown="1F90E"
heart_black="1FA76"
heart_white="1F90D"

poopile="1F4A9"

kiss="1F48B"

explosion="1F4A5"
collision="1F4A5"
thought_balloon="1F4AD"

hammer="1F528"
axe="1FA93"
pickaxe="26CF"
hammer_and_pick="2692"
hammer_and_wrench="1F6E0"
bomb="1F4A3"
shield="1F6E1"
saw="1FA9A"
wrench="1F527"
screwdriver="1FA9B"
nut_and_bolt="1F529"
gear="2699"
hook="1FA9D"
toolbox="1F9F0"
magnet="1F9F2"
ladder="1FA9C"
shovel="1FA8F"

dna="1F9EC"
microscope="1F52C"
telescope="1F52D"
satellite_antenna="1F4E1"
broom="1F9F9"
basket="1F9FA"
bucket="1FAA3"
shopping_cart="1F6D2"

no_entry="26D4"
prohibited="1F6AB"
radioactive="2622"
biohazard="2623"

recycling="267B"
check_mark_button="2705"
cross_mark_button="274E"
check_mark="2714"
cross_mark="274C"
splatter="1FADF"

circle_red="1F534"
circle_orange="1F7E0"
circle_yellow="1F7E1"
circle_green="1F7E2"
circle_blue="1F535"
circle_purple="1F7E3"
circle_brown="1F7E4"
circle_black="26AB"
circle_white="26AA"

flag_chequered="1F3C1"
