#!/bin/sh

# contents are compatability wrappers for deprecated functions

# @note =====[ Section 0: Global Instructions ]===========================================

# @note =====[ Section 1: Global Variables  ]=============================================


#-----[ Select Graphics Rendition on/off ]------------------------------------------

LBLUE="36"       # foreground light blue (cyan)(deprecated - keep here for compatibility)

LBACK="46"       # background light blue (cyan)(deprecated - keep here for compatibility)

Lon="${CSI}${LBLUE}m"   # (deprecated - keep here for compatibility)

LBon="${CSI}${LBLUE};${BOLD}m"   # (deprecated - keep here for compatibility)



# @note =====[ Section 2: Terminal & Cursor Control Functions ]=====================================================

# @note =====[ Section 3: Core Validation Functions ]===============================================================

isnumber() # (deprecated - use isint() or isnumeric(); isnumber tests if $1 is an integer
{ legacy_wrapper_dispatch isnumber isnumeric "$@" ; }

# @note =====[ Section 4: String & Layout Utilities ]===============================================================


echo_n_long() # deprecated - use smart_wrap_n
{ W_message "${BYon}Warning:${Boff} echo_n_long is deprecated (use smart_wrap_n(), which has been upgraded)"
  [ ! $# -eq 3 ] && die "invalid arguments"
  # translate for compatibility - smartwrap also uses r_margin
  _enl_start_col="$1"; shift
  _ens_indent="$1"; shift
  _enl_msg="$@"
  smart_wrap_n "$_enl_start_col" "$_ens_indent" "" "$_enl_msg" ; }



# @note =====[ Section 5: Logic & Conversion ]======================================================================

# @note =====[ Section 6: Logging, Messaging, & UI ]==================================================================

#-----[ new generation info_msg era created in feb26 now already deprecated in feb26 ]------------------------------------------------------------------

_j_msg_compat_warn()
{ # help recently retired legacy msg functions transition to j_msg
  _jcw_legacy="$1"; _jcw_flags="$2"
#echo "warning: $warning"
  [ "$DEBUG" ] && j_msg "-$warning" "${BYon}Warning:${Boff} $_jcw_legacy is deprecated; use \"j_msg $_jcw_flags\""
  unset -v _jcw_legacy _jcw_flags
}
# @usage _j_msg_compat_warn <legacy_func_name> <replacement_flags>
# @args $1: name of the calling function
# @args $2: the flags that should be used instead (e.g. -6)

emerg_msg() { e_ret=0; _j_msg_compat_warn "emerg_msg" "-0"; j_msg -0 "$@"; e_ret=$?; return $e_ret ; }
alert_msg() { a_ret=0; _j_msg_compat_warn "alert_msg" "-1"; j_msg -1 "$@"; a_ret=$?; return $a_ret ; }
crit_msg() { c_ret=0; _j_msg_compat_warn "crit_msg" "-2"; j_msg -2 "$@"; c_ret=$?; return $c_ret ; }
error_msg() { er_ret=0; _j_msg_compat_warn "error_msg" "-3"; j_msg -3 "$@"; er_ret=$?; return $er_ret ; }
warn_msg() { w_ret=0; _j_msg_compat_warn "warn_msg" "-4"; j_msg -4 "$@"; w_ret=$?; return $w_ret ; }
notice_msg() { n_ret=0; _j_msg_compat_warn "notice_msg" "-5"; j_msg -5 "$@"; n_ret=$?; return $n_ret ; }
info_msg() { i_ret=0; _j_msg_compat_warn "notice_msg" "-6"; j_msg -6 "$@"; i_ret=$?; return $i_ret ; }
debug_msg() { d_ret=0; _j_msg_compat_warn "debug_msg" "-7"; j_msg -7 "$@"; d_ret=$?; return $d_ret ; }
echo_e_msg()   { eem_ret=0;  _j_msg_compat_warn "echo_e_msg" "-ue";  j_msg -ue "$@";  eem_ret=$?;  return $eem_ret; }
echo_e_msg_n() { eemn_ret=0; _j_msg_compat_warn "echo_e_msg_n" "-uen"; j_msg -uen "$@"; eemn_ret=$?; return $eemn_ret; }
echo_msg()     { em_ret=0;   _j_msg_compat_warn "echo_msg" "-u";    j_msg -u "$@";   em_ret=$?;   return $em_ret; }
echo_msg_n()   { emn_ret=0;  _j_msg_compat_warn "echo_msg_n" "-un";  j_msg -un "$@";  emn_ret=$?;  return $emn_ret; }
notice_echo_msg()    { nem_ret=0;  _j_msg_compat_warn "notice_echo_msg" "-5u";  j_msg -5u "$@";  nem_ret=$?;  return $nem_ret; }
info_echo_msg()      { iem_ret=0;  _j_msg_compat_warn "info_echo_msg" "-6u";  j_msg -6u "$@";  iem_ret=$?;  return $iem_ret; }
debug_echo_msg()     { dem_ret=0;  _j_msg_compat_warn "debug_echo_msg" "-7u";  j_msg -7u "$@";  dem_ret=$?;  return $dem_ret; }
info_echo_msg_n()    { iemn_ret=0; _j_msg_compat_warn "info_echo_msg_n" "-6un"; j_msg -6un "$@"; iemn_ret=$?; return $iemn_ret; }
debug_echo_msg_n()   { demn_ret=0; _j_msg_compat_warn "debug_echo_msg_n" "-7un"; j_msg -7un "$@"; demn_ret=$?; return $demn_ret; }
info_echo_e_msg_n()  { ieemn_ret=0; _j_msg_compat_warn "info_echo_e_msg_n" "-6uen"; j_msg -6uen "$@"; ieemn_ret=$?; return $ieemn_ret; }
debug_echo_e_msg_n() { deemn_ret=0; _j_msg_compat_warn "debug_echo_e_msg_n" "-7uen"; j_msg -7uen "$@"; deemn_ret=$?; return $deemn_ret; }
notice_msg_n() { nmn_ret=0; _j_msg_compat_warn "notice_msg_n" "-5n"; j_msg -5n "$@"; nmn_ret=$?; return $nmn_ret; }
info_msg_n()   { imn_ret=0; _j_msg_compat_warn "info_msg_n" "-6n"; j_msg -6n "$@"; imn_ret=$?; return $imn_ret ; }
debug_msg_n()  { dmn_ret=0; _j_msg_compat_warn "debug_msg_n" "-7n"; j_msg -7n "$@"; dmn_ret=$?; return $dmn_ret ; }

info_right_status()  { irs_ret=0; _j_msg_compat_warn "info_right_status" "right_status <status> \$info";
  right_status "$1" "$info"; irs_ret=$?; return $irs_ret; }
info_handle_result() { ihr_ret=0; _j_msg_compat_warn "info_handle_result" "handle_result <status> <ok> <err> \$info";
  handle_result "$1" "$2" "$3" "$info"; ihr_ret=$?; return $ihr_ret; }
debug_right_status() { drs_ret=0; _j_msg_compat_warn "debug_right_status" "right_status <status> \$debug";
 right_status "$1" "$debug"; drs_ret=$?; return $drs_ret; }
debug_handle_result(){ dhr_ret=0; _j_msg_compat_warn "debug_handle_result" "handle_result <status> <ok> <err> \$debug";
 handle_result "$1" "$2" "$3" "$debug"; dhr_ret=$?; return $dhr_ret; }

# comment-out these two (BASH) tests below, so they don't cause errors in ash, busybox, etc.
#   They can be un-commented to enable for testing in a bash environment if needed, but must be commented out
#   otherwise, to prevent errors in sh environments
#test_rs() {
#  for x in "5:notice:" "6:info:info" "7:debug:debug" ; do
#    IFS=':' read -ra prefix <<< "$x";
#    echo "x: $x  #prefix: ${#prefix[@]}";
#    verbosity=5 loglevel=5 ${prefix[1]}_msg_n "testing [${prefix[1]}]";
#    verbosity=5 loglevel=5 ${prefix[2]+${prefix[2]}_}right_status $? ${prefix[0]};
#  done
#  for x in "5:notice:" "6:info:info" "7:debug:debug" ; do
#    IFS=':' read -ra prefix <<< "$x";
#    echo "x: $x  #prefix: ${#prefix[@]}";
#    verbosity=${prefix[0]} loglevel=${prefix[0]} ${prefix[1]}_msg_n "testing [${prefix[1]}]";
#    verbosity=${prefix[0]} loglevel=${prefix[0]} ${prefix[2]+${prefix[2]}_}right_status $? ${prefix[0]};
#  done
#}
#
#test_rs_hr() {
#  for x in "5:notice:" "6:info:info" "7:debug:debug" ; do
#    IFS=':' read -ra prefix <<< "$x";
#    echo "x: $x  #prefix: ${#prefix[@]}";
#    verbosity=5 loglevel=5 ${prefix[1]}_msg_n "testing [${prefix[1]}]";
#    verbosity=5 loglevel=5 ${prefix[2]+${prefix[2]}_}handle_result $? "" "" ${prefix[0]};
#  done
#  for x in "5:notice:" "6:info:info" "7:debug:debug" ; do
#    IFS=':' read -ra prefix <<< "$x";
#    echo "x: $x  #prefix: ${#prefix[@]}";
#    verbosity=${prefix[0]} loglevel=${prefix[0]} ${prefix[1]}_msg_n "testing [${prefix[1]}]";
#    verbosity=${prefix[0]} loglevel=${prefix[0]} ${prefix[2]+${prefix[2]}_}handle_result $? "" "" ${prefix[0]};
#  done
#}

#-----[ previous generation deprecated messaging functions ]------------------------------------------------

legacy_wrapper_dispatch()
{ lwd_ret=0
  [ $# -lt 3 ] && die "insufficient args. legacy_wrapper_dispatch requires legacy_func target_func + args"
  _lwd_legacy_func=$1; _lwd_target_func=$2
  _lwd_SEVERITY="$FALSE"; _lwd_LOGGING="$FALSE"
  shift 2 # remove the legacy and new function names from the argument list

  # formulate an appropriate deprecation warning based on name of legcy function
  case "$_lwd_legacy_func" in log_*|*_log_*) _lwd_LOGGING="$TRUE" ;; esac
  case "$_lwd_legacy_func" in d_*|de_*|dE_*) _lwd_SEVERITY="$TRUE" ;; esac
  if [ "$_lwd_LOGGING" ]; then
    _lwd_dep_msg="$_lwd_legacy_func is deprecated; use \"LOGGING=\$TRUE $_lwd_target_func\"."
  else
    _lwd_dep_msg="$_lwd_legacy_func is deprecated; use \"$_lwd_target_func\"."
  fi
  if [ "$_lwd_SEVERITY" ]; then
    _lwd_dep_msg="${_lwd_dep_msg} (stripping severity arg if integer)"
  fi
  [ "$DEBUG" ] && j_msg -4 "${BYon}Warning:${Boff} $_lwd_dep_msg"
  # consider legacy *E* messages to be used in error, inconsistent with severity model
  # so issue a second (error) message
  case "$_lwd_legacy_func" in
    *E*)
      _lwd_err_msg="$_lwd_legacy_func is obsolete and inconsistent"
      _lwd_err_msg="${_lwd_err_msg} with the severity model; use $_lwd_target_func instead"
      j_msg -3 "${BRon}Deprecated:${Boff} $_lwd_err_msg" ;;
  esac
  # if severity is "claimed" check if last arg is integer before bothering to rotate
  _lwd_last_arg=""
  for _lwd_last_arg; do : ; done
  if ! isint "$_lwd_last_arg"; then _lwd_SEVERITY="$FALSE"; fi
  # iterate over all args but not w while $# -gt 0 b/c rotation "puts them back"
  _lwd_n=$#
   # guard: only want to strip for d_ w a severity arg
   #   but if there is only one integer arg, I am going to assume it is NOT severity
   #   (therefor the quantitative guard is -gt 1 rather than -gt 0)
  if [ "$_lwd_SEVERITY" ] && [ "$_lwd_n" -gt 1 ]; then
    _lwd_i=1    # now rotate (move first (n-1) args to the end of $@ args
    while [ "$_lwd_i" -lt "$_lwd_n" ]; do
      set -- "$@" "$1"
      shift
      _lwd_i=$(( _lwd_i + 1 ))
    done
    shift # discard what was originally the last argument (the severity level)
  fi
  # hand-off from legacy to new target function
  if [ "$_lwd_LOGGING" ]; then
    LOGGING=$TRUE "$_lwd_target_func" "$@"  # hand off from legacy to inheriting function
  else
    "$_lwd_target_func" "$@"
  fi
  lwd_ret=$?
  unset -v _lwd_legacy_func _lwd_target_func _lwd_SEVERITY _lwd_LOGGING
  unset -v _lwd_n _lwd_i _lwd_last_arg
  return $lwd_ret
}
# @note routes legacy calls, handles logging state, and strips severity args
# @usage legacy_wrapper_dispatch <legacy_func> <target_func> [args ...]
# @args $1: Name of the calling legacy function (for pattern matching)
# @args $2: Name of the new function to be executed
# @args $@: Positional parameters to be processed and passed
# @vars _lwd_legacy_func, _lwd_target_func, _lwd_SEVERITY, _lwd_LOGGING
# @ret exit status of the executed <target_func>
# @rule mode is inferred from legacy_name prefix (d_, *_log_*, *E*)
# @rule uses parameter rotation to avoid eval/subshell limits (POSIX safe)
# @ex legacy_wrapper_dispatch "d_message" "info_msg" "Hello" "critical"
# @cont results in: info_msg "Hello"

log_separator() # (deprecated; use LOGGING="$TRUE" separator() instead)
{ legacy_wrapper_dispatch log_separator separator "$@" ; }

d_log_separator() # (deprecated; use LOGGING="$TRUE" separator() instead)
{ legacy_wrapper_dispatch d_log_separator separator "$@" ; }

log_right_status() # (deprecated; use LOGGING="$TRUE" right_status() instead)
{ legacy_wrapper_dispatch log_right_status right_status "$@" ; }

d_right_status() # (deprecated; use right_status, which is conditional now, instead)
{ drs_ret=0; _drs_last=""
  _drs_target="right_status" # default - notice/5
  for _drs_last; do :; done     # peek at severity arg
  case "$_drs_last" in
    "$info"  ) _drs_target="info_right_status" ;;
    "$debug" ) _drs_target="debug_right_status" ;;
  esac
  legacy_wrapper_dispatch d_right_status "$_drs_target" "$@" ; drs_ret=$?
  unset -v _drs_last _drs_target
  return $drs_ret
}

d_log_right_status() # (deprecated; use right_status, which is conditional now, instead)
{ dlrs_ret=0; _dlrs_last=""
  _dlrs_target="right_status" # default - notice/5
  for _dlrs_last; do :; done     # peek at severity arg
  case "$_dlrs_last" in
    "$info"  ) _dlrs_target="info_right_status" ;;
    "$debug" ) _dlrs_target="debug_right_status" ;;
  esac
  legacy_wrapper_dispatch d_log_right_status "$_dlrs_target" "$@" ; dlrs_ret=$?
  unset -v _dlrs_last _dlrs_target
  return $dlrs_ret
}

non_stty_right_status()    # (deprecated; use right_status)
{ W_message "${BYon}Warning:${Boff} non_stty_right_status is deprecated (use right_status(), which has been upgraded)"
  right_status "$@" ; }


log_handle_result() # (deprecated; use LOGGING=$TRUE handle_result() instead)
{ legacy_wrapper_dispatch log_handle_result handle_result "$@" ; }

d_handle_result() # (deprecated; use handle_result(), which is conditional now, instead)
{ dhr_ret=0; _dhr_last=""
  _dhr_target="handle_result" # default - notice/5
  for _dhr_last; do :; done     # peek at severity arg
  case "$_dhr_last" in
    "$info"  ) _dhr_target="info_handle_result" ;;
    "$debug" ) _dhr_target="debug_handle_result" ;;
  esac
  legacy_wrapper_dispatch d_handle_result "$_dhr_target" "$@" ; dhr_ret=$?
  unset -v _dhr_last _dhr_target
  return $dhr_ret
}

d_log_handle_result() # (deprecated; use LOGGING=$TRUE handle_result() instead)
{ d_log_handle_result_ret=0; if [ "$DEBUG" ]; then
    warn_msg "${BYon}Warning:${Boff} d_log_handle_result() is deprecated; use LOGGING=\$TRUE handle_result() instead"; fi
  eval "$(strip_last_arg "$@")"
  LOGGING="$TRUE" handle_result "$@"; d_log_handle_result=$?; return $d_log_handle_result ; }
# @usage d_log_handle_result <status> <ok_msg> <err_msg> <level>
# @rule deprecated; use LOGGING=$TRUE handle_result() instead
# @rule DEBUG prints a deprecation warning
# @rule strips trailing level arg, forces LOGGING, delegates to handle_result

prompt() # deprecated (use yn_prompt)
{ legacy_wrapper_dispatch prompt yn_prompt "$@" ; }

new_prompt() # deprecated (use yns_prompt)
{ legacy_wrapper_dispatch prompt yns_prompt "$@" ; }


message() # (deprecated; use info_msg) display text message $@ (like echo -e)
{ legacy_wrapper_dispatch message info_msg "$@" ; }

W_message() # (deprecated; use warn_msg) display warning message $@ (like echo -e)
{ legacy_wrapper_dispatch W_message warn_msg "$@" ; }

E_message() # (deprecated; use error_msg) display error message $@ (like echo -e)
{ legacy_wrapper_dispatch E_message error_msg "$@" ; }

log_message() # (deprecated; use info_msg with LOGGING="$TRUE") display text message $@ (like echo -e)
{ legacy_wrapper_dispatch log_message info_msg "$@" ; }

log_E_message() # (deprecated; use error_msg) display error message $@ (like echo -e)
{ legacy_wrapper_dispatch log_E_message error_msg "$@" ; }

d_message()   # (deprecated; use notice/info/debug_msg)
{ dm_ret=0; _dm_last=""
  _dm_target="notice_msg" # default - notice/5
  for _dm_last; do :; done     # peek at severity arg
  case "$_dm_last" in
    "$info"  ) _dm_target="info_msg" ;;
    "$debug" ) _dm_target="debug_msg" ;;
  esac
  legacy_wrapper_dispatch d_message "$_dm_target" "$@" ; dm_ret=$?
  unset -v _dm_last _dm_target
  return $dm_ret
}

dE_message()  # (deprecated; inconsistent legacy behavior; use error_msg)
{ legacy_wrapper_dispatch dE_message error_msg "$@" ; }

d_log_message()  # (deprecated; use LOGGING="$TRUE" info_msg)
{ dlm_ret=0; _dlm_last=""
  _dlm_target="notice_msg" # default - notice/5
  for _dlm_last; do :; done     # peek at severity arg
  case "$_dlm_last" in
    "$info"  ) _dlm_target="info_msg" ;;
    "$debug" ) _dlm_target="debug_msg" ;;
  esac
  legacy_wrapper_dispatch d_log_message "$_dlm_target" "$@" ; dlm_ret=$?
  unset -v _dlm_last _dlm_target
  return $dlm_ret
}

d_log_E_message()  # (deprecated; use LOGGING="$TRUE" info_msg)
{ legacy_wrapper_dispatch d_log_E_message error_msg "$@" ; }

log_echo() # (deprecated; use LOGGING="$TRUE" echo_msg() instead)
{ legacy_wrapper_dispatch log_echo echo_msg "$@" ; }

log_echo_e() # (deprecated; use LOGGING="$TRUE" echo_e_msg() instead)
{ legacy_wrapper_dispatch log_echo_e echo_e_msg "$@" ; }

d_echo() # (deprecated; use echo_msg() instead)
{ legacy_wrapper_dispatch d_echo echo_msg "$@" ; }

de_echo() # (deprecated; use echo_e_msg() instead)
{ legacy_wrapper_dispatch de_echo echo_e_msg "$@" ; }

d_log_echo() # (deprecated; use LOGGING="$TRUE" echo_msg() instead)
{ legacy_wrapper_dispatch d_log_echo echo_msg "$@" ; }

d_log_echo_e()  # (deprecated; use LOGGING="$TRUE" echo_e_msg instead)
{ legacy_wrapper_dispatch d_log_echo_e echo_e_msg "$@" ; }

message_n() # (deprecated; use <severity>_msg_n instead)
{ legacy_wrapper_dispatch message_n info_msg_n "$@" ; }

E_message_n() # (deprecated; use error_msg_n instead)
{ legacy_wrapper_dispatch E_message_n error_msg "$@" ; }

log_message_n() # (deprecated; use LOGGING=$TRUE info_msg_n() instead)
{ legacy_wrapper_dispatch log_message_n info_msg_n "$@" ; }

log_E_message_n() # (deprecated; use LOGGING=$TRUE error_msg_n instead)
{ legacy_wrapper_dispatch log_E_message_n error_msg "$@" ; }

d_message_n() # (deprecated; use <severity>_msg_n instead)
{ legacy_wrapper_dispatch d_message_n info_msg_n "$@" ; }

dE_message_n() # (deprecated; use error_msg_n instead)
{ legacy_wrapper_dispatch dE_message_n error_msg "$@" ; }

d_log_message_n() # (deprecated; use LOGGING=$TRUE info_msg_n() instead)
{ legacy_wrapper_dispatch d_log_message_n info_msg_n "$@" ; }

d_log_E_message_n() # (deprecated; use LOGGING=$TRUE error_msg_n() instead)
{ legacy_wrapper_dispatch d_log_E_message_n error_msg "$@" ; }

d_echo_n() # (deprecated; use echo_msg_n() instead)
{ legacy_wrapper_dispatch d_echo_n echo_msg_n "$@" ; }

de_echo_n() # (deprecated; use echo_e_msg_n() instead)
{ legacy_wrapper_dispatch de_echo_n echo_e_msg_n "$@" ; }

log_echo_n() # (deprecated; use LOGGING=$TRUE echo_msg_n instead)
{ legacy_wrapper_dispatch log_echo_n echo_msg_n "$@" ; }

log_echo_e_n() # (deprecated; use LOGGING=$TRUE echo_e_msg_n instead)
{ legacy_wrapper_dispatch log_echo_e_n echo_e_msg_n "$@" ; }

d_log_echo_n() # (deprecated; use LOGGING=$TRUE echo_msg_n instead)
{ legacy_wrapper_dispatch d_log_echo_n echo_msg_n "$@" ; }

d_log_echo_e_n() # (deprecated; use LOGGING=$TRUE echo_e_msg_n instead)
{ legacy_wrapper_dispatch d_log_echo_e_n echo_e_msg_n "$@" ; }

log_show_config() # (deprecated; use LOGGING="$TRUE" show_config() instead)
{ legacy_wrapper_dispatch log_show_config show_config "$@" ; }

debug_do() # (deprecated; use d_do ... <severity> instead)
{ legacy_wrapper_dispatch debug_do d_do "$@" ; }

# @note =====[ Section 7: System, Net & LUKS ]========================================================================

# @note =====[ Section 8: Command Sequence Framework ]================================================================

# @note =====[ Section 9: Summary & Demonstration Suite ]=============================================================
