#!/bin/sh

# contents are compatability wrappers for deprecated functions

# @note =====[ Section 0: Global Instructions ]===========================================

# @note =====[ Section 1: Global Variables  ]=============================================


#-----[ Select Graphics Rendition on/off ]------------------------------------------

LBLUE="36"       # foreground light blue (cyan)(deprecated - keep here for compatibility)

LBACK="46"       # background light blue (cyan)(deprecated - keep here for compatibility)

Lon="${CSI}${LBLUE}m"   # (deprecated - keep here for compatibility)

LBon="${CSI}${LBLUE};${BOLD}m"   # (deprecated - keep here for compatibility)



# @note =====[ Section 2: Terminal & Cursor Control Functions ]=====================================================

# @note =====[ Section 3: Core Validation Functions ]===============================================================

isnumber() # (deprecated - use isint() or isnumeric(); isnumber tests if $1 is an integer
{ legacy_wrapper_dispatch isnumber isnumeric "$@" ; }

# @note =====[ Section 4: String & Layout Utilities ]===============================================================


echo_n_long() # deprecated - use smart_wrap_n
{ W_message "${BYon}Warning:${Boff} echo_n_long is deprecated (use smart_wrap_n(), which has been upgraded)"
  [ ! $# -eq 3 ] && die "invalid arguments"
  # translate for compatibility - smartwrap also uses r_margin
  _enl_start_col="$1"; shift
  _ens_indent="$1"; shift
  _enl_msg="$@"
  smart_wrap_n "$_enl_start_col" "$_ens_indent" "" "$_enl_msg" ; }



# @note =====[ Section 5: Logic & Conversion ]======================================================================

# @note =====[ Section 6: Logging, Messaging, & UI ]==================================================================

log_separator() # (deprecated; use LOGGING="$TRUE" separator() instead)
{ legacy_wrapper_dispatch log_separator separator "$@" ; }

d_log_separator() # (deprecated; use LOGGING="$TRUE" separator() instead)
{ legacy_wrapper_dispatch d_log_separator separator "$@" ; }

log_right_status() # (deprecated; use LOGGING="$TRUE" right_status() instead)
{ legacy_wrapper_dispatch log_right_status right_status "$@" ; }

d_right_status() # (deprecated; use right_status, which is conditional now, instead)
{ drs_ret=0; _drs_last=""
  _drs_target="right_status" # default - notice/5
  for _drs_last; do :; done     # peek at severity arg
  case "$_drs_last" in
    "$info"  ) _drs_target="info_right_status" ;;
    "$debug" ) _drs_target="debug_right_status" ;;
  esac
  legacy_wrapper_dispatch d_right_status "$_drs_target" "$@" ; drs_ret=$?
  unset -v _drs_last _drs_target
  return $drs_ret
}

d_log_right_status() # (deprecated; use right_status, which is conditional now, instead)
{ dlrs_ret=0; _dlrs_last=""
  _dlrs_target="right_status" # default - notice/5
  for _dlrs_last; do :; done     # peek at severity arg
  case "$_dlrs_last" in
    "$info"  ) _dlrs_target="info_right_status" ;;
    "$debug" ) _dlrs_target="debug_right_status" ;;
  esac
  legacy_wrapper_dispatch d_log_right_status "$_dlrs_target" "$@" ; dlrs_ret=$?
  unset -v _dlrs_last _dlrs_target
  return $dlrs_ret
}

non_stty_right_status()    # (deprecated; use right_status)
{ W_message "${BYon}Warning:${Boff} non_stty_right_status is deprecated (use right_status(), which has been upgraded)"
  right_status "$@" ; }


log_handle_result() # (deprecated; use LOGGING=$TRUE handle_result() instead)
{ legacy_wrapper_dispatch log_handle_result handle_result "$@" ; }

d_handle_result() # (deprecated; use handle_result(), which is conditional now, instead)
{ dhr_ret=0; _dhr_last=""
  _dhr_target="handle_result" # default - notice/5
  for _dhr_last; do :; done     # peek at severity arg
  case "$_dhr_last" in
    "$info"  ) _dhr_target="info_handle_result" ;;
    "$debug" ) _dhr_target="debug_handle_result" ;;
  esac
  legacy_wrapper_dispatch d_handle_result "$_dhr_target" "$@" ; dhr_ret=$?
  unset -v _dhr_last _dhr_target
  return $dhr_ret
}

d_log_handle_result() # (deprecated; use LOGGING=$TRUE handle_result() instead)
{ d_log_handle_result_ret=0; if [ "$DEBUG" ]; then
    warn_msg "${BYon}Warning:${Boff} d_log_handle_result() is deprecated; use LOGGING=\$TRUE handle_result() instead"; fi
  eval "$(strip_last_arg "$@")"
  LOGGING="$TRUE" handle_result "$@"; d_log_handle_result=$?; return $d_log_handle_result ; }
# @usage d_log_handle_result <status> <ok_msg> <err_msg> <level>
# @rule deprecated; use LOGGING=$TRUE handle_result() instead
# @rule DEBUG prints a deprecation warning
# @rule strips trailing level arg, forces LOGGING, delegates to handle_result

prompt() # deprecated (use yn_prompt)
{ legacy_wrapper_dispatch prompt yn_prompt "$@" ; }

new_prompt() # deprecated (use yns_prompt)
{ legacy_wrapper_dispatch prompt yns_prompt "$@" ; }


message() # (deprecated; use info_msg) display text message $@ (like echo -e)
{ legacy_wrapper_dispatch message info_msg "$@" ; }

W_message() # (deprecated; use warn_msg) display warning message $@ (like echo -e)
{ legacy_wrapper_dispatch W_message warn_msg "$@" ; }

E_message() # (deprecated; use error_msg) display error message $@ (like echo -e)
{ legacy_wrapper_dispatch E_message error_msg "$@" ; }

log_message() # (deprecated; use info_msg with LOGGING="$TRUE") display text message $@ (like echo -e)
{ legacy_wrapper_dispatch log_message info_msg "$@" ; }

log_E_message() # (deprecated; use error_msg) display error message $@ (like echo -e)
{ legacy_wrapper_dispatch log_E_message error_msg "$@" ; }

d_message()   # (deprecated; use notice/info/debug_msg)
{ dm_ret=0; _dm_last=""
  _dm_target="notice_msg" # default - notice/5
  for _dm_last; do :; done     # peek at severity arg
  case "$_dm_last" in
    "$info"  ) _dm_target="info_msg" ;;
    "$debug" ) _dm_target="debug_msg" ;;
  esac
  legacy_wrapper_dispatch d_message "$_dm_target" "$@" ; dm_ret=$?
  unset -v _dm_last _dm_target
  return $dm_ret
}

dE_message()  # (deprecated; inconsistent legacy behavior; use error_msg)
{ legacy_wrapper_dispatch dE_message error_msg "$@" ; }

d_log_message()  # (deprecated; use LOGGING="$TRUE" info_msg)
{ dlm_ret=0; _dlm_last=""
  _dlm_target="notice_msg" # default - notice/5
  for _dlm_last; do :; done     # peek at severity arg
  case "$_dlm_last" in
    "$info"  ) _dlm_target="info_msg" ;;
    "$debug" ) _dlm_target="debug_msg" ;;
  esac
  legacy_wrapper_dispatch d_log_message "$_dlm_target" "$@" ; dlm_ret=$?
  unset -v _dlm_last _dlm_target
  return $dlm_ret
}

d_log_E_message()  # (deprecated; use LOGGING="$TRUE" info_msg)
{ legacy_wrapper_dispatch d_log_E_message error_msg "$@" ; }

log_echo() # (deprecated; use LOGGING="$TRUE" echo_msg() instead)
{ legacy_wrapper_dispatch log_echo echo_msg "$@" ; }

log_echo_e() # (deprecated; use LOGGING="$TRUE" echo_e_msg() instead)
{ legacy_wrapper_dispatch log_echo_e echo_e_msg "$@" ; }

d_echo() # (deprecated; use echo_msg() instead)
{ legacy_wrapper_dispatch d_echo echo_msg "$@" ; }

de_echo() # (deprecated; use echo_e_msg() instead)
{ legacy_wrapper_dispatch de_echo echo_e_msg "$@" ; }

d_log_echo() # (deprecated; use LOGGING="$TRUE" echo_msg() instead)
{ legacy_wrapper_dispatch d_log_echo echo_msg "$@" ; }

d_log_echo_e()  # (deprecated; use LOGGING="$TRUE" echo_e_msg instead)
{ legacy_wrapper_dispatch d_log_echo_e echo_e_msg "$@" ; }

message_n() # (deprecated; use <severity>_msg_n instead)
{ legacy_wrapper_dispatch message_n info_msg_n "$@" ; }

E_message_n() # (deprecated; use error_msg_n instead)
{ legacy_wrapper_dispatch E_message_n error_msg "$@" ; }

log_message_n() # (deprecated; use LOGGING=$TRUE info_msg_n() instead)
{ legacy_wrapper_dispatch log_message_n info_msg_n "$@" ; }

log_E_message_n() # (deprecated; use LOGGING=$TRUE error_msg_n instead)
{ legacy_wrapper_dispatch log_E_message_n error_msg "$@" ; }

d_message_n() # (deprecated; use <severity>_msg_n instead)
{ legacy_wrapper_dispatch d_message_n info_msg_n "$@" ; }

dE_message_n() # (deprecated; use error_msg_n instead)
{ legacy_wrapper_dispatch dE_message_n error_msg "$@" ; }

d_log_message_n() # (deprecated; use LOGGING=$TRUE info_msg_n() instead)
{ legacy_wrapper_dispatch d_log_message_n info_msg_n "$@" ; }

d_log_E_message_n() # (deprecated; use LOGGING=$TRUE error_msg_n() instead)
{ legacy_wrapper_dispatch d_log_E_message_n error_msg "$@" ; }

d_echo_n() # (deprecated; use echo_msg_n() instead)
{ legacy_wrapper_dispatch d_echo_n echo_msg_n "$@" ; }

de_echo_n() # (deprecated; use echo_e_msg_n() instead)
{ legacy_wrapper_dispatch de_echo_n echo_e_msg_n "$@" ; }

log_echo_n() # (deprecated; use LOGGING=$TRUE echo_msg_n instead)
{ legacy_wrapper_dispatch log_echo_n echo_msg_n "$@" ; }

log_echo_e_n() # (deprecated; use LOGGING=$TRUE echo_e_msg_n instead)
{ legacy_wrapper_dispatch log_echo_e_n echo_e_msg_n "$@" ; }

d_log_echo_n() # (deprecated; use LOGGING=$TRUE echo_msg_n instead)
{ legacy_wrapper_dispatch d_log_echo_n echo_msg_n "$@" ; }

d_log_echo_e_n() # (deprecated; use LOGGING=$TRUE echo_e_msg_n instead)
{ legacy_wrapper_dispatch d_log_echo_e_n echo_e_msg_n "$@" ; }

log_show_config() # (deprecated; use LOGGING="$TRUE" show_config() instead)
{ legacy_wrapper_dispatch log_show_config show_config "$@" ; }

debug_do() # (deprecated; use d_do ... <severity> instead)
{ legacy_wrapper_dispatch debug_do d_do "$@" ; }

# @note =====[ Section 7: System, Net & LUKS ]========================================================================

# @note =====[ Section 8: Command Sequence Framework ]================================================================

# @note =====[ Section 9: Summary & Demonstration Suite ]=============================================================
