#!/bin/bash
# determine which ipset(s) match search criteria
# Joe Brendler, 2 Nov 14

source /usr/local/sbin/script_header_joe_brendler
BUILD="0.0.01"

ip_found_color="${BGon}"
ip_not_found_color="${BRon}"

#DEBUG="true"
DEBUG="false"

useage()
{
  echo -e "${BGon}Useage:  ${Boff}ipset-find <search_criterion>"
  echo -e "${BBon}Example: ${Boff}ipset-find '^192.'"
}

#---[ main script ]-------------------------------
checkroot

[ -z "$1" ] && useage && exit 1

separator "ipset-find-${BUILD}"

message "Searching ipsets for: [ ${BYon}${1}${Boff} ]"
# ipsets named "ipdeny" and "*_set" are of type list:set (ignore these)
for i in $(ipset list -n | grep -v "_set" | grep -v "ipdeny" )
do
  ipset test $i $1 2>1 && \
    message "${1} ${ip_found_color}IS${Boff} in set ${ip_found_color}${i}${Boff}" || \
    E_message "${1} is ${ip_not_found_color}NOT${Boff} in set ${i}"
done
