#!/bin/bash
source /usr/local/sbin/script_header_brendlefly

BUILD="0.0.0a"

#-----------[ start main script ]------------------------------
checkroot

separator "ipset-block-suspicious-url-"${BUILD}


for ip in $(nslookup $1 | grep Address | grep -v '#' | cut -d' ' -f2); do ipset add suspicious $ip/32; message "added: $ip/32"; done
