#!/bin/bash
inputfile=$1
source /usr/sbin/script_header_joetoo
if [[ ! -e ${inputfile} || $# -eq 0 ]]
then
  E_message "provide path to file to be checked"
  exit
fi

# output lines that define d_ functions not ending in a digit
# -n: show line numbers, -E: extended regex, ^: beginning of line, $: end of line
# W0: whitespace (from script_header_joetoo),
# d_: literal, .*: any characters, [^0-9]: not a digit
grep -n -E "^${W0}d_.*[^0-9]$" $inputfile