#!/bin/bash
source /usr/sbin/script_header_joetoo
#for x in testfile
for x in ../init ../validated_functions_header ../testing_functions_header
do
    separator "$x" "checking logical tests in"
#    message_n "[^[ ]: "; grep -n '^\[ ' $x  | ./strip_d_lines.sh; echo
#    message_n "[ [ ]: "; grep -n ' \[ ' $x  | ./strip_d_lines.sh; echo
#    message_n "[ ] ]: "; grep -n ' \] ' $x  | ./strip_d_lines.sh; echo
#    message_n "[ ]$]: "; grep -n ' \]$' $x  | ./strip_d_lines.sh; echo
    message "[${W0}^[${W0}]: "; grep -n "^${W0}\[${W0}" $x
    message "[${W0}]${W0}$]: "; grep -n "${W0}\]${W0}$" $x
done
