#!/bin/bash
source /usr/sbin/script_header_joetoo

inputfile=$1
if [[ $# -eq 0 ||  ! -f "$inputfile" ]]; then
  E_message "provide path to file to be checked"
  exit 1
fi

PN=$(basename "$0")

# output lines with an odd number of quotation marks
separator "$PN" "( missing double qoute [\"] )"
# -F'"'" -> double quote divides line into fields
# NF % 2 == 0  -> Number of fields is even (meaning quotes are ODD)
# $0 !~ /^$/   -> The line is NOT empty (start-to-finish match)
awk -F '"' '    NF % 2 == 0 && $0 !~ /^[[:space:]]*$/ {
        printf "Line %4d: %s\n", NR, $0
    }
' "$inputfile"

# output lines with an odd number of quotation marks
separator "$PN" "( missing single quote ['] )"
# -F"'" -> single quote divides line into fields
# NF % 2 == 0  -> Number of fields is even (meaning quotes are ODD)
# $0 !~ /^$/   -> The line is NOT empty (start-to-finish match)
awk -F "'" '
    NF % 2 == 0 && $0 !~ /^[[:space:]]*$/ {
        printf "Line %4d: %s\n", NR, $0
    }
' "$inputfile"
