#!/bin/bash
source /usr/local/sbin/script_header_brendlefly
for x in init validated_functions_header testing_functions_header
do
    separator "$x" "listing functions in"
    grep '()' ../$x | sed 's|^[[:space:]]*||' | grep -v '^#'
done
