# Simple case: WPA-PSK, PSK as an ASCII passphrase, allow all valid ciphers
update_config=1
country=US
eapol_version=2  # 20260322 changed 1->2 (wpa2 std)
ap_scan=1
fast_reauth=1
ctrl_interface_group=0
ctrl_interface=/run/wpa_supplicant

network={
        ssid="replace-with-your-SSID"
        psk="replace-with-plaintext-passphrase8-63char-or-64char-hex-PSK"
        key_mgmt=WPA-PSK
        proto=RSN      # Robust Security Network = WPA2 (uses CCMP [AES-128 in Counter Mode])
        pairwise=CCMP  # Counter Mode with Cipher Block Chaining Message Authentication Code Protocol [AES-128]
        group=CCMP     # Prevents APs from offering TKIP (obsolete)
        priority=5     # Higher number is more preferred (only matters if multiple network blocks are enabled)
        disabled=1     # Change to 0 for the network block(s) to be enabled
}

