#! /bin/bash

# /usr/local/sbin/ipdeny
# based on ipdeny by BoneKracker Rev. 11 October 2012
# Modified by Joe Brendler Rev 21 Feb 2015 - ipset setlist size bugfix
# Rev 17 Feb 2022 - further adapted to refer to ipsets separately loaded for ALL countries

# Purpose: Use sets of ip networks registered in a country pre-loaded into a country-coded ipset
#   to load that ipset name into a setlist containing several such ipsets, while this setlist is
#   being used in a running firewall.
#
# Notes: Call this from crontab. Feed updated about 05:07 and 15:07 daily.
#
# Usage: 'ipdeny <TLD>' (where TLD is top-level national domain, such as "us")

source /usr/sbin/script_header_joetoo

#-----[ variable initialization ]----------------------------------
# Reference: http://www.ipdeny.com/ipblocks/data/countries/
denied_countries="af ae al am ao az bd bg bh by cn cx cz dz eg eh er es et \
  fm fr gb ge hk hn hr hu id il iq ir jo kh kg kp kr la lb li lt lv ly \
  ma mc md me mm mn ms mt my nc ni ng om pk pl ps pe ph pt qa ro rs ru \
  sa si sk sl sn so ss su sy tj th tm tn tr tw ua uz va ve vn ye za zw"

#-----[ functions ]-------------------------------------------------
update_ipdeny() {
  [ -n "$1" ] && firewall_ipset="$1" || exit 1

  timestamp=$(my_date)

  # if the setlist does not exist, create it
  ipset create -exist ipdeny list:set --size 256

  # if the ipset is not already in the setlist, add it
  ipset add -exist ipdeny ${firewall_ipset}

  # log the file modification time for use in minimizing lag in cron schedule
  msg="ipdeny setlist updated for [${firewall_ipset}] (as of: ${timestamp})."
  message "Logging --> ${msg}"
  logger -p cron.notice ${msg}
}

#-----[ main script ]------------------------------------------------
checkroot
separator "ipset_countrycode_load-$BUILD" "$(hostname)"

for c in ${denied_countries}
do
  update_ipdeny $c
done
