#!/bin/bash
source /usr/sbin/script_header_joetoo

PN=${0##*/}

# add ip 4/6 addresses associated with suspicious urls to block lists
# ToDo: add more command line handling, root check, etc
[ $# -eq 0 ] && { j_msg -${err} "${BRon}usage${Boff}: $PN <target_url>"; exit 1; }
target="$1"

j_msg -${info} -m -n "getting ip addresses for target [$target]"
readarray -t iplist < <(ipset-url ${target} | strip_ansi | grep '\[' | awk '{print $2}')
handle_result $? "recorded ${#iplist[@]} ips" "" ${info} || die "failed to get ip addresses for $target"

for ip in "${iplist[@]}";  do
  case "$ip" in
    *'.'*)   # ipv4
        if ipset add suspicious "$ip"; then
            j_msg -${debug} -p "added $ip to suspicious (ipv4)"
        else
            j_msg -${warn} "failed to add $ip to suspicious (ipv4)"
        fi
        ;;
    *':'*) # ipv6
        if ipset add suspicious_6 "$ip"; then
            j_msg -${debug} -p "added $ip to suspicious_6 (ipv6)"
        else
            j_msg -${warn} "failed to add $ip to suspicious_6 (ipv6)"
        fi
        ;;
    *) j_msg -${err} "invalid ip addr [$ip]; continuing" ;;
  esac
done

j_msg -${info} -m "done"
