#!/bin/bash
source /usr/sbin/script_header_joetoo
SOURCES_DIR=/home/joe/myUtilities/mkinitramfs/scratch/usr/src/initramfs
MAKE_DIR=/home/joe/myUtilities/mkinitramfs
CONF_DIR=${MAKE_DIR}
source ${MAKE_DIR%/}/make_sources_functions_header
source ${MAKE_DIR%/}/common_bash_functions_header  # load_ list_ dump_executables
source ${MAKE_DIR%/}/common_ash_functions_header   # display_config, echo_long_string
verbosity=5

# source the init_structure list
source ${MAKE_DIR%/}/init_structure


sudo rm -r ${SOURCES_DIR%/}/*
mkdir ${SOURCES_DIR%/}/usr

# drop
# /proc/partitions \    # this is an empty file

#buildem $bins
#buildem $libs
build_structure $structure
build_other_devices

#source ${MAKE_DIR}/dyn_executables_header
# initialize list of executables
executables=()
# initialize list of dependencies of executables
dependencies=()

separator "executables"
load_executables
#list_executables
#dump_executables
copy_executables

separator "other parts"
copy_other_parts

separator "create links"
create_links

separator "dependencies"
#identify_all_dependencies
#dump_dependencies

### copy_dependent_libraries

copy_dependencies

echo
tree
