#!/bin/bash
# Standardized Joetoo Update Sequence (jus), implemented as interactive
#   script with "resume" functionality
# Author: Joe Brendler 14 October 2020
#   based on author's "update-sequence" and "gus" scripts of 23 Jan 2011 and 9 Mar 2017 respectively
# Build 6 notes:
#   removed previous functionality atttempting to deal with distcc-friendliness in the script
#     (now use per-package env to set FEATURES=" -distcc -distcc-pump")
#   borrowed some ideas from https://serverfault.com/questions/9936/optimal-procedure-to-upgrade-gentoo-linux
#     -- check for major upgrade to key packages and recommend full rebuild
#     -- added companion script "rus" to automate that rebuild
#     -- included "fixpackages" and "eselect python update" as default options in command sequence
#     -- also included "glsa-check -vp affected" and "emaint --check all"
#  New idea - nested loops of command sequences within phases

# Source the variable assignments made in jus.conf (/etc/ overrides pwd)
#   This will supercede/modify the default assignments made below
CONF_DIR="defaults"

# User-defined variables - modify assignments below, according to your system.
#   Deviate from defaults in jus.conf

## SCRIPT_DIR is the directory in which you have placed the show-elogs script.
#   (only needed if it is not in your path. Normally "/usr/local/sbin/"; must end with '/' if specified)
#   (assigned here, prior to sourcing jus.conf so it will be properly initialized, just in case it is not assigned in jus.conf
SCRIPT_DIR=""

# source jus.conf in order to load user-configured settings
#   check each setting below to assign default values if needed
#   Note: jus.conf in /etc/jus/ will override one in pwd
[[ -e jus.conf ]] && source jus.conf && CONF_DIR=$PWD"/jus.conf"
[[ -e /etc/jus/jus.conf ]] && source /etc/jus/jus.conf && CONF_DIR="/etc/jus/jus.conf"

# STATUS_FILE is the name of the status file
#   generated and used by this script.  Provide the complete pathname
[ -z "$STATUS_FILE" ] && \
    STATUS_FILE="/root/bin/jus-status" || \
    STATUS_FILE=$STATUS_FILE

# EIX indicates whether you use app-portage/eix, which will significantly speed up parts of jus
[ -z "$EIX" ] && EIX="yes"

# DISTCC indicates whether you use sys-devel/distcc, which can significantly speed up compiling for jus
[ -z "$DISTCC" ] && DISTCC="yes"

# PUMP indicates whether you use cpp capable distcc hosts, and you want to pump emerge
#[ "$DISTCC" == "yes" ] && [ -z "$PUMP" ] && PUMP="no"
PUMP="no"  ## disabling selection, since global use of pump is ill advised - known to break many pkgs

# unfriendlies is a file listing packages known to not be friendly to distcc
### this gus functionality removed in jus
### (use per-package environment to set FEATURES instead)

# SYNC_TS is the pathname of the file the timestamp of which will
#   be checked to determine how long it's been since the portage
#   tree was last sync'd
[ -z "$SYNC_TS" ] && SYNC_TS="/usr/portage/metadata/timestamp.chk"       # emerge --sync timestamp

# SYNC_CMD is the command used to sync the portage tree
#[ -z "$SYNC_CMD" ] && SYNC_CMD="WEBRSYNC"       # emerge-webrsync
#[ -z "$SYNC_CMD" ] && SYNC_CMD="SYNC"           # emerge --sync
[ -z "$SYNC_CMD" ] && SYNC_CMD="EIX_SYNC"        # eix-sync

# MAX_AGE is the maximum time in hours since last sync before this script
#   will automatically choose to emerge --sync
[ -z "$MAX_AGE" ] && MAX_AGE=24

# ELOG_DIR is the location of elog files
[ -z "$ELOG_DIR" ] && ELOG_DIR="/var/log/portage/elog/"

# SELINUX_RELABEL
[ -z "$SELINUX_RELABEL" ] && SELINUX_RELABEL="no"

# PERL_CLEANER
[ -z "$PERL_CLEANER" ] && PERL_CLEANER="no"

# HASKELL_UPDATER
[ -z "$HASKELL_UPDATER" ] && HASKELL_UPDATER="no"

# REGEN_OVERLAY_METADATA
[ -z "$REGEN_OVERLAY_METADATA" ] && REGEN_OVERLAY_METADATA="yes"

# EIX_UPDATE
[ -z "$EIX_UPDATE" ] && EIX_UPDATE="no"

# PYTHON_UPDATER
[ -z "$PYTHON_UPDATER" ] && PYTHON_UPDATER="yes"

# MODULE_REBUILD
[ -z "$MODULE_REBUILD" ] && MODULE_REBUILD="no"

# X11_MODULE_REBUILD
[ -z "$X11_MODULE_REBUILD" ] && X11_MODULE_REBUILD="no"

# RKHUNTER propupd
[ -z "$RKHUNTER" ] && RKHUNTER="no"

# GLSA_CHECK
[ -z "$GLSA_CHECK" ] && GLSA_CHECK="yes"

# EMAINT_CHECK
[ -z "$EMAINT_CHECK" ] && EMAINT_CHECK="yes"

# --- source common functions and variables --------------------
source /usr/local/sbin/script_header_brendlefly
source /usr/local/sbin/script_header_brendlefly_extended

# --- Define local variables -----------------------------------
worldfile="/var/lib/portage/world"
VERBOSE=$FALSE
#VERBOSE=$TRUE
verbosity=0

BUILD="6.0.2 (20201015)"

continue="y"
RESUME="no"
SYNC="no"
EXCLUDE=""
UPDATE_CHECK="no"  # default; command line option only (forces update check only), otherwise part of phase
GO_AHEAD="no"
KEEPGOING="yes"
# Do not move these to .conf and set like those above --
#  They are only used when set to "yes" (otherwise, global settings in make.conf apply)
USEPKG="no"
USEPKGONLY="no"
GETBINPKG="no"
GETBINPKGONLY="no"
WITH_BDEPS_Y="yes"

updateables=""

KP_FOUND=${FALSE}

# Array of messages used to announce each phase
phase_message=(
'Sync'
'Update-Check'
'Emerge Updates'
'Review news and Maintain Config Files'
'Review elogs'
'Handle Dependencies'
'Final steps'
)

phase_function_sequence=(
'emerge_sync'
'update_check'
'emerge_updates'
'show_news; maintain_config_files'
'showelogs'
'handle_dependencies'
'final_phases'
)

phase=0


# --- function blocks ------------------------------------------


sanity_check()
{
# veryfy the sanity of the combination of arguments on the command line
[ "$SYNC" == "yes" ] && [ "$RESUME" == "yes" ] && \
   E_message "Nonsensical option combination: sync and resume" && \
   useage && exit 1

[ "$SYNC" == "yes" ] && [ "$GO_AHEAD" == "yes" ] && \
   E_message "Dangerous option combination: sync and go_ahead" && \
   E_message "(you should never merge packages blindly, please check first)" && \
   useage && exit 1

# if both remote/local and local-only are set local-only should over-ride
[ "$GETBINPKG" == "yes" ] && [ "$GETBINPKGONLY" == "yes" ] && GETBINPKG="no"
[ "$USEPKG" == "yes" ] && [ "$USEPKGONLY" == "yes" ] && USEPKG="no"
}

process_command_line()
{
# process command line arguments (for now only -x/--exclude option can have argument(s))
last=""
d_message "processing command line with argument(s): [ ${*} ]" 2
# shift each argument into position $1 and examine it
#   process the argument or processit with its own arguments
while [ ! -z "$1" ]
do
  d_message "arg1 = [ $1 ]" 3
  # if arg begins with a single dash, process it alone
  if [ "${1:0:1}" == "-" ] && [ "${1:1:1}" != "-" ]
  then
    d_message "processing [ $1 ] alone as single-dash argument" 3
    process_argument $1
    shift
  # if arg begins with a double dash, process it alone if it is not --exclude
  elif [ "${1:0:2}" == "--" ] && [ "$1" != "--exclude" ]
  then
    d_message "processing [ $1 ] alone as double-dash non-exclude argument" 3
    process_argument $1
    shift
  # if arg begins with a double dash, and it is --exclude,
  #   then process it with its own agruments (identified by no leading - or --)
  elif [ "${1:0:2}" == "--" ] && [ "$1" == "--exclude" ]
  then
    d_message "processing [ $1 ] as --exclude, with own args:" 3
    tmp_cmd=$1
    tmp_args=""
    shift
    while [ ! -z "$1" ]
    do
      if [ "${1:0:1}" != "-" ]
      then
        d_message "adding [ $1 ] to tmp_args:" 3
        # formulate this so as to preserve internal white space between multiple exclude atoms, but to not add extra whitespace
        [ -z "${tmp_args}" ] && tmp_args=${1} || tmp_args="${tmp_args} ${1}"
      else
        d_message "non-argument [ $1 ], exiting" 2
        exit
      fi
      shift
    done
    d_message "processing [ $tmp_cmd \"$tmp_args\" ]" 1
    process_argument $tmp_cmd "$tmp_args"
  else
    # bogus argument
    d_message "bogus argument [ $1 ]" 1
    E_message "${E_BAD_ARGS}" && useage && exit 1
  fi
done
sanity_check
}

process_argument()
{
EXCLUDE=""
d_message "about to process argument(s): [ $* ]" 1
d_message "1: [ $1 ], 2: [ $2 ]" 2
# process command line argument (must be one of the following)
[ ! -z "$1" ] && case "$1" in
    "-a" | "--glsa"          ) GLSA_CHECK="yes" ;;
    "-c" | "--check"         ) UPDATE_CHECK="yes" ;;
    "-e" | "--eix"           ) EIX_UPDATE="yes" ;;
    "-g" | "--getbinpkg"     ) GETBINPKG="yes" ;;
    "-G" | "--getbinpkgonly" ) GETBINPKGONLY="yes" ;;
    "-k" | "--usepkg"        ) USEPKG="yes" ;;
    "-K" | "--usepkgonly"    ) USEPKGONLY="yes" ;;
    "-m" | "--modules"       ) MODULE_REBUILD="yes" ;;
    "-M" | "--emaint"        ) EMAINT_CHECK="yes" ;;
    "-p" | "--perl_cleaner"  ) PERL_CLEANER="yes" ;;
    "-P" | "--python"        ) PYTHON_UPDATER="yes" ;;
    "-r" | "--resume"        ) RESUME="yes" ;;
    "-R" | "--regen"         ) REGEN_OVERLAY_METADATA="yes" ;;
    "-s" | "--status"        ) status ; exit 0 ;;
    "-S" | "--selinux"       ) SELINUX_RELABEL="yes" ;;
    "-t" | "--rkhunter"      ) RKHUNTER="yes" ;;
    "-v" | "--verbose"       ) VERBOSE=$TRUE; let "verbosity+=1" ;;
    "-w" | "--with-bdeps=y"  ) WITH_BDEPS_Y="yes" ;;
    "-x" | "--exclude"       ) EXCLUDE="${2}" ;;
    "-X" | "--X11"           ) X11_MODULE_REBUILD="yes" ;;
    "-y" | "--sync"          ) SYNC="yes" ;;
    "-Y" | "--go-ahead"      ) GO_AHEAD="yes" ;;
    "-Z" | "--keep-going"    ) KEEPGOING="yes" ;;
    "-H" | "--haskell"       ) HASKELL_UPDATER="yes" ;;
    "-h" | "--help"          ) useage ; exit 0 ;;
    "-u" | "--update-all"    ) GLSA_CHECK="yes"; EIX_UPDATE="yes"; MODULE_REBUILD="yes"; \
                               EMAINT_CHECK="yes"; PERL_CLEANER="yes"; \
                               PYTHON_UPDATER="yes"; REGEN_OVERLAY_METADATA="yes"; \
                               SELINUX_RELABEL="yes"; RKHUNTER="yes"; WITH_BDEPS_Y="yes"; \
                               X11_MODULE_REBUILD="yes"; SYNC="yes"; HASKELL_UPDATER="yes" ;;
    *                        ) process_compound_arg $1 ;;
esac
}

process_compound_arg()
{
# must begin with a single dash
[ ! "${1:0:1}" == "-" ] && E_message "${E_BAD_ARGS}" && useage && exit 1
# must not begin with two dashes (would have been picked in process_argument)
[ "${1:0:2}" == "--" ] && E_message "${E_BAD_ARGS}" && useage && exit 1
# strip leading dash(es)
myargs=${1##-}
# handle remaining characters in sequence
while [ -n "${myargs}" ]
do
    #handle first char
    case ${myargs:0:1} in
        "a") GLSA_CHECK="yes" ;;
        "c") UPDATE_CHECK="yes" ;;
        "e") EIX_UPDATE="yes" ;;
        "g") GETBINPKG="yes" ;;
        "G") GETBINPKGONLY="yes" ;;
        "k") USEPKG="yes" ;;
        "K") USEPKGONLY="yes" ;;
        "m") MODULE_REBUILD="yes" ;;
        "M") EMAINT_CHECK="yes" ;;
        "p") PERL_CLEANER="yes" ;;
        "P") PYTHON_UPDATER="yes" ;;
        "r") RESUME="yes" ;;
        "R") REGEN_OVERLAY_METADATA="yes" ;;
        "S") SELINUX_RELABEL="yes" ;;
        "t") RKHUNTER="yes" ;;
        "v") VERBOSE=$TRUE; let "verbosity+=1" ;;
        "w") WITH_BDEPS_Y="yes" ;;
        "X") X11_MODULE_REBUILD="yes" ;;
        "Y") GO_AHEAD="yes" ;;
        "y") SYNC="yes" ;;
        "Z") KEEPGOING="yes" ;;
        "H") HASKELL_UPDATER="yes" ;;
        "u") GLSA_CHECK="yes"; EIX_UPDATE="yes"; MODULE_REBUILD="yes"; \
             EMAINT_CHECK="yes"; PERL_CLEANER="yes"; \
             PYTHON_UPDATER="yes"; REGEN_OVERLAY_METADATA="yes"; \
             SELINUX_RELABEL="yes"; RKHUNTER="yes"; WITH_BDEPS_Y="yes" \
             X11_MODULE_REBUILD="yes"; SYNC="yes"; HASKELL_UPDATER="yes" ;;
        *  ) E_message "${E_BAD_ARGS}" && useage && exit 1
esac
    #strip first char from myargs (i.e. "shift")
    myargs=${myargs:1}
done
}

useage()
{
   echo -e $BGon"Useage: jus [option]"$Boff
   echo -e " Command line options:"
   echo -e "   Options for all phases"
   echo -e "    "$BBon"[-s | --status]"$Boff"...........print next phase in update sequence"
   echo -e "    "$BBon"[-r | --resume]"$Boff"...........resume update sequence at next phase"
   echo -e "    "$BBon"[-v | --verbose]"$Boff"..........increase verbosity"
   echo -e "    "$BBon"[-h | --help]"$Boff".............print this text"
   echo -e "   Options for ${phase_message[0]}"   ## phase 0 - Sync
   echo -e "    "$BBon"[-y | --sync]"$Boff".............force sync portage tree"
   echo -e "    "$BBon"[-R | --regen]"$Boff"............regenerate portage tree metadata (including overlays) "
   echo -e "   Options for ${phase_message[1]}"   ## phase 1 - Update-Check
   echo -e "    "$BBon"[-c | --check]"$Boff"............check for and list updateable installed packages"
   echo -e "   Options for ${phase_message[2]}"   ## phase 2 - Emerge Updates
   echo -e "    "$BBon"[-g | --getbinpkg]"$Boff"........use local and remote binary packages and ebuilds"
   echo -e "    "$BBon"[-G | --getbinpkgonly]"$Boff"....use local and remote binary packages only"
   echo -e "    "$BBon"[-k | --usepkg]"$Boff"...........use local binary packages and ebuilds"
   echo -e "    "$BBon"[-K | --usepkgonly]"$Boff".......use local binary packages only"
   echo -e "    "$BBon"[-w | --WITH_BDEPS_Y]"$Boff".....emerge with build-time dependencies"
   echo -e "    "$BBon"[-x | --exclude <atom>]"$Boff"...exclude <atom> from emerge"
   echo -e "    "$BBon"[-Y | --go-ahead]"$Boff".........automatically continue to next phases"
   echo -e "    "$BBon"[-Z | --keep-going]"$Boff".......on emerge failure, try to keep emerging other packages"
   echo -e "   Options for ${phase_message[3]}"   ## phase 3 - Review news and Maintain Config Files
   echo -e "    "$LBon"[for future development]"$Boff
   echo -e "   Options for ${phase_message[4]}"   ## phase 4 - Review elogs
   echo -e "    "$LBon"[for future development]"$Boff
   echo -e "   Options for ${phase_message[5]}"   ## phase 5 - Handle Dependencies
   echo -e "    "$LBon"[for future development]"$Boff
   echo -e "   Options for ${phase_message[6]}"   ## phase 6 - Final steps
   echo -e "    "$BBon"[-a | --glsa]"$Boff".............run glsa-check -vp affected"
   echo -e "    "$BBon"[-e | --eix]"$Boff"..............run eix-update"
   echo -e "    "$BBon"[-m | --modules]"$Boff"..........run emerge @module-rebuild"
   echo -e "    "$BBon"[-M | --emaint]"$Boff"...........run emaint --check all"
   echo -e "    "$BBon"[-p | --perl_cleaner]"$Boff".....run perl-cleaner --all"
   echo -e "    "$BBon"[-P | --python]"$Boff"...........run python-updater"
   echo -e "    "$BBon"[-S | --selinux]"$Boff"..........redo selinux lablels"
   echo -e "    "$BBon"[-t | --rkhunter]"$Boff".........run rkhunter --propupd"
   echo -e "    "$BBon"[-X | --X11]"$Boff"..............run emerge @x11-module-rebuild"
   echo -e "    "$BBon"[-H | --haskell]"$Boff"..........run haskell-updater"
   echo
   echo -e "  "$BYon"Notes: "$Boff
   echo -e "  "$BYon" 1)"$Boff" --status and --resume both identify the next phase"
   echo -e "    (which is the last successfully completed phase + 1)"
   echo -e "  "$BYon" 2)"$Boff" --sync is set automatically if portage tree is older"
   echo -e "    than MAX_AGE (set in jus.conf)"
   echo -e "  "$BYon" 3)"$Boff" option(s) -[k|K|g|G] function as explained in gentoo binary package guide:"
   echo -e "    https://wiki.gentoo.org/wiki/Binary_package_guide"
   echo
}

status()
{
    read phase < ${STATUS_FILE}
    echo "next phase: ${phase_message[${phase}]}"
    echo
}

display_config()
{
message "${BWon}Using configuration data below: ${Boff}"
echo -e ${BYon}"Global Congiguration${Boff}"
echo -e ${LBon}"Configuration..........: "${Boff}${CONF_DIR}
echo -e ${LBon}"SCRIPT_DIR.............: "${Boff}${SCRIPT_DIR}
echo -e ${LBon}"STATUS_FILE............: "${Boff}${STATUS_FILE}
echo -e ${LBon}"DISTCC.................: "$(status_color ${DISTCC})${DISTCC}${Boff}
echo -e ${LBon}"EIX....................: "$(status_color ${EIX})${EIX}${Boff}
echo -e ${LBon}"VERBOSE................: "$(status_color ${VERBOSE})$(TrueFalse ${VERBOSE})${Boff}
echo -e ${LBon}"verbosity..............: "${Boff}${verbosity}
echo -e ${BYon}"Options for Phase 0 - ${phase_message[0]}${Boff}"   ## phase 0 - Sync
echo -e ${LBon}"SYNC...................: "$(status_color ${SYNC})${SYNC}${Boff}
echo -e ${LBon}"REGEN_OVERLAY_METADATA.: "$(status_color ${REGEN_OVERLAY_METADATA})${REGEN_OVERLAY_METADATA}${Boff}
echo -e ${LBon}"SYNC_CMD...............: "${Boff}${SYNC_CMD}
echo -e ${LBon}"SYNC_TS................: "${Boff}${SYNC_TS}
echo -e ${LBon}"MAX_AGE................: "${Boff}${MAX_AGE}
echo -e ${BYon}"Options for Phase 1 - ${phase_message[1]}${Boff}"   ## phase 1 - Update Check
echo -e ${LBon}"UPDATE_CHECK...........: "$(status_color ${UPDATE_CHECK})${UPDATE_CHECK}${Boff}
echo -e ${BYon}"Options for Phase 2 - ${phase_message[2]}${Boff}"   ## phase 2 - Emerge Updates
echo -e ${LBon}"USEPKG.................: "$(status_color ${USEPKG})${USEPKG}${Boff}
echo -e ${LBon}"USEPKGONLY.............: "$(status_color ${USEPKGONLY})${USEPKGONLY}${Boff}
echo -e ${LBon}"GETBINPKG..............: "$(status_color ${GETBINPKG})${GETBINPKG}${Boff}
echo -e ${LBon}"GETBINPKGONLY..........: "$(status_color ${GETBINPKGONLY})${GETBINPKGONLY}${Boff}
echo -e ${LBon}"WITH_BDEPS_Y...........: "$(status_color ${WITH_BDEPS_Y})${WITH_BDEPS_Y}${Boff}
echo -e ${LBon}"GO_AHEAD...............: "$(status_color ${GO_AHEAD})${GO_AHEAD}${Boff}
echo -e ${LBon}"KEEPGOING..............: "$(status_color ${KEEPGOING})${KEEPGOING}${Boff}
echo -e ${LBon}"EXCLUDE................: "${Boff}${EXCLUDE}
echo -e ${BYon}"Options for Phase 3 - ${phase_message[3]}${Boff}"   ## phase 3 - Review news and Maintain Configs
echo -e ${BYon}"Options for Phase 4 - ${phase_message[4]}${Boff}"   ## phase 4 - Review elogs
echo -e ${BYon}"Options for Phase 5 - ${phase_message[5]}${Boff}"   ## phase 5 - Handle Dependencies
echo -e ${BYon}"Options for Phase 6 - ${phase_message[6]}${Boff}"   ## phase 6 - Final Steps
echo -e ${LBon}"EIX_UPDATE.............: "$(status_color ${EIX_UPDATE})${EIX_UPDATE}${Boff}
echo -e ${LBon}"HASKELL_UPDATER........: "$(status_color ${HASKELL_UPDATER})${HASKELL_UPDATER}${Boff}
echo -e ${LBon}"MODULE_REBUILD.........: "$(status_color ${MODULE_REBUILD})${MODULE_REBUILD}${Boff}
echo -e ${LBon}"PERL_CLEANER...........: "$(status_color ${PERL_CLEANER})${PERL_CLEANER}${Boff}
echo -e ${LBon}"PYTHON_UPDATER.........: "$(status_color ${PYTHON_UPDATER})${PYTHON_UPDATER}${Boff}
echo -e ${LBon}"RESUME.................: "$(status_color ${RESUME})${RESUME}${Boff}
echo -e ${LBon}"SELINUX_RELABEL........: "$(status_color ${SELINUX_RELABEL})${SELINUX_RELABEL}${Boff}
echo -e ${LBon}"RKHUNTER...............: "$(status_color ${RKHUNTER})${RKHUNTER}${Boff}
echo -e ${LBon}"X11_MODULE_REBUILD.....: "$(status_color ${X11_MODULE_REBUILD})${X11_MODULE_REBUILD}${Boff}
echo -e ${LBon}"GLSA_CHECK.............: "$(status_color ${GLSA_CHECK})${GLSA_CHECK}${Boff}
echo -e ${LBon}"EMAINT_CHECK...........: "$(status_color ${EMAINT_CHECK})${EMAINT_CHECK}${Boff}
}

check_timestamp()
{
    # compute age in hours of timestamp on file passed as argument
    # set $SYNC flag to "yes" if timestamp is older than $MAX_AGE allows
    SPM=60   # seconds per minute
    MPH=60   # minutes per hour
    agehours=$(( $(( $(date -u +%s) - $(date -u -r $1 +%s))) / $SPM / $MPH ))
    #if it's old, set SYNC flag
    message "Portage tree last sync'd $agehours hours ago"
    [ "$SYNC" == "yes" ] && \
        message "option: sync set by command line" || \
        message "option: sync not set by command line"
    if [ $agehours -gt $MAX_AGE ]
    then
        if [ "$GO_AHEAD" == "yes" ]
        then
            # sanity-check: unwise to go-ahead immediately after sync
            #  without checking what will be merged
            E_message "You selected option: go-ahead " && \
            E_message "but you also set MAX_AGE: $MAX_AGE hours in jus.conf" && \
            E_message "The latter would cause this program to sync and then auto-emerge non-interactively" && \
            E_message "(you should never merge packages blindly, please check first)" && \
            useage && exit 1
        else
            SYNC="yes" && \
            message "portage tree sync required by MAX_AGE ($MAX_AGE hours) set in jus.conf"
        fi
    else
        message "portage tree sync not required by MAX_AGE ($MAX_AGE hours) set in jus.conf"
    fi
}

emerge_sync()
{
    # check to see if portage tree is up to date
    # if timestamp of last emerge --sync is old, do a new one
    check_timestamp "$SYNC_TS"
    if [ "$SYNC" == "yes" ]
    then
        fixpackages   # Perform package move updates for all packages
        case ${SYNC_CMD} in
            "WEBRSYNC" ) message "Running emerge-webrsync... " && emerge-webrsync ;;
            "SYNC"     ) message "Running emerge --sync... " && emerge --sync ;;
            "EIX_SYNC" ) message "Running eix-sync..." && eix-sync ;;
            *          ) E_message "Error: invalid sync option [ $SYNC_CMD ]" ; return 1 ;;
        esac
        [ "${REGEN_OVERLAY_METADATA}" == "yes" ] && message "Running emerge --regen ..." && emerge --regen
    else
        message "Not running a sync for portage tree."
    fi
    return 0
}

update_check()
{
  # repurposed with ver 6 -- used to separate updateables into distcc-friendly and -unfriendly lists
  # with ver 6, just check for major upgrades in key packages
  # (linux-headers, glibc, binutils, libtool, gcc) and branch to full rebuild

  key_packages=(
    'sys-kernel/linux-headers'
    'sys-libs/glibc'
    'sys-devel/binutils'
    'sys-devel/gcc-config'
    'sys-devel/libtool'
    'sys-devel/gcc'
    )
  KP_FOUND=${FALSE}

  # first populate the updateables list (note, calling script has already run emerge_sync()
  if [ "$EIX" == "yes" ]
  then
    if [[ "$SYNC_CMD" != "EIX_SYNC" ]]
    then
      ### make sure the index is current
      d_message "${BMon}running eix-update to ensure index is up to date${Boff}" 1 ;
      eix-update ;
    else
      d_message "${BMon}eix-update not needed -- eix-sync should have already done it -- continuing...${Boff}" 1 ;
    fi
    d_message "EIX=[$EIX]; assiging updateables with \"eix -u\"" 1 ;
    updateables=($(eix -u#)) ;
  else
    d_message "EIX=[$EIX]; assigning updateables with \"emerge -puDN world | grep ...\" please wait..." 1 ;
    updateables=($(for x in $(emerge -puDN world | grep '\[ebuild' | cut -c18- | cut -d' ' -f1); do qatom -F %{CATEGORY}/%{PN} $x; done)) ;
  fi

  # now determine if any key packages are in the updatables list
  updateablecount=${#updateables[@]}
  message "${BWon}There are $updateablecount ${LBon}updateable installed${BWon} packages:${Boff}"
  for ((i=0; i<${updateablecount}; i++))
  do
    pkg_color=${BGon}
    # determine if this is a key package using bs() tool in script_header_brendlefly_extended
    depth=0; bs ${updateables[i]} 0 ${#key_packages[@]} ${key_packages[@]}
    d_message "$i ${updateables[i]} $result" 1
    [[ ${result} -gt 0 ]] && KP_FOUND=${TRUE} && pkg_color=${BRon}
    echo -e "   ${pkg_color}${updateables[i]}${Boff}"
    [[ ${result} -gt 0 ]] && echo -n "       " && eix -uc ${updateables[i]}
  done
  if [[ ${KP_FOUND} ]]
  then
    echo

    update_message="${BRon}  **  ${BYon}There is a key package to update\n" \
    update_message+="  --> ${BRon}if this is a major version upgrade, ${BWon}exit ${BRon}and run a ${BWon}rebuild ${BRon}sequence ${BYon}(rus)${Boff}\n" \
    update_message+="  --> ${BMon}if binary package server is updated, ${BWon}rebuild toolchain${BMon} and then run ${BGon}emerge -avbgke world --keep-going${Boff}"
  else
    update_message="${BGon}  **  ${BYon}There are no key pakages to update\n" \
    update_message+="  --> ${BGon}ok to continue update sequence${Boff}"
  fi
  message "${update_message}"
  d_message "done with update_check. returning with answer = [ $answer ]" 1
  return 0
}

emerge_updates()
{
    # assemble the emerge option string and message with baseline options (note --oneshot prevents jus
    #   from just adding all updateable packages to the world favorites file)
    OPTS1="uvDN"
    OPTS2=""
    MSG="emerging updates"
    if [ ! "${GO_AHEAD}" == "yes" ]
    then
        OPTS1="a"${OPTS1}
        MSG+=" interactively"
    else
        MSG+=" non-interactively"
    fi
    [ "${USEPKG}" == "yes" ] && OPTS1+="k"
    [ "${USEPKGONLY}" == "yes" ] && OPTS1+="K"
    [ "${GETBINPKG}" == "yes" ] && OPTS1+="g"
    [ "${GETBINPKGONLY}" == "yes" ] && OPTS1+="G"
    [ "${KEEPGOING}" == "yes" ] && OPTS2+=" --keep-going"
    [ "${WITH_BDEPS_Y}" == "yes" ] && OPTS2+=" --with-bdeps=y"

    # add --binpkg-respect-use=y and --binpkg-changed-deps=y universally (for now anyway)
    OPTS2+=" --binpkg-respect-use=y --binpkg-changed-deps=y"

    # if we have an exclude, put it on the end of the command line
    [ ! -z "${EXCLUDE}" ] && OPTS2+=" --exclude ${EXCLUDE}"

    message "${MSG}"
    # first, emerge the packages that do not like distcc (if any need it)
    # then, emerge the packages that do like distcc (if any need it)
    [[ "$DISTCC" == "yes" ]] && MyCMD='FEATURES="${FEATURES} distcc" ' || MyCMD=""
    MyCMD+="emerge -${OPTS1} @world${OPTS2}" && \
    message "${BWon}About to run - [ ${BRon}${MyCMD}${BWon} ]${Boff}" && \
    eval ${MyCMD} || return 1
    return 0
}

show_news()
{
    # display any news...
    message "The following news has been generated:"
    eselect news read new
    echo
}

maintain_config_files()
{
    # run dispatch-conf to maintain configs, if this is necessary
    # if the optional go-ahead flag is set, skip this (remind user later)
    if $( [[ -z "$(find /etc/ -iname '*._cfg***')" ]] && \
       [[ -z "$(find /usr/share/config/ -iname '*._mrg***')" ]] )
    then
        message "No config files need maintenance."
    else
        if [ ! "$GO_AHEAD" == "yes" ]     # note: use of the GO_AHEAD option will cause this phase to be skipped
        then
            message "Launching dispatch-conf to maintain the following config files:"
            echo $(find /etc/ -iname '*._cfg***')
            dispatch-conf
        fi  # not go_ahead
    fi  # find/not-find
    echo
    return 0
}

showelogs()
{
    # run show-elogs script to apply important phases from emerge notes
    # if the optional go-ahead flag is set, skip this (remind user later)
    message "Running show-elogs -l | less ..." && [ "$GO_AHEAD" == "no" ] && ${SCRIPT_DIR}show-elogs -l | less && return 0 || return 1
}

handle_dependencies()
{
    echo && message "Running emerge -av --depclean ..." && emerge -av --depclean
    echo && message "Running emerge @preserved-rebuild ..." && emerge @preserved-rebuild
    echo && message "Running revdep-rebuild -p ..." && revdep-rebuild -p
    # recommend you run revdep-rebuild again if it had to
    #   emerge something to fix dependencies
    # TO DO: check if that is the case and ask this only if so
    [ "$GO_AHEAD" == "no" ] && \
    echo -en $BYon"would you like to run revdep-rebuild again, for action? (y/n) "$Boff && \
    read rerun && echo || \
    rerun="y"
    case $rerun in
        "y") revdep-rebuild ;;
        *) ;; # do nothing
    esac
    echo && message "Double-checking configuration files now ..." && maintain_config_files
    return 0
}

final_phases()
{
    # as indicated by option flags, perform additional phases
    [ "${EIX_UPDATE}" == "yes" ] && [ "${SYNC_CMD}" != "EIX_SYNC" ] && message "Running eix-update ..." && eix-update
    [ "${PERL_CLEANER}" == "yes" ] && message "Running ${BGon}perl-cleaner --all${Boff} ..." && perl-cleaner --all
    [ "${HASKELL_UPDATER}" == "yes" ] && message "Running ${BGon}haskell-updater${Boff} ..." && haskell-updater
    [ "${PYTHON_UPDATER}" == "yes" ] && message "Running ${BGon}eselect python update${Boff} ..." && eselect python update && eselect python cleanup
    [ "${MODULE_REBUILD}" == "yes" ] && message "Running ${BGon}emerge @module-rebuild${Boff} ..." && emerge @module-rebuild
    [ "${X11_MODULE_REBUILD}" == "yes" ] && message "Running ${BGon}emerge @x11-module-rebuild${Boff} ..." && emerge @x11-module-rebuild
    [ "${SELINUX_RELABEL}" == "yes" ] && message "Running ${BGon}rlpkg -a -r${Boff} ..." && rlpkg -a -r
    [ "${RKHUNTER}" == "yes" ] && message "Running ${BGon}rkhunter --propupd${Boff} ..." && rkhunter --propupd
    [ "${GLSA_CHECK}" == "yes" ] && message "Running ${BGon}glsa-check -vp affected${Boff} ..." && glsa-check -vp affected
    [ "${EMAINT_CHECK}" == "yes" ] && message "Running ${BGon}emaint --check all${Boff} ..." && emaint --check all

    # clean un-needed package and distribution files, run localepurge
    [ -d "/usr/portage/packages" ] && message "Running ${BGon}eclean-pkg${Boff} ..." && eclean-pkg
    message "Running ${BGon}eclean-dist -d${Boff} ..." && eclean-dist -d
    return 0
}

get_answer()        # set external variable $answer based on reponse to prompt $1
{ ps=$1; echo; echo; CUU; SCP; message_n "$ps [yngYNG]: " && read answer;
while ! expr "${answer:0:1}" : [yngYNG] >/dev/null;  # answer not a regex match
do RCP; echo -en "$(repeat ' ' $(termwidth))";  ## blank the line
RCP; message_n "$ps [yngYNG]: " && read answer; done; }

# --- start main script ---------------------------------------------------------

# display script kick-off separator
separator "joetoo Update Sequence -- jus-${BUILD}"

# process command line to set and check sanity of option flags
process_command_line $*

# must be root
message "Checking root UID... "&& checkroot

# display config variables from jus.conf and option flags from command line
display_config

# if calling for an update check, then sync if necessary and list updateables
[ "$UPDATE_CHECK" == "yes" ] && emerge_sync && update_check && exit 0

# if resuming, retrieve number of next phase to be performed from status file
[ "$RESUME" == "yes" ] && read phase < $STATUS_FILE

[[ "$GO_AHEAD" == "yes" ]] && answer="g" || answer=""
# proceed thru each phase, as allowed to continue, until complete
for ((l=phase; l<${#phase_function_sequence[@]}; l++))
do
  [[ ! $answer == [gG] ]] && answer="" && \
    separator "${phase_message[l]}" "jus-${BUILD} Now starting" && \
    get_answer "Are you ready to ${BYon}${phase_message[l]}${Boff}?"
  if [[ $answer == [YyGg] ]]
  then
    [[ $answer == [gG] ]] && GO_AHEAD="yes"
    message "About to run [ $l of ${#phase_function_sequence[@]} : ${phase_function_sequence[l]} ]"
    eval ${phase_function_sequence[l]}; right_status $?
    echo $l > ${STATUS_FILE}
  else
    message "User chose NOT to ${BYon}${phase_message[l]}${Boff}. Quitting..."
    echo $l > ${STATUS_FILE}
    exit
  fi
done

# if go-ahead flag was set, remind user and check for new configs and elogs
if [ "$GO_AHEAD" == "yes" ]
then
    # remind user
    message "You ran update sequence with option: go-ahead."

    # check for new config files
    if [[ ! -z "$(find /etc/ -iname '*._cfg***')" ]] || \
       [[ ! -z "$(find /usr/share/config/ -iname '*._mrg***')" ]]
    then
        E_message 'You have updated config files pending. You should run "dispatch-conf"'
        E_message "found the following pending config file updates:"
        echo $(find /etc/ -iname '*._cfg***')
    fi # found new configs

    # check for elogs
    for x in $(ls $ELOG_DIR | cut -d":" -f 3 | cut -d"-" -f 1 | sort -nu); do : ; done && \
    [ "$x" == "$(date -u +%Y%m%d)" ] && \
    E_message 'jus produced new elogs.  You should run "show-elogs"'
fi  # go_ahead

echo && message "Don't forget rebuild modules if needed\n\temerge @[x11-]module-rebuild\n"

/usr/bin/logger -p cron.notice "jus complete at $(my_short_date)."
msg="Logged and done at: "$(date +"%T %Z, %d %B %Y.")
message "$msg"
exit 0
