#!/bin/bash
source /usr/sbin/script_header_joetoo
BUILD=0.0.0001a
separator "examine_timestamps-$BUILD"
message "about to issue command [ for x in \$(locate metadata/timestamp); do echo \"----[ \$x ]----\" && cat \$x; done ] "
for x in $(locate metadata/timestamp); do echo "----[ $x ]----" && cat $x; done
message "updating mlocate database..." && updatedb
