#!/bin/bash

for x in $(echo "
=kde-frameworks/kpackage-5.39.0 ~amd64
# required by kde-frameworks/baloo-5.37.0::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo[semantic-desktop]
# required by media-video/plasma-mediacenter (argument)
=kde-frameworks/kcrash-5.39.0 ~amd64
# required by kde-frameworks/ktextwidgets-5.39.0::gentoo
# required by kde-frameworks/kio-5.39.0::gentoo
# required by kde-plasma/plasma-vault-5.11.3::gentoo
# required by kde-plasma/plasma-vault (argument)
=kde-frameworks/kwidgetsaddons-5.39.0 ~amd64
# required by kde-plasma/plasma-vault-5.11.3::gentoo
# required by kde-plasma/plasma-vault (argument)
=kde-frameworks/kconfigwidgets-5.39.0 ~amd64
# required by app-crypt/kencfs-plasma (argument)
=app-crypt/kencfs-plasma-2.0.1_alpha ~amd64
# required by kde-plasma/plasma-desktop-5.10.5::gentoo
# required by @selected
# required by @world (argument)
=kde-frameworks/plasma-5.39.0 ~amd64
# required by kde-frameworks/plasma-5.39.0::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo
# required by media-video/plasma-mediacenter (argument)
=kde-frameworks/karchive-5.39.0 ~amd64
# required by kde-frameworks/kcmutils-5.37.0::gentoo
# required by kde-apps/ktp-text-ui-17.04.3::gentoo
# required by kde-apps/plasma-telepathy-meta-17.04.3::gentoo
# required by kde-apps/kdenetwork-meta-17.04.3::gentoo
# required by @selected
# required by @world (argument)
=kde-frameworks/kauth-5.39.0 ~amd64
# required by kde-frameworks/kconfigwidgets-5.39.0::gentoo[man]
# required by kde-frameworks/kbookmarks-5.39.0::gentoo
# required by kde-frameworks/kio-5.39.0::gentoo
# required by kde-plasma/plasma-vault-5.11.3::gentoo
# required by kde-plasma/plasma-vault (argument)
=kde-frameworks/kdoctools-5.39.0 ~amd64
# required by kde-plasma/plasma-vault-5.11.3::gentoo
# required by kde-plasma/plasma-vault (argument)
=kde-frameworks/ki18n-5.39.0 ~amd64
# required by kde-apps/konqueror-17.04.3::gentoo
# required by kde-apps/kdecore-meta-17.04.3::gentoo
# required by kde-apps/kdebase-meta-17.04.3::gentoo
# required by kde-apps/kdebase-meta (argument)
=kde-frameworks/kcompletion-5.39.0 ~amd64
# required by kde-apps/dolphin-17.04.3::gentoo
# required by kde-apps/kdecore-meta-17.04.3::gentoo
# required by kde-apps/kdebase-meta-17.04.3::gentoo
# required by kde-apps/kdebase-meta (argument)
=kde-frameworks/kjobwidgets-5.39.0 ~amd64
# required by kde-frameworks/kconfig-5.39.0::gentoo
# required by kde-plasma/libksysguard-5.11.3::gentoo
# required by kde-plasma/plasma-vault-5.11.3::gentoo
# required by kde-plasma/plasma-vault (argument)
=kde-frameworks/extra-cmake-modules-5.39.0 ~amd64
# required by kde-plasma/kwin-5.10.5::gentoo
# required by kde-plasma/plasma-workspace-5.10.5-r1::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo
# required by media-video/plasma-mediacenter (argument)
=kde-frameworks/kactivities-5.39.0 ~amd64
# required by kde-frameworks/kconfigwidgets-5.39.0::gentoo
# required by kde-frameworks/kbookmarks-5.39.0::gentoo
# required by kde-frameworks/kio-5.39.0::gentoo
# required by kde-plasma/plasma-vault-5.11.3::gentoo
# required by kde-plasma/plasma-vault (argument)
=kde-frameworks/kcodecs-5.39.0 ~amd64
# required by kde-frameworks/kcmutils-5.37.0::gentoo
# required by kde-apps/ktp-text-ui-17.04.3::gentoo
# required by kde-apps/plasma-telepathy-meta-17.04.3::gentoo
# required by kde-apps/kdenetwork-meta-17.04.3::gentoo
# required by @selected
# required by @world (argument)
=kde-frameworks/kdeclarative-5.39.0 ~amd64
# required by kde-apps/k3b-17.04.3-r1::gentoo
# required by kde-apps/kdemultimedia-meta-17.04.3::gentoo[cdrom]
# required by @selected
# required by @world (argument)
=kde-frameworks/solid-5.39.0 ~amd64
# required by kde-frameworks/ktextwidgets-5.39.0::gentoo
# required by kde-frameworks/kio-5.39.0::gentoo
# required by kde-plasma/plasma-vault-5.11.3::gentoo
# required by kde-plasma/plasma-vault (argument)
=kde-frameworks/kconfig-5.39.0 ~amd64
# required by kde-apps/akonadi-contacts-17.04.3::gentoo
# required by kde-apps/kgpg-17.04.3::gentoo
# required by kde-apps/kdeutils-meta-17.04.3::gentoo
# required by @selected
# required by @world (argument)
=kde-frameworks/kservice-5.39.0 ~amd64
# required by kde-plasma/plasma-desktop-5.10.5::gentoo
# required by @selected
# required by @world (argument)
=kde-frameworks/kwallet-5.39.0 ~amd64
# required by kde-plasma/ksysguard-5.10.5::gentoo
# required by kde-plasma/plasma-workspace-5.10.5-r1::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo
# required by media-video/plasma-mediacenter (argument)
=kde-frameworks/kinit-5.39.0 ~amd64
# required by kde-frameworks/knewstuff-5.37.0::gentoo
# required by kde-apps/dolphin-17.04.3::gentoo
# required by kde-apps/kdecore-meta-17.04.3::gentoo
# required by kde-apps/kdebase-meta-17.04.3::gentoo
# required by kde-apps/kdebase-meta (argument)
=kde-frameworks/kcoreaddons-5.39.0 ~amd64
# required by kde-frameworks/ktexteditor-5.37.0::gentoo
# required by kde-plasma/plasma-workspace-5.10.5-r1::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo
# required by media-video/plasma-mediacenter (argument)
=kde-frameworks/kguiaddons-5.39.0 ~amd64
# required by kde-plasma/khotkeys-5.10.5::gentoo
# required by kde-plasma/kmenuedit-5.10.5::gentoo[hotkeys]
# required by kde-plasma/plasma-meta-5.10.5::gentoo
# required by kde-apps/kdebase-meta-17.04.3::gentoo
# required by kde-apps/kdebase-meta (argument)
=kde-frameworks/kded-5.39.0 ~amd64
# required by kde-plasma/ksysguard-5.10.5::gentoo
# required by kde-plasma/plasma-workspace-5.10.5-r1::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo
# required by media-video/plasma-mediacenter (argument)
=kde-frameworks/kiconthemes-5.39.0 ~amd64
# required by kde-plasma/plasma-workspace-5.10.5-r1::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo
# required by media-video/plasma-mediacenter (argument)
=kde-plasma/libksysguard-5.11.3 ~amd64
# required by kde-frameworks/kcmutils-5.37.0::gentoo
# required by kde-apps/ktp-text-ui-17.04.3::gentoo
# required by kde-apps/plasma-telepathy-meta-17.04.3::gentoo
# required by kde-apps/kdenetwork-meta-17.04.3::gentoo
# required by @selected
# required by @world (argument)
=kde-frameworks/kxmlgui-5.39.0 ~amd64
# required by kde-plasma/kwin-5.10.5::gentoo
# required by kde-plasma/plasma-workspace-5.10.5-r1::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo
# required by media-video/plasma-mediacenter (argument)
=kde-frameworks/kwindowsystem-5.39.0 ~amd64
# required by kde-frameworks/plasma-5.39.0::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo
# required by media-video/plasma-mediacenter (argument)
=kde-frameworks/kio-5.39.0 ~amd64
# required by kde-plasma/plasma-vault (argument)
=kde-plasma/plasma-vault-5.11.3 ~amd64
# required by kde-plasma/khotkeys-5.10.5::gentoo
# required by kde-plasma/kmenuedit-5.10.5::gentoo[hotkeys]
# required by kde-plasma/plasma-meta-5.10.5::gentoo
# required by kde-apps/kdebase-meta-17.04.3::gentoo
# required by kde-apps/kdebase-meta (argument)
=kde-frameworks/ktextwidgets-5.39.0 ~amd64
# required by kde-plasma/khotkeys-5.10.5::gentoo
# required by kde-plasma/kmenuedit-5.10.5::gentoo[hotkeys]
# required by kde-plasma/plasma-meta-5.10.5::gentoo
# required by kde-apps/kdebase-meta-17.04.3::gentoo
# required by kde-apps/kdebase-meta (argument)
=kde-frameworks/kglobalaccel-5.39.0 ~amd64
# required by kde-frameworks/kdelibs4support-5.37.0::gentoo
# required by kde-apps/kmix-17.04.3::gentoo
# required by kde-apps/kdemultimedia-meta-17.04.3::gentoo
# required by @selected
# required by @world (argument)
=kde-frameworks/kdbusaddons-5.39.0 ~amd64
# required by kde-apps/kmix-17.04.3::gentoo
# required by kde-apps/kdemultimedia-meta-17.04.3::gentoo
# required by @selected
# required by @world (argument)
=kde-frameworks/knotifications-5.39.0 ~amd64
# required by kde-apps/ktp-text-ui-17.04.3::gentoo
# required by kde-apps/plasma-telepathy-meta-17.04.3::gentoo
# required by kde-apps/kdenetwork-meta-17.04.3::gentoo
# required by @selected
# required by @world (argument)
=kde-frameworks/sonnet-5.39.0 ~amd64
# required by kde-plasma/ksysguard-5.10.5::gentoo
# required by kde-plasma/plasma-workspace-5.10.5-r1::gentoo
# required by media-video/plasma-mediacenter-5.7.5::gentoo
# required by media-video/plasma-mediacenter (argument)
=kde-frameworks/kitemviews-5.39.0 ~amd64
# required by kde-frameworks/kio-5.39.0::gentoo
# required by kde-plasma/plasma-vault-5.11.3::gentoo
# required by kde-plasma/plasma-vault (argument)
=kde-frameworks/kbookmarks-5.39.0 ~amd64
" | grep -v '#' | sed 's/^=//' | cut -d' ' -f1); do echo $(qatom $x | cut -d' ' -f1,2 | sed 's/ /\//') ~amd64; done
