#!/bin/bash
source /usr/sbin/script_header_joetoo
source /usr/sbin/script_header_joetoo_extended

frequencies=(0 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 2484)

useage() {
  j_msg -${err} "Useage: freq2chan <freq>"
  j_msg -${err} "  where <freq> is one of:"
  j_msg -${err} "     2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 2484"
}

test() {
for ((i=0; i<${#frequencies[@]}; i++))
do
  j_msg -mp $i: ${frequencies[i]}
done
}

[ $# -ne 1 ] && useage && exit 1
[ $1 -gt 2484 ] && useage && exit 1
[ $1 -lt 2412 ] && useage && exit 1

freq=$1
#bs() is a recursive binary search for $1 target(s) from $2 start(d) to $3 end(d) in search_list $@
#     (after 3 shifts)
result=0; depth=0
j_msg -${notice} -p -n "Looking up the channel for frequency ${freq}..."
bs  ${freq} 1 ${#frequencies[@]} ${frequencies[@]}; right_status $?
j_msg -${notice} -p "Frequency ${freq} is channel: $result"
