#!/bin/bash

#d_message_n "sourcing make.conf to set PORTDIR, PKGDIR ..." 1
j_msg -${notice} -p -n "sourcing make.conf to set PKGDIR ..."
PKGDIR=$(source /etc/portage/make.conf ; echo $PKGDIR)
right_status $? ${notice}

j_msg -${notice} -p -n "sourcing make.conf to set PORTDIR ..."
PORTDIR=$(source /etc/portage/make.conf ; echo $PORTDIR)
right_status $? ${notice}


for y in \
    $(for x in \
        $(grep '>' /home/joe/temp | \
          cut -d'>' -f2 | \
          sed 's/\ //'); \
        do qatom $x; \
     done | awk '{ print $1"/"$2 }'); \
do rm -rv $PKGDIR/${y}*; \
done
