#!/bin/bash
[[ $# -gt 0 ]] && \
    MAKEOPTS="-j1" FEATURES=" getbinpkg -userpriv -distcc -distcc-pump" emerge -av1 \
         $(echo "$@" | grep '(' | cut -d'(' -f2 | cut -d':' -f1 | xargs qatom -F %{CATEGORY}/%{PN}) --keep-going --with-bdeps=y|| \
    echo "Error: provide a quoted \"failed to build\" list"


