#!/bin/bash
# distccmon-tui   (c) joe brendler 2026
#
#  bi-modal (client/server) dashboard for distcc
#  Note: uses script_header_joetoo including command line interface tools but not interactive sequencing
#        also uses script_header_joetoo_ssh tools for enabling root use of user ssh key to transfer
#        dns records and conduct remote status sensing, etc.
# ToDo: make use of a config file and possibly employ script_header_joetoo app_configure

#-----[ distcc client event lifecycle ]------------------------------------------------------------------------------------
# For a single job, distcc writes a sequence of status changes to the log file
# It includes these and more events ...
#   distcc[469498] (dcc_trace_version) distcc 3.4 x86_64-pc-linux-gnu; built Jun 10 2026 11:16:15
#   distcc[646584] (dcc_scan_args) found object/output file "src/accounts-daemon.p/extensions.c.o"
#   distcc[646584] (dcc_scan_args) found input file "../accountsservice-23.13.9/src/extensions.c"
#   distcc[646584] compile from extensions.c to extensions.c.o
#   distcc[646584] (dcc_lock_host) got cpu lock on gmki92,lzo/4 slot 0 as fd3
#   distcc[646584] exec on gmki92,lzo/4: x86_64-pc-linux-gnu-gcc -fdiagnostics-color=always -Wall -Winvalid-pch -O2 -pipe -march=k8-sse3 -mtune=k8 -msahf -pthread -o src/accounts-daemon.p/extensions.c.o -c ../accountsservice-23.13.9/src/extensions.c
#   distcc[646584] (dcc_note_state) note state 2, file "extensions.c", host "gmki92"
#   distcc[646584] cpp ../accountsservice-23.13.9/src/extensions.c on localhost completed ok
#   distcc[646584] (dcc_compile_remote) client finished sending request to server
#   distcc[646584] 1489729 bytes from ../accountsservice-23.13.9/src/extensions.c compiled on gmki92 in 3.1308s, rate 465kB/s
#   distcc[646584] compile ../accountsservice-23.13.9/src/extensions.c on gmki92,lzo/4 completed ok
#   distcc[646584] elapsed compilation time 3.136191s
#   distcc[646584] (dcc_exit) exit: code 0; self: 0.008061 user 0.016122 sys; children: 0.270012 user 0.214661 sys
#   distcc[3193833] (dcc_cleanup_tempfiles_inner) deleted 0 temporary files
#   distcc[469498] (dcc_spawn_child) child started as pid469499
#   distccd[1460350] (dcc_readx) ERROR: unexpected eof on fd5
#   distccd[1460350] (dcc_r_token_int) ERROR: read failed while waiting for token "DOTI"
# Note: client pid is terminated with (dcc_exit) - duration = one compile job done by remote server
#-----[ distcc server event lifecycle ]------------------------------------------------------------------------------------
#   distccd[96193] (dcc_check_client) connection from fd62:6262:6262:0:d9ac:eab7:6d40:2331:40662
#   distccd[96193] compile from gtkactions_interface.cpp to gtkactions_interface.cpp.o
#   distccd[96193] (dcc_r_file_timed) 2150561 bytes received in 0.897576s, rate 2340kB/s
#   distccd[96193] (dcc_collect_child) cc times: user 0.000000s, system 0.000000s, 0 minflt, 0 majflt
#   distccd[96193] x86_64-pc-linux-gnu-g++ /var/tmp/portage/kde-plasma/plasma-workspace-6.6.5-r1/work/plasma-workspace-6.6.5_build/gmenu-dbusmenu-proxy/gtkactions_interface.cpp
#                ...    on localhost completed ok
#   distccd[96193] job complete
#   distccd[96193] (dcc_job_summary) client: fd62:6262:6262:0:d9ac:eab7:6d40:2331:40662 COMPILE_OK exit:0 \
#                ... sig:0 core:0 ret:0 time:21251ms x86_64-pc-linux-gnu-g++  \
#                ... /var/tmp/portage/kde-plasma/plasma-workspace-6.6.5-r1/work/plasma-workspace-6.6.5_build/gmenu-dbusmenu-proxy/gtkactions_interface.cpp
#   distcc[2463201] ERROR: compile (null) on localhost failed
#   distcc[2463400] ERROR: compile /var/tmp/portage/dev-db/mysql...SymbolExists.c on nuthuvia,lzo/7 failed
# Mote: server pid persists as long as the server keeps this slot available (seemingly for one remote client) - multiple files compile locally for remote client

#-----[ headers ]----------------------------------------------------------------------------
# source script_header_joetoo to get CLR, CUP, termidth, repeat functions as well as others they
# depend on like isint, and to set up for later color/unicode beautification
source /usr/sbin/script_header_joetoo
source /usr/sbin/script_header_joetoo_ssh

#-----[ variables ]--------------------------------------------------------------------------

PN=${0##*/}     # basename
if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi

# default mode is server
# (Note: using client mode takes external steps to set DISTCC_LOG and DISTCC_VERBOSITY=1 for emerge)
mode=server

dns="elrond.brendler"
local_user="joe"
remote_user="joe"
SSH_KEY="/home/${local_user}/.ssh/id_rsa"

portage_tmpdir=$(portageq envvar PORTAGE_TMPDIR)
[ -z "$portage_tmpdir" ] && portage_tmpdir="/var/tmp"  # fallback
portage_prefix="${portage_tmpdir%/}/portage"   # use to extract package name from in/out filename

# to-do: make these config-file sourcable and/or command_line configurable
history_depth=5  #........# how many records to show in the recent history section
max_package_lines=4  #....# maximum number of lines to allow in the active packaages section
max_active_lines=9  #....# maximum number of lines to allow in the active records section
ssh_timeout=2  #..........# how many seconds to wait for ssh connection for dns update
tui_refresh_period=0.1  #.# tui screen refresh period
package_timeout=180  #....# how many seconds before expired package is "aged out"
job_timeout=600  #........# how many seconds before expired job (pid) is "aged out"
dead_pid_timeout=600  #...# how many seconds before a pid already declared dead is "aged out"
diagnostic_timeout=10  #..# how many seconds before expired diagnotic message is "aged out"
tw=$(termwidth)  #........# used only initially to set -v width for awk /// over-ridden by __HEARTBEAT__

# leverage cli tools in script_header_joetoo incl process_cmdline and show_config, but not using command sequence
# so just set some expected variables already in varlist with placeholder info
INTERACTIVE=$FALSE
LOGGING=$TRUE

log_dir="/var/log"
distcc_logdir="${log_dir%/}/distcc"
archive_dir="${log_dir%/}/old_logs"

logFile="${log_dir%/}/distcc/${PN}.log"
# tui_DISTCC_LOG is set in configure_mode

status_file="/root/bin/${PN}_status"
config_dir="/etc/${PN}"
config_files="${PN}.conf"
app_customization_root="${PN}"
local_cmdline_arg_handler="built-in"
starting_step=0
stopping_step=0
num_cmds=0
handle_local_arg_EXISTS=$TRUE
handle_local_compound_arg_EXISTS=$TRUE
handle_local_usage_EXISTS=$TRUE

varlist+=" mode dns local_user remote_user SSH_KEY package_timeout job_timeout ssh_timeout diagnostic_timeout"
varlist+=" tui_refresh_period history_depth max_active_lines tw portage_prefix rlv.tui_DISTCC_LOG"
varlist+=" rlv.grep_filter"

# AWKs data structure will include these associative arrays (not visible to bash)
# active_peers           # list of distcc remote peer client/servers keyed on pid of jobs they are working
# active_starts          # recorded start-time when this keyed pid was first observed (job start)
# active_input_files     # list of files processed in this keyed pid job
# active_output_files    # list of files processed in this keyed pid job
# active_outcomes        # result of remote compile job ( success / failure )
# active_duration        # list of elapsed compile time keyed on pid
# active_ip_addrs        # list of ip addresses for server mode keyed on pid
# active_packages        # list of packages keyed on pid
# last_contact           # systime stored for key (pid) every time pid is observed
# dead_pids              # list of pids declared dead after results found (prevent accidental "rejuvination"
# diagnostic_messages    # list of informative diagnostic messages to display

# TBD if this will be a bash associative array for reading dns hostnames keyed to ip
declare -A host_names      # list of host names, keyed on ip addresses (read from dns)
declare -A bash_reg_locks  # tbd if needed (anti-avalanche guard -  dont spawn redundant network tasks for the same IP)

# identify client mode selector string patterns to capture important lifecycle events as shown above
c_file_selector="compile from"  #..............# input_file = $4 ;  output_file = $6
c_pkg_selector="found input file${P1}/work" #..# pkg is extracted from $6/$NF
c_host_selector="\] exec on"  #................#  --> host_name = $4
#c_success_selector="completed ok"  #..........# && / compile / not / cpp /  -->  host_name = $5; outcome = success
#c_failure_selector="ERROR:"  #................# && /compile/ && /failed/ --> outcome = failure /// but pid may continue
c_result_selector="compile${P1} on" #..........# host_name = $5; outcome = $NF
c_elapsed_selector="elapsed compilation time"  # elapsed = $5
c_exit_selector="(dcc_exit)"  #................# record to history and delete from active records
c_child_selector="(dcc_spawn_child)"  #........# premptively declare pids dead to ignore child process
# todo: identify package selector
#   distcc[3193833] (dcc_cleanup_tempfiles_inner) deleted 0 temporary files

# identify server mode selector string patterns to capture important lifecycle events as shown above
s_ip_selector="(dcc_check_client)"  #.....#  --> host_ip_address = $NF /// incl port#
s_file_selector="compile from"  #..............# input_file = $4 ;  output_file = $6
s_success_selector="completed ok"  #...........# package = $3 (extractable);  outcome = success
s_failure_selector="ERROR:"  #.................# && /dcc_r/ --> outcome = all after ERROR:
s_summary_selector="(dcc_job_summary)"  #......# elapsed = $10; exit_code = $6 (set outcome)
#                                       #......# package = $12 (extract); infile = $12 (basename)
#                                       #......# also record to history and delete from active records

# set up diagnostic message type order to control order of display
diag_msg_type_order=(
    "dns_ip_diagnostic"
    "dns_host_diagnostic"
    "dns_cache_diagnostic"
    "ip_is_in_not_cache"
    "invalid_mode"
    "mode_mismatch"
    "pkg_index_lacking"
    "unexpected_data"
    "expired_job_pruned"
    "dead_pid_pruned"
)

# set up a readable array of variables to pass into the awk script
awk_vars=(
    -v hostname=$(hostname)
    -v mode="$mode"
    -v verbosity="$verbosity"
    -v DEBUG=$(TrueFalse $DEBUG)
    -v history_depth="$history_depth"
    -v pkg_timeout="$package_timeout"
    -v job_timeout="$job_timeout"
    -v dead_pid_timeout="$dead_pid_timeout"
    -v diagnostic_timeout="$diagnostic_timeout"
    -v port_prefix="$portage_prefix"
    -v width="$tw"
    -v W0="${W0}"       # W0="[[:space:]]*"     posix zero+ whitespace
    -v W1="${W1}"       # W1="[[:space:]]${W0}" posix one+ whitespace
    -v P0="${P0}"       # P0="[[:print:]]*"     posix zero+ printable
    -v P1="${P1}"       # P1="[[:print:]]${P0}" posix one+ printable
    -v clr="$(CLR)"
    -v cup="$(CUP)"
    -v line_clr="${BBon}"
    -v data_clr="${BMon}"
    -v ts_clr="${BAon}"
    -v host_clr="${Gon}"
    -v ip_clr="${BTon}"
    -v pkg_clr="${BLon}"
    -v file_clr="${Gon}"
    -v mode_clr="${BYon}"
    -v success_clr="${BGon}"
    -v failure_clr="${BRon}"
    -v title_clr="${BWon}"
    -v heading_clr="${BCon}"
    -v clr_off="${Boff}"
    -v placeholder_clr="${BOon}"
    -v max_package_lines="$max_package_lines"
    -v max_active_lines="$max_active_lines"
    -v diag_msg_type_order="${diag_msg_type_order[*]}"   # [*] vs [@] to create one space delimited string
)

#-----[ functions ]----------------------------------------------------------------------------

# try just including local cli stuff here instead of getting app_configure to source it
# Convention for cmdline arg handling:
#   set result=0 for success with no operand
#   set result=6 for success with operand
#   set result=7 for file not found (to differentiate from error)
#   set result=1 for error

handle_local_arg() # (POSIX) local compound arg handler to extend cli in script_header_joetoo
{ local hla_ret=0 _hla_arg="$1" _hla_operand="$2"
  j_msg -${debug} -p "in handle_local_arg with _hla_arg: [$_hla_arg], _hla_operand: [$_hla_operand]"
  case "$_hla_arg" in
    "-"[S] | "--server" )
      mode="server" || hla_ret=1
      j_msg -${notice} -p "assigned mode = server"
      ;;
    "-"[C] | "--client" )
      mode="client" || hla_ret=1
      j_msg -${notice} -p "assigned mode = client"
      ;;
    * )
      # NOTICE: getting here does not mean error - it just means no single flag option matched,
      # but $1 could still be a compound argument (cluster of single-letter flags), so we have
      # to differentiate that (not found) status from "error", and fall back to the main script's logic
      hla_ret=7 # not found
      ;;
  esac
  j_msg -${debug} -p "handle_local_arg complete, returning [$hla_ret]"
  return $hla_ret
}
# @usage handle_local_arg (called from script_header_joetoo)
# @args $1=current arg, $2=potential operand
# @ret 0: successful action option for flag identified, 1: error
# @ret 6: consumed an operand, 7: file not found
# @note operates at INFO severity level
# @note examines string for match to known flags (e.g. -r|--resume)

handle_local_compound_arg() # (POSIX) local compound arg handler to extend cli in script_header_joetoo
{ local hlca_ret=0 _hlca_char="$1" # Get the first character of the parent's _pca_args directly as $1 now
  j_msg -${debug} -p "in handle_local_compound_arg with _pca_args: [$_pca_args], _hlca_char: [$_hlca_char]"
  case "$_hlca_char" in
    [S] )
      mode="server" || hlca_ret=1
      j_msg -${notice} -p "assigned mode = server"
      ;;
    [C] )
      mode="client" || hlca_ret=1
      j_msg -${notice} -p "assigned mode = client"
      ;;
    *    )
      # NOTICE: getting here does not mean error - it just means no single flag option matched,
      # but $1 could still be a compound argument (cluster of single-letter flags), so we have
      # to differentiate that (not found) status from "error", and fall back to the main script's logic
      hlca_ret=7 # not found
      ;;
  esac
  j_msg -${debug} -p "handle_local_compound_arg complete, returning [$hlca_ret]"
  return $hlca_ret
}
# @usage handle_local_compound_arg (called from script_header_joetoo)
# @ret 0: successful action option for flag identified, 1: error, 7: file not found
# @rule this function expects the parent script to have already stripped the leading '-'
# @note operates at INFO severity level
# @note examines the *first character* of the remaining _pca_args string

handle_local_usage() # (POSIX) local usage module to extend cli in script_header_joetoo
{
  j_msg -${notice} -m "  -[S] | --server ..........: operate ${PN} in server mode"
  j_msg -${notice} -m "  -[C] | --client ..........: operate ${PN} in server mode"
  j_msg -${notice} -pm ""  # severity-sensitive newline
  j_msg -${notice} -m "${BYon}Copy/create/set configuration (/etc/${PN}/${PN}.conf)${Boff}"
  j_msg -${notice} -m "${BYon}using ${BGon}eselect$ ${PN} ${BWon}list|set n${Boff}"
  j_msg -${notice} -pm ""  # severity-sensitive newline
}
# @usage handle_local_usage  (called from usage() in script_header_joetoo)
# @rule user-script specific usage-module which should be built in joetoo format
# @rule this file must contain legitimate bash assignments and commands
# @note operates at NOTICE severity level
# @note options h, i, n, s, r, v, q V, Q are already used by the joetoo cmdline processor


good_connectivity() {
    local ip_addr="$1"
    # first check connectivity, and then if possible use ssh to get hostname from server and tell it to register with dns
    # -c count; -W wait; -n nodns; note gnu timeout assurance
#    if timeout 1.5 ping -c 1 -W 1.5 -n "$ip_addr" &>/dev/null ; then
    # switch to devtcp to use port 22
    if timeout 1.5 bash -c "</dev/tcp/${ip_addr}/22" 2>/dev/null; then
        return 0
    else
        return 1
    fi
}

maybe_get_and_register_hostname() {
    # take over the screen to do this
    CLR; CUP 1 1
    j_msg -$notice -p "getent failed looking up ip_address [$ip_address], but it pings; trying ssh"
    # if ssh_agent isnt started start it and load keys (should only need to happen once)
    if [ -z "$AGENT_ENV" ] ; then
        j_msg -$notice -p "AGENT_ENV not set up; doing so now"
        j_msg -$notice -p -n "starting ssh agent ..."
        start_ssh_agent "$local_user" "$SSH_KEY"
        handle_result $? '' 'failed to start_ssh_agent' $notice || exit 1
        j_msg -$notice -p -n "loading local_user ssh key"
        load_key "$local_user"
        handle_result $? '' 'failed to load_key' $notice || exit 1
        sleep 3
        CLR; CUP 1 1
    fi
#    d_do 'echo "AGENT_ENV_FILE:"; cat $AGENT_ENV_FILE; echo "==========================="' $debug
    j_msg -$notice -p -n "sourcing AGENT_ENV_FILE [$AGENT_ENV_FILE]"
    source $AGENT_ENV_FILE  # source ssh_agent stuff incl auth sock
    handle_result $? '' 'failed to source AGENT_ENV_FILE' $notice || echo "maybe exit here"
    # set up a specific-identity, batchmode, timeout-sensitive ssh command to use in all four cases
    local -a ssh_cmd=( ssh -q -o ConnectTimeout=2 -o BatchMode=yes -i "$SSH_KEY" "${remote_user}@${ip_address}" )
    # use ssh to ask the remote ip_address to tell its hostname
    j_msg -$notice -p -n "looking up hostname"
    host_name=$(sudo -E -u "${local_user}" "${ssh_cmd[@]}" hostname)
    handle_result $? "$host_name" 'failed to look up host_name' $notice
    # if that did not work, then mark it unknown
    if [ -z "$host_name" ] ; then
        j_msg -$debug -p "failed to get hostname from ip_address, despite good ping"
        return 1
    else
        # get interface and ask remote machine to submit unregistered hostname to dns
        # Note: using -- /usr/sbin/ddns-update "$EVENT" "$ADDR" "$INTERFACE" "$SOURCE"
        j_msg -$notice -p -n "looking up interface"
        ssh_payload_command="ip -o addr show | grep '$ip_address'"
        iface=$(sudo -E -u "$local_user" "${ssh_cmd[@]}" "$ssh_payload_command" | awk '{print $2}')
        result=$?
        handle_result $result "$iface" '' $notice || return 1
        if [ -z "$iface" ] ; then
            j_msg -$debug -p "Note: host [$host_name] ip address [$ip_address] [unknown interface] is not registered with dns"
            sleep 3
            return 1
        else
#echo "in NOT -z (i.e. else) branch of if -z iface block"
            j_msg "-${notice}" -p "Note: host [$host_name] ip address [$ip_address] is not registered with dns"
            j_msg -$notice -p -n "Asking host [$host_name] via ssh to do that now"
            # now via ssh have the remote machine submit the update
            ssh_payload_command="rm -f /run/ddns-daemon.cache.*"
            sudo -E -u "$local_user" "${ssh_cmd[@]}" "$ssh_payload_command"
            result=$?
#echo "just ran sudo ... ssh ... status: [$result]"
            ssh_payload_command="/usr/sbin/ddns-update 'add' '$ip_address' '$iface' '${PN}-${BUILD}'"
            sudo -E -u "$local_user" "${ssh_cmd[@]}" "$ssh_payload_command"
            result=$?
#echo "just ran sudo ... ssh ... status: [$result]"
            handle_result $result '' "Host [$host_name] failed to reginster [$ip_address], [$iface] with dn" $notice || return 1
            sleep 3
        fi
#echo "now completely past if -z iface block"
    fi
    return 0
}

configure_mode() {
    local c_ret=0
    j_msg -$debug -p "running ${FUNCNAME[0]} for mode: [$mode]"
    case "$mode" in
        client)
            # identify client log file
            # Note: externally, client emerge must use DISTCC_VERBOSE=1
            #   and DISTCC_LOG= either on the emerge command line or in make.conf
            tui_log_basename="distcc-client.log"
            # set up a client grep_filter string with selectors to capture important lifecycle events as shown above
            grep_filter='__HEARTBEAT__'  #..................# ignore heartbeat - just update clock
            grep_filter+="|${c_file_selector}"
            grep_filter+="|${c_pkg_selector}"
            grep_filter+="|${c_host_selector}"
            grep_filter+="|${c_result_selector}"
            grep_filter+="|${c_elapsed_selector}"
            grep_filter+="|${c_exit_selector}"
            grep_filter+="|${c_child_selector}"
            # append client selectors to awk_vars array for use in the awk script
            # (also include updates of vars that cmdline can modify (mode, verbosity, DEBUG)
            awk_vars+=(
                -v mode="$mode"
                -v verbosity="$verbosity"
                -v DEBUG=$(TrueFalse $DEBUG)
                -v file_sel="$c_file_selector"
                -v pkg_sel="$c_pkg_selector"
                -v host_sel="$c_host_selector"
                -v result_sel=$"c_result_selector"
                -v elapsed_sel="$c_elapsed_selector"
                -v exit_sel="$c_exit_selector"
                -v child_sel="$c_child_selector"
            )
            varlist+=" c_file_selector c_pkg_selector c_host_selector c_result_selector c_elapsed_selector c_exit_selector"
            ;;
        server)
            # identify server log file
            tui_log_basename="distccd.log"
            # set up a server grep_filter string with selectors to capture important lifecycle events as shown above
            grep_filter='__HEARTBEAT__'  #..................# update dynamic data like termwidth, and refresh screen to see clock tick
            grep_filter+="|__DNS_UPDATE__"  #...........# enable pre-load dns_cache stream and later updates
            grep_filter+="|${s_ip_selector}"
            grep_filter+="|${s_file_selector}"
            grep_filter+="|${s_success_selector}"
            grep_filter+="|${s_failure_selector}"
            grep_filter+="|${s_summary_selector}"
            # append server selectors to awk_vars array for use in the awk script
            # (also include updates of vars that cmdline can modify (mode, verbosity, DEBUG)
            awk_vars+=(
                -v mode="$mode"
                -v verbosity="$verbosity"
                -v DEBUG=$(TrueFalse $DEBUG)
                -v ip_sel="$s_ip_selector"
                -v file_sel="$s_file_selector"
                -v success_sel="$s_success_selector"
                -v summary_sel="$s_summary_selector"
            )
            varlist+=" s_ip_selector s_file_selector s_success_selector s_failure_selector s_summary_selector"
            ;;
        * ) c_ret=1 ;;
    esac
    tui_DISTCC_LOG="${distcc_logdir%/}/${tui_log_basename}"
    tui_DISTCC_OLDLOG_GLOB="${archive_dir%/}/${tui_log_basename}"'-*.gz'
    awk_vars+=( -v logfile="$tui_DISTCC_LOG" )


    j_msg -$debug -p "tui_DISTCC_LOG: [$tui_DISTCC_LOG]"
    # return non-zero bitmask on error or empty data structure(s)
    [ -z "$tui_DISTCC_LOG" ] && c_ret=$(( c_ret | 2 ))
    [ -z "$grep_filter" ] && c_ret=$(( c_ret | 4 ))
    [ ${#awk_vars[@]} -eq 0 ] && c_ret=$(( c_ret | 4 ))
    return $c_ret
}
#                -v success_sel="$c_success_selector"
#                -v failure_sel="$c_failure_selector"

run_tui_engine() {
    # create a background loop, grouped with tail using ( ... & ... ) and pipe this through
    # grep_filter to select relevant lines with --line-buffered immediately rendering then to output,
    # which is then piped to awk script to handle with associative arrays all keyed on pid
    # (HA! - but note that parallelism farms out preprocessing and compile with different pids,
    #  so the pid that competes the job may not be the one that "started" it)
    # (use tail -F rathern than -f so it will auto renew when log is rotated)

    # caution: the entire awk script must be single-quoted, so it cannot have ANY single-quites INSIDE it
    # (including contractions so do not put any apostraphe in dont; or just say do not instead)

    # 20260716 - instead of -
    #  (...) | awk '{...}' | while read signals ... /// chage to -
    #  awk '{...}' <(...#1) <(...#2) | while read signals ...
    #  (so we can feed two entire processes #1 being short-duration, and #2 being "infinite")
    # 20260718 - going back to (...) | grep | awk '{...}' | consumer to eliminate the first
    #  process substitution and the NR == NFR { ... } action block inside awk designed to consume
    #  dns updates, in favor of a single dns_cachu update block that can be called before and after
    #  the infinte hearbeat loop starts
    ( stream_log_data ) | awk "${awk_vars[@]}" '
    #-----[ awk functions ]---------------------------------------------------------------
    # Debug: dump every incoming line to stderr to verify the pipe is alive
#    { print "DEBUG [awk input]: " $0 > "/dev/stderr"; fflush("/dev/stderr") }
    # use this function to shift historical items down and append anew entry
    function rotate_history(new_record) {
        # shift existing records down by one index
        for (i = history_depth; i > 1; i--) {
            history[i] = history[i-1]
        }
        # insert the new record at the head of the array
        history[1] = new_record
    }
    # use this function to clean up record of pid when it is done
    function delete_active_records(p) {
        delete active_peers[p]
        delete active_starts[p]
        delete active_input_files[p]
        delete active_output_files[p]
        delete active_outcomes[p]
        delete active_duration[p]
        delete active_ip_addrs[p]
        delete last_contact[p]
    }
    # use this function to prune dead pids
    function prune_dead_pids(    pid, parts, ts, reason) {
        # consider aged-out and prune active records older than job_timeout
        for (pid in dead_pids) {
            # examine the reason the pid died, to determine wheter to do diagnostic message
            # format: dead_pid[pid] = systyme() "|" reason
            split(dead_pids[pid], parts, "|")
            ts = parts[1] + 0  # force awk to understand ts is a number
            reason = parts[2]
            # compare elapsed time against globally passed job_timeout
            if ((systime() - ts) > dead_pid_timeout) {
                # prune the dead pid
                delete dead_pids[pid]
                if (reason != "exit") {
                    # log to diagnostics
                    diagnostic_messages["dead_pid_pruned"][systime()] = \
                        "Pruned dead pid " pid " (reason: " reason ", timeout: " dead_pid_timeout "s)"
                }
            }
        }
    }
    # use this function to prune expired jobs
    function prune_expired_jobs(    pid) {
        # consider aged-out and prune active records older than job_timeout
        for (pid in last_contact) {
            # compare elapsed time against globally passed job_timeout
            if ((systime() - last_contact[pid]) > job_timeout) {
                # declare this pid dead for the anomalous reason "stale"
                dead_pids[pid] = systime() "|stale"
                # use existing cleanup function
                delete_active_records(pid)
                # log to diagnostics
                diagnostic_messages["expired_job_pruned"][systime()] = "Pruned expired job " pid " (timeout: " job_timeout "s)"
            }
        }
    }
    # use this function to prune expired packages
    function prune_expired_packages(    now, client_id, pkg) {
        now = systime()
        # consider aged-out and prune active packages older than pkg_timeout
        if (mode == "client") {
            client_id = "localhost"
            for (pkg in active_packages[client_id]) {
                if (now - active_packages[client_id][pkg] > pkg_timeout) {
                    delete active_packages[client_id][pkg]
                }
            }
        } else if (mode == "server") {
            for (client_id in active_packages) {
                for (pkg in active_packages[client_id]) {
                    if (now - active_packages[client_id][pkg] > pkg_timeout) {
                        delete active_packages[client_id][pkg]
                    }
                }
                # cleanup empty records
                if (length(active_packages[client_id]) == 0) {
                    delete active_packages[client_id]
                }
            }
        } else {
            diagnostic_messages["invalid_mode"][systime()] = "Invalid mode case in prune_expired_packages"
        }
    }
    # use this function to generate ui assets needed by the script
    function repeat(marker, reps,    i, out_str) {
        # trim marker to just its first character
        marker = substr(marker, 1, 1)
        # loop and concatenate
        i = 0; out_str = ""
        while (i++ < reps) out_str = out_str marker
        return out_str
    }
    # use this function to draw the heading panel at the top of each frame
    function draw_heading() {
        # clear screen and print heading for client mode
        printf "%s%s", clr, cup ;
        printf "%s\n", dubdashline ;
        # first line - DISTCC_LOG and Current Time
        printf "  %sDISTCC_LOG%s = %s%-35.35s%s %sCurrent Time:%s %s%s%s\n",
            heading_clr, clr_off,
            file_clr, logfile, clr_off,
            heading_clr, clr_off, ts_clr, strftime("%H:%M:%S"), clr_off ;
        # second line - DISTCC Mode and hostname
        printf "  %sDISTCC Mode: %s%s%s %s %sHostname: %s%s%s\n",
            heading_clr, mode_clr, mode, clr_off, repeat(" ", 28),
            heading_clr, mode_clr, hostname, clr_off ;
#        printf "  %sDISTCC Mode: %s%s%s %20.20s %s%s%s\n",
#            heading_clr, mode_clr, mode, clr_off, "", mode_clr, hostname, clr_off ;
        printf "%s\n", dubdashline ;
    }
    # use this function to draw the active package section
    function draw_packages(    client_id, pkg, host, count, elapsed, n, ip_arr, ip_suffix, host_str, done_printing) {
        printf "  %sRecent Packages -%s (elapsed since 1st seen)\n", title_clr, clr_off ;
        printf "%s\n", dashline ;
        count = 0
        done_printing = 0
        if (mode == "client") {
            client_id = "localhost"
            # print the package name (key of array) for each active packate
            for (pkg in active_packages[client_id]) {
                # cap this section at max_package_lines lines max
                if (count >= max_package_lines - 1) {
                    printf "  %s[... output capped at %d lines; more packages hidden ...]%s\n",
                        placeholder_clr, max_package_lines, clr_off
                    count++
                    break
                }
                host = client_id   # trivial in client mode
                elapsed = systime() - active_packages[client_id][pkg]
                printf "[%s%s%s] %s%s%s [%s%s%s] (%s%s%ss)\n",
                    ts_clr, strftime("%H:%M:%S", active_packages[client_id][pkg]), clr_off,
                    host_clr, host, clr_off,
                    pkg_clr, pkg, clr_off,
                    ts_clr, elapsed, clr_off
                count++
            }
        } else if (mode == "server") {
            # print the timestamp (content) package name (key1) of array for each active package
            for (client_id in active_packages) {
                if (done_printing) break
                if (client_id in dns_cache) {
                    host = dns_cache[client_id]
                } else {
                    host = "UNKNOWN_" client_id  # fallback
                }
                # pull ip_suffix from the last hextet if ipv6 or last octet if ipv4
                n = split(client_id, ip_arr, ":")
                if (n > 1) {
                    ip_suffix = ip_arr[n]
                } else {
                    split(ip, ip_arr, ".")
                    ip_suffix = ip_arr[4]
                }
                host_str = host_clr host clr_off ":" ip_clr ip_suffix clr_off

                for (pkg in active_packages[client_id]) {
                    # cap this section at max_package_lines lines max
                    if (count >= max_package_lines - 1) {
                        printf "%s[... output capped at %d lines; more packages hidden ...]%s\n",
                            placeholder_clr, max_package_lines, clr_off
                        count++
                        done_printing = 1    # break only leaves the inner loop, so ensure the outer knows to stop
                        break
                    }
                    elapsed = systime() - active_packages[client_id][pkg]
                    printf "[%s%s%s] %s [%s%s%s] (%s%s%ss)\n",
                        ts_clr, strftime("%H:%M:%S", active_packages[client_id][pkg]), clr_off,
                        host_str,
                        pkg_clr, pkg, clr_off,
                        ts_clr, elapsed, clr_off
                    count++
                }
            }
        } else {
            diagnostic_messages["invalid_mode"][systime()] = "Invalid mode in draw_packages"
        }
        # if there are currently no active packages, say so
        if (count == 0) {
            printf "  %s[ . . . Idle - Waiting for packages from Portage . . . ]%s\n", placeholder_clr, clr_off
            count++
        }
        while (count < max_package_lines) {
            printf "  ...\n"
            count++
        }
        printf "%s\n", dubdashline ;
    }
    # use this function to render the active panel within the frame
    function draw_active(    now, COL3_TITLE, p, count) {
        now = systime()
        if (mode == "client") {
            COL3_TITLE = "SERVER"
        } else if (mode == "server") {
            COL3_TITLE = "CLIENT"
        } else {
            diagnostic_messages["invalid_mode"][systime()] = "Invalid mode in draw_active"
            return 1
        }
        printf "  %sActive remote %s%s%s threads%s\n", title_clr, mode_clr, mode, title_clr, clr_off ;
        printf "%s\n", dashline ;
        # drop output file; add precision
        printf "%s%-7.7s%s %s %s%-35.35s%s %s %s%-14.14s%s %s %s%-4.4s%s %s %s%-8.8s%s\n",
           title_clr, "  PID", clr_off, separator,
           title_clr, "SOURCE FILE", clr_off, separator,
           title_clr, COL3_TITLE, clr_off, separator,
           title_clr, "SEC", clr_off, separator,
           title_clr, "STATUS", clr_off
        printf "%s\n", dashline ;
        # awk loop syntax assigns key to loop variable (so p is pid here)
        count = 0
        for (p in active_peers) {
            # cap this section at max_active_lines lines max
            if (count >= max_active_lines - 1) {
                printf "  %s[... output capped at %d lines; more jobs hidden ...]%s\n",
                    placeholder_clr, max_active_lines, clr_off
                count++
                break
            }
            elapsed = now - active_starts[p]
            # update the active records (dont .10 precision last field (outcome) or it truncated/break its clr_off
            printf "%s%-7.7s%s %s %s%-35.35s%s %s %s%-14.14s%s %s %s%-4.4s%s %s %s\n",
                data_clr, p, clr_off, separator,
                file_clr, active_input_files[p], clr_off, separator,
                host_clr, active_peers[p], clr_off, separator,
                ts_clr, elapsed, clr_off, separator,
                active_outcomes[p]
            count++
        }
        # if there are currently no active jobs, say so
        if (count == 0) {
            printf "  %s[ . . . Idle - Waiting for jobs from Portage . . . ]%s\n", placeholder_clr, clr_off
            count++
        }
        while (count < max_active_lines) {
            printf "  ...\n"
            count++
        }
        printf "%s\n", dubdashline ;
    }
    # use this function to render the recent history panel within the frame
    function draw_recent_history(    count, i) {
        # update recently completed jobs
        # draw a heading for recent history section
        printf "  %sRecently completed%s\n", title_clr, clr_off
        printf "%s\n", dubdashline ;
        for (i = 1; i <= history_depth; i++) {
            print (history[i] != "" ? history[i] : "  ...")
        }
        printf "%s\n", dubdashline
    }
    # use this function to render the client mode rollup
    function draw_clientmode_rollup(    peer, count, has_data) {
        # only draw if we actually have data
        has_data = 0
        for (peer in clientmode_servers_rollup) { has_data = 1; break }
        if (!has_data) return
        printf "  %sClient%s %smode - Total Jobs Completed per Remote Server%s\n", mode_clr, clr_off, title_clr, clr_off
        printf "%s\n", dashline
        # iterate through servers in array
        for (peer in clientmode_servers_rollup) {
            count = clientmode_servers_rollup[peer]
            # print the formatted row (room for space then 1000000 then hostname)
            printf "%s%8d%s %s%s%s\n",
                data_clr, count, clr_off, host_clr, peer, clr_off
        }
        printf "%s\n", dubdashline
    }
    # use this function to render the server mode rollup
    function draw_servermode_rollup(    ip, count, has_data, host_str, n, ip_arr, ip_suffix) {
        # only draw if we actually have data
        has_data = 0
        for (ip in servermode_clients_rollup) { has_data = 1; break }
        if (!has_data) return
        printf "  %sServer%s %smode - Total Jobs Completed per Remote Client%s\n", mode_clr, clr_off, title_clr, clr_off
        printf "%s\n", dashline
        # iterate through server ips in array
        for (ip in servermode_clients_rollup) {
            count = servermode_clients_rollup[ip]
            # resolve hostname with ip suffix differentiation
            if (ip in dns_cache) {
                # pull ip_suffix from the last hextet if ipv6 or last octet if ipv4
                n = split(ip, ip_arr, ":")
                if (n > 1) {
                    ip_suffix = ip_arr[n]
                } else {
                    split(ip, ip_arr, ".")
                    ip_suffix = ip_arr[4]
                }
                # append ip_suffix to host hame to summarize
                host_str = host_clr dns_cache[ip] clr_off ":" ip_clr ip_suffix clr_off
            } else {
                host_str = "UNKNOWN_" ip
            }
            # print the formatted row (room for space then 1000000 then hostname)
            printf "%s%8d%s %s\n",
                data_clr, count, clr_off, host_str
        }
        printf "%s\n", dubdashline
    }
    # use this function to render diagnostic information below other frames (uncomment to enable)
    function draw_diagnostics(    i, k, diag_title, hosts_cnt, starts_cnt, inputs_cnt, outputs_cnt,
                                  outcomes_cnt, dur_cnt, ip_cnt, last_cnt, cache_cnt, local_now,
                                  diag_time_left, has_errors, diag_err_cnt, err_key, parts, type,
                                  ts, ordered_types, n_types ) {
        #printf "%s\n", dubdashline
        printf "  %s[ DIAGNOSTICS ]%s\n", title_clr, clr_off
        #-----[ display verbosity ]----------------------------------------------------------
        printf "  verbosity: [%s]", verbosity
        printf " DEBUG: [%s]", DEBUG
        #-----[ verify dynamic shell data (width) ingested  ]-----------------------------
        printf "  width: [%s]", width
        printf " mode: [%s]\n", mode
        #-----[ show active array record counts ]---------------------------------------
        printf "  Active Array Record Counts:\n"
        # Safely loop through and count active tracking keys
        hosts_cnt = 0;    for (k in active_peers) hosts_cnt++
        starts_cnt = 0;   for (k in active_starts) starts_cnt++
        inputs_cnt = 0;   for (k in active_input_files) inputs_cnt++
        outputs_cnt = 0;  for (k in active_output_files) outputs_cnt++
        outcomes_cnt = 0; for (k in active_outcomes) outcomes_cnt++
        dur_cnt = 0;      for (k in active_duration) dur_cnt++
        last_cnt = 0;     for (k in last_contact) last_cnt++
        ip_cnt = 0;       for (k in active_ip_addrs) ip_cnt++
        cache_cnt = 0;    for (k in dns_cache) cache_cnt++
        printf "    Hosts: %d", hosts_cnt
        printf " | Starts: %d", starts_cnt
        printf " | Input Files: %d", inputs_cnt
        printf " | Output Files: %d\n", outputs_cnt
        printf "    Outcomes: %d", outcomes_cnt
        printf " | Durations: %d", dur_cnt
        printf " | Last_contact: %d", last_cnt
        printf " | IPs: %d", ip_cnt
        printf " | Cache: %d\n", cache_cnt

#        printf "  Hosts: %d | Starts: %d | Input Files: %d | Output Files: %d \n  Outcomes: %d | Durations: %d |IPs: %d | Last_contact: %d | dns_cache: %d\n",
#            hosts_cnt, starts_cnt, inputs_cnt, outputs_cnt, outcomes_cnt, dur_cnt, ip_cnt, last_cnt, cache_cnt
        #printf "%s\n", dubdashline
        #-----[ show dns_caceh record count ]--------------------------------------------
#        printf "  [ DIAGNOSTICS ] dns_cache keys (first 3):\n"
#        i = 0
#        for (k in dns_cache) {
##            if (k ~ /fd62:6262:6262:0/){
#                printf "    > [%s]\n", k
#            }
#           if (++i > 2) break   # zero-indexed (allows 3)
#        }
        #printf "last __HEARTBEAT__: [%s]\n", $0
        #-----[ show accumulated diagnostic errors ]--------------------------------------
        # 20260722 - changed from pseudo (POSIX) multi-demensional array diagnostic_messages[err_key]
        #   where err_key is stored internally by awk as "<err_type><FS><timestamp>" and
        #   FS = ascii File/Field separator, \034 - identified by SUBSEP
        #   thus effective format is diagnostic_messages[type, timestamp] = "message"
        # and changed TO (GAWK) multi-dimensional array diagnostic_messages[type][timestamp]
        # note: systime timestamps have one-second resolution so these are throttled at max 1/sec
        local_now = systime()
        has_errors = 0

        # first, pass - check for and purge expired errors
        diag_err_cnt=0
        # pass 1 - prune expired diagnostic messages
        for (type in diagnostic_messages) {
            for (ts in diagnostic_messages[type]) {
                if ((local_now - ts) > diagnostic_timeout) {
                    delete diagnostic_messages[type][ts]
                } else {
                    diag_err_cnt++
                }
            }
            # check if type sub-array is empty and delete if so, to prune empty outer category from diagnostic_messages,
            # and keep it from causing diag_err_cnt to remain above 0 indefinitely
            if (length(diagnostic_messages[type]) == 0) {
                delete diagnostic_messages[type]
            }
        }
        printf "  Active Diagnostic Message Count: [%s]\n", diag_err_cnt

        # pass 2 - if there are errors to display, print them
        if (diag_err_cnt > 0) {
            printf "%s\n", dubdashline
            printf "  %s[ Diagnostic Alert Messages ]%s\n", title_clr, clr_off

            # process types in specified variable order
            n_types = split(diag_msg_type_order, ordered_types)
            for (i = 1; i <= n_types; i++) {
                type = ordered_types[i]
                if (type in diagnostic_messages) {
                    # iterate over active timestamps
                    for (ts in diagnostic_messages[type]) {
                        diag_time_left = diagnostic_timeout - (systime() - ts)
                        printf "  [%s%s%s] %s (%s%s%s)\n",
                            failure_clr, strftime("%H:%M:%S", ts), clr_off,
                            diagnostic_messages[type][ts],
                            ts_clr, diag_time_left, clr_off
                    }
                }
            }
        }
#            for (type in diagnostic_messages) {
#                for (ts in diagnostic_messages[type]) {
#                    # calculate and display the seconds until expiration of this diagnostic message
#                    diag_time_left = diagnostic_timeout - (systime() - ts)
#                    printf "  [%s%s%s] %s (%s%s%s)\n",
#                        failure_clr, strftime("%H:%M:%S", parts[2]), clr_off,
#                        diagnostic_messages[type][ts],
#                        ts_clr, diag_time_left, clr_off
#                }
#            }
#        }
    }
    ### awk function for CLIENT mode ###-------------------------------------------------------------------------------------
    function parse_client_line(    pid, child_pid, client_id, parts, path, n, path_parts, final_time, log_str, clean_peer) {
        # if it is a real log line, parse the data
        # and ignore (dcc_increment_safeguard) lines that are sqawned child processes that generate only one line
        if ($0 !~ /__HEARTBEAT__/ && $0 !~ /dcc_increment_safeguard/) {
            # assign client_id so both client and server modes can use same data structure for active packages
            # (for client mode, it is trivial and by definition)
            client_id = "localhost"
            # extract pid (numeric part of first field; format: "distcc[1234567]"
            match($1, /[0-9]+/)
            pid = substr($1, RSTART, RLENGTH)   # RSTART, RLENGTH are awk built-in tracking regex matched pattern relative to full string
            # guard against a pid declared dead having a follow-on line revive it
            if (pid in dead_pids) { return 0 }
            # update last contact for every line received (enable prune if job dies with no exit_sel)
            last_contact[pid] = systime()
            # safe default initialization for fields required by piping and logging (do only on first observation of pid)
            if (!(pid in active_starts)) {
                active_input_files[pid]  = "(null)"
                active_peers[pid]        = "localhost"
                active_duration[pid]     = "0s"
                active_starts[pid]       = systime()

                # DIAGNOSTIC: Log the PID right before deletion to a temp file
                print systime() " PRE-PROCESS: First observance of PID " pid >> "/tmp/distcc_awk_debug.log"
            }
            # set start placeholder outcome only on the very first encounter (if empty)
            if (!(pid in active_outcomes)) {
                active_outcomes[pid] = sprintf("%s%-8.8s%s", placeholder_clr, "pending", clr_off) }

            # if line matches selector, save input and output file name and start time for this pid
            #   distcc[646584] "compile from" extensions.c to extensions.c.o
            if ($0 ~ file_sel) {
                active_input_files[pid] = $4
                active_output_files[pid] = $6
            }
            # if line matches selector, save distcc server host_name for this pid
            #   distcc[666568] (dcc_scan_args) found input file "/var/tmp/portage/dev-db/mysql-8.0.45/work/mysql/client/dump/database.cc"
            #   c_pkg_selector="found input file${P1}/work" #...# pkg is extracted from $6/$NF
            if ($0 ~ pkg_sel) {
                # for client mode, there is there can be a number of packages - one per ongoing emerge job in different sessions
                # to make the array self-deduplicating, key on the package name itself
                # (should be one package per emerge/make process tho ea session can have many concurrent jobs)
                # this split method is agnostic to which field the package name occupies
                split($0, parts, port_prefix)  # like cut, using port_prefix as delimiter - use parts[2]
                split(parts[2], path, "/")     # like cut, using "/" as delimiter - concat first two fields with another "/"
                pkg = path[2] "/" path[3]      # again like cut, so f1 is left of first / - take f2 f3
                # if pkg and client_id are both assigned, and if active_packages is not already assigned, do so
                if (pkg != "" && client_id != "") {
                    # key on client_id (assigned above) and package name to self-deduplicate, and store systime() so we can prune if aged-out
                    if (active_packages[client_id][pkg] == "") { active_packages[client_id][pkg] = systime() }
                } else {
                    diagnostic_messages["pkg_index_lacking"][systime()] = sprintf( \
                        "(client mode) missing index - client_id: [%s], pkg: [%s]", client_id, pkg)
                }
            }
            # if line matches selector, save distcc server host_name for this pid
            #   distcc[646584] "exec on" gmki92,lzo/4: x86_64-pc-linux-gnu-gcc ...
            #   distcc[646584] "(dcc_lock_host) got cpu lock on" gmki92,lzo/4 slot 0 as fd3 /// <-- alt if not localhost
            #   c_host_selector="\] exec on"  #................#  --> host_name = $4
            if ($0 ~ host_sel) {
                active_peers[pid] = $4              # like basename split
            }
            # if line matches selector, save outcome for this pid
            #   distcc[646584] "compile" ../accountsservice-23.13.9/src/extensions.c on gmki92,lzo/4 "completed ok"
            #   distcc[2463400] ERROR: compile /var/tmp/portage/dev-db/mysql...SymbolExists.c on nuthuvia,lzo/7 failed
            #   c_result_selector=" compile${P1} on" #.......# outcome = $NF; ok: infile=$3host_name=$5; failed; infile=$4/host_name=$6
            if (($0 ~ success_sel) && ($0 ~ / compile /) && ($0 !~ / cpp /)) {
                if ($0 ~ /completed ok/) {
                    split($0, parts, " compile ")
                    split(parts[2], path, " on ")
                    n = split(path[1], path_parts, "/")
                    if (!(pid in active_input_files)) { active_input_files[pid] = path_parts[n] }
                    split($0, parts, " completed ok")
                    n = split(parts[1], line_parts, " ")
                    if (!(pid in active_peers)) { active_peers[pid] = line_parts[n] }
                    active_outcomes[pid] = sprintf("%s%-8.8s%s", success_clr, "success", clr_off)
                } else if ($0 ~ /failed/) {
                    split($0, parts, " compile ")
                    split(parts[2], path, " on ")
                    n = split(path[1], path_parts, "/")
                    if (!(pid in active_input_files)) { active_input_files[pid] = parts[n] }
                    split($0, parts, " failed")
                    n = split(parts[1], line_parts, " ")
                    if (!(pid in active_peers)) { active_peers[pid] = line_parts[n] }
                    active_outcomes[pid] = sprintf("%s%-8.8s%s", failure_clr, "failure", clr_off)
                }
            }
            # if line matches selector, record the elapsed time for this pid
            #   distcc[646584] elapsed compilation time 3.136191s
            #   c_elapsed_selector="elapsed compilation time"  # elapsed = $5 ($NF)
            if ($0 ~ elapsed_sel) {
                active_duration[pid] = $NF
            }
            # if line matches selector, rotate history and delete active records for this pid
            #   distcc[646584] "(dcc_exit)" exit: code 0; self: 0.008061 user 0.016122 sys; children: 0.270012 user 0.214661 sys
            if ($0 ~ exit_sel) {

                # DIAGNOSTIC: Log the PID right before deletion to a temp file
                print systime() " PRE-DELETE: exit_sel matched for PID " pid >> "/tmp/distcc_awk_debug.log"

                # use exit code (awk sees "0;" as number 0 in this context) to set active_outcomes for this job
                if (($5 + 0) == 0) {
                    active_outcomes[pid] = sprintf("%s%-8.8s%s", success_clr, "success", clr_off)
                    # if we have a hostname, then sanitize it for use as a rollup array key
                    if (active_peers[pid] != "") {
                        clean_peer = active_peers[pid]
                        sub(/,.*/, "", clean_peer)    # strip distcc options (comma and all after, e.g., ,lzo/7, ,cpp)
                        sub(/:$/, "", clean_peer)     # strip trailing colon if present from "exec on" line
                        clientmode_servers_rollup[clean_peer]++
                    }                } else {
                    active_outcomes[pid] = sprintf("%s%-8.8s%s", failure_clr, "failure", clr_off)
                }
                final_time = (active_duration[pid] != "" ? active_duration[pid] : 0)
                log_str = sprintf("[%s%s%s] [%s%s%s] %s%s%s on %s%s%s (%s%ds%s) [%s]",
                                  data_clr, pid, clr_off,
                                  ts_clr, strftime("%H:%M:%S"), clr_off,
                                  file_clr, active_input_files[pid], clr_off,
                                  host_clr, active_peers[pid], clr_off,
                                  ts_clr, final_time, clr_off,
                                  active_outcomes[pid])
                rotate_history(log_str)
                delete_active_records(pid)
                # declare this pid dead now for the routing reason "exit"
                # to ignore any trailing lines that would otherwise re-initialize it
                dead_pids[pid] = systime() "|exit"

                # DIAGNOSTIC: verify if the arrays actually cleared
                if ((!(pid in active_starts)) && (!(pid in last_contact)) && (!(pid in active_peers))) {
                     print systime() " POST-DELETE SUCCESS: PID " pid " cleared." >> "/tmp/distcc_awk_debug.log"
                } else {
                     print systime() " POST-DELETE FAIL: PID " pid " still exists in tracking arrays!" >> "/tmp/distcc_awk_debug.log"
                }
            }
        }
    }   # end parse_client_line
    ### awk function for SERVER mode ###-------------------------------------------------------------------------------------
    function parse_server_line(    pid, child_pid, ip, parts, path, client_id, pkg, log_str, time_str) {
    # Debug: dump every incoming line to stderr to verify the pipe is alive
#     { print "DEBUG [awk server mode input]: " $0 > "/dev/stderr"; fflush("/dev/stderr") }

        # if it is a real log line, parse the data
        # and ignore (dcc_increment_safeguard) lines that are sqawned child processes that generate only one line
        if ($0 !~ /__HEARTBEAT__/ && $0 !~ /dcc_increment_safeguard/) {
            # extract pid (numeric part of first field; format: "distcc[1234567]"
            match($1, /[0-9]+/)
            pid = substr($1, RSTART, RLENGTH)   # RSTART, RLENGTH are awk built-in tracking regex matched pattern relative to full string
            # guard against a pid declared dead having a follow-on line revive it
#            if (pid in dead_pids) { return 0 } <-- server mode: pid persists over several jobs
            # update last contact for every line received (enable prune if job dies with no exit_sel)
            last_contact[pid] = systime()
            # safe default initialization for fields required by piping and logging (do only on first observation of pid)
            if (!(pid in active_starts)) {
                active_input_files[pid]  = "(null)"
                active_peers[pid]        = "UNKNOWN_0.0.0.0"
                active_ip_addrs[pid]     = "0.0.0.0"
                active_duration[pid]     = "0ms"       # "0ms" matching distccd (server) native time unit output format
                active_starts[pid]       = systime()
            }
            # set start placeholder outcome only on the very first encounter (if empty)
            if (!(pid in active_outcomes)) {
                active_outcomes[pid] = sprintf("%s%-8.8s%s", placeholder_clr, "pending", clr_off) }
            # if line matches selector, save input ip address for this pid (assumes it always has a port number to strip
            #   distccd[96193] "(dcc_check_client)" connection from fd62:6262:6262:0:d9ac:eab7:6d40:2331:40662
            if ($0 ~ ip_sel) {
                ip = $NF
                gsub(/:[0-9]+$/, "", ip)             # strip trailing colon and digits (port number)
                active_ip_addrs[pid] = ip           # assign to array
                # guard - check if the ip exists in pre-loaded list
                if (ip in dns_cache) {
                    active_peers[pid] = dns_cache[ip]
# uncomment to debug
#                    diagnostic_messages["ip_is_in_cache"][systime()] = sprintf("ip address [%s] is in cache with host [%s]", ip, dns_cache[ip])
                } else {
                    # emit signal to shell to trigger call to maybe_get_and_register_hostname
#                    printf "__REGISTER_ME__ %s %s\n", pid, ip
                    active_peers[pid] = "UNKNOWN_" ip  # fallback
                    diagnostic_messages["ip_is_in_not_cache"][systime()] = sprintf("(ip) ip address [%s] is NOT in cache", ip)
                }
            }
            # if line matches selector, save input and output file names for this pid (already short form in log)
            #   distccd[96193] "compile from" gtkactions_interface.cpp to gtkactions_interface.cpp.o
            if ($0 ~ file_sel) {
                active_input_files[pid] = $4
                active_output_files[pid] = $6
            }
            # if line matches selector, save distcc server host_name for this pid
            #   1              2                       3                                     4  5         6
            #   distccd[96193] x86_64-pc-linux-gnu-g++ /var/tmp/portage/kde-plasma/.../work  on localhost "completed ok" --> outcome=$NF
            if ($0 ~ success_sel) {
                # for server mode, the list of packages for multiple ip addresses of clients (should be one per)
                # use array of arrays [client_id][pkg] rather than 2-d array (indexing is independent)
                # store systime to know the age of this package record
                # this split method is agnostic to which field the package name occupies
                # but need to ensure port_prefix is found, else test-compile lines that dont have it will assign " / " as pkg
                if (split($0, parts, port_prefix) > 1) {  # like cut, using port_prefix as delimiter - use parts[2]
                    split(parts[2], path, "/")            # like cut, using "/" as delimiter - concat first two fields with another "/"
                    pkg = path[2] "/" path[3]             # again like cut, so f1 is left of first / - take f2 f3
                } else {
                    pkg = ""                              # assign null pkg to preclude active_packages assignment below
                }
                # server-mode client_id is ip of client
                client_id = active_ip_addrs[pid]
                # if pkg and client_id are both assigned, and if active_packages is not already assigned, do so
                if (pkg != "" && client_id != "" && client_id != "0.0.0.0") {
                    # key on client_id (assigned above) and package name to self-deduplicate, and store systime() so we can prune if aged-out
                    if (active_packages[client_id][pkg] == "") { active_packages[client_id][pkg] = systime() }
                 # removed else block with diagnostic because, in the dcc_job_summary, messages NOT including a portage prefixed path
                 # are almosts certainly just "test compile" cases running for the ebuild and not actual files being compiled for pkg
#                } else {
#                    diagnostic_messages["pkg_index_lacking"][systime()] = sprintf( \
#                        "(success block) array index missing or default - client_id: [%s], pkg: [%s]", client_id, pkg)
                }
                # dont need to annotate history section for success until summary is processed, but do annotate outcome in active section for a blink
                active_outcomes[pid] = sprintf("%s%-8.8s%s", success_clr, $NF, clr_off)
            }
            # if line matches selector, record the outcome for this pid
            #   distccd[1460350] (dcc_readx) ERROR: unexpected eof on fd5
            #   s_failure_selector="ERROR:"  #.................# && /dcc_r/ --> outcome = all after ERROR:
            if (($0 ~ failure_sel) && ($0 ~ /dcc_r/)) {
                split($0, parts, "ERROR: ")
                active_outcomes[pid] = sprintf("%s%-8.8s%s", failure_clr, parts[2], clr_off)
                log_str = sprintf("[%s%s%s] [%s%s%s] %s%s%s on %s%s%s (%s%ds%s) [%s]",
                                  data_clr, pid, clr_off,
                                  ts_clr, strftime("%H:%M:%S"), clr_off,
                                  file_clr, active_input_files[pid], clr_off,
                                  host_clr, active_peers[pid], clr_off,
                                  ts_clr, final_time, clr_off,
                                  active_outcomes[pid])
                # update history with record of failure, but dont delete active records as pid will continue on new remote host
                rotate_history(log_str)
            }
            # if line matches selector, record the elapsed time for this pid
            #   distccd[96193] (dcc_job_summary) client: fd62:6262:6262:0:d9ac:eab7:6d40:2331:40662 COMPILE_OK exit:0 \
            #                ... sig:0 core:0 ret:0 time:21251ms x86_64-pc-linux-gnu-g++  \
            #                ... /var/tmp/portage/kde-plasma/plasma-workspace-6.6.5-r1/work/plasma-workspace-6.6.5_build/gmenu-dbusmenu-proxy/gtkactions_interface.cpp
            if ($0 ~ summary_sel) {
                # assess success/falure - note both get exit: 0 status, so use COMPILE_OK vs OTHER in $5
                if ($5 == "COMPILE_OK") {
                    active_outcomes[pid] = sprintf("%s%-8.8s%s", success_clr, "success", clr_off)
                } else {
                    active_outcomes[pid] = sprintf("%s%-8.8s%s", failure_clr, "failure", clr_off)
                }
                # if ip or host_name is empty, try to fill it
                if (active_ip_addrs[pid] =="" || active_ip_addrs[pid] == "0.0.0.0") {
                    ip = $4
                    gsub(/:[0-9]+$/, "", ip)             # strip trailing colon and digits (port number)
                    active_ip_addrs[pid] = ip           # assign to array
                    # guard - check if the ip exists in pre-loaded list
                    if (ip in dns_cache) {
                        active_peers[pid] = dns_cache[ip]
                    } else {
                        # emit signal to shell to trigger call to maybe_get_and_register_hostname
#                        printf "__REGISTER_ME__ %s %s\n", pid, ip
                        active_peers[pid] = "UNKNOWN_" ip  # fallback
                        diagnostic_messages["ip_is_in_not_cache"][systime()] = sprintf("(summary) ip address [%s] is NOT in cache", ip)
                    }
                }
                # if job is complete and we have a ip address, increment the server mode rollup
                if ($5 == "COMPILE_OK" && active_ip_addrs[pid] != "") {
                    servermode_clients_rollup[active_ip_addrs[pid]]++
                }                # if package is empty, try to fill it
                # this split method is agnostic to which field the package name occupies
                # but need to ensure port_prefix is found, else test-compile lines that dont have it will assign " / " as pkg
                if (split($0, parts, port_prefix) > 1) {  # like cut, using port_prefix as delimiter - use parts[2]
                    n = split(parts[2], path, "/")            # like cut, using "/" as delimiter - concat first two fields with another "/"
                    pkg = path[2] "/" path[3]             # again like cut, so f1 is left of first / - take f2 f3
                } else {
                    pkg = ""                              # assign null pkg to preclude active_packages assignment below
                }
                # server-mode client_id is ip of client
                client_id = active_ip_addrs[pid]
                # if pkg and client_id are both assigned, and if active_packages is not already assigned, do so
                if (pkg != "" && client_id != "" && client_id != "0.0.0.0") {
                    # key on client_id (assigned above) and package name to self-deduplicate, and store systime() so we can prune if aged-out
                    if (active_packages[client_id][pkg] == "") { active_packages[client_id][pkg] = systime() }
                 # removed else block with diagnostic because, in the dcc_job_summary, messages NOT including a portage prefixed path
                 # are almosts certainly just "test compile" cases running for the ebuild and not actual files being compiled for pkg
#                } else {
#                    diagnostic_messages["pkg_index_lacking"][systime()] = sprintf( \
#                        "(summary block) array index missing or default - client_id: [%s], pkg: [%s]", client_id, pkg)
                }
                # if infile is still empty, fill it with last element of path
                if (!(pid in active_input_files)) {active_input_files[pid] = path[n] }
                # record elapsed time
                split($0, parts, "time:")    #...# format: " ... time:21576ms ..." cut from line using "time:" as delimiter
                split(parts[2], time_str, " ")   # cut from remaining line using " " as delimiter
                active_duration[pid] = time_str[1]
                final_time = (active_duration[pid] != "" ? active_duration[pid] : "0ms")
                log_str = sprintf("[%s%s%s] [%s%s%s] %s%s%s for %s%s%s (%s%s%s) [%s]",
                                  data_clr, pid, clr_off,
                                  ts_clr, strftime("%H:%M:%S"), clr_off,
                                  file_clr, active_input_files[pid], clr_off,
                                  host_clr, active_peers[pid], clr_off,
                                  ts_clr, final_time, clr_off,
                                  active_outcomes[pid])
                rotate_history(log_str)
                delete_active_records(pid)
                # do NOT declare this pid dead now - pid persists in server mode as long as the compiler slot stays open
                # likely for the duration of the package.  We actually NEED trailing lines (for new jobs under this pid)
                # to re-initialize the active records associated with pid and get new filename, etc.
            }
        }
    }   # end parse_server_line
    #-----[ main block of awk script ]-------------------------------------------------------------------------
    {
        # Debug: dump every incoming line to stderr to verify the pipe is alive
#        { print "DEBUG [dns cache input]: " $0 > "/dev/stderr"; fflush("/dev/stderr") }
        # structure is four logically orthogonal blocks for three kinds of
        # streaming data uniquely identified by the beginning of each line
        # __DNS_UPDATE__ and __HEARTBEAT__ come from the parent bash shell itself
        # distcc[ and distccd[ come from log data tailed to awk by the parent bash shell
        if (match($0, "^__DNS_UPDATE__" W1)) {
            # bash is injecting a dns update (or initialization) for the dns_cache; consume it
            # dont trust the field sepation enumeration $2, $3, etc...
            # strip the tag and following whitespace (W1 is posix one+ whitespace) - leaving ip first in remainder
            # extract everything after the tag and its spaces
            payload = substr($0, RSTART + RLENGTH)
            split(payload, data_parts)
            ip = data_parts[1]
            host = data_parts[2]
            dns_cache[ip] = host
            # check ingested values and log diagnostic report (for debugging)
            if (ip != "") {
                diagnostic_messages["dns_ip_diagnostic"][systime()] = sprintf( \
                    "Ingested ip: [%s] from line [%s]", ip, $0 )
            } else {
                diagnostic_messages["dns_ip_diagnostic"][systime()] = sprintf( \
                    "Failed to ingest ip from line [%s]", $0 )
            }
            # check ingested values and log diagnostic report (for debugging)
            if (host != "") {
                diagnostic_messages["dns_host_diagnostic"][systime()] = sprintf( \
                     "Ingested host: [%s] from line [%s]", host, $0 )
            } else {
                diagnostic_messages["dns_host_diagnostic"][systime()] = sprintf( \
                      "Failed to ingest host from line [%s]", $0 )
            }
            # check ingested values and log diagnostic report (for debugging)
            if (ip in dns_cache) {
                diagnostic_messages["dns_cache_diagnostic"][systime()] = sprintf( \
                    "Ingested dns_cache[%s] content: [%s] from line [%s]", ip, dns_cache[ip], $0 )
            } else {
                diagnostic_messages["dns_cache_diagnostic"][systime()] = sprintf( \
                    "Failed to ingest dns_cache[%s] content from line [%s]", ip, $0 )
            }
        } else if ($0 ~ /^__HEARTBEAT__/) {
            # heartbeat carries field(s) that enable dynamic interaction with awk
            # e.g. update terminal width dynamically
            width = $2
            # update ui assets using dynamic width
            dashline = sprintf("%s%s%s", line_clr, repeat("-", width), clr_off)
            dubdashline = sprintf("%s%s%s", line_clr, repeat("=", width), clr_off)
            separator = sprintf("%s%s%s", line_clr, "|", clr_off)
            # prune expired data
            prune_expired_packages()
            prune_expired_jobs()
            # todo - code the if client into prune_dead_pids (find a different way/timeout for server pids)
#            if (mode == "client") prune_dead_pids()
            prune_dead_pids()
            # redraw the frame with dynamic width every cycle
            draw_heading()
            draw_packages()
            # reset timer, count, elapsed; render active jobs
            now = systime()
            count = 0
            draw_active()
            draw_recent_history()
            if (mode == "server") { draw_servermode_rollup() }
            if (mode == "client") { draw_clientmode_rollup() }
            if (verbosity > 5 || DEBUG == "True") { draw_diagnostics() }
        } else if ($0 ~ /^distcc\[/) {
            # this is client-mode log data coming from tail -F of distcc-client.log
            # let the parsing function extract pid locally rathern than make it global
            if (mode == "server") {
                diagnostic_messages["mode_mismatch"][systime()] = "Ingested client data while in server mode"
            }
            parse_client_line()
        } else if ($0 ~ /^distccd\[/) {
            # this is server-mode log data coming from tail -F of distccd.log
            # let the parsing function extract pid locally rathern than make it global
            if (mode == "client") {
                diagnostic_messages["mode_mismatch"][systime()] = "Ingested server data while in client mode"
            }
            parse_server_line()
        } else {
                diagnostic_messages["unexpected_data"][systime()] = sprintf("Ingested unexpected or malformed data [%s]", $0)
        }
        # force output to terminal immediately
        fflush()
    }   # main block
        # the output of awk text processing is piped into a signal handler in real time
    ' | consume_tui_output          # this \' char is the end of awk itself
}   # end run_tui_engine bash function

consume_tui_output() {
    while IFS= read -r line; do
        # simple pass-through for now
        # future: insert signal parsing or update logic here
        printf "%s\n" "$line"
    done
}

broken_consume_tui_output_stuff_parkinglot() {
    # reintegration notes:
    # When you are ready to move the logic from broken_consume_tui_output_stuff_parkinglot
    #  into your active consume_tui_output, remember these two specific adjustments to comply with your architecture:
    # variable scoping: ensure every variable used within the loop (e.g., pid, target_ip, host_name) is initialized
    #   with local at the top of the function and prefixed with the function namespace identifier (e.g., _consume_pid,
    #   _consume_target_ip).
    # explicit array declaration: you noted a to-do item to rectify array nomenclature; before activating the
    #   bash_reg_locks logic, verify that bash_reg_locks is explicitly declared as an array
    #   (e.g., declare -A bash_reg_locks) to avoid unexpected behavior when writing to it.
        while read -r signal arg1 arg2 arg3; do
             case "$signal" in
                 "__REGISTER_ME__")
                     pid="$arg1"
                     target_ip="$arg2"

                     # anti-avalanche guard: dont spawn redundant network tasks for the same IP
                     if [ -z "${bash_reg_locks[$target_ip]}" ]; then
                         bash_reg_locks[$target_ip]="LOCKED"

                         # Run your legacy network validation out-of-band using &
                         (
                             if good_connectivity "$target_ip"; then
                                 if maybe_get_and_register_hostname "$target_ip"; then
                                     # We write an entry back to the log file.
                                     # Awk reads it, pulls it into RAM cache, and continues streaming.
                                     echo "__DYNAMIC_UPDATE__ $target_ip $host_name" >> /var/log/distcc.log
                                 fi
                             fi
                             unset "bash_reg_locks[$target_ip]"
                         ) &
                     fi
                     ;;

                 "JOB_DONE")
                     j_msg -$notice "PID [$arg1] completed compilation task via [$arg2] in [$arg3]"
                     ;;

                 "RESOLVED")
                     j_msg -$debug "PID [$arg1] instantly matched to [$arg2]"
                     ;;
             esac
         done

}

stream_log_data() {
    # setup and messaging block goes to stderr so awk ignores it
    {
        j_msg -$notice -p "Starting log stream for: [$tui_DISTCC_LOG]"
        j_msg -$debug -p "grep_filter: [$grep_filter]"
        j_msg -$debug -p "tui_refresh_period: [$tui_refresh_period]"
        j_msg -$debug -p "mode: [$mode]"

    } >&2
    # data generation block must go to stdout so awk receives it
    {
        # first call stream_dns_hostfiles (once) if in server mode (not applicable to client mode
        # because client knows it is "localhost" and tui already knows who is in /etc/distcc/hosts
        # but server gets requests from ip addresses and tui has to look them up to be useful)
        [[ "$mode" == "server" ]] && stream_dns_hostfiles

        j_msg -$notice -p "First ingesting all of recorded history, please wait a few seconds ..." >&2
        # first dump and roll up all of recorded history - do not background this
        # ensure this massive dump is complete BEFORE backgrounding tail -F and interleaving the hearbeat
        for old_log in ${tui_DISTCC_OLDLOG_GLOB}; do [[ -f "$old_log" ]] && zcat "$old_log"; done
        cat "$tui_DISTCC_LOG"
        j_msg -$notice -p "Now backgrounding tail -F to stream all future lines" >&2
        sleep 0.5
        # now background the continued steaming of any future lines in this file
        tail -F "$tui_DISTCC_LOG" &

        # infinite loop, injecting hearbeat with dynamic formatting data (width)
        # (optionally also include "spoofed" log data to test error handling)
        while [ $TRUE ]; do
            printf "__HEARTBEAT__ %d\n" "$(tput cols)"
            # for testing diagnostic logic only (match both "distcc[" AND "compile from"
#            printf "distcc[000000] compile from spoofed client record for testing \n"
            # for testing diagnostic logic only (match both "distcc[" AND "compile from"
#            printf "distccd[000000] compile from spoofed server record for testing\n"
            # for testing diagnostic logic only (match  "__DNS_UPDATE__")
#            printf "__DNS_UPDATE__    1.1.1.1    spoofed_test_host\n"
            sleep "$tui_refresh_period"
        done
    } | grep --line-buffered --text -E "$grep_filter"
}

stream_dns_hostfiles() {
    local result=0 ssh_cmd=""

    # define a sed filter to transform raw lines of dns /etc/hosts.d/* files
    #   into the update input format expected by the awk's __DNS_UPDATE__ action block
    #   employ with LC_ALL=C sed "$SED_DNS_FILTER"
    # line format: 192.168.62.183  g3nuc01.brendler  # eth0  2026-06-12_07:40:38  ddns-update-hook-ipv4-0.3.1
    # strip blank lines and comments
    SED_DNS_FILTER="/^${W0}#/d; /^${W0}$/d; "
    # strip all right of including # and whitespace immediately preceding it (note: escape \#)
    SED_DNS_FILTER+="s/${W1}#${P1}$//; "
    # prepend "__DNS_UPDATE__" as awk action block expects
    SED_DNS_FILTER+="s/^/__DNS_UPDATE__ /; "
    # now sort the data on ip address
    SORT_DNS_FILTER+="sort -k2"

    # group setup commands and redirect stdout to stderr to protect the awk stream
    {
        start_ssh_agent "$local_user"
        source "$AGENT_ENV_FILE"
        load_key "$local_user"
        j_msg -$debug -p "local_user: $local_user"
        j_msg -$debug -p "dns: $dns"
        j_msg -$debug -p "SSH_KEY: $SSH_KEY"
        j_msg -$notice -p -n "Streaming dns hosts files directly to awk memory cache"
    } >&2

    # run the ssh command, outputting the raw file contents directly to stdout
    # note: -n prevents stdin hanging; BatchMode=yes prevents interactive prompts
    sudo_cmd=( sudo -u "$local_user" SSH_AUTH_SOCK="$SSH_AUTH_SOCK" )
    ssh_cmd=( ssh -n -q -i "$SSH_KEY" -o ConnectTimeout=2 -o BatchMode=yes "${remote_user}@${dns}" )
    payload_cmd=( cat '/etc/hosts.d/*' )
    sort_cmd=( sort -k2 )
    "${sudo_cmd[@]}" "${ssh_cmd[@]}" "${payload_cmd[@]}" | sed "$SED_DNS_FILTER" | "${sort_cmd[@]}"
    result=$?
    # group teardown commands and redirect stdout to stderr
    {
        handle_result $result "" "" $notice
        unload_key "$local_user" && \
        stop_ssh_agent "$local_user"
        result=$?
        j_msg -$notice -p "Done streaming dns host files; exiting with status code [$result]"
    } >&2
}

validate_tui_iput_logfile() {
    vti_ret=0
    # ensure mode-dependet log file exists and has proper ownership and permissions
    local file="" perms="" ownership=""
    case "$mode" in
        client)
            file="/var/log/distcc/distcc-client.log"
            perms="644"
            ownership="portage:portage"
            ;;
        server)
            file="/var/log/distcc/distccd.log"
            perms="644"
            ownership="distcc:daemon"
            ;;
        *) return 1 ;;
    esac
    # find or create the input logfile
    j_msg -$notice -p -n "Looking for input logfile [$file]"
    [ -f "$file" ]
    handle_result $? "found" "not found" $notice
    if [ ! $? -eq 0 ]; then
        j_msg -$notice -p -n "Creating input logfile [$file]"
        touch "$file"
        handle_result $? "created" "" $notice || vti_ret=1
    fi
    # set permissions on input logfile
    j_msg -$notice -p -n "Setting permissions on input logfile [$file]"
    chmod "$perms" "$file"
    handle_result $? "$(stat -c %a "$file")" "" $notice || vti_ret=$(( vti_ret | 2 ))
    # set ownership on input logfile
    j_msg -$notice -p -n "Setting ownership of input logfile [$file]"
    chown "$ownership" "$file"
    handle_result $? "$(stat -c %U:%G  "$file")" "" $notice || vti_ret=$(( vti_ret | 4 ))
    return $vti_ret
}

#-----[ main script ]--------------------------------------------------------------------------
checkroot
separator "${PN}-${BUILD}" "(initialization)"
validate_logfile
# status file is not used since there is no command sequence, but validate and store 0 to prevent errors
validate_root_file "$status_file"
echo 0 > "$status_file"

process_cmdline "$@" || die "failed to parse_cmdline"
configure_mode || die "failed to configure_mode"
# validate availability of input logfile (must configure mode first)
validate_tui_iput_logfile || die "failed to validate_tui_iput_logfile"

show_config || die "failed to show_config"
confirm_continue_or_exit

# run this "forever"
run_tui_engine || die "failed to run_tui_engine"

