#!/bin/bash
source /usr/sbin/script_header_joetoo
#IPnet=192.168.66
#IPnet=192.168.1
#IPnet=169.254.1
PN=${0##*/}   # basename

#-----[ variables ]----------------------------------------------
livehosts=()
yes_count=0
wait_time=2
cnum=0; start=1;  end=254

#-----[ functions ]----------------------------------------------

usage(){
  j_msg -${err} "usage: ${PN} [cnum] [start] [end]"
  exit 1
}

#-----[ main script ]----------------------------------------------
[[ $1 == "-h" ]] && usage
[[ $# -gt 0 ]] && cnum=$1
[[ $# -gt 1 ]] && start=$2
[[ $# -gt 2 ]] && end=$3
IPnet=192.168.$cnum

j_msg -${notice} -p "scanning..."
for ip in $(seq $start $end)
do
SCP
HCU
j_msg -${notice} -p -n "scanning ${IPnet}.${ip} "
RCP
  result=$(ping -c1 -w${wait_time} ${IPnet}.${ip} | grep transmitted | \
           cut -d',' -f3 | cut -d'%' -f1 | sed 's/ //g')
  if [[ ${result} == 0 ]]
  then
    j_msg -${notice} -mp -n "${IPnet}.${ip}"
    j_msg -${notice} -mp -n " ("${result}"% loss) --> ${BGon}*** YES ***${Boff}"
    j_msg -${notice} -mp " ${BGon}${IPnet}.${ip}${Boff}"
    let "yes_count++";  livehosts[$yes_count]="$ip"
  else
    j_msg -${notice} -mp -n "${IPnet}.${ip}"
    j_msg -${notice} -mp " ("${result}"% loss) --> ${BRon}--- no ---${Boff}"
  fi
done
j_msg -${notice} -p "Done scanning."
SCU
