#!/bin/bash
source /usr/sbin/script_header_joetoo
#IPnet=192.168.66
#IPnet=192.168.1
#IPnet=169.254.1
VERBOSE=$FALSE
verbosity=0
livehosts=()
yes_count=0
wait_time=2
cnum=0; start=1;  end=254
[[ $# -gt 0 ]] && cnum=$1
[[ $# -gt 1 ]] && start=$2
[[ $# -gt 2 ]] && end=$3
IPnet=192.168.$cnum
message "scanning..."
for ip in $(seq $start $end)
do
SCP
HCU
message_n "scanning ${IPnet}.${ip} "
RCP
  result=$(ping -c1 -w${wait_time} ${IPnet}.${ip} | grep transmitted | \
           cut -d',' -f3 | cut -d'%' -f1 | sed 's/ //g')
  if [[ ${result} == 0 ]]
  then
    echo -n "${IPnet}.${ip}"
    echo -en " ("${result}"% loss) --> ${BGon}*** YES ***${Boff}"
    echo -e " ${BGon}${IPnet}.${ip}${Boff}"
    let "yes_count++";  livehosts[$yes_count]="$ip"
  else
    echo -n "${IPnet}.${ip}"
    echo -e " ("${result}"% loss) --> ${BRon}--- no ---${Boff}"
  fi
done
echo "Done scanning."
SCU
#if [[ $yes_count -gt 0 ]]
#then
#  for (( i=1; i<$(($yes_count + 1)); i++))
#  do
#    message_n "Looking up live host [${IPnet}.${livehosts[i]}]"
#    result="$(traceroute -w .2 -m 1 ${IPnet}.${livehosts[i]} | grep ' ms')"
#    [[ $result ]] && name=$(echo "$result" | sed 's/  / /g' | cut -d' ' -f3) \
#                  || name="No name found for ${IPnet}.${livehosts[i]}"
#    echo -e " name: $name"
#  done
#fi
