#!/bin/bash
#
# mitigate 2025-2026 problem with Elrond
# (joetoo dns/router/radvd/openvpn/stubby/chronyd... server)
# failing to answer IPv6 neighbor solicitations
# for its LAN ULA address
#
JOETOO_LAN_ROUTER_IP6="fd62:6262:6262::17"
JOETOO_LAN_ROUTER_MAC="92:50:42:51:f1:c1"

iface=${1:?interface required}

ip link show dev "${iface}" &>/dev/null || exit 0

declare -a ip_args=( -6 neigh )  #........# operate on the IPv6 neighbor table
ip_args+=( replace "${JOETOO_LAN_ROUTER_IP6}" )  # create/replace the neighbor entry for the dns/router
ip_args+=( lladdr "${JOETOO_LAN_ROUTER_MAC}" )   # associate the dns/router's MAC address
ip_args+=( dev "${iface}" )   #...........# install the entry on this interface
ip_args+=( nud permanent )   #............# make this neighbor mapping static

ip "${ip_args[@]}"   #....................# install the mapping
