#!/bin/bash
#mysubnet="192.168.7.0/24"
#mysubnet="192.168.67.0/24"
#mysubnet="192.168.66.0/24"
#mysubnet="192.168.1.0/24"
#mysubnet="192.168.64.0/22"

outfile=/home/joe/nmap_report

ABnet="192.168"
#ABnet="10.0"
#Cnet="64"
Cnet="66"
#Cnet="1"
#MASKbits="22"
MASKbits="24"

[[ $# -gt 0 ]] && Cnet=$1
[[ $# -gt 1 ]] && MASKbits=$2

mysubnet="${ABnet}.${Cnet}.0/${MASKbits}"
rm ${outfile}
echo "Scanning subnet [ ${mysubnet} ]..."
nmap -A -T5 -p22 -v3 ${mysubnet} > ${outfile}

echo && echo "Found info for:"
cat ${outfile} | grep -v 'host down' | grep '(' | grep 'report for'
