#!/bin/bash
source /usr/sbin/script_header_joetoo

tcp_neighbors=()
for x in $(ip tcp_metrics | cut -d' ' -f1 | sort -u )
do
  tcp_neighbors+=("$x")
  # use 'host' for clean POSIX-style parsing (rather than nslookup)
  this_name=$(host "$x" 2>/dev/null | awk '/domain name pointer/ {print $NF}' | sed 's/\.$//')
  if [ -n "${this_name}" ]; then
    neighbor_names+=("ns: ${this_name}")  # note: ns indicates source = nameserver
  else
    # whois grep to catch OrgName or Organization
    _org=$(whois "$x" 2>/dev/null | awk -F': ' '/^OrgName|^Organization|^owner/ {print $2; exit}' | sed 's/^[ \t]*//')
    neighbor_names+=("wi: ${_org:-Unknown}")   # note: wi indicates source = whois
  fi
  count=$((${#tcp_neighbors[@]}-1))
  j_msg -${notice} -p "tcp neighbor: ${tcp_neighbors[$count]}"
  j_msg -${notice} -mp "    neighbor name: [${neighbor_names[$count]}]"
  j_msg -${notice} -mp "    ${BCon}$x ${BRon}${neighbor_names[$count]}${Boff}"
done

j_msg -mp "\nfound ${#tcp_neighbors[@]} tcp neighbors"
j_msg -mp "found ${#neighbor_names[@]} neighbors names"

