# Configuration for resolvconf(8)
# See resolvconf.conf(5) for details

resolv_conf=/etc/resolv.conf
# If you run a local name server, you should uncomment the below line and
# configure your subscribers configuration files below.
#name_servers=127.0.0.1

# prevent specific domains from ever entering the search path
# (e.g. this one from cayenne)
domain_blacklist="mynetworksettings.com"

# optional: to totally ignore the WiFi DNS server
# (e.g. for cayenne)
name_server_blacklist="192.168.7.31"
