# /etc/tmux.conf
# user can override in  ~/.tmux.conf

# screen muscle memory: prefix to ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# true color and terminal compatibility
# Tc tells tmux to use true color, and xterm-256color as default terminal
#set -g default-terminal "xterm-256color"   # <-- change to tmux-256color
set -g default-terminal "tmux-256color"    # match tmux capability properly
set -as terminal-overrides ",xterm*:Tc"    # baseline template xterm default
set -as terminal-overrides ",konsole*:Tc"  # add konsole to template (comment out if not present)

# increase scrollback buffer
set -g history-limit 10000

# enable mouse and clipboard (optional but helpful)
set -g mouse on
set -s set-clipboard on

# colorize status bar red for root, green for user
if-shell '[ "$USER" = "root" ]' \
    "set -g status-style bg=red,fg=white,bold" \
    "set -g status-style bg=green,fg=black"


# Use system vlock (either kbd or app-misc/vlock) to secure detached sessions
set -g lock-command "vlock" # (this command meybe un-needed)
bind x lock-session
