#!/bin/bash
source /usr/sbin/script_header_joetoo
#useFile="$1"
[ $# -eq 1 ] && useFile="$1" || E_message "specify the use file to be sorted"
[ ! -f "$useFile" ] && E_message "Error argument [$1] is not a file" && exit 1

sortline()
{
  # first entry on the line is the package name
  local pkg="$1"; shift
  # in a use_expand variable, the second entry would contain a colon
  if echo $1 | grep -q ":" 
  then
    pkg+=" $1" ; shift
  fi
  local instr="$@"
  local outstr="$pkg $( echo $(for x in $instr; do echo $x; done | sort -i))"
  [[ ${#outstr} -gt 1 ]] && echo "${outstr}"
}

#-----[ main script ]--------------------------------------------------------------
while read Line; do sortline $Line; done < $useFile | sort | grep -v '^#'


