#!/bin/bash
# bashrc_aliases_include_joe_brendler
# source this in your .bashrc file, where it says "Put your fun stuff here."

#-----[ my aliases ]--------------------------------------------------------------------
alias ll='ls -l --color=tty' 2>/dev/null
alias la='ls -al --color=tty' 2>/dev/null
alias lt='ls -alt --color=tty' 2>/dev/null
alias lr='ls -altr --color=tty' 2>/dev/null
alias lsr='ls -Slr --color=tty' 2>/dev/null
alias lz='ls -alZ --color=tty' 2>/dev/null

alias gcsm='git commit -s -m '
alias gpom='git push origin master'

alias bt='LC_ALL=en_US.UTF8 btop'

alias qm='qemu-image-mount'
alias ql='qemu-image-launch'

alias ow='xdotool_open_windows'
alias cw='xdotool_close_windows'
alias mw='xdotool_sizemove_this_window'

alias tl='tail -n50'

alias mb='mount /boot'

alias eix-names='eix -#'
alias clean-perl='emerge -avC $(eix -cI# perl)'

alias make0="make O=~/build/dom0"
alias makeU="make O=~/build/domU"

alias joemerge='emerge --keep-going --with-bdeps=y --binpkg-respect-use=y --binpkg-changed-deps=y'

alias icmerge='FEATURES="-collision-detect -protect-owned" emerge -1'
alias nobinmerge='MAKEOPTS="-j2 -l2" FEATURES=" -getbinpkg -userpriv -distcc" emerge -1'
alias j1merge='MAKEOPTS="-j1" FEATURES=" -getbinpkg -userpriv -distcc" emerge -1'
alias nodistmerge='MAKEOPTS="-j2 -l2" FEATURES=" -userpriv -distcc" emerge -1'
alias distmon='DISTCC_DIR="/var/tmp/.distcc" distccmon-text 1'
alias distgui='DISTCC_DIR="/var/tmp/.distcc" distccmon-gui'

#-----[ my commonly used functions ]----------------------------------------------------
# to do  -- rename these "-joetoo" and then fix everything that breaks
source /usr/sbin/script_header_joetoo
source /usr/sbin/script_header_joetoo_extended

#-----[ my PATH ]-----------------------------------------------------------------------
export PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/bin:/sbin:/usr/sbin:/root/bin:/usr/local/sbin:/usr/local/bin:${PATH}:/opt/bin:/home/joe/script

#/usr/sbin:/usr/bin:/sbin:/bin:

alias dist_path='export PATH=/usr/lib/distcc/bin:/root/bin:/usr/local/sbin:/usr/local/bin:${PATH}:/opt/bin:/home/joe/script'

alias nodist_path='source /usr/bin/setnodistpath'

which()         # return full path of executable "$1"
{ (alias; declare -f) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@ ; } ; export -f which

mequery_b()     # identify the package that installed file $1
{ (alias; declare -f) | grep -l -r -e $(echo "bin/"$(basename $(which ${1?} ))) /var/db/pkg/ --include=CONTENTS | awk -F'/' '{print $5"/"$6}' ; }

#-----[ PORTDIR, PKGDIR, DISTDIR ]-----------------------------------------------------
#eval $( grep ^PORTDIR /etc/portage/make.conf )
#eval $( grep ^PKGDIR /etc/portage/make.conf )
#eval $( grep ^DISTDIR /etc/portage/make.conf )
# source make.conf b/c we can't do it this way for systems that set e.g. PORTDIR="${ROOT}var/db/repos/gentoo"
source /etc/portage/make.conf
