#!/bin/bash
# filter output of "git status" and automatically act on it
# joe brendler 06/09/2024
#
while read line
do 
  set -- ${line}
  case $# in
    2 )
      # these objects may have been added, modified, or deleted - act appropriately
      action="$1"
      object="$2"
      echo "-----[ case: $# ]----------------------------" ;
      echo -e "action: $action \t object: $object" ;
      [ "${action}" == "deleted:" ] && git rm $object || git add $object ;
      echo "Done with ${action} for object ${object}" ;;
    1 )
      # these are "untracked" objects, so add them
      action="add-untracked"
      object="$1"
      echo "-----[ case: $# ]----------------------------" ;
      echo -e "action: $action \t object: $object" ;
      git add $object ;
      echo "Done with ${action} for object ${object}" ;;
    * )
      echo "-----[ case: * ]----------------------------" ;
      echo "Invalid line [ ${line} ]" ;
      echo "# args: [ $# ]";
      exit 1 ;;
  esac
  echo
done <<<$(git status | grep '^[[:space:]]' | grep -v '(use')
