#!/bin/bash
# bs2 - implements simple binary search for target ($2) in list or inputfile ($1)
source /usr/sbin/script_header_joetoo
source /usr/sbin/script_header_joetoo_extended
if ! command -v j_msg >/dev/null 2>&1; then printf '%s\n' "error: header /usr/sbin/script_header_joetoo not sourced"; exit 1; fi
if ! command -v bs_2 >/dev/null 2>&1; then die "header /usr/sbin/script_header_joetoo_extended not sourced"; fi

### note: function bs2() incorporated into   /usr/sbin/script_header_joetoo_extended

#----[ main script - alphabetize the list, then search it ]---------------

(( depth = 0 ))     # ((...)) forces arithmetic context, where = assigns and == compares
(( result = -1 ))
if [ -f "$1" ]; then
  # read an input file (sort lines)
  j_msg -${debug} -p "reading input file into search_array array"
  infile="$1"
  readarray -t search_array < <(sort -udb  "$infile")
  j_msg -${debug} -p "array search_array has [${#search_array[@]}] elements"
else
  # read a regular quoted list (for-loop to word-split and sort words)
  j_msg -${debug} -p "reading input list into search_array array"
  list="$1"
  readarray -t search_array < <(for x in $list; do echo $x; done | sort -udb)
  j_msg -${debug} -p "array search_array has [${#search_array[@]}] elements"
fi

(( limit = ${#search_array[@]} ))
target="$2"
j_msg -${notice} -p "${BYon}Looking for ${BWon}$target ${BYon}in ${BWon}${search_array[@]} ${BYon}--${Boff}"
j_msg -${notice} -p "  ${BYon}searching among ${BWon}${#search_array[@]} ${BYon}candidate elements ...${Boff}"
j_msg -${debug} -p "search_array[@]: ${search_array[@]}"
j_msg -${debug} -p "target: $target"
j_msg -${debug} -p "limit: $limit"
echo
# pass the NAME of the global array (not the array itself)
bs_2 search_array "$target" 0 $limit
j_msg -${debug} -p "just got back from doing bs, result is $result"
if [[ ${result} -gt 0 ]]; then
  j_msg -${notice} -p "${BGon}Found ${search_array[result]} at element ${BWon}${result}${BGon} of input --${Boff}"
  j_msg -${notice} -m "[${search_array[@]}]"
else
  j_msg -${err} "${BRon}Not found${Boff}"
fi
echo
j_msg -${debug} -p "(had to go to depth $depth to figure that out)"
