#!/bin/bash
source /usr/sbin/script_header_joetoo
source /usr/sbin/script_header_joetoo_unicode

#-----[ varaiables ]-----------------------------------------

PN=$(basename $0)

archives=(
'/usr/local/share/ca-certificates/server_certs/archive/'
'/usr/local/share/ca-certificates/server_certs/'
'/usr/local/share/ca-certificates/archive/'
)

#-----[ functions ]-----------------------------------------
die() {
    bremoji "$no_entry"
    E_message "$1"
    exit 1
}

clean_archive() {
    _archive="$1"
    for x in $(find "${_archive}" -type f -printf '%f\n' | sed 's|.crt||'); do
        # remove the symlink in /etc/ssl/certs
        message_n "removing /etc/ssl/certs/ symlink [$x.pem] ... "
        if [ -L "/etc/ssl/certs/$x.pem" ] ; then
            rm /etc/ssl/certs/$x.pem || die "failed to rm /etc/ssl/certs/$x.pem"
            bremoji "$check_mark_button"
            right_status $TRUE
        else
            E_message "No /etc/ssl/certs/$x.pem symlink exists on this system"
        fi
        # now remove the cert from ${_archive}
        message_n "removing archived [$x.crt] ... "
        if [ -f "${_archive}/$x.crt" ] ; then
            rm -r "${_archive}/$x.crt" || die "failed to rm -r ${_archive}/$x.crt"
            bremoji "$check_mark_button"
            right_status $TRUE
        else
            E_message "No ${_archive}/$x.crt file exists on this system"
        fi
    done

    #now remove the parent directory (${_archive})
    message_n "removing ${_archive} ... "
    if [ -d "${_archive}" ] ; then
        rm -r "${_archive}" || die "failed to rm -r ${_archive}"
        bremoji "$check_mark_button"
        right_status $TRUE
    else
        "No ${_archive} directory exists on this system"
    fi
}


#-----[ main script ]-----------------------------------------
checkroot
separator "$(hostname)" "$PN"

for archive in "${archives[@]}"; do
    if [ -d "${archive}" ] ; then
        echo
        bremoji "$hammer"
        message "cleaning archive [${archive}]"
        clean_archive "${archive}"
    else
        E_message "No [${archive}] exists on this system, skipping"
    fi
done

echo
bremoji "$axe"
message_n "cleaning residual broken symlinks in /etc/ssl/certs"
# find ... -delete returns 0 if no file found, or if found an properly deleted
find /etc/ssl/certs/ -xtype l -delete >/dev/null 2>&1
result="$?"
if [ $result -eq 0 ] ; then
    bremoji "$check_mark_button"
    right_status $TRUE
else
    bremoji "$cross_mark"
    right_status 1
    E_message "error [$result]"
fi

message "${BYon}run ${Gon}ls -al /etc/ssl/certs/${BYon} to verify${Boff}"
bremoji "$face_beam"
message "${BGon}Done${Boff}"
echo
