#!/bin/bash
source /usr/sbin/script_header_joetoo
source /usr/sbin/script_header_joetoo_unicode

PN=$(basename $0)
checkroot

separator "$(hostname)" "$PN"

archive="/usr/local/share/ca-certificates/server_certs/archive/"

die() {
    bremoji "$no_entry"
    E_message "$1"
    exit 1
}

for x in $(find "${archive}" -type f -printf '%f\n' | sed 's|.crt||'); do
    # remove the symlink in /etc/ssl/certs
    message_n "removing /etc/ssl/certs/ symlink [$x.pem] ... "
    rm /etc/ssl/certs/$x.pem || die "failed to rm /etc/ssl/certs/$x.pem"
    bremoji "$check_mark_button"
    right_status $TRUE
    # now remove the cert from ${archive}
    message_n "removing archived [$x.crt] ... "
    rm -r "${archive}/$x.crt" || die "failed to rm -r ${archive}/$x.crt"
    bremoji "$check_mark_button"
    right_status $TRUE
done

#now remove the parent directory (${archive})
message_n "removing ${archive} ... "
rm -r "${archive}" || die "failed to rm -r ${archive}"
bremoji "$check_mark_button"
right_status $TRUE

bremoji "$face_beam"
message "${BGon}Done${Boff}"
echo
