#!/bin/bash
source /usr/sbin/script_header_joetoo

#-----[ varaiables ]-----------------------------------------

PN=${0##*/}

archives=(
'/usr/local/share/ca-certificates/server_certs/archive/'
'/usr/local/share/ca-certificates/server_certs/'
'/usr/local/share/ca-certificates/archive/'
'/usr/local/share/ca-certificates/'
)

#-----[ functions ]-----------------------------------------

clean_archive() {
    _archive="$1"
    # load array of certs found in this archive (excluding ones to keep)
    mapfile -t _certs_list < <(
        find "${_archive}" -type f \
            ! -name "imjoe*" \
            ! -name "Brendler_Consulting*" \
            -printf '%f\n' | \
        sed 's|\.crt||'
    )

    for x in "${_certs_list[@]}"; do
        # remove the symlink in /etc/ssl/certs
        j_msg -${notice} -p -n "removing /etc/ssl/certs/ symlink [$x.pem] ... "
        if [ -L "/etc/ssl/certs/$x.pem" ] ; then
            rm /etc/ssl/certs/$x.pem || die "failed to rm /etc/ssl/certs/$x.pem"
            bremoji "$check_mark_button"
            right_status $TRUE ${notice}
        else
            j_msg -${err} "No /etc/ssl/certs/$x.pem symlink exists on this system"
        fi
        # now remove the cert from ${_archive}
        j_msg -${notice} -p -n "removing archived [$x.crt] ... "
        if [ -f "${_archive}/$x.crt" ] ; then
            rm -r "${_archive}/$x.crt" || die "failed to rm -r ${_archive}/$x.crt"
            bremoji "$check_mark_button"
            right_status $TRUE ${notice}
        else
            j_msg -${err} "No ${_archive}/$x.crt file exists on this system"
        fi
    done

    #now remove ${_archive} if it is a sub-directory
    if [ "${_archive}" != "/usr/local/share/ca-certificates/" ] ; then
        j_msg -${notice} -p -n "removing ${_archive} ... "
        if [ -d "${_archive}" ] ; then
            rm -r "${_archive}" || die "failed to rm -r ${_archive}"
            bremoji "$check_mark_button"
            right_status $TRUE ${notice}
        else
            "No ${_archive} directory exists on this system"
        fi # directory exists
    else
        j_msg -${err} "Not deleting parent directory /usr/local/share/ca-certificates/"
    fi # subdirectory
}


#-----[ main script ]-----------------------------------------
checkroot
separator "$(hostname)" "$PN"

for archive in "${archives[@]}"; do
    if [ -d "${archive}" ] ; then
        echo
        bremoji "$hammer"
        message "cleaning archive [${archive}]"
        clean_archive "${archive}"
    else
        j_msg -${err} "No [${archive}] exists on this system, skipping"
    fi
done

echo
bremoji "$axe"
j_msg -${notice} -p -n "cleaning residual broken symlinks in /etc/ssl/certs"
# find ... -delete returns 0 if no file found, or if found an properly deleted
find /etc/ssl/certs/ -xtype l -delete >/dev/null 2>&1
result="$?"
if [ $result -eq 0 ] ; then
    bremoji "$check_mark_button"
    right_status $TRUE ${notice}
else
    bremoji "$cross_mark"
    right_status 1 ${notice}
     j_msg -${err} "error [$result]"
fi

message "${BYon}run ${Gon}ls -al /etc/ssl/certs/${BYon} to verify${Boff}"
bremoji "$face_beam"
message "${BGon}Done${Boff}"
echo
