#!/bin/bash
# ebup - (c) joe brendler 2025-2055
# create an ebuild with version-upgraded filename
#

source /usr/sbin/script_header_joetoo

PN=${0##*/}   #  like =$(basename $0) but w/o subshell and function call

if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi

[ -z $verbosity ] && verbosity=${notice}  # assign default if null; allow calling program to dictate

user="joe"
archived_ebuilds_dir="/home/${user}/archived_ebuilds"

#-----[ variables ]--------------------------------------------------

to_be_archived_ebuild_version=""   # oldest (to-be-archived) version string (to be determined)
latest_ebuild_version=""           # latest version string (to be determined)
new_ebuild_version=""              # new version string (to be calculated)
output_ebuild_filename=""          # filename for the new version's ebuild

declare -a ebuild_versions         # indexed array of version strings

current_version_numbers=( 0 0 0 )  # array of digits constituting the parts (major minor patch) of current version number
new_version_numbers=()             # array to hold new version's digits, when calculated

old_dir=$(pwd)

#-----[ functions ]--------------------------------------------------
usage() {
    j_msg -${err} -p "${BRon}usage: ${BGon}${PN} <SOURCE_DIR> [-major|-minor]${Boff}"
    j_msg -${notice} -p "${BYon}Notes:${Boff}"
    j_msg -${notice} -m "${BCon}(1)${Boff} ${BMon}SOURCE_DIR${Boff} must be a directory (containing a package's ebuilds)"
    j_msg -${notice} -m "${BCon}(2)${Boff} only one of the semantic versioning format numbers will be incremented"
    j_msg -${notice} -m "    automatically (major.minor.patch)"
    j_msg -${notice} -p "${BCon}(3)${BWon} upgrade type [-pa|ma|mi] is optional${Boff}"
    j_msg -${notice} -m "  -pa[tch] optionally indicates a patch upgrade (${BWon}default${Boff})"
    j_msg -${notice} -m "  -ma[jor] optionally indicates a major upgrade"
    j_msg -${notice} -m "  -mi[nor] optionally indicates a minor upgrade"
    exit 1
}

load-ebuild_versions() {
    # check SOURCE_DIR
    if [[ "$SOURCE_DIR" == "." ]] ; then
        j_msg -${notice} -p -n "updating SOURCE_DIR [$SOURCE_DIR]"
        SOURCE_DIR=$(pwd) || die "failed to set SOURCE_DIR to pwd"
        j_msg -${notice} -mp -n " (${BGon}${SOURCE_DIR##*/}${Boff})"   # display only basename for brevity
        right_status $TRUE ${notice}
    elif [[ "$SOURCE_DIR" == ".." ]] ; then
        j_msg -${notice} -p -n "moving to .."
        cd .. || die "failed to move to .."
        right_status $TRUE ${notice}
        j_msg -${notice} -p -n "updating SOURCE_DIR [$SOURCE_DIR]"
        SOURCE_DIR=$(pwd) || die "failed to set SOURCE_DIR to pwd"
        j_msg -${notice} -mp -n " (${BGon}${SOURCE_DIR##*/}${Boff})"   # display only basename for brevity
        right_status $TRUE ${notice}
    elif [[ "$SOURCE_DIR" == *"/"* ]] ; then
        j_msg -${notice} -p -n "moving to .."
        cd "$SOURCE_DIR" || die "failed to move to [$SOURCE_DIR]"
        right_status $TRUE ${notice}
        j_msg -${notice} -p -n "updating SOURCE_DIR [$SOURCE_DIR]"
        SOURCE_DIR=$(pwd) || die "failed to set SOURCE_DIR to pwd"
        j_msg -${notice} -mp -n " (${BGon}${SOURCE_DIR##*/}${Boff})"   # display only basename for brevity
        right_status $TRUE ${notice}
    else
        [ ! -d $SOURCE_DIR ] && die "SOURCE_DIR [$SOURCE_DIR] does not exist"
    fi
    # if we get here, SOURCE_DIR is set to something that exists

    # load the ebuild_versions array
    # load array of version numbers for ebuilds matching the name of SOURCE_DIR
    # use \0 as newline delimter for whitespace-safe handling of filenames
    # subsititutions strip the package name and .ebuild extension to leave just the version number
    # sort -rV puts them in reverse version order , -z tells sort to use the \0 delimiter
    readarray -d $'\0' ebuild_versions < <(
        find ./ -maxdepth 1 -name "${SOURCE_DIR}*.ebuild" -printf '%f\0' |
        sed -z "s|^${SOURCE_DIR}-|| ; s|.ebuild$||" |
        sort -rVz
    )
    result=$?
    j_msg -${debug} -p "#: [$#ebuild_versions[@]}] ebuild_versions: [${ebuild_versions[*]}]"

    # return to old_dir
    j_msg -${notice} -p -n "moving back to old_dir [$old_dir]"
    cd "$old_dir" || die "failed to cd to old_dir"
    right_status $TRUE ${notice}

    return $result
}

get-current-version() {
    j_msg -${debug} -p "in ${FUNCNAME[0]}"
    # put the latest version number string into latest_ebuild_version variable
    local result=""
    j_msg -${debug} -p "ebuild_versions #: ${#ebuild_versions[@]}"
    # identify the latest version (sort -r puts it at array index 0)
    if [ ${#ebuild_versions[@]} -eq 0 ] ; then
        # there are no ebuilds matching SOURCE_DIR,
        # so current ebuild version = 0.0.0 [i.e. none]
        j_msg -${notice} -p "no ebuilds matching SOURCE_DIR [${SOURCE_DIR}] found"
        j_msg -${notice} -m " so current ebuild version = 0.0.0 [i.e. none]"
    else
        latest_ebuild_version="${ebuild_versions[0]}"
        j_msg -${debug} -p "latest_ebuild_version: [$latest_ebuild_version]"
        # ignore any revision number that may be part of the current version number
        # final substitution sed -z 's|-r.*$|| removes such a trailing revision number
        # (ok here, b/c the new version just bumps patch, minor, or major // never rev)
        latest_ebuild_version=$(printf '%s\n' "$latest_ebuild_version" | sed -z 's|-r.*$||' )
        j_msg -${notice} -p "current version: [${latest_ebuild_version}]"
        # split version into ( major minor patch )
        IFS='.' read -ra current_version_numbers <<< "$latest_ebuild_version"
        result=$?
         # bash/ksh/zsh non-portable idiom: $'...'
         #(ANSI-C Quoting): tells shel to interpret backslash-escaped chars as literal control chars
#        IFS=$' \t\n'
        # Reset IFS to its default value (portable version)
        IFS=$(printf ' \t\n')
    fi
    j_msg -${notice} -m "  current major: ${current_version_numbers[0]}"
    j_msg -${notice} -m "  current minor: ${current_version_numbers[1]}"
    j_msg -${notice} -m "  current patch: ${current_version_numbers[2]}"
    return $result
}

get-archive-version() {
    local _gav_count="${#ebuild_versions[@]}"
    local _gav_idx=$(( _gav_count - 1 ))  # index of the oldest version
    # put the oldest (to-be-archived) version number string into to_be_archived_ebuild_version variable
    j_msg -${debug} -p "ebuild_versions #: ${#ebuild_versions[@]}"
    # identify the latest version
    if [ "${#ebuild_versions[@]}" -le 1 ] ; then
        # if there are no ebuilds matching SOURCE_DIR, or
        # if there is only 1, then there is nothing to archive
        case "${#ebuild_versions[@]}" in
            0 ) j_msg -${notice} -m "no ebuilds matching SOURCE_DIR [${SOURCE_DIR}] found" ;;
            1 ) j_msg -${notice} -m "not archiving the only ebuild present" ;;
            * ) j_msg -${err} -p "Error: this cannot happen"; return 1 ;;
        esac
        to_be_archived_ebuild_version="none"
    else
        to_be_archived_ebuild_version="${ebuild_versions[_gav_idx]}" || die "failed to assign to_be_archived_ebuild_version="
        j_msg -${notice} -m "archive version: [${to_be_archived_ebuild_version}]"
    fi
    return 0
}

calculate-new-version() {
    # increment the version number appropriately
    local result=""
    local UPGR="$1"
    case "${UPGR}" in
        "major" )
            # increment major number and reset minor patch number to 0
            new_version_numbers[0]="$(( ${current_version_numbers[0]} + 1 ))"
            new_version_numbers[1]="0"
            new_version_numbers[2]="0"
            ;;
        "minor" )
            # increment minor number and reset patch number to 0
            new_version_numbers[0]="${current_version_numbers[0]}"
            new_version_numbers[1]="$(( ${current_version_numbers[1]} + 1 ))"
            new_version_numbers[2]="0"
            ;;
        "patch" )
            # just increment patch number
            new_version_numbers[0]="${current_version_numbers[0]}"
            new_version_numbers[1]="${current_version_numbers[1]}"
            new_version_numbers[2]="$(( ${current_version_numbers[2]} + 1 ))"
            ;;
        * )  j_msg -${err} -p "invalid UPGRADE type [${UPGR}]" && exit ;;
    esac
    j_msg -${notice} -p "  new major: ${new_version_numbers[0]}"
    j_msg -${notice} -p "  new minor: ${new_version_numbers[1]}"
    j_msg -${notice} -p "  new patch: ${new_version_numbers[2]}"
    new_ebuild_version="${new_version_numbers[0]}.${new_version_numbers[1]}.${new_version_numbers[2]}"
    result=$?
    j_msg -${notice} -p "new version: ${new_ebuild_version}"
    return $result
}

archive-old-version() {
    # move the oldest version to the archived_ebuilds_dir
    local msg=""
    archive_ebuild_filename="${SOURCE_DIR}-${to_be_archived_ebuild_version}.ebuild"

    # ensure the archive directory exists before attempting mv
    [ -d "${archived_ebuilds_dir}" ] || mkdir -p "${archived_ebuilds_dir}" || die "failed to create archive directory"

    if [[ "${to_be_archived_ebuild_version}" == "none" ]] ; then
        j_msg -${debug} -p "no ebuild to archive"
    elif [ -f "${archive_ebuild_filename}" ] ; then
        response=""
        msg="${BYon}About to run command:\n${Boff}"
        msg+="    ${BGon}mv  ${archive_ebuild_filename} "
        msg+="${archived_ebuilds_dir%/}/${Boff}"
        j_msg -${notice} -p "$msg"
        msg="${BYon}Please confirm ( ${BWon}y|Y[es]; "
        msg+=" s|S[kip]; n|N[o] (abort) ${BYon})${Boff}"
        yns_prompt "${msg}"
        case "$response" in
            [yY]*) mv "${archive_ebuild_filename}" "${archived_ebuilds_dir%/}/" || \
                     die "failed to archive old ebuild" ;;
            [sS]*) j_msg -${notice} -p "${BMon}Skipping archive as instructed${Boff}" ;;
            [nN]*) j_msg -${err} -p "Aborting as instructed" ; return 1;;
            *) j_msg -${err} -p "Invalid response [$response]" ; return 1;;
        esac
    else
        j_msg -${err} -p "Error: ebuild [${archive_ebuild_filename}] not found"
        return 1
    fi
    return 0
}

create-new-ebuild() {
    current_ebuild_filename="${SOURCE_DIR}-${latest_ebuild_version}.ebuild"
    output_ebuild_filename="${SOURCE_DIR}-${new_ebuild_version}.ebuild"
    local msg="${BYon}About to run command:\n${Boff}"
    msg+="    ${BGon}cp ${current_ebuild_filename} ${output_ebuild_filename}${Boff}"
    j_msg -${notice} -p "${msg}"
    confirm_continue_or_exit
    cp "${current_ebuild_filename}" "${output_ebuild_filename}"
    return $?
}

edit-new-ebuild() {
    response=""
    local msg="${BYon}Ready to edit new ebuild "
    msg+="[${BMon}${output_ebuild_filename}${BYon}]?${Boff}"
    yns_prompt "$msg"
    case ${response:0:1} in
        [yY] ) nano "${output_ebuild_filename}" ; result=$? ;;
        [sS] ) j_msg -${notice} -p "${BMon}Skipping edit as instructed${Boff}" ; result=0 ;;
        [nN] ) j_msg -${err} -p "Aborting as instructed" ; return 1;;
        *    ) j_msg -${err} -p "Invalid response [$response]" ; return 1;;
    esac
    return $result
}

pkgdev_manifest_new-ebuild() {
    response=""
    local msg="${BYon}Ready to run pkgdev manifest -f for the new ebuild "
    msg+="[${BMon}${output_ebuild_filename}${BYon}]?${Boff}"
    yns_prompt "$msg"
    case "$response" in
        [yY]*) pkgdev manifest -f "${output_ebuild_filename}" ; result=$? ;;
        [sS]*) j_msg -${notice} -p "${BMon}Skipping edit as instructed${Boff}" ; result=0 ;;
        [nN]*) j_msg -${err} -p "Aborting as instructed" ; return 1;;
        *) j_msg -${err} -p "Invalid response [$response]" ; return 1;;
    esac
    return $result
}

debug_marker() {
    # note: close double-quotes, single-quote the !, then re-open double quotes, else bash interprets ! as history expansion
    j_msg -${notice} -M $idx_heart_red -p "${Ron}D${BRon}e${Yon}b${BYon}u${Gon}g${BGon}_${BCon}M${Bon}a${BBon}r${Mon}k${BMon}e${Won}r${BWon}"'!'"${Boff} ${bin_explosion}"
    leave
}

#-----[ main script ]------------------------------------------------
checknotroot

[ $# -eq 0 ] && { j_msg -${err} -p "SOURCE_DIR not specified" ; usage ; }
[ $# -gt 2 ] && { j_msg -${err} -p "invalid arguments" ; usage ; }
if [ ! -d "$1" ]; then j_msg -${err} -p "SOURCE_DIR: [$1] does not exist" ; usage; else SOURCE_DIR="$1"; fi


if [ $# -eq 2 ] ; then
    [[ "${2:0:1}" != "-" ]] && j_msg -${err} -p "prefix option with \"-|\"" && usage
    case "$2" in
        "ma"*) UPGRADE="major" ;;
        "mi"*) UPGRADE="minor" ;;
        "pa"*) UPGRADE="patch" ;;
        *) j_msg -${err} -p "invalid option: [$2]"; usage ;;
    esac
    j_msg -${notice} -p "initiating ${UPGRADE=} upgrade ..."
else
    UPGRADE="patch"; j_msg -${notice} -p "initiating patch upgrade (as default) ..."
fi

separator "$(hostname)" "${PN}-${BUILD}"

load-ebuild_versions || die "failed to load-ebuild_versions"
get-current-version || die "failed to get-current-version"
get-archive-version || die "failed to get-archive-version"

archive-old-version || die "failed to archive-old-version"

calculate-new-version "${UPGRADE}" || die "failed to calculate-new-version ${UPGRADE}"

create-new-ebuild || die "failed to create-new-ebuild"

edit-new-ebuild || die "failed to edit-new-ebuild"

pkgdev_manifest_new-ebuild || die "failed to pkgdev_manifest_new-ebuild"

j_msg -${notice} -p -n "moving back to old_dir [$old_dir]"
cd "$old_dir" || die "failed to cd to old_dir"
right_status $TRUE ${notice}

j_msg -${notice} -p "${BGon}Done${Boff}"

#debug_marker
