#!/bin/bash
source /usr/sbin/script_header_joetoo
checkroot
distcc_log_dir="/var/log/distcc"
distcc_log_file="distccd.log"
intended_ownership="distcc:daemon"
PN=${0##*/}
if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD=0; fi

separator "$(hostname)" "${PN}-${BUILD}"
# check or create distcc_log_dir
j_msg -${notice} -p -n "checking for ${distcc_log_dir}"
if [ -d ${distcc_log_dir} ] ; then
    j_msg -${notice} -mp -n " (${BGon}exists${Boff})"
    right_status $TRUE ${notice}
else
    j_msg -${notice} -mp -n " (${BYon}creating${Boff})"
    mkdir ${distcc_log_dir} ; result=$?
    if [ $result -eq 0 ] ; then
        j_msg -${notice} -mp -n "(${BGon}done${Boff})"
        right_status $TRUE ${notice}
    else
        right_status 1 ${notice}
        die "failed to create ${distcc_log_dir}"
    fi # mkdir
fi # -d

# check or create distcc_log_file
j_msg -${notice} -p -n "checking for ${distcc_log_file}"
if [ -f ${distcc_log_dir%/}/${distcc_log_file} ] ; then
    j_msg -${notice} -mp -n " (${BGon}exists${Boff})"
    right_status $TRUE ${notice}
else
    j_msg -${notice} -mp -n " (${BYon}creating${Boff})"
    touch ${distcc_log_dir%/}/${distcc_log_file} ; result=$?
    if [ $result -eq 0 ] ; then
        j_msg -${notice} -mp -n "(${BGon}done${Boff})"
        right_status $TRUE ${notice}
    else
        right_status 1 ${notice}
        die "failed to create ${distcc_log_file}"
    fi # touch
fi # -f

# check or set permissions on distcc_log_file
j_msg -${notice} -p -n "checking ownership of ${distcc_log_file}"
ownership="$(stat -c '%U:%G' "${distcc_log_dir%/}/${distcc_log_file}")"
if [[ "${ownership}" == "${intended_ownership}" ]] ; then
    j_msg -${notice} -mp -n " (${BGon}${ownership}${Boff})"
    right_status $TRUE ${notice}
else
    j_msg -${notice} -mp -n " (${BRon}${ownership}, ${BYon}resetting${Boff})"
    chown "${intended_ownership}" "${distcc_log_dir%/}/${distcc_log_file}" ; result=$?
    if [ $result -eq 0 ] ; then
        j_msg -${notice} -mp -n "(${BGon}done${Boff})"
        right_status $TRUE ${notice}
    else
        right_status 1 ${notice}
        die "failed to reset ownership of ${distcc_log_file}"
    fi # chown
fi # ownerhsip

# restart distcc
j_msg -${notice} -p -n "restarting distcc service"
/etc/init.d/distccd restart >/dev/null 2>&1 ; result=$?
if [ $result -eq 0 ] ; then
    j_msg -${notice} -mp -n " (${BGon}started${Boff})"
    right_status $TRUE ${notice}
else
    right_status 1 ${notice}
    die "failed to restart distcc service"
fi # restart

separator "${PN}" "(current log)"
cat /var/log/distcc/distccd.log | sed 's|^|    |'
