#!/bin/bash
# see news grub2 article - recommends install both with and w/o --removable 
# syntax here taken from https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Bootloader
grub-install --efi-directory=/efi --target=x86_64-efi
grub-install --efi-directory=/efi --target=x86_64-efi --removable
