#!/bin/bash
source /usr/sbin/script_header_joetoo

PN=$(basename $0)
[ $# -gt 0 ] && E_message "${PN} does not accept arguments" && exit 1

separator $(hostname) ${PN}

# find the most recent sbc-headless-meta ebuild (find, sort by timestamp, pick last)
SEARCH_TERM="sbc-headless-meta"
SEARCH_DIR="/var/db/repos/joetoo/"
TARGET_EBUILD=$(find ${SEARCH_DIR} -iname "*${SEARCH_TERM}*.ebuild" -type f  -printf "%T@ %p\n" | \
    sort -n | tail -1 | cut -d' ' -f2)

# source this ebuild to evaluate is IUSE variable
source ${TARGET_EBUILD}

BOARD_LIST=()
# read only board names into BOARD_LIST() array
for x in $IUSE; do
    # ignoring the first character if it is a "+" or "-"
    case ${x#[+-]} in
        "innercore"|"gpio"|"joetoo"|"boot-fw"|"kernelimage") : ;; # do nothing
        * ) BOARD_LIST+=("${x}") ;;
    esac
done

# dump BOARD_LIST
for ((i=0; i<${#BOARD_LIST[@]}; i++)); do echo "  ${BOARD_LIST[${i}]}" ; done
