#!/bin/bash

for iface in $(netstat -iaw | grep -v Kernel | grep -v Iface | awk '{print $1}')
do
  altnames="$(ip link show dev ${iface} | grep altname | awk '{print $2}')"
  if [[ -n ${altnames} ]]
  then
    j_msg -${notice} -p -n "  ${iface}: "
    for x in ${altnames}
    do
      j_msg -${notice} -p -n "$x "
    done
    j_msg -${notice} -mp ""  # newline
  fi
done
