#!/bin/bash
for iface in $(netstat -iaw | grep -v Kernel | grep -v Iface | awk '{print $1}')
do
  altnames="$(ip link show dev ${iface} | grep altname | awk '{print $2}')"
  if [[ -n ${altnames} ]]
  then
    echo -n "  ${iface}: "
    for x in ${altnames}
    do
      echo -n "$x "
    done
    echo
  fi
done
