#!/bin/bash
# /usr/sbin/loggit
# Joe Brendler 1 Mar 2009
#
# Modified from John Brendler's Rev. 20 July 2007

[[ $# -gt 2 ]] && E_message "invalid loggit arguments" && exit 1;
[[ -z $2 ]] && EXIT_STATUS=0 || EXIT_STATUS="$2";
[[ -z $1 ]] && PROGRAM=Unspecified || PROGRAM="$1";
case $EXIT_STATUS in
    0) PRIORITY="notice" && MESSAGE="succeeded." ;;
    *) PRIORITY="err" && MESSAGE="failed with exit status ${EXIT_STATUS}" ;;
esac;
/usr/bin/logger -p cron.$PRIORITY "$PROGRAM $MESSAGE"
