#!/bin/bash
# move_joetoo_kernels_to_webserver  - (c) joe brendler 2025-2975
source /usr/sbin/script_header_joetoo
PN=$(basename $0)

user="joe"
joetoo_kernel_webserver_dir="/var/www/localhost/htdocs/joetoo-kernels"

TRIED=$FALSE ; ERROR=$FALSE
for tarball in $(find /home/${user}/ -maxdepth 1 -name 'linux*.tar.bz2') ; do
    TRIED=$TRUE
    message "found: ${tarball}"
    /usr/bin/logger -p cron.notice "${PN} found ${tarball}"
    message_n "moving it to webserver ..."
    cp ${tarball} ${joetoo_kernel_webserver_dir%/}/ 2>/dev/null ; result=$?
    if [ ! $result -eq 0 ] ; then
        ERROR=$TRUE ; right_status 1
        /usr/bin/logger -p cron.err "${PN} failed to copy tarball to webserver"
    else
        right_status $TRUE
        /usr/bin/logger -p cron.notice "${PN} copied tarball to webserver"
        message_n "removing  copy from /home/${user} ..."
        rm ${tarball} 2>/dev/null ; result=$?
        if [ ! $result -eq 0 ] ; then
            ERROR=$TRUE ; right_status 1
            /usr/bin/logger -p cron.err "${PN} failed to remove copy of tarball from /home/${user}/"
        else
            right_status $TRUE
            /usr/bin/logger -p cron.notice "${PN} removed copy of tarball from /home/${user}/"
        fi
    fi
done
[ $ERROR ] && exit_status=1 || exit_status=0
[ $TRIED ] && loggit $(basename $0) ${exit_status}
exit ${exit_status}
