#!/bin/bash
#
# source header (for checkroot, TRUE/FALSE, j_msg, etc.)
source /usr/sbin/script_header_joetoo

#----[ functions ]---------------------------------

usage() { j_msg -${err} "usage: php_memory_limit [show|fix <newlimit>] ";
          j_msg -${err} -mp "   e.g. php_memory_limit fix 1G" ; exit 1 ; }

#----[ local variables ]---------------------------
newlimit="1G" # default vaule; $2 overrides, if provided

#----[ main script ]--------------------------------
checkroot
[ $# -gt 2 -o $# -eq 0 ] && usage
[ $# -gt 1 -a ! "$1" == "fix" ] && usage || newlimit="$2"
[ $# -eq 1 -a "$1" == "fix" ] && usage
cmd="$1"
 j_msg -${debug} -p "cmd: [${cmd}] \tnewlimit: [${newlimit}]"

# edit each file in which memory_limit is found
while read operation
do
  # grep -iR returns in the format "<filename>:<matching line found>"
  filename=$(echo $operation | cut -d':' -f1)
  # old limit is the last space-delimited on the line
  #   '##' = aggressively ltrim; '*' = match all; ' ' = delimiter
  case ${cmd} in
    "show" ) echo "$operation" ;;
    "fix"  )
        oldlimit=${operation##* }
        line=$(echo $operation | cut -d':' -f2)
        assignment=$(echo $line | cut -d' ' -f1,2)
         j_msg -${debug} -p "file: [${filename}]" && echo "line: [${line}]" && echo "oldlimit: [${oldlimit}]"
        # escape ';', '[' and ']' chracters
        oldassignment=$(echo $assignment | sed 's|\;|\\\;|' | sed 's|\[|\\\[|' | sed 's|\]|\\\]|')
        # remove semicolon comment mark to activatte assignment
        newassignment=$(echo $assignment | sed 's|\;||' | sed 's|\[|\\\[|' | sed 's|\]|\\\]|')
        # replace assigned value
        oldline="${oldassignment} ${oldlimit}"
         j_msg -${debug} -p "oldline: [${oldline}]"
        newline="${newassignment} ${newlimit}"
         j_msg -${debug} -p "newline: [${newline}]"
         j_msg -${debug} -p "  prepared, escaoed newline: [${newline}]"
         j_msg -${debug} -p -n "  Confirming new line: " && \
            sed "s|${oldline}|${newline}|" ${filename} | grep memory_limit
        sed -i "s|${oldline}|${newline}|" ${filename}
        ;;
    *      ) usage ;;
  esac
done <<< $(grep -iR memory_limit /etc/php/ 2>/dev/null | grep -v config-archive)
