#!/bin/bash
source /usr/sbin/script_header_joetoo
checkroot

#-----[ !!CAUTION!! ]---------------------------------------------------
# The setting 'allow_local_remote_servers => true' disables a key protection
# against a vulnerability called Server-Side Request Forgery (SSRF).
# This could allow a sophisticated attacker to exploit a weakness in the
# Nextcloud server and then force it to make unauthorized requests to
# internal network resources.
#
# The best practice is to configure the internal DNS to resolve
# public domain names of Nextcloud servers to their local IP addresses.
# This method, often called "DNS hairpinning" or "loopback DNS," prevents
# the insecure local request while still letting servers communicate using
# their trusted public addresses (names)
# ///----- but for some reason that doesn't work -----///

#-----[ variables ]-----------------------------------------------------

PN=$(basename $0)
nextcloud_dir="/var/www/localhost/htdocs/myCloud"
silent=">/dev/null 2>&1"

VERBOSE=$TRUE
# don't set verbosity unless it is not already set (allow calling program to set it)
[ -z $verbosity ] && verbosity=3


separator $(hostname) ${PN}
command_sequence=(
    "sudo -u apache php occ config:system:set allow_local_remote_servers --value true --type bool ${silent}"
)

msg_sequence=(
    'allow local_remote_servers'
)

#-----[ main script ]--------------------------------------------------

old_dir=$(pwd)
message_n "${BYon}Moving to ${BMon}${nextcloud_dir}${Boff}"
cd ${nextcloud_dir} || die "failed to move to ${nextcloud_dir}"
right_status $TRUE
d_message "${BWon}pwd: ${LBon}$(pwd)${Boff}" 3

for ((i=0; i< ${#command_sequence[@]}; i++)) ; do
    message_n "${BWon}running ${BGon}${msg_sequence[$i]}${Boff} ..."
    eval "${command_sequence[$i]}" || die "failed: ${command_sequence[$i]}"
    right_status $TRUE
done
echo
message_n "${BYon}Moving back to ${BMon}${old_dir}${Boff}"
cd ${nextcloud_dir} || die "failed to move to ${nextcloud_dir}"
right_status $TRUE
d_message "${BWon}pwd: ${LBon}$(pwd)${Boff}" 3
message "${BGon}Done${Boff}"
