#!/bin/bash
eval $( grep ^PORTDIR /etc/portage/make.conf )
eval $( grep ^PKGDIR /etc/portage/make.conf )
for y in \
    $(for x in \
        $(grep '>' /home/joe/temp | \
          cut -d'>' -f2 | \
          sed 's/\ //'); \
        do qatom $x; \
     done | awk '{ print $1"/"$2 }'); \
do rm -rv $PKGDIR/${y}*; \
done
