#!/bin/bash
# setnodistpath - modify PATH to eliminate distcc masquerades
#
# NOTE:  must *source* this script to make the export assignment active in calling shell

# fallback: if not already defined by a parent script, define a dummy logger
type debug_echo_msg &>/dev/null || debug_echo_msg() { :; }

_old_path=() _new_path=()

IFS=':' read -r -a _old_path <<<"$PATH"

for x in "${_old_path[@]}"; do
  if [[ "$x" != *"distcc"* && "$x" != *"ccache"* ]]
  then
    _new_path+=("$x")
  else
    debug_echo_msg "dropping old path element --> $x"
  fi
done
debug_echo_msg "new path has ${#_new_path[@]} elements"
debug_echo_msg "new path: ${_new_path[@]}"

export PATH=$(IFS=:; echo "${_new_path[*]}")

for ((i=0; i<${#_new_path[@]}; i++ )); do debug_echo_msg "$i: ${_new_path[i]}"; done
debug_echo_msg "PATH = ${PATH}"
