#!/usr/bin/python3
#
# note: run emerge --info --verbose | grep -i python to see which version of python3 is in use by portage
#   then run eselect python list/set/show to pick that same version
#   then you can invoke this script with ./show-resume-lists
#
import portage
mtimedb = portage.mtimedb

print("----[ resume ]----")
print(portage.mtimedb.get("resume", {}).get("mergelist"))
print("----[ resume_backup ]----")
print(portage.mtimedb.get("resume_backup", {}).get("mergelist"))
