#!/bin/bash
# tarup - (c) joe brendler 2025-2055
# create a tar archive with version-upgraded filename
#
source /usr/sbin/script_header_joetoo

VERBOSE=$TRUE
[ -z $verbosity ] && verbosity=3  # assign default if null; allow calling program to dictate

PN=$(basename $0)

separator ${PN} $(hostname)

user="joe"
archived_tarballs_dir="/home/${user}/archived_tarballs"

#-----[ variables ]--------------------------------------------------

taroptions="-cvjpf"                # options for tar command
to_be_archived_tarball_version=""  # oldest (to-be-archived) version string (to be determined)
latest_tarball_version=""          # latest version string (to be determined)
new_tarball_version=""             # new version string (to be calculated)
output_tarball_filename=""         # filename for the new version's tarball

declare -a tarball_versions        # array of version strings

current_version_numbers=( 0 0 0 )  # array of digits constituting the parts (major minor patch) of current version number
new_version_numbers=()             # array to hold new version's digits, when calculated

#-----[ functions ]--------------------------------------------------
usage() {
    error_msg "${BGon}usage: ${PN} <SOURCE_DIR> [-major|-minor]${Boff}"
    notice_msg "${BYon}Notes:${Boff}"
    notice_msg "${LBon}(1)${Boff} ${BMon}SOURCE_DIR${Boff} must be a directory (containing a package's sources)"
    notice_msg "${LBon}(2)${Boff} only one of the semantic versioning format numbers will be incremented"
    notice_msg "    automatically (major.minor.patch)"
    notice_msg "${LBon}(3)${BWon} upgrade type [-pa|ma|mi] is optional${Boff}"
    notice_msg "  -pa[tch] optionally indicates a patch upgrade (${BWon}default${Boff})"
    notice_msg "  -ma[jor] optionally indicates a major upgrade"
    notice_msg "  -mi[nor] optionally indicates a minor upgrade"
    exit 1
}

load-tarball_versions() {
    # load the tarball_versions array
    # load array of version numbers for tarballs matching the name of SOURCE_DIR
    # use \0 as newline delimter for whitespace-safe handling of filenames
    # subsititutions strip the package name and .tbz2 extension to leave just the version number
    # sort -rV puts them in reverse version order , -z tells sort to use the \0 delimiter
    readarray -d $'\0' tarball_versions < <(
        find ./ -name "${SOURCE_DIR}*.tbz2" -printf '%f\0' |
        sed -z "s|${SOURCE_DIR}-||g" |
        sed -z "s|.tbz2$||g" |
        sort -rVz
    )
    return $?
}

get-current-version() {
    # put the latest version number string into latest_tarball_version variable
    local result=""
    notice_msg "tarball_versions #: ${#tarball_versions[@]}"
    # identify the latest version
    if [ ${#tarball_versions[@]} -eq 0 ] ; then
        # there are no tarballs matching SOURCE_DIR,
        # so current tarball version = 0.0.0 [i.e. none]
        notice_msg "no tarballs matching SOURCE_DIR [${SOURCE_DIR}] found"
        notice_msg " so current tarball version = 0.0.0 [i.e. none]"
    else
        latest_tarball_version="${tarball_versions[0]}"
        notice_msg "current version: [${latest_tarball_version}]"
        # split version into ( major minor patch )
        IFS='.' read -ra current_version_numbers <<< $latest_tarball_version
        result=$?
        # Reset IFS to its default value
        IFS=$' \t\n'
    fi
    notice_msg "  current major: ${current_version_numbers[0]}"
    notice_msg "  current minor: ${current_version_numbers[1]}"
    notice_msg "  current patch: ${current_version_numbers[2]}"
    return $result
}

get-archive-version() {
    # put the oldest (to-be-archived) version number string into to_be_archived_tarball_version variable
    notice_msg "tarball_versions #: ${#tarball_versions[@]}"
    # identify the latest version
    if [ ${#tarball_versions[@]} -eq 0 ] ; then
        # there are no tarballs matching SOURCE_DIR,
        # so archive tarball version = 0.0.0 [i.e. none]
        notice_msg "no tarballs matching SOURCE_DIR [${SOURCE_DIR}] found"
        notice_msg "  (so there is nothing to archive)"
        to_be_archived_tarball_version="none"
    else
        to_be_archived_tarball_version="${tarball_versions[ -1 ]}" || die "failed to assign to_be_archived_tarball_version="
        notice_msg "archive version: [${to_be_archived_tarball_version}]"
    fi
    return 0
}

calculate-new-version() {
    # increment the version number appropriately
    local result=""
    local UPGR="$1"
    case ${UPGR} in
        "major" )
            # increment major number and reset minor patch number to 0
            new_version_numbers[0]="$(( ${current_version_numbers[0]} + 1 ))"
            new_version_numbers[1]="0"
            new_version_numbers[2]="0"
            ;;
        "minor" )
            # increment minor number and reset patch number to 0
            new_version_numbers[0]="${current_version_numbers[0]}"
            new_version_numbers[1]="$(( ${current_version_numbers[1]} + 1 ))"
            new_version_numbers[2]="0"
            ;;
        "patch" )
            # just increment patch number
            new_version_numbers[0]="${current_version_numbers[0]}"
            new_version_numbers[1]="${current_version_numbers[1]}"
            new_version_numbers[2]="$(( ${current_version_numbers[2]} + 1 ))"
            ;;
        * )  error_msg "invalid UPGRADE type [${UPGR}]" && exit ;;
    esac
    notice_msg "  new major: ${new_version_numbers[0]}"
    notice_msg "  new minor: ${new_version_numbers[1]}"
    notice_msg "  new patch: ${new_version_numbers[2]}"
    new_tarball_version="${new_version_numbers[0]}.${new_version_numbers[1]}.${new_version_numbers[2]}"
    result=$?
    notice_msg "new version: ${new_tarball_version}"
    return $result
}

archive-old-version() {
    # move the oldest version to the archived_tarballs_dir
    archive_tarball_filename="${SOURCE_DIR}-${to_be_archived_tarball_version}.tbz2"
    if [[ "${to_be_archived_tarball_version}" == "none" ]] ; then
        notice_msg "no tarball to archive"
    elif [ -f "${archive_tarball_filename}" ] ; then
        response=""
        msg="${BYon}About to run command:\n${Boff}"
        msg+="    ${BGon}mv  ${archive_tarball_filename} ${archived_tarballs_dir%/}/${Boff}\n"
        msg+="    ${BYon}Please confirm ( ${BWon}y|Y[es]: yes; s|S[kip]: skip; n|N[o]: No (abort program)${Boff} )"
        new_prompt "${msg}"
        case ${response:0:1} in
            [yY] )
                 mv "${archive_tarball_filename}" "${archived_tarballs_dir%/}/" || die "failed to archive old tarball" ;;
            [sS] ) notice_msg "${BMon}Skipping archive as instructed${Boff}" ;;
            [nN] ) error_msg "Aborting as instructed" ; return 1;;
            *    ) error_msg "Invalid response [$response]" ; return 1;;
        esac
    else
        error_msg "Error: tarball [${archive_tarball_filename}] not found"
        return 1
    fi
    return 0
}

create-new-tarball() {
    output_tarball_filename="${SOURCE_DIR}-${new_tarball_version}.tbz2"

    msg="${BYon}About to run command:\n${Boff}"
    msg+="    ${BGon}tar ${taroptions} ${output_tarball_filename} ${SOURCE_DIR}${Boff}"
    notice_msg "${msg}"
    confirm_continue_or_exit
    tar "${taroptions}" "${output_tarball_filename}" "${SOURCE_DIR}"
    return $?
}

#-----[ main script ]------------------------------------------------
checknotroot

[ $# -eq 0 ] && error_msg "SOURCE_DIR not specified" && usage
[ $# -gt 2 ] && error_msg "invalid arguments" && usage
[ ! -d "$1" ] && error_msg "SOURCE_DIR: [$1] does not exist" && usage || SOURCE_DIR="$1"

if [ $# -eq 2 ] ; then
    [[ "${2:0:1}" != "-" ]] && error_msg "prefix option with \"-|\"" && usage
    case ${2:1:2} in
        "ma" ) UPGRADE="major"; notice_msg "initiating major upgrade ..." ;;
        "mi" ) UPGRADE="minor"; notice_msg "initiating minor upgrade ..." ;;
        "pa" ) UPGRADE="patch"; notice_msg "initiating patch upgrade ..." ;;
        *    ) error_msg "invalid option: [$2]"; usage ;;
    esac
else
    UPGRADE="patch"; notice_msg "initiating patch upgrade (as default) ..."
fi

load-tarball_versions || die "failed to load-tarball_versions"
get-current-version || die "failed to get-current-version"
get-archive-version || die "failed to get-archive-version"

archive-old-version || die "failed to archive-old-version"

calculate-new-version "${UPGRADE}" || die "failed to calculate-new-version ${UPGRADE}"

create-new-tarball || die "failed to create-new-tarball"

notice_msg "${BGon}Done${Boff}"
