#!/bin/sh
#
cpufreq=()
c_temp=()
f_temp=()

printf '%s\n' "temp data:"
i=0
for x in /sys/class/thermal/thermal_zone*
do
  c_temp[$i]=$(printf '%s\n' "scale=2; $(cat $x/temp)/1000" | bc)
  f_temp[$i]=$(printf '%s\n' "scale=2; (9/5) * ${c_temp[$i]} + 32" | bc)
  printf '%s\n' "  thermal_zone $i: ${c_temp[$i]} C; ${f_temp[$i]} F"
  let "i++"
done
printf '\n%s\n' "freq data:"
f_max=$( printf '%s\n' "scale=2; $(lscpu | grep -i 'max' | awk '{print $4}')/1000" | bc)
printf '%s\n' "  f_max: $f_max MHz"
f_min=$( printf '%s\n' "scale=2; $(lscpu | grep -i 'min' | awk '{print $4}')/1000" | bc)
printf '%s\n\n' "  f_min: $f_min MHz"
i=0
while read line
do
  cpufreq[$i]=$( printf '%s\n' "scale=2; $(printf '%s' "$line" | awk '{print $4}') / 1000" | bc)
  printf '%s\n' "  cpu $i: ${cpufreq[$i]} MHz"
  let "i++"
done <<< $(cat /proc/cpuinfo | grep -i mhz)
