#!/bin/bash
source /usr/sbin/script_header_joetoo

PN=${0##*/}

#BUILD=0.0
if [ -f /etc/joetoolkig/BUILD ]; then . /etc/joetoolkig/BUILD; else BUILD="0.0.1"; fi

separator "${PN}-${BUILD}"
checkroot
if [[ ! $1 == "go" ]]; then
  j_msg -${err} "Error: provide a \"dependency confilict\" list in /home/joe/temp. Then run w argument \"go\""
  exit 1
fi

blockerlist=()
blockerlist2=()

cmd='emerge -avC '
# eliminate instances of " and (-)
j_msg -${notice} -p -n "clearing out \" characters"
sed -i 's/\"//g' /home/joe/temp; right_status $? ${notice}
j_msg -${notice} -p -n "clearing out instances of \"(-)\""
sed -i 's/(-)//g' /home/joe/temp; right_status $? ${notice}
j_msg -${notice} -p -n "clearing out instances of \"(+)\""
sed -i 's/(+)//g' /home/joe/temp; right_status $? ${notice}

blockerlist=($(cat /home/joe/temp | grep installed | cut -d'(' -f2 | cut -d':' -f1))
j_msg -${notice} -p "atoms in blockerlist: ${#blockerlist[@]}"

j_msg -${notice} -p -n "clearing out redundant and invalid atoms"
for x in "${blockerlist[@]}"; do
  blockerlist2+=($(qatom \
    $(qatom "$x" | awk '{ print  $1"/"$2 }') \
    | awk '{ print  $1"/"$2 }'))
done
j_msg -${debug} -p "'\${#blockerlist2[@]}': ${#blockerlist2[@]}"
j_msg -${debug} -p  "blockerlist2: [\n${blockerlist2[@]}\n]"

count=0
# output the list of blockers
for z in $(for x in "${blockerlist2[@]}"; do printf '%s\n' "$x"; done | sort -u | grep -v "unset")
do
  cmd+=" $z"
  let count++
done
j_msg -${notice} -p -n "unique blockers: ${count}\n"
separator "clear blocker command follows"
j_msg -${notice} -mp "${cmd}"
#sh_countdown 3
## todo - interactive prompt to run the command
#eval ${cmd}
