#!/bin/bash
# ckinitramfs
# joe brendler, 17 May 2018
# check to see if initramfs should be rebuilt
#  (i.e. if normally included components have changed since last build)

source /usr/local/sbin/script_header_brendlefly

checkroot

SOURCES_DIR="/usr/src/initramfs"
MAKE_DIR="/usr/src/mkinitramfs"

# set ckinitramfs BUILD; not the kernel's BUILD used by mkinitramfs for init
BUILD="$(cat ${MAKE_DIR%/}/PKG_PVR)"

# source the list of executables used by the init script (from init_structure)
executables=()
message_n "sourcing ${MAKE_DIR%/}/init_structure ..."
source ${MAKE_DIR%/}/init_structure; right_status $?
# source header for load_ list_ dump_executables
message_n "sourcing ${MAKE_DIR%/}/common_bash_functions_header ..."
source ${MAKE_DIR%/}/common_bash_functions_header; right_status $?

# source header for display_config, echo_long_string
message_n "sourcing ${MAKE_DIR%/}/common_ash_functions_header ..."
source ${MAKE_DIR%/}/common_ash_functions_header; right_status $?
load_executables

# initialize VERBOSE and verbosity by sourcing mkinitramfs.conf
if [[ -e ${MAKE_DIR%/}/mkinitramfs.conf ]] ; then
  config_file=${MAKE_DIR%/}/mkinitramfs.conf
elif [[ -e /etc/mkinitramfs/mkinitramfs.conf ]] ; then
  config_file="/etc/mkinitramfs/mkinitramfs.conf"
else
  E_message "${BRon}Error: no mkinitramfs.conf found"
  exit
fi
message_n "sourcing config file ${config_file} ..."
source ${config_file}; right_status $?

init_config_title="configuration"
varlist="SOURCES_DIR MAKE_DIR VERBOSE verbosity init_executables"
display_config $varlist

# compare current system executables (identified by the whioch command) with those installed in intramfs
for x in ${executables[@]}
do
  y=$(find ${SOURCES_DIR%/} -name $(basename $x))
  message_n "Component: ${LBon}$(basename $x)"
  if [[ $(diff $y $x >/dev/null 2>/dev/null) ]]
  then
    echo -e "${BRon} has changed${Boff} --> ${BMon}Rebuild your initramfs${Boff}"
  else
    echo -e "${BGon} has not changed${Boff}"
  fi
done

