#!/bin/bash
# ckinitramfs
# joe brendler, 17 May 2018
# check to see if initramfs should be rebuilt
#  (i.e. if normally included components have changed since last build)

source /usr/local/sbin/script_header_brendlefly
BUILD="0.0.1a"

source /usr/src/mkinitramfs/dyn_executables_header
executables=(${bin_dyn_executables} ${sbin_dyn_executables} ${usr_bin_dyn_executables} ${sbin_non_dyn_executables})

separator "ckinitramfs-${BUILD}"
checkroot

for x in ${executables[@]}
do
  y=$(which $x)
  message_n "Component: ${LBon}${x}"
  if [[ $(diff /usr/src/initramfs$y $y) ]]
  then
    echo -e "${BRon} has changed${Boff} --> ${BMon}Rebuild your initramfs${Boff}"
  else
    echo -e "${BGon} has not changed${Boff}"
  fi
done

