#!/bin/bash
# ckinitramfs
# joe brendler, 17 May 2018
# check to see if initramfs should be rebuilt
#  (i.e. if normally included components have changed since last build)

source /usr/local/sbin/script_header_brendlefly
BUILD="0.0.2"

checkroot

SOURCES_DIR="/usr/src/initramfs"
MAKE_DIR="/usr/src/mkinitramfs"

#source the list of executables used by the init script, using the
#  which command to locate each on the host system
executables=()
source ${MAKE_DIR}/init_structure
source ${MAKE_DIR}/common_functions_header
load_executables
init_config_title="ckinitramfs"
varlist="SOURCES_DIR MAKE_DIR VERBOSE verbosity executables"
display_config $varlist

# compare current system executables (identified by the whioch command) with those installed in intramfs
for x in ${executables[@]}
do
  y=$(find ${SOURCES_DIR} -name $(basename $x))
  message_n "Component: ${LBon}$(basename $x)"
  if [[ $(diff $y $x >/dev/null 2>/dev/null) ]]
  then
    echo -e "${BRon} has changed${Boff} --> ${BMon}Rebuild your initramfs${Boff}"
  else
    echo -e "${BGon} has not changed${Boff}"
  fi
done

