#!/bin/bash
#
# finalize-chroot joe brendler 17 April 2025
#
# should be run automatically by /root/.bashrc if file /root/firstlogin exists

# if all goes well, remove the firstlogin file
source /usr/local/sbin/script_header_brendlefly
COMPLETE=$TRUE  # (tentatively; any step below can change this)
result=0

# determine what chroot crossbuild environment (target) I'm running inisde of
TARGET=$(portageq envvar CHOST)

[ ! -e /root/firstlogin ] && exit

# Create the chroot's portage temporary directory with ln;
message_n "creating portage temporary directory with ln ..."
if [ ! -L /usr/${TARGET}/tmp ] ; then
    ln -s /tmp /usr/${TARGET}/tmp
    result=$?
    [ $result -ne 0 ] && COMPLETE=$FALSE
fi
right_status $result

# carefully validate or create a link to the chroot's /var for portage PKGDIR and DISTDIR directories
message_n "checking for /usr/${TARGET}/var ..."
check_target=/usr/${TARGET}/var
check_status=$(file ${check_target} | sed "s|${check_target}: ||")
case $(echo $check_status | awk '{print $1}') in
    "cannot"    )
        # it does not exist (create link)
        echo -en " (ok: not found) linking ..."
        ln -s /var /usr/${TARGET}/var
        result=$?
        [ $result -ne 0 ] && COMPLETE=$FALSE
        ;;
    "directory" )
        # it exists and is a directory (undesireable - move and link)
        echo -en " (directory) moving/linking ..."
        # move it; then link it
        cp -a ${check_target}/* /var/ && \
        rm -r ${check_target} && \
        ln -s /var ${check_target}
        result=$?
        [ $result -ne 0 ] && COMPLETE=$FALSE
        ;;
    "symbolic"  )
        # it exists (validate link)
        echo -en " (link found)"
        if [[ "${check_status}" == "symbolic link to /var" ]] ; then
            # valid
            echo -en " (valid)"
            result=$TRUE
        else
            echo -en " (invalid)"
            result=1
        fi

    #    ln -s /var /usr/${TARGET}/var
        result=$?
        [ $result -ne 0 ] && COMPLETE=$FALSE
        ;;
    * )
        E_message "invalid chroot layout: ${check_target} is [${check_status}]"
        E_message "fix layout; conisder running crossdev -C -t ${TARGET}"
        E_message "and/or rebuild with mkcrossbuildenv from dev-sbc/crossbuild-tools::joetoo"
        ;;
esac
right_status $result


# /etc/locale.gen and /etc/env.d/02locale were updated by populate-target script
message "running locale-gen ..."
locale-gen ; result=$?
[ $result -ne 0 ] && COMPLETE=$FALSE
right_status $result

# check/reload config
message "checking/reloading config ..."
gcc-config -l && \
ldconfig -v && \
ROOT=/ env-update && \
source /etc/profile ; result=$?
[ $result -ne 0 ] && COMPLETE=$FALSE
right_status $result

message_n "removing /root/firstlogin ..."
rm /root/firstlogin ; result=$?
[ $result -ne 0 ] && COMPLETE=$FALSE
right_status $result

[[ $COMPLETE ]] && \
message "chroot firstlogin configuration complete" || \
E_message "chroot firstlogin configuration failed"
echo
