#!/bin/bash
[[ ! -e /usr/local/share/ca-certificates ]] && mkdir -p /usr/local/share/ca-certificates/
cp -av /usr/local/sbin/server_certs/*.crt /usr/local/share/ca-certificates/
update-ca-certificates
