#!/bin/bash
# nubaldurbackup_mount
# joe brendler - 17 Feb 2021

source /usr/sbin/script_header_joetoo
BUILD=0.0

#---[ variables ]-----------------------------------------------------------


#---[ functions ]-----------------------------------------------------------

useage() {
  E_message "Useage: nubaldurbackup [TBD]" && exit
}

#---[ main script ]---------------------------------------------------------
checkroot
separator "nubaldurbackup-${BUILD}"

message_n "mounting LVs on /mnt/nubaldurbackupROOT..."
mount /dev/mapper/vg_nubaldurbackup-nubaldurbackupROOT /mnt/nubaldurbackupROOT && \
mount /dev/mapper/vg_nubaldurbackup-nubaldurbackupUSR /mnt/nubaldurbackupROOT/usr/ && \
mount /dev/mapper/vg_nubaldurbackup-home  /mnt/nubaldurbackupROOT/home && \
mount /dev/mapper/vg_nubaldurbackup-var   /mnt/nubaldurbackupROOT/var && \
mount /dev/mapper/vg_nubaldurbackup-opt   /mnt/nubaldurbackupROOT/opt && \
mount /dev/mapper/vg_nubaldurbackup-srv   /mnt/nubaldurbackupROOT/srv && \
mount /dev/mapper/vg_nubaldurbackup-tmp   /mnt/nubaldurbackupROOT/tmp && \
right_status $?; echo

message "mounted LVs on /mnt/nubaldurbackupROOT as shown below:"
mount | grep nubaldurbackupROOT
