#!/bin/bash
# nuoromisbackup_umount
# joe brendler - 17 Feb 2021

source /usr/sbin/script_header_joetoo
BUILD=0.0

#---[ main script ]---------------------------------------------------------
checkroot
separator "nuoromisbackup_umount-${BUILD}"
echo; message_n "unmounting ..."
#umount /mnt/nuoromisbackupROOT{/opt,/var,/home/,/usr,/tmp,}
cd / && umount -R /mnt/nuoromisbackupROOT
right_status $?; echo

echo; message "un-mounted nuoromisbackup"
mount | grep nuoromisbackupROOT
