#!/bin/bash
yes | for x in /dev/mapper/vg_ssda-*; do mkfs.ext4 $x; done
mkswap /dev/mapper/vg_ssda-swap
nuoromisbackup_mount
for x in home opt usr var srv tmp; do mkdir -p /mnt/nuoromisbackupROOT/$x; done
nuoromisbackup_umount
