#!/bin/bash
# oromisbackup_mount
# joe brendler - 19 May 2019

source /usr/sbin/script_header_joetoo
BUILD=0

#---[ variables ]-----------------------------------------------------------


#---[ functions ]-----------------------------------------------------------

useage() {
  E_message "Useage: oromisbackup [TBD]" && exit
}

#---[ main script ]---------------------------------------------------------
checkroot
separator "oromisbackup${BUILD}"

message_n "mounting LVs on /mnt/oromisbackupROOT..."
mount /dev/mapper/vg_oromisbackup-ROOT /mnt/oromisbackupROOT && \
mount /dev/mapper/vg_oromisbackup-USR /mnt/oromisbackupROOT/usr/ && \
mount /dev/mapper/vg_oromisbackup-home  /mnt/oromisbackupROOT/home && \
mount /dev/mapper/vg_oromisbackup-var   /mnt/oromisbackupROOT/var && \
mount /dev/mapper/vg_oromisbackup-tmp   /mnt/oromisbackupROOT/tmp && \
mount /dev/mapper/vg_oromisbackup-opt   /mnt/oromisbackupROOT/opt && \
mount /dev/mapper/vg_oromisbackup-srv   /mnt/oromisbackupROOT/srv
right_status $?; echo

message "mounted LVs on /mnt/oromisbackupROOT as shown below:"
mount | grep oromisbackupROOT
