#!/bin/bash
# tahawusbackup_umount
# joe brendler - 17 Feb 2021

source /usr/sbin/script_header_joetoo
BUILD=0.0

#---[ main script ]---------------------------------------------------------
checkroot
separator "tahawusbackup_umount-${BUILD}"

echo; message_n "unmounting ..."
umount /mnt/tahawusbackupROOT{/opt,/var,/home/,/usr,/tmp,}
right_status $?; echo

echo; message "un-mounted tahawusbackup"
mount | grep tahawusbackupROOT
