#!/bin/bash
# oromisbackup - backup everything on my router/firewall/vpnserver
# joe brendler - 19 May 2019

source /usr/sbin/script_header_joetoo
BUILD=0

#---[ variables ]-----------------------------------------------------------


#---[ functions ]-----------------------------------------------------------

useage() {
  E_message "Useage: thuviabackup [TBD]" && exit
}

#---[ main script ]---------------------------------------------------------
checkroot
separator "thuviabackup${BUILD}"

echo; message_n "unmounting ..."
umount /mnt/thuviabackupROOT{/opt,/var,/home/,/usr,}
right_status $?; echo

echo; message "un-mounted thuviabackup"
mount | grep thuviabackupROOT
