#[yorsqui]
#priority = 9999
#sync-uri = https://yorsqui.brendler/packages/x86_64-pc-linux-gnu-skylake-packages

[q552u01]
priority = 9999
sync-uri = https://q552u01.brendler/packages/x86_64-pc-linux-gnu-skylake-packages

