#!/bin/bash
source /usr/local/sbin/script_header_brendlefly
#useFile="$1"
[ $# -eq 1 ] && useFile="$1" || E_message "specify the use file to be sorted"
[ ! -f "$useFile" ] && E_message "Error argument [$1] is not a file" && exit 1

sortline()
{
  local pkg="$1";
  shift;
  local instr="$@";
  local outstr="$pkg $( echo $(for x in $instr; do echo $x; done | sort))";
  echo "$outstr";
}

#-----[ main script ]--------------------------------------------------------------
while read Line; do sortline $Line; done < $useFile | sort | strip_blanklines_and_comments.sh
