#!/bin/bash
# /root/bin/loggit
# Joe Brendler 1 Mar 2009
#
# Borrowed from John Brendler's Rev. 20 July 2007

# Standard code snippet to include at the bottom of cron scripts.
# The $? variable expands to the exit status of the previous command.
# To include, use ". /root/bin/loggit" or "source /root/bin/loggit

EXIT_STATUS=$?

case $EXIT_STATUS in
        0) PRIORITY="notice" && MESSAGE="succeeded.";;
        *) PRIORITY="err" && MESSAGE="failed with exit status ${EXIT_STATUS}";;
esac

/usr/bin/logger -p cron.$PRIORITY "$0 $MESSAGE"

