#!/usr/bin/python3.9
import portage;
print("----[ resume ]----")
print(portage.mtimedb.get("resume", {}).get("mergelist"))
print("----[ resume_backup ]----")
print(portage.mtimedb.get("resume_backup", {}).get("mergelist"))
