#!/bin/bash
#[[ $# -gt 0 ]] && \
#    MAKEOPTS="-j1" FEATURES=" -getbinpkg -userpriv -distcc -distcc-pump" emerge -av1 \
#         $(echo "$@" | grep '(' | cut -d'(' -f2 | cut -d':' -f1 | \
#         xargs qatom -F %{CATEGORY}/%{PN} $(qatom -F %{CATEGORY}/%{PN}) \
#          )  --keep-going || \
#    echo "Error: provide a quoted \"failed to build\" list"

filter() {
    echo $(while read LINE
      do
         result=$( echo "${LINE}" | grep '(' | cut -d'(' -f2 | cut -d':' -f1 )
         [[ ! -z ${result} ]] && qatom -F %{CATEGORY}/%{PN} $(qatom -F %{CATEGORY}/%{PN} ${result})
      done  < /home/joe/temp )
}

merge() {
  MAKEOPTS="-j1" FEATURES=" -sandbox -usersandbox -getbinpkg -userpriv -distcc -distcc-pump" emerge -av1 --keep-going $(filter)

}

[[ "$1" == "go" ]] && merge || echo "Error: place \"failed to build\" list in /home/joe/temp and run\nx_arg_nobinmergelist go"

