#!/bin/bash

#
source /usr/sbin/script_header_joetoo

msg="${BYon}$bin_hammer Running${_cmd_color} parallel ${_data_color}-j4${BWon} sudo "
msg+="QUIET${_op_color}=${BRon}\$TRUE ${_op_color}./${_func_color}assemble-make-conf"
msg+="${Boff} for all joetoo-supported platforms and configs${Boff}"
tw=$(termwidth)
j_msg -${notice} -mp ""  # serverity-aware newline
box_msg "$msg" $(( tw - ( tw / 4 ) ))
j_msg -${notice} -mp ""  # serverity-aware newline
j_msg -${notice} -p "${Con}this may take a minute or so; $(emoji_safe $uT_watch) please wait ...${Boff}"
j_msg -${notice} -mp ""  # serverity-aware newline

old_v=$verbosity
export QUIET=$TRUE
export verbosity=0

# generate all new make.conf files
for ENV in crossbuild chroot; do
    for SYSTEM in headless desktop; do
        config="assemble-make-conf.${SYSTEM}.${ENV}.conf"
        for board in $(joetoo-sbc-list | awk '{print $1}'); do
            echo "board: $board config: $config (E: $ENV S: $SYSTEM)" ;
            # needs to be run by root b/c we assemble ${DRAFT_FILE} in ${DRAFT_DIR} = /tmp/...
#            sudo ./assemble-make-conf $board $config;
            sudo QUIET=$TRUE ./assemble-make-conf $board $config;
        done # board
    done # SYSTEM
done # ENV

export QUIET=$FALSE
export verbosity=$old_v
