#!/bin/sh

# to tar-up the utility_archive.tbz2 --
# from /home/joe/myUtilities/dev-util/joetoolkit ...
rm utility_archive.tbz2   # remove the old copy first
tar -cvjpf utility_archive.tbz2 utility_archive
rm -r utility_archive     # then remove the directory


# to UN-tar the utility_archive.tbz2 tarball ...
tar -xvjpf utility_archive.tbz2 -C ./
