#!/bin/ash

### -----[ duplicated functions ]--------------------------------------------------------------
### These scripts exist in both "validated_" and "testing_" headers but have been modified in each
### In the live init script, source the "testing_" header first and "validated_" header second
### In the testing script, source "validated_" header first and the "testing_" header second
### The later-sourced will override, and this avoid having the "testing" script mess with
###    non-testing luks devices on a testing host system
assign_volume() {
    ret=0
    # given string volume name (root_ usr_volume), scan lvs and make volume pathname assignment
    _av_volume_name=$1
#    _av_prefix="${_av_volume_name/_volume}"     # e.g. assign root, from root_volume (bash substitution)
    _av_prefix="${_av_volume_name%_volume}"     # e.g. assign root, from root_volume (POSIX strip from end)
    eval "_av_volume=\"\$${_av_volume_name}\""
    if [ -z "${_av_volume}" ] ; then
#        d_message "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep ${_av_prefix} | awk '{print $2"-"$1}')" 3
#        d_message_n "${_av_prefix} _av_volume_name not assigned, scanning ..." 1
#        _av_volume="/dev/mapper/$(lvs | grep ${_av_prefix} | awk '{print $2"-"$1}')"
# substitute for testing only -
        d_message "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep -v 'gmki91' | grep ${_av_prefix} | awk '{print $2"-"$1}')" 3
        d_message_n "${_av_prefix} _av_volume_name not assigned, scanning ..." 1
        _av_volume="/dev/mapper/$(lvs | grep -v 'gmki91' | grep $_av_prefix | awk '{print $2"-"$1}')"
        eval "${_av_prefix}_volume=$_av_volume"
        ret=$?
        d_handle_result $ret 1
        d_message "_av_volume: [$_av_volume]" 3
    else
        message "No action. ${_av_prefix} volume already assigned [$_av_volume]"
    fi
    unset -v _av_prefix _av_volume_name _av_volume
    return $ret
}

unlock_devices() {
    ret=0
    # for version 4.x and beyond, this is a complete re-write of the unlocking procedure.
    # The unlock method has already been determined, and the script will now "scan" for LUKS
    # devices and automatically use the selected method (key vs prompt) to unlock all of them
    _ud_method=$1;
    _ud_device="";

    # securely read the passphrase with POSIX ask_pass function if needed
    if [ "$_ud_method" = "prompt" ]; then _ud_pass=$(ask_pass "Enter LUKS passphrase: "); fi

### substitute for testing only
    for _ud_device in $(blkid | grep -i luks | grep -v 'UUID="ef4195f0-6c4a-4116-86dd-fc469ddb6e21"' |cut -d':' -f1 )
###    for _ud_device in $(blkid | grep -i luks | cut -d':' -f1)
    do
        # use get_luks_edev_name in script_header_joetoo to id each _ud_device /dev/sdxn with corresponding name edxn
        get_luks_edev_name "$_ud_device"
        case "$_ud_method" in
            "prompt")
                # this is no longer a f-ing "indented" heredoc '-' tells it to ignore leading TABs (not spaces)
                # so the next two lines MUS begin with tabs
                message "About to run cryptsetup luksOpen ${_ud_device} ${edev} with passphrase provided ..."
#               cryptsetup luksOpen "${_ud_device}" "${edev}" <<-EOF
cryptsetup luksOpen "${_ud_device}" "${edev}" <<EOF
$_ud_pass
EOF
                _ud_result=$?
                handle_result "$_ud_result" "Unlocked ${_ud_device} ${edev} with passphrase provided" "mycmd failed. Dropping to a shell ..."
                if [ ! "$_ud_result" -eq 0 ]; then
                    ret=1
                    d_do sh_countdown $(( $init_wait * 5 )) 4
                    [ ! "${init_lock_down}" ] && rescue_shell
                fi;
                ;;
            "key")
                # passdevice already mounted,
                # Use cryptsetup option for key file -d <mount_point><keyfile> and -S <key slot #>
                # unmount the passdevice when we are done with it
                _ud_keyfile="${init_passdevice_mount_point%/}/${init_keyfile}"
                message "About to execute command [ cryptsetup -d ${_ud_keyfile} -S 1 luksOpen ${_ud_device} ${edev} ]"
                cryptsetup -d $(echo "${_ud_keyfile}") -S 1 luksOpen "${_ud_device}" "${edev}"
                _ud_result=$?
                handle_result "$_ud_result"
                if [ "$_ud_result" -eq 0 ]; then
                    message "Unlocked ${_ud_device} ${edev} with key found at $(echo ${init_passdevice_mount_point}${init_keyfile})"
                else  # cryptsetup luksOpen with key failed
                    ret=1
                    _ud_msg="${BRon}Error: Could not unlock ${BYon}${_ud_device} ${edev}"
                    _ud_msg="${_ud_msg} ${BRon}with key found at ${BMon}${_ud_keyfile}${Boff}"
                    E_message "${_ud_msg}"
                    if [ ! "${init_lock_down}" ]; then
                        E_message "${BRon}Dropping to a shell${Boff}"
                        sh_countdown $(( $init_wait * 5 ))
                        rescue_shell
                    fi
                fi
                ;;
        esac
    done
    unset -v _ud_method _ud_device _ud_pass _ud_keyfile
    return $ret
}


### ----[ end duplicated functions ]--------------------------------------------------------------------------------------------------------------

test() {
        verbosity=2
        d_echo "testing d_echo" 2
        d_echo "testing d_echo" 3
        message "should have printed only ${BGon}one${Boff} \"testing d_echo\" line"
}

teststringlength() {
    str="$1"
    echo "str: ${str}"
    echo -n "1: "; [ ! -z $str ] && echo "non-zero" || echo "zero"
    echo -n "2: "; [ ${#str} -gt 0 ] && echo "-gt zero" || echo "zero"
    echo -n "3: "; [[ ! -z $str ]] && echo "non-zero" || echo "zero"
    echo -n "4: "; [[ ${#str} -gt 0 ]] && echo "-gt zero" || echo "zero"
    echo -n "5: "; [[ ${#str} -ne 0 ]] && echo "-ne zero" || echo "zero"
    echo -n "6: "; [[ ${#str} -eq 0 ]]  && echo "-eq zero" || echo "not -eq zero"
    echo -n "7: "; [[ ! ${#str} -eq 0 ]]  && echo "not -eq zero" || echo "-eq zero"
    echo -n "8: "; [[ -n ${str} ]]  && echo "-n zero" || echo "zero"
}

