#!/bin/bash
source /usr/local/sbin/script_header_brendlefly
for x in $@
do
    separator "$x" "checking logical tests in"
#    message_n "[^[ ]: "; grep -n '^\[ ' $x  | ./strip_d_lines.sh; echo
#    message_n "[ [ ]: "; grep -n ' \[ ' $x  | ./strip_d_lines.sh; echo
#    message_n "[ ] ]: "; grep -n ' \] ' $x  | ./strip_d_lines.sh; echo
#    message_n "[ ]$]: "; grep -n ' \]$' $x  | ./strip_d_lines.sh; echo
    message "[^[ ]: "; grep -n '^\[ ' $x
    message "[ [ ]: "; grep -n ' \[ ' $x
    message "[ ] ]: "; grep -n ' \] ' $x
    message "[ ]$]: "; grep -n ' \]$' $x
done
