#!/bin/sh
# /etc/openvpn/openvpnkeys_2024/joetoo-up.sh
# dual-stack DNS integration for joetoo architecture

echo "(debug) running brendler-up.sh" > /tmp/brendler-up_debug.log
_log_prefix="[vpn-dns-up]"

# initialize (ju_-localized) variables for exit status and data
ju_status=0
_ju_ns=""
_ju_domain=""
_ju_search=""

# iterate through foreign options pushed by openvpn server (Elrond)
# this is a copy/paste of gnu up.sh extended locally for dual-stack
#  ipv4/ipv6 support
_i=1
while true; do
    eval _opt=\$foreign_option_${_i}
    [ -z "${_opt}" ] && break

    case "${_opt}" in
        *DOMAIN*)
            # gnu standard up.sh author roy marples (uberlord) uses this parameter expansion
            # strip the shortest match for "dhcp-option DOMAIN *" from the left -
            # leaving _val as one or more domain names
            _val="${_opt#dhcp-option DOMAIN *}"
            if [ -z "${_ju_domain}" ]; then
                _ju_domain="${_val}"
            else
            # gnu standard up.sh author roy marples (uberlord) uses this parameter expansion
            # append a space if and only if _ju_search is not null, then append _val
                _ju_search="${_ju_search}${_ju_search:+ }${_val}"
            fi
            ;;
        *DNS*)
            # this catch-all handles both 'DNS' and 'DNS6' tags
            # gnu standard up.sh author roy marples (uberlord) uses this parameter expansion
            # strip the shortest match for "dhcp-option DNS* *" from the left -
            # ( i.e. matching either DNS or DNS6) - leaving _val as one or more DNS identities
            _val="${_opt#dhcp-option DNS* *}"
            # append a full nameserver line to _ju_ns
            _ju_ns="${_ju_ns}nameserver ${_val}\n"
            ;;
    esac
    _i=$((_i + 1))
done

# prepare the DNS payload for resolvconf - add eithr the search or the domain but not both
# (like the gnu standard up.sh script)
if [ -n "${_ju_ns}" ]; then
    _dns_payload="# Generated by brendler-up for ${dev}\n"
    if [ -n "${_ju_search}" ]; then
        _dns_payload="${_dns_payload}search ${_ju_domain} ${_ju_search}\n"
    elif [ -n "${_ju_domain}" ]; then
        _dns_payload="${_dns_payload}domain ${_ju_domain}\n"
    fi
    _dns_payload="${_dns_payload}${_ju_ns}"
echo "(debug) _dns_payload: $_dns_payload" > /tmp/brendler-up_debug.log

    # submit to openresolv - printf pipes the payload to openresolv on stdin;
    #   -a means "add" to database for "$dev" (which openvpn sets to tun0)
    #   (after which openresolv re-merges this with info from other interfaces
    #    and resolf.conf.head / tail, to write the actual resolv.conf located
    #    by link /etc/resolv.conf --> /run/resolvconf/resolv.conf )
    #   (like the standard gnu up.sh script, the fallback path creates a ".sv"
    #    saved copy of the old /etc/resolv.conf, but that still allows whichever
    #    interface brought an update most recently to over-writet others in a
    #    three+ interface situation; so use of the net-dns/openresolv package
    #    and the the pipeline submission method is cleaner/safer and reversible
    #    in brendler-up/down.sh)
    if [ -x /sbin/resolvconf ]; then
        # PREFERRED path - (if net-dns/openresolv is installed, providing /sbin/resolvconf)
        # use pipeline submission to openresolv manager; calculate metric to ensure VPN DNS
        # outranks physical interface DNS; use a default low metric (high priority)
        # of 10 for VPN tunnels.
        _ju_metric=10
        printf "${_dns_payload}" | /sbin/resolvconf -a "${dev}" -m "${_ju_metric}"
        ju_status=$?
    else
        # FALLBACK path - (if net-dns/openresolv is not installed, i.e. no /sbin/resolvconf)
        # use "destructive" direct-write for nodes without a DNS manager;
        # save a tagged backup of the current resolv.conf so brendler-down.sh
        # can restore the system state upon tunnel closure
        if [ -e /etc/resolv.conf ]; then
            cp /etc/resolv.conf /etc/resolv.conf."${dev}".sv
        fi
        printf "${_dns_payload}" > /etc/resolv.conf
        chmod 644 /etc/resolv.conf
        ju_status=$?
    fi
fi

# Clean up localized variables
unset -v _ju_ns _ju_domain _ju_search _i _opt _val _dns_payload _ju_metric _log_prefix

exit ${ju_status}
