#!/bin/sh
#-----[ Test procedure ]--------------------------------------------------------------------------------
#
#  Strategy: FIRST - build a source tree
#    + creating a source tree also tests make_sources.sh
#    + basic init script testing can be done in that source tree (initramfs/) directory, with init.test rather than init
#    + a test version of make_sources.sh can create the test source tree (initramfs/) inside scratch/
#    + a test version of make_image.sh can create a test initramfs image file inside scratch/
#    + full initramfs can be tested with qemu
#
#  To build a source tree in /home/joe/myUtilities/dev-util/mkinitramfs/scratch (and test make_sources.sh) --
#    + copy GLOBALS to scratch/GLOBALS.scratch_test and change these assignments as follows --
#      SOURCES_DIR="/home/joe/myUtilities/dev-util/mkinitramfs/scratch/initramfs"
#      MAKE_DIR="/home/joe/myUtilities/dev-util/mkinitramfs"
#    + copy make_sources.sh to scratch/make_sources.sh.test and change the source GLOBALS line as follows --
#      ' source GLOBALS.scratch_test '
#    * NOTE: ' *** make_sources.sh.test must be run *** from the dir where GLOBALS.scratch_test resides *** '
#        and ' GLOBALS.scratch_test must assign absolute paths ' (or relative to that location)
#    + from scratch/ run ./make_sources.sh.test
#
#  To test the init script ability to unlock a root_fs --
#    + copy /home/joe/myUtilities/dev-util/mkinitramfs/init ... mkinitramfs/scratch/init.test
#    + reverse its sourcing order of testing_functions_header and validated_functions_header
#      (so testing functions override validated functions for testing purposes)
#    + change cmdline= assignment to testing version
#    + comment/uncomment to change mount_newroot...() line to mount_and_test_newroot()
#    + comment out lines unique to an initramfs environment, to test just unlock/ and prep to switch root
#      -mini_udev()
#      -switch_root
#    + comment/uncomment to ensure testing_functions_header has --
#       unlock_devices() set to grep for a correct test UUID, and
#       assign_volume() set to grep for a correct vg name rather than _av_prefix
#    * NOTE: ' v10.0+ changed from deselecting gmki91 to SELECTING a specific test device
#            ' UUID="b3c2b95f-1477-4433-b653-310e03dbffc2", vg_ incl: "rock5bplus6401" '
#    + change init_ROOT= to the testing assignment
#    + copy the finalized init.test from scratch/ to scratch/initramfs/
#    + start an ash shell as root ' # ash '
#    + from scratch/initramfs/ run ./init.test
#
# To test make_image.sh --
#    + copy make_image.sh scratch/make_image.sh.test, and chage the source GLOBALS line as follows
#      ' source GLOBALS.scratch_test '
#    + mkdir scratch/boot if it does not already exist
#    + from scratch/ run ./make_image.sh.test
#    + examine scratch/boot <-- see new initramfs file there (copy name)
#
# To test the actual initramfs, complete, edit /home/joe/myUtilities/dev-util/mkinitramfs/scratch.qemu-test.sh
#   + set apprpriate keydev, root_vg, and luks_partition_device (defaults match above)
#       also be sure to change the tested initramfs name to the one just copied (ensure relative path works)
#   + from scratch/ run ./qemu-test.sh
#   + in scratch/boot now find qemu_boot.log
#   * NOTE: ' you can convert to pdf for AI assessment ' with --
#     - cat qemu_boot.log | strip_ansi > qemu_boot.log.noansi
#     - text2pdf qemu_boot.log.noansi
#     * now upload qemu_boot.log.noansi.pdf
#
# To test the combined mkinitramfs, first test the rotate_initramfs.sh utility --
#   + copy mkinitramfs/rotate_initramfs.sh to .../mkinitramfs/scratch/rotate_initramfs.sh.test and change these lines
#      ' source GLOBALS.scratch_test '
#      ' img_ROOT="${MAKE_DIR%/}/scratch/"; suffix=".test"; prefix="scratch/" '
#   + from scratch/ run ./mkinitramfs.test

# ---[ end of test procedure ]--------------------------------------------------------
