#!/bin/sh
#-----[ Test procedure ]--------------------------------------------------------------------------------
#
#  Strategy: FIRST - build a source tree
#    + creating a source tree also tests make_sources.sh
#    + basic init script testing can be done in that source tree (initramfs/) directory, with init.test rather than init
#    + a test version of make_sources.sh can create the test source tree (initramfs/) inside scratch/
#    + a test version of make_image.sh can create a test initramfs image file inside scratch/
#    + full initramfs can be tested with qemu
#
#  To build a source tree in /home/joe/myUtilities/dev-util/mkinitramfs/scratch (and test make_sources.sh) --
#    + copy GLOBALS to scratch/GLOBALS.scratch_test and change these assignments as follows --
#      SOURCES_DIR="/home/joe/myUtilities/dev-util/mkinitramfs/scratch/initramfs"
#      MAKE_DIR="/home/joe/myUtilities/dev-util/mkinitramfs"
#    + copy make_sources.sh to scratch/make_sources.sh.test and change the source GLOBALS line as follows --
#      ' source GLOBALS.scratch_test '
#    * NOTE: ' *** make_sources.sh.test must be run *** from the dir where GLOBALS.scratch_test resides *** '
#        and ' GLOBALS.scratch_test must assign absolute paths ' (or relative to that location)
#    + from scratch/ run 'sudo ./make_sources.sh.test'
#
#  To test the init script ability to unlock a root_fs --
#    + copy /home/joe/myUtilities/dev-util/mkinitramfs/init ... mkinitramfs/scratch/init.test
#    + change init_ROOT= to the testing assignment
#    + reverse its sourcing order of testing_functions_header and validated_functions_header
#      (so testing functions override validated functions for testing purposes)
#    + change cmdline= assignment to testing version
#    + comment/uncomment to change mount_newroot...() line to mount_and_test_newroot()
#    + comment out lines unique to an initramfs environment, to test just unlock/ and prep to switch root
#      -mini_udev()
#      -#mount_new_root_and_prepare_to_switch_root()
#    + comment/uncomment to ensure testing_functions_header has --
#       unlock_devices() set to grep for a correct test UUID, and
#       assign_volume() set to grep for a correct vg name rather than _av_prefix
#    * NOTE: ' v10.0+ changed from deselecting gmki91 to SELECTING a specific test device
#            ' UUID="b3c2b95f-1477-4433-b653-310e03dbffc2", vg_ incl: "rock5bplus6401" '
#    + copy the finalized init.test from scratch/ to scratch/initramfs/
#    + start an ash shell as root ' # ash '
#    + from scratch/initramfs/ run 'sudo ./init.test'
#
# To test make_image.sh --
#    + copy make_image.sh scratch/make_image.sh.test
#    + change the source GLOBALS line as follows
#      ' source GLOBALS.scratch_test '
#    + change the img_ROOT= line as well
#    + mkdir scratch/boot if it does not already exist
#    + from scratch/ run 'sudo ./make_image.sh.test'
#    + examine scratch/boot <-- see new initramfs file there (copy name)
#
# To test the combined mkinitramfs, first test the rotate_initramfs.sh utility --
#   + copy mkinitramfs/rotate_initramfs.sh to .../mkinitramfs/scratch/rotate_initramfs.sh.test and change these lines
#      ' source GLOBALS.scratch_test '
#      ' img_ROOT="${MAKE_DIR%/}/scratch/"; suffix=".test"; prefix="scratch/" '
#   + from scratch/ run 'sudo ./mkinitramfs.test'
#   * note that mkinitramfs/rotate_initramfs.sh will automatically update the initramfs.latest symlink
#
# To test the actual initramfs in qemu assisted boot scenarios, first  verify the configs of
#      /home/joe/myUtilities/dev-util/mkinitramfs/scratch/qemu-test.sh, and/or
#      /home/joe/myUtilities/dev-util/mkinitramfs/scratch/qemu-test2.sh
#      (they use different qemu directives to manage the nature and order of assignment of backing devices)
#   + set apprpriate keydev, root_vg, and luks_partition_device (defaults match above)
#       also be sure to change the tested initramfs name to the one just copied (ensure relative path works)
#       or from scratch/boot/ run 'ln -s <new.filename.copied.above> initramfs.latest'
#   + absent major config changes, the initramfs.latest link may already exist, and no change to qemu-test.sh is necessary
#   + from scratch/ run 'sudo ./qemu-test.sh'
#   * NOTE: you will probably need to kill the qemu process ps -aef | grep qemu (kill -9 the qemu-system pid)
#   + in scratch/boot now find qemu_boot.log
#   * NOTE: ' you can convert to pdf for AI assessment ' with --
#     - text2pdf qemu_boot.log
#     * now upload qemu_boot.log.pdf
#

# ---[ end of test procedure ]--------------------------------------------------------

# To Do: create image files for supported boards type incl. generic-amd64, bcm2712-rpi-5-b, etc.
