#!/bin/bash
# assemble a make.conf file

# source headers
#script_header_installed_dir=./         ## only when testing, pre-ebuild
script_header_installed_dir=/usr/sbin   # this is where it should be installed
source ${script_header_installed_dir%/}/script_header_joetoo
message_n "sourcing BUILD ..."
source /etc/crossbuild-tools/BUILD ; right_status $?
message_n "sourcing BPN ..."
source /etc/crossbuild-tools/BPN ; right_status $?
source ${script_header_installed_dir%/}/script_header_joetoo_extended

# only needed for testing sources pending package build
#script_header_installed_dir=/home/joe/myUtilities/dev-util/script_header_joetoo

#-----[ variables ]------------------------------------------------------
VERBOSE=$TRUE
verbosity=3
PN=$(basename $0)

varlist=" PN BUILD"
varlist+=" BREAK BOARD TARGET TARGET_ARCH QEMU_ARCH TUPLE1"
varlist+=" BREAK config_file bool.INTERACTIVE SYS_TYPE"
varlist+=" ENV_TYPE lv.OUT_FILE bool.OVER_WRITE lv.FINAL_OUTPUT_FILE"
varlist+=" BREAK MAKE_CONF_PARTS_DIR user lv.DRAFT_FILE"
varlist+=" bool.FLAGGED bool.VERBOSE verbosity"

hidden_varlist="result response answer "

#-----[ functions ]------------------------------------------------------

message_n "sourcing cb-common-functions ..."
source /usr/sbin/cb-common-functions ; right_status $?
TARGET=""

# override usage in script_header_joetoo and local.usage in crossbuild-tools
usage() {
    message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
    smaller_script_common_usage_message
    message "${BYon}${PN} also supports:${Boff}"
    for board in generic-amd64; do
        echo -e "         ${board}"
    done
    echo
    exit 1
}

initialize_variables() {
    # use script_header_joetoo functions
    initialize_vars ${varlist}
    initialize_vars ${hidden_varlist}

    FLAGGED=$FALSE
    # assign initial values
    message_n "Re-assigning PN = $(basename $0) ..."
    PN=$(basename $0) ; result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "sourcing BUILD ..."
    source /etc/crossbuild-tools/BUILD
    result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "sourcing BPN ..."
    source /etc/crossbuild-tools/BPN
    result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "Assigning config_file = /etc/crossbuild-tools/cb-assemble-make-conf.conf ..."
    config_file="/etc/crossbuild-tools/cb-assemble-make-conf.conf"
    result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "sourcing ${config_file} ..."
    source "${config_file}"
    result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "Re-assigning BOARD = \$1 [$1] ..."
    export BOARD=${myBOARD} ; result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "Assigning FINAL_OUTPUT_FILE = \${OUT_FILE}.\${SYS_TYPE}.\${ENV_TYPE}.\${BOARD}"
    export FINAL_OUTPUT_FILE="${OUT_FILE}.${SYS_TYPE}.${ENV_TYPE}.${BOARD}"
    result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "Re-assigning VERBOSE = \$TRUE ..."
    export VERBOSE=$TRUE ; result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "Re-assigning verbosity = 3 ..."
    export verbosity=3 ; result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "Re-assigning user = joe ..."
    export user="joe" ; result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "Assigning MAKE_CONF_PARTS_DIR = /home/${user}/myUtilities/dev-sbc/crossbuild-tools/make-conf-parts ..."
    export MAKE_CONF_PARTS_DIR="/home/${user}/myUtilities/dev-sbc/crossbuild-tools/make-conf-parts"
    result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "Assigning DRAFT_FILE = /tmp/draft-make-conf/make.conf.draft_${BOARD} ..."
    export DRAFT_FILE="/tmp/draft-make-conf/make.conf.draft_${BOARD}"
    result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    message_n "Assigning OUT_FILE = /home/${user}/myUtilities/dev-sbc/crossbuild-tools/make-conf-files/make.conf.${BOARD} ..."
    export OUT_FILE="/home/${user}/myUtilities/dev-sbc/crossbuild-tools/make-conf-files/make.conf.${BOARD}"
    result=$? ; right_status $result
    [ ! $result -eq 0 ] && FLAGGED=$TRUE

    [ $FLAGGED ] && return 1 || return 0
}

display_configuration() {
    separator ${PN} "(display configuration)"
    # use script_header_joetoo functions
    longest=$(get_longest ${varlist})
    display_vars $longest ${varlist} || return 1
    return 0
}

sanity_check() {
    separator ${PN} "(sanity check)"
    # put some code here to catch dumb stuff like cmdline option assignments that should
    # be mutually exclusive
    [[ "${SYS_TYPE:0:1}" != [hH] ]] && [[ "${SYS_TYPE:0:1}" != [dD] ]] && \
        die "invalid SYS_TYPE [${SYS_TYPE}] ; please correct this in ${config_file}"
    [[ "${ENV_TYPE:1:1}" != [rR] ]] && [[ "${ENV_TYPE:0:1}" != [hH] ]] && \
        die "invalid ENV_TYPE [${ENV_TYPE}] ; please correct this in ${config_file}"
    # don't need to sanity check OUT_FILE - if the dirname does not exist, we create it
    # and if the file already exists, and OVER_WRITE=$FALSE, we get user to confirm
    return 0
}

add-part() {
    # $1 is the input file path
    INFILE=$1
    while read -r LINE; do
        echo "${LINE}" >> "${DRAFT_FILE}"
    done < "${INFILE}"
    return $?
}

create-draft-file() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "initializing draft make.conf file ..."
    z=$(dirname "${DRAFT_FILE}")
    export DRAFT_DIR="${z}"
    if [ -d "${z}" ] ; then
        echo -en " (dir ${BGon}exists${Boff})"
    else
        mkdir -p "${z}" && echo -en " (${BMon}created${Boff} dir)" || die "failed to mkdir -p ${z}"
    fi && \
    if [ -e "${DRAFT_FILE}" ] ; then
        rm "${DRAFT_FILE}" || die "failed to rm ${DRAFT_FILE}"
    fi
    touch "${DRAFT_FILE}"
    result=$? ; right_status $result ; return $result
}

add-heading() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding heading ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/01_heading-common"
    result=$? ; right_status $result ; return $result
}

add-COMMON_FLAGS() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding COMMON_FLAGS ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/02_COMMON_FLAGS_${BOARD}"
    result=$? ; right_status $result ; return $result
}

add-CFLAGS() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding CFLAGS ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/03_CFLAGS-common"
    result=$? ; right_status $result ; return $result
}

add-CHOST() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding CHOST for ${TUPLE1} ${ENV_TYPE} ..."
    # append the version for both TUPLE1 (i.e. arch) and ENV_TYPE (crossbuild/chroot) version of this
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/04_CHOST-${TUPLE1}.${ENV_TYPE}"
    result=$? ; right_status $result ; return $result
}

add-MAKEOPTS_header() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding MAKEOPTS_header ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/05_MAKEOPTS_header-common"
    result=$? ; right_status $result ; return $result
}

add-MAKEOPTS() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding MAKEOPTS for ${BOARD} ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/06_MAKEOPTS_${BOARD}"
    result=$? ; right_status $result ; return $result
}

add-ACCEPT_KEYWORDS() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding ACCEPT_KEYWORDS for ${TUPLE1} ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/07_ACCEPT_KEYWORDS-${TUPLE1}"
    result=$? ; right_status $result ; return $result
}

add-ACCEPT_LICENSE() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding ACCEPT_LICENSE ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/08_ACCEPT_LICENSE-common"
    result=$? ; right_status $result ; return $result
}

add-FEATURES() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding FEATURES ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/09_FEATURES-common"
    result=$? ; right_status $result ; return $result
}

add-DIRS() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding DIRS ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/10_DIRS-common"
    result=$? ; right_status $result ; return $result
}

add-LANGUAGE() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding LANGUAGE ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/11_LANGUAGE-common"
    result=$? ; right_status $result ; return $result
}

add-INPUT_DEVICES() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding INPUT_DEVICES for ${BOARD} ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/12_INPUT_DEVICES_${BOARD}"
    result=$? ; right_status $result ; return $result
}

add-VIDEO_CARDS() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding VIDEO_CARDS for ${BOARD} ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/13_VIDEO_CARDS_${BOARD}"
    result=$? ; right_status $result ; return $result
}

add-INSTALL_MASK() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding INSTALL_MASK ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/14_INSTALL_MASK-common"
    result=$? ; right_status $result ; return $result
}


add-USE() {
    d_message "inside ${FUNCNAME[0]}" 4

    message_n "adding  USE flags for ${SYS_TYPE} ${ENV_TYPE} ..."
    # append the version for both SYS_TYPE (headless/desktop) and ENV_TYPE (crossbuild/chroot) version of this
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/15_USE-${SYS_TYPE}.${ENV_TYPE}"
    result=$? ; right_status $result ; return $result
}

add-GRUB_PLATFORMS() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding GRUB_PLATFORMS for ${BOARD} ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/16_GRUB_PLATFORMS_${BOARD}"
    result=$? ; right_status $result ; return $result
}

add-MIRRORS() {
    d_message "inside ${FUNCNAME[0]}" 4
    message_n "adding MIRRORS ..."
    add-part "${MAKE_CONF_PARTS_DIR%/}/00_BLANK_LINE" && \
    add-part "${MAKE_CONF_PARTS_DIR%/}/17_MIRRORS-common"
    result=$? ; right_status $result ; return $result
}

post-file() {
    d_message "inside ${FUNCNAME[0]}" 4
    PROCEED=$TRUE
    message_n "copying draft"
    if [ -e "${OUT_FILE}" ] && [ ! ${OVER_WRITE} ] ; then
        # same-named file already exists, and OVER_WRITE=$FALSE, so confirm with user before writing
        echo  # was otherwise waiting from message_n above
        message "${OUT_FILE}"
        new_prompt "already exists; overwrite?"
        [[ "${response:0:1}" != [yY] ]] && PROCEED=$FALSE
    fi
    if [ ${PROCEED} ] ; then
        z=$(dirname "${FINAL_OUTPUT_FILE}")
        # create directory if needed
        if [ -d "${z}" ] ; then
            echo -en " (dir ${BGon}exists${Boff})"
        else
            mkdir -p "${z}" && echo -en " (${BMon}created${Boff} dir)" || die "failed to mkdir -p ${z}"
        fi
        # copy file to final
        cp -a "${DRAFT_FILE}" "${FINAL_OUTPUT_FILE}" && result=$? && echo -en "(copied)" || die "failed to copy draft to final"
    fi
    right_status $result ; return $result
}


#-----[ main script ]----------------------------------------------------
checkroot
separator ${PN} $(hostname)
[ $# -ne 1 ] && usage
myBOARD=$1

# basic common approach -
# initialize variables (local function)
# local validation, configuration, and variable assignment (local function(s))
# display_configuration so we can see what's what if insane (script_header_joetoo_extended)
# sanity_check (cb-common-functions)
# do local parts

# initialize variables and set default values
initialize_variables || die "Failed to initialize_variables"

# local validation, configuration, and variable assignment (local function(s))
# work-around 1 for generic-amd64, for now
if [[ ${BOARD} == "generic-amd64" ]] ; then
    TARGET=x86_64-pc-linux-gnu
    TARGET_ARCH=amd64
    QEMU_ARCH=x86_64
#    STAGE3_SELECTOR="stage3-armv6j_hardfp-openrc-[0-9]"
    profile_number=21
    VALID=$TRUE
else
    validate_target ${BOARD} || die "Failed to validate_target [${BOARD}]"
fi

# identify TUPLE1 - used to pick CFLAGS, etc
message_n "extracting TUPLE1 from TARGET ..."
# work-around 2 for generic-amd64, for now
if [[ ${BOARD} == "generic-amd64" ]] ; then
    TUPLE1="amd64"
else
    TUPLE1=$(echo "${TARGET}" | cut -d'-' -f1) result=$?
fi
[ $result -eq 0 ] && echo -en " (${TUPLE1})" || echo -en " (failed)"
right_status $result

display_configuration || die "Failed to display_configuration"
echo
message "NOTE: $(status_color ${INTERACTIVE})INTERACTIVE${Boff}, ${LBon}SYS_TYPE${Boff}, ${LBon}ENV_TYPE${Boff}, ${LBon}OUT_FILE${Boff}, and $(status_color ${OVER_WRITE})OVER_WRITE${Boff} are configured"
message "(and may be modified) in ${config_file}"
[ $INTERACTIVE ] && confirm_continue_or_exit

# sanity check configuration
#sanity_check || die "Failed sanity_check"

separator ${PN} "(build make.conf)"
create-draft-file || die "failed to create-draft-file"
add-heading || die "failed to add-heading"
add-COMMON_FLAGS || die "failed to add-COMMON_FLAGS"
add-CFLAGS || die "failed to add-CFLAGS"
add-CHOST || die "failed to add-CHOST"
add-MAKEOPTS_header || die "failed to add-MAKEOPTS_header"
add-MAKEOPTS || die "failed to add-MAKEOPTS"
add-ACCEPT_KEYWORDS || die "failed to add-ACCEPT_KEYWORDS"
add-ACCEPT_LICENSE || die "failed to add-ACCEPT_LICENSE"
add-FEATURES || die "failed to add-FEATURES"
add-DIRS || die "failed to add-DIRS"
add-LANGUAGE || die "failed to add-LANGUAGE"
add-INPUT_DEVICES || die "failed to add-INPUT_DEVICES"
add-VIDEO_CARDS || die "failed to add-VIDEO_CARDS"
add-INSTALL_MASK || die "failed to add-INSTALL_MASK"
add-USE || die "failed to add-USE"
add-GRUB_PLATFORMS || die "failed to add-GRUB_PLATFORMS"
add-MIRRORS || die "failed to add-MIRRORS"
post-file || die "failed to post-file"

message "${PN} Complete"
echo


