#!/bin/bash
#
# buildtarget-qemu
#

source /usr/sbin/script_header_joetoo
message_n "sourcing BUILD ..."
source /etc/crossbuild-tools/BUILD ; right_status $?
message_n "sourcing BPN ..."
source /etc/crossbuild-tools/BPN ; right_status $?
source /usr/sbin/script_header_joetoo_extended

VERBOSE=$TRUE
verbosity=3
PN=$(basename $0)

message_n "sourcing cb-common-functions ..."
source /usr/sbin/cb-common-functions ; right_status $?

TARGET=""
ARCH=""

usage() {
    message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
    smaller_script_common_usage_message
    exit
}

#-----[ main script ]---------------------------------------------
checkroot
separator ${PN} $(hostname)
[ $# -ne 1 ] && usage
BOARD=$1
validate_target ${BOARD} || die "Failed to validate_target [${BOARD}]"

old_dir="$(pwd)"
cd /usr/${TARGET}
message "now working in crossbuild target directory: [${Mon}$(pwd)${Boff}]"

[[ $INTERACTIVE ]] && emerge_options="-av1" || emerge_options="-v1"

message "building qemu for ${TARGET} ..."
FEATURES="-getbinpkg" QEMU_USER_TARGETS="${QEMU_ARCH}" QEMU_SOFTMMU_TARGETS="${QEMU_ARCH}" \
    USE="static-user -plugins static-libs" emerge ${emerge_options} --buildpkg qemu
result=$? ; right_status $result

if [ $result -eq 0 ] ; then
    message "installing qemu binary in ${TARGET} ..."
    ROOT=/usr/${TARGET}/ emerge ${emerge_options} --usepkgonly --nodeps qemu && \
    right_status $? || ( right_status $? && exit 1 )
else
    E_message "${BRon}Failed to build qemu for ${TARGET} ...${Boff}"
    exit 1
fi

# cross-rust setup has been relocated to step 16 in cb-mkenv

echo
cd $old_dir
message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
exit 0
