#!/bin/bash
#
# cb-cleanup   (c) joe.brendler  2025-2072
# clean up the crossbuild (crossdev) environment
#
source /usr/sbin/script_header_joetoo
source /usr/sbin/script_header_joetoo_unicode
message_n "sourcing BUILD ..."
source /etc/crossbuild-tools/BUILD ; right_status $?
message_n "sourcing BPN ..."
source /etc/crossbuild-tools/BPN ; right_status $?
source /usr/sbin/script_header_joetoo_extended

VERBOSE=$TRUE
# set default verbosity only if it is not already set
[ -z $verbosity ] && verbosity=3

PN=$(basename $0)

message_n "sourcing cb-common-functions ..."
source /usr/sbin/cb-common-functions ; right_status $?
TARGET=""

usage() {
    message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
    smaller_script_common_usage_message
    exit 1
}

cleanup-crossdev-environment() {
    # inspect target (mount point) - is anything mounted? (un-mount)
    # (moved to cb-umount, called by cb-mkenv0

    # examine ${BOARD}.img - ask what to do with it
    if [ -f /usr/${BOARD}.img ] ; then
        d_message "INTERACTIVE: $(status_color $INTERACTIVE)$(TrueFalse $INTERACTIVE)${Boff}" 3
        if [[ $INTERACTIVE ]] ; then
            msg="${BYon}Do you want to delete image file /usr/${BOARD}.img ?\n"
            msg+="     y: delete | s: skip, but continue cleanup | n: no, abort"
            response="" ; new_prompt "${msg}"
        else
            response="s"  # take the safe course. don't non-interactively destroy stuff
        fi
        case ${response:0:1} in
            [yY] ) message "deleting /usr/${BOARD}.img ..." ;
                   rm /usr/${BOARD}.img || die "failed to rm /usr/${BOARD}.img"
                   right_status $TRUE
                   ;;
            [sS] ) message "Skipping as instructed [ ${response} ]" ;;
            [nN] ) E_message "Exiting as instructed [ ${response} ]" ; exit 1 ;;
            * ) E_message "Invalid response [ ${response} ]; exiting" ; exit ;;
        esac
    else
        message "no /usr/${BOARD}.img file exists ; continuing"
    fi

    # examine crossdev situation and offer to use crossdev -C to cleanup crossdev crosscompiler and its TARGET directory; ask what to do with it
    if [ -d /usr/${TARGET} ] || [ -d /var/db/repos/crossdev/cross-${TARGET} ] ; then
        d_message "INTERACTIVE: $(status_color $INTERACTIVE)$(TrueFalse $INTERACTIVE)${Boff}" 3
        if [[ $INTERACTIVE ]] ; then
            msg="${BYon}Do you want to cleanup with ${BBon}crossdev ${BMon}-C -t ${LBon}${TARGET}${Boff}?\n"
            msg+="     y: clean | s: no, but continue update | n: no, abort"
            response="" ; new_prompt "${msg}"
        else
            response="s"  # take the safe course. don't non-interactively destroy stuff
        fi
        case ${response:0:1} in
            [yY] ) message "removing crossdev toolchain for $TARGET"
                   message "Note: you may also remove the mountpoint tree (say yes to rm recursive? prompt)"
                   crossdev -C -t ${TARGET} || die "failed to crossdev -C -t ${TARGET}"
                   right_status $TRUE
                   ;;
            [sS] ) message "Skipping as instructed [ ${response} ]" ;;
            [nN] ) die "Aborting as instructed [ ${response} ]" ;;
            * ) die "Invalid response [ ${response} ]; exiting" ;;
        esac
    else
        E_message "no crossdev mountpoint nor repository for target exists (${BGon}Ok; will build${Boff})"
    fi

    return 0
}

#-----[ main script ]---------------------------------------------
checkroot
separator ${PN} $(hostname)
[ $# -ne 1 ] && usage
BOARD=$1
validate_target ${BOARD} || die "Failed to validate_target [${BOARD}]"

old_dir="$(pwd)"
cd /usr/
message "now working in parent of crossbuild target directory: [${Mon}$(pwd)${Boff}]"

cleanup-crossdev-environment || die "Failed to cleanup-crossdev-environment"

echo
cd $old_dir
message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
exit 0
