#!/bin/bash
#
# cb-dashboard   (c) joe.brendler  2025-2072
# mount a crossbuild image file on its associated TARGET
#

source /usr/sbin/script_header_joetoo
message_n "sourcing BUILD ..."
source /etc/crossbuild-tools/BUILD ; right_status $?
message_n "sourcing BPN ..."
source /etc/crossbuild-tools/BPN ; right_status $?
source /usr/sbin/script_header_joetoo_extended

VERBOSE=$TRUE
verbosity=2

PN=$(basename $0)

# specify cross-build targets to look for
TARGETS="aarch64-unknown-linux-gnu\|armv7a-unknown-linux-gnueabihf\|armv6j-unknown-linux-gnueabihf"

message_n "sourcing cb-common-functions ..."
source /usr/sbin/cb-common-functions ; right_status $?

usage() {
    E_message "${BRon}usage: ${BGon}${PN}${Boff}"
    echo -e "${BMon} * ${Boff}(no arguments)"
    smaller_script_common_usage_message
    exit
}

show-dashboard() {
    # minimal start-point for dashboard info gathering
    echo
    separator ${PN} "(active crossbuild loop devices)"
    d_message "(running losetup -a | grep '/usr/' | sed 's|^|    |')" 3
    losetup -a | grep '/usr/' | sed 's|^|    |'
    echo
    separator ${PN} "(active binhost loop devices)"
    d_message "(running losetup -a | grep 'stockpile' | sed 's|^|    |')" 3
    losetup -a | grep 'stockpile' | sed 's|^|    |'
    echo
    separator ${PN} "(active crossbuild mounts)"
    d_message "(running mount | grep 'loop' | grep \"${TARGETS}\" |sed 's|^|    |')" 3
    findmnt -lo SOURCE,TARGET | grep 'loop' | grep "${TARGETS}" |sed 's|^|    |'
    echo
    separator ${PN} "(active binhost mounts)"
    d_message "(running mount | grep 'loop' | grep 'binhost' |sed 's|^|    |')" 3
    findmnt -lo SOURCE,TARGET  | grep 'loop' | grep 'binhost' |sed 's|^|    |'
}

#-----[ main script ]---------------------------------------------
checkroot
separator "$(hostname)" "${PN}"
[ $# -ne 0 ] && usage

old_dir="$(pwd)"
cd /usr/
message "now working in parent of crossbuild target directory: [${Mon}$(pwd)${Boff}]"

show-dashboard || die "failed to show-dashboard"

echo
cd $old_dir
message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
exit 0
