#!/bin/bash
source /usr/sbin/script_header_joetoo

package_dir=/home/joe/myUtilities/dev-sbc/crossbuild-tools

for x in $(joetoo-sbc-list | awk '{print $1}'); do
    echo
    echo $x
    sfdisk_template="$(find ${package_dir%/}/cb-layout-device-sfdisk-templates/ -type f -name "*\.${x}\.*" -printf '%f\n')"
    [ -z "${sfdisk_template}" ] && E_message "sfdisk template not found" || message "${sfdisk_template}"

    blkid_template="$(find ${package_dir%/}/cb-layout-device-blkid-templates/ -type f -name "*\.${x}\.*" -printf '%f\n')"
    [ -z "${blkid_template}" ] && E_message "blkid template not found" || message "${blkid_template}"

    lsblk_template="$(find ${package_dir%/}/cb-layout-device-lsblk-templates/ -type f -name "*\.${x}\.*" -printf '%f\n')"
    [ -z "${lsblk_template}" ] && E_message "lsblk template not found" || message "${lsblk_template}"

done
