#!/bin/bash
#
# cb-mount   (c) joe.brendler  2025-2072
# mount a crossbuild image file on its associated TARGET
#

source /usr/sbin/script_header_joetoo
message_n "sourcing BUILD ..."
source /etc/crossbuild-tools/BUILD ; right_status $?
message_n "sourcing BPN ..."
source /etc/crossbuild-tools/BPN ; right_status $?
source /usr/sbin/script_header_joetoo_extended

VERBOSE=$TRUE
# set default verbosity only if it is not already set
[ -z $verbosity ] && verbosity=3

PN=$(basename $0)

message_n "sourcing cb-common-functions ..."
source /usr/sbin/cb-common-functions ; right_status $?
TARGET=""

usage() {
    message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
    smaller_script_common_usage_message
    exit
}

mount-board() {
    # inspect target (mount point) - is anything mounted? (un-mount)
    if [ ! -z "$(findmnt -n -M /usr/${TARGET})" ] ; then
        # something is mounted - un-mount it
        E_message "${BYon}the following devices are already mounted on /usr/${TARGET} --${Boff}"
        mount | grep "on /usr/${TARGET}" | sed 's|^|    |'
        exit 1
    else
        message "nothing is mounted on /usr/${TARGET} ; continuing"
    fi
    # inspect for loop devices attached to BOARD image file
    message "looking for loop device attached to /usr/${BOARD}.img ..."
    loop_dev=$(losetup -a | grep "/usr/${BOARD}.img" | cut -d':' -f1)
    if [ ! -z "${loop_dev}" ] ; then
        E_message "${BYon}${loop_dev} is already attached to /usr/${BOARD}.img"
        exit 1
    else
        message "no loop device is yet attached to /usr/${BOARD}.img; continuing"
    fi

    # attach loop device (read-write)
    message_n "attaching loop device"
    img_loop_dev=$(losetup --find --show --partscan /usr/${BOARD}.img) || die "failed to attach loop device"
    echo -n " (${img_loop_dev})"
    right_status $TRUE

    # assign partition device names
    message_n "assigning device name for partition 1 ..."
    img_partition1_dev="${img_loop_dev}p1" || die "failed to assign img_partition1_dev"
    echo -n " ( ${img_partition1_dev} )"
    right_status $TRUE
    message_n "assigning device name for partition 2 ..."
    img_partition2_dev="${img_loop_dev}p2" || die "failed to assign img_partition2_dev"
    echo -n " ( ${img_partition2_dev} )"
    right_status $TRUE

    # use fsck to preen bootfs (vfat)
    message_n "preening bootfs (vfat) ..."
    fsck.vfat -a ${img_partition1_dev} >/dev/null 2>&1
    right_status $?

    # use fsck to preen rootfs (ext4)
    message_n "preening rootfs (ext4) ..."
    e2fsck -p ${img_partition2_dev} >/dev/null 2>&1 ; result=$?
    case $result in
        0|1|2 ) right_status $TRUE ;; # 0: clear; 1: fixed; 2: fixed->reboot (N/A for .img)
        *     ) die "${BRon}e2fsck failed!${Boff} exit code: [${Mon}$result${Boff}]. Fix before continuing"
    esac

    # now mount the partitions
    message_n "mounting rootfs (${img_partition2_dev}) on /usr/${TARGET}/ ..."
    mount ${img_partition2_dev} /usr/${TARGET}/ || die "failed to mount img_partition2_dev"
    right_status $TRUE
    message_n "mounting bootfs (${img_partition1_dev}) on /usr/${TARGET}/boot/ ..."
    mount ${img_partition1_dev} /usr/${TARGET}/boot/ || die "failed to mount img_partition1_dev"
    right_status $TRUE
    return 0
}

#-----[ main script ]---------------------------------------------
checkroot
separator "(${BOARD})" "${PN}"
[ $# -ne 1 ] && usage
BOARD=$1
validate_target ${BOARD} || die "Failed to validate_target [${BOARD}]"

old_dir="$(pwd)"
cd /usr/
message "now working in parent of crossbuild target directory: [${Mon}$(pwd)${Boff}]"

mount-board || die "failed to mount-board"

echo
cd $old_dir
message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
exit 0
