#!/bin/bash
# expects $TARGET to be set in the environment
# Filter out host cross-compiler specific flags that leak from host Perl
# do not error-trap with die() here; it isn't available (do that in calling script)
args=()
host_cflags=$(source /etc/portage/make.conf; echo $CFLAGS)
target_cflags=$(source /usr/${TARGET}/etc/portage/make.conf; echo $CFLAGS)

for arg in "$@"; do
    # if this arg is in host_cflags and NOT in target_cflags, then skip it
    # pad both sides of each to ensure match and accomodate "end of list" element
    if [[ " ${host_cflags} " == *" ${arg} "* ]] && [[ " ${target_cflags} " != *" ${arg} "* ]]; then
        continue  # just go on to then next arg
    else
        # append arg to args() array
        args+=("$arg")
    fi
done
exec ${TARGET}-gcc "${args[@]}"
