#!/bin/bash
#
# populate-target   (c) joe.brendler  2025-2072
# copy appropriate template files into crossbuild target filesystem
#

source /usr/sbin/script_header_joetoo
source /usr/sbin/script_header_joetoo_unicode
message_n "sourcing BUILD ..."
source /etc/crossbuild-tools/BUILD ; right_status $?
message_n "sourcing BPN ..."
source /etc/crossbuild-tools/BPN ; right_status $?
source /usr/sbin/script_header_joetoo_extended

VERBOSE=$TRUE
# set default verbosity only if it is not already set
[ -z $verbosity ] && verbosity=3

PN=$(basename $0)

SOURCE_DIR="/etc/crossbuild-tools/mkenv-files"
IMAGE_CONFIG_FILE="/root/.cb-config"    # relative to /usr/${TARGET}

message_n "sourcing cb-common-functions ..."
source /usr/sbin/cb-common-functions ; right_status $?
TARGET=""

usage() {
    message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
    smaller_script_common_usage_message
    exit
}

save_config() {
    FLAGGED=$FALSE
    # first write creates/overwrites file; others append
    message_n "saving BOARD to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
    echo "export cb_BOARD=${BOARD}" > /usr/${TARGET}${IMAGE_CONFIG_FILE}  ; result=$?
    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi

    message_n "saving TARGET to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
    echo "export cb_TARGET=${TARGET}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}  ; result=$?
    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi

    message_n "saving TARGET_ARCH to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
    echo "export cb_TARGET_ARCH=${TARGET_ARCH}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE} ; result=$?
    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi

    message_n "saving QEMU_ARCH to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
    echo "export cb_QEMU_ARCH=${QEMU_ARCH}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE} ; result=$?
    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi

    message_n "saving STAGE3_SELECTOR to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
    echo "export cb_STAGE3_SELECTOR=${STAGE3_SELECTOR}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}; result=$?
    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi

    message_n "saving default_profile to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
    echo "export cb_default_profile=${default_profile}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}; result=$?
    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi

    message_n "saving LLVM_TARGET to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
    echo "export cb_LLVM_TARGET=${LLVM_TARGET}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}; result=$?
    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi

    [ $FLAGGED ] && return 1
    return 0
}

#-----[ main script ]---------------------------------------------
checkroot
separator ${PN} $(hostname)
[ $# -ne 1 ] && usage
BOARD=$1
validate_target ${BOARD} || die "Failed to validate_target [${BOARD}]"

old_dir="$(pwd)"
cd /usr/${TARGET}
message "now working in crossbuild target directory: [${Mon}$(pwd)${Boff}]"

# populate the BUILD assignment file in this board image's own
# /etc/crossbuild-tools directory by pre-populating BUILD in mkenv-files/common
# the "install files from common sources" step below will actually put it in the image
build_dir="${SOURCE_DIR%/}/common/etc/crossbuild-tools"
message_n "checking for build_dir [${build_dir}] ..."
[ ! -d ${build_dir} ] && mkdir -p ${build_dir} ; right_status $?
message_n "updating BUILD ..."
cp /etc/crossbuild-tools/BUILD ${build_dir%/}/ ; right_status $?

# populate the BPN assignment file in this board image's own
# /etc/crossbuild-tools directory by pre-populating BPN in mkenv-files/common
# the "install files from common sources" step below will actually put it in the image
bpn_dir="${SOURCE_DIR%/}/common/etc/crossbuild-tools"
message_n "checking for bpn_dir [${bpn_dir}] ..."
[ ! -d ${bpn_dir} ] && mkdir -p ${bpn_dir} ; right_status $?
message_n "updating BPN ..."
cp /etc/crossbuild-tools/BPN ${bpn_dir%/}/ ; right_status $?

# install files from board-unique sources
install_files_from_source "${SOURCE_DIR%/}/${BOARD}/" || \
    E_message "failed while installing files from ${SOURCE_DIR%/}/${BOARD}/"

# install files from common sources
install_files_from_source "${SOURCE_DIR%/}/common/" || \
    E_message "failed while installing files from ${SOURCE_DIR%/}/common/"

# make scripts executable in chroot (joetoo-meta should have deployed them with emerge-world)
DESTINATION="/usr/${TARGET}/usr/sbin"
for x in "script_header_joetoo*" "finalize-chroot" "install_my_local_ca_certificates"; do
    message_n "setting permissions on ${DESTINATION}/$x ..."
    eval "chmod +x ${DESTINATION}/$x" || die "failed to chmod +x ${DESTINATION}/$x"
    right_status $TRUE
done

# save basic confguration data in /usr/${TARGET}${IMAGE_CONFIG_FILE}
save_config || die "Failed to save_config"

echo
cd $old_dir
message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
exit 0
