#!/bin/bash
#
# quickpkg-toolchain   joe brendler 14 April 2025
#
# run this to build binary packages of the crossbuild toolchain on the host system
#   (i.e. cross-${TARGET}/gcc, etc.)
#
source /usr/local/sbin/script_header_brendlefly
VERBOSE=$TRUE
verbosity=3

PN=$(basename $0)

message_n "sourcing BUILD ..."
source /etc/crossbuild-tools/BUILD ; right_status $?

message_n "sourcing cb-common-functions ..."
source /usr/bin/cb-common-functions ; right_status $?

TARGET=""

toolchain=(
'gcc'
'glibc'
'binutils'
'linux-headers'
)

usage() {
    message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
    usage-common-message
    exit
}

#-----[ main script ]---------------------------------------------
checkroot
separator ${PN} $(hostname)
[ $# -ne 1 ] && usage
BOARD=$1
validate_target ${BOARD}

old_dir="$(pwd)"
cd /usr/${TARGET}
message "now working in target directory: [${Mon}$(pwd)${Boff}]"

for tool in ${toolchain[@]}; do
    message "  building (quickpkg) binary package for ${LBon}cross-${TARGET}/${tool}${Boff}"
    quickpkg --include-unmodified-config=y cross-${TARGET}/${tool} ; right_status $?
done

echo
cd $old_dir
message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
