#!/bin/bash
#
# populate-target   (c) joe.brendler  2025-2072
# copy appropriate template files into crossbuild target filesystem
#


source /usr/sbin/script_header_joetoo
message_n "sourcing BUILD ..."
source /etc/crossbuild-tools/BUILD ; right_status $?
message_n "sourcing BPN ..."
source /etc/crossbuild-tools/BPN ; right_status $?
source /usr/sbin/script_header_joetoo_extended

VERBOSE=$TRUE
#verbosity=2
verbosity=3

PN=$(basename $0)

message_n "sourcing cb-common-functions ..."
source /usr/sbin/cb-common-functions ; right_status $?
TARGET=""

imagefile=/etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img

usage() {
    message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
    smaller_script_common_usage_message
    exit
}

setup-board-image() {
    FLAGGED=$FALSE
    # check for template imagefile and create if needed
    if [ ! -f ${imagefile} ] ; then
        E_message "template imagefile ${imagefile} does not exist; calling cb-mktemplateimage"
        # using sparse image format (for now)
        cb-mktemplateimage s; result=$?
        if [[ ${result} -ne 0 ]] ; then
            E_message "cb-mktemplateimage ${BRon}failed${Boff}"
            FLAGGED=$TRUE
        else
            message "cb-mktemplateimage ${BGon}succeeded${Boff}"
        fi
    fi
    # if parts already exist, consider re-running cleanup
    [ -d /usr/${TARGET} ]  && E_message "target directory /usr/${TARGET} already exists" && FLAGGED=$TRUE
    [ -f /usr/${BOARD}.img ]  && E_message "image file target /usr/${BOARD}.img already exists" && FLAGGED=$TRUE
#    ( [ -b /dev/loop0p1 ] || [ -b /dev/loop0p2 ] ) && E_message "/dev/loop0 is active" && FLAGGED=$TRUE
#    ( [ -b /dev/loop1p1 ] || [ -b /dev/loop1p2 ] ) && E_message "/dev/loop1 is active" && FLAGGED=$TRUE
    # if any currently active loop device is already mounted on TARGET, flag out (i.e. ignore e.g. xen loop devs)
    if [ ! -z "$(losetup -a | grep ${TARGET})" ] ; then
        problem_dev="$(losetup -a | grep ${TARGET} | awk '{print $1}')"
        problem_dir="$(losetup -a | grep ${TARGET} | awk '{print $3}')"
        E_message "${problem_dev} is active and mounted on ${problem_dir} (i.e. TARGET [${TARGET}])"
        FLAGGED=$TRUE
    fi
    if [[ $FLAGGED ]] ; then
        E_message "${BYon}Note red flags above. You should consider re-running cleanup${Boff}"
        d_message "INTERACTIVE: $(status_color $INTERACTIVE)$(TrueFalse $INTERACTIVE)${Boff}" 3
        if [[ $INTERACTIVE ]] ; then
            msg="${BWon}Do you want to re-run cleanup?\n"
            mst+="    y: yes; re-run cleanup | s: no; continue to set up | n: no; exit"
            response="" ; new_prompt "${msg}"
        else
            response="n"  # take the safe course (to NOT non-interactively destroy stuff)
        fi
        case ${response:0:1} in
            [yY] ) message "re-running cleanup" ; cb-cleanup ${BOARD} && \
                   ( right_status $? && message "cb-cleanup succeeded" ) || \
                   ( right_status $? && exit 1 ) ;;
            [sS] ) message "OK; no action; continuing" ;;
            [nN] ) E_message "Exiting as instructed [ ${response} ]" ; exit 1 ;;
            * ) E_message "Invalid response; exiting" ; exit 1 ;;
        esac
    else
        message "no red flags noted"
    fi
    # use or create target directory
    message "red flags either not present, dealt with, or ignored; proceeding with setup"
    # use or create target directory
    if [ -d /usr/${TARGET} ] ; then
        # exists apparently because we said tp keep it, above - use
        message "target directory /usr/${TARGET} already exists - using"
    else
        message_n "making target /usr/${TARGET} ...."
        mkdir /usr/${TARGET} && right_status $? || ( right_status $? && exit 1 )
    fi
    # use or create board image file
    if [ -f /usr/${BOARD}.img ] ; then
        # exists apparently because we said tp keep it, above - use
        message "image file /usr/${BOARD}.img already exists - using"
    else
        message_n "generating /usr/${BOARD}.img from template ...."
        cp /etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img /usr/${BOARD}.img && \
        right_status $? || ( right_status $? && exit 1 )
    fi
    # loopmount board image file on target directory
    # (moved to cb-mount, called by cb-mkenv)
    return 0
}

#-----[ main script ]---------------------------------------------
checkroot
separator ${PN} $(hostname)
[ $# -ne 1 ] && usage
BOARD=$1

validate_target ${BOARD} || die "failed to validate_target [${BOARD}]"

old_dir="$(pwd)"
cd /usr/
message "now working in parent of crossbuild target directory: [${Mon}$(pwd)${Boff}]"

setup-board-image || die "failed to setup-board-image"

echo
cd $old_dir
message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
exit 0
