#!/bin/bash
source /usr/sbin/script_header_joetoo
checkroot

package_dir=/home/joe/myUtilities/dev-sbc/crossbuild-tools
raw_input_source_dir=${package_dir%/}/cb-layout-device-sfdisk-raw-input-files
# process all files in the main "-raw-input-files" directory
# do not process files in the archive sub-directory
for x in $(find ${raw_input_source_dir} -mindepth 1 -maxdepth 1 -type f); do
    ${package_dir%/}/cb-sfdisk-layout-fix $x
done
