#!/bin/bash
source /usr/sbin/script_header_joetoo

user="joe"
stockpile_dir="/home/${user}/sbc-stockpile"

message "${BYon}un-mounting all binhosts${Boff}"
for x in $(find /mnt/ -maxdepth 1 -mindepth 1 -type d | grep '_binhost'); do
    message_n "looking for mounts on $x"
    result="$(findmnt | grep $x)";
    if [ ! -z "$result" ] ; then
        echo -e -n " (${BYon}un-mounting -R${Boff})"
        umount -Rv "${x}" >/dev/null 2>&1 || die "failed to unmount $x"
    else
        echo -e -n " (${BWon}none found${Boff})"
    fi
    right_status $TRUE
done

message "${BYon}disconnecting active stockpile-image loop devices${Boff}"
for loop_dev in $(losetup -a | grep ${stockpile_dir} | cut -d: -f1); do
    message_n "running losetup -d $loop_dev"
    losetup -d $loop_dev >/dev/null 2>&1 || die "failed to disconnect loop_dev [$loop_dev]"
    right_status $TRUE
done
message "${BGon}Done${Boff}"
