#!/bin/sh
####!/bin/bash   ### switched so it's also valid in busybox (ash) shell
#   script header with basic functions
# Author: brendlefly 19 Jul 2014
#

#---[ Define common variables for use in various scripts ]---
BUILD="0.0.0 (19620207)"  #redefine in base script
ROOT_UID=0       # Only users with $UID 0 have root privileges
#  Error message used by various scripts
E_NOTROOT="Must be root to run this script."
E_ROOT="Please run this script as user, not root."
E_BAD_ARGS="Improperly formatted command line argument."

TRUE=0    # will evaluate to be logically true in a boolean operation
FALSE=""  # will evaluate to be logically false in a boolean operation
  # play with test function:
  # test ( ) { [ $1 ] && echo "$1 is true" || echo "$1 is false"; }
  # asign VERBOSE and verbosity, but only if not yet assigned
[[ -z $VERBOSE ]] && VERBOSE=$FALSE
[[ -z $verbosity ]] && verbosity=1

non_interactive_header=/usr/local/sbin/script_header_brendlefly_noninteractive

#--[ Easy ANSI Escape sequences to put color in my scripts ]---
#  see http://en.wikipedia.org/wiki/ANSI_escape_code
#  see also http://ascii-table.com/ansi-escape-sequences.php

CSI="\033["             # control sequence initiator == hex "\x1b["
#---[ Select Graphics Rendition on/off ]---------------------------
BOLD="1"       # bold on
UL="4"         # underline on
BLINK="5"      # slow blink on
BLINKFAST="6"  # fast blink on
REVERSE="7"        # image: inverse (reverse video)
ULoff="24"     # underline off
BLINKoff="25"  # blink off
SGRoff="0"     # Bold off (reset all SGR (e.g. blink, underline)
#---[ Set Text Color, Foreground ]---------------------------------
BLACK="30"     # foreground black
RED="31"       # foreground red
GREEN="32"     # foreground green
YELLOW="33"    # foreground yellow
BLUE="34"      # foreground blue
MAG="35"       # foreground magenta (it's like fucia)
LBLUE="36"     # foreground light blue (cyan)
WHITE="37"     # foreground white (cyan)
#---[ Set Background Color ]---------------------------------------
BACKoff="40"   # background black
RBACK="41"     # background red
GBACK="42"     # background green
YBACK="43"     # background yellow
BBACK="44"     # background blue
MBACK="45"     # background magenta
LBACK="46"     # background light blue (cyan)
WBACK="47"     # background white
#---[ My Favorite Colors (terminate with ${Boff} ]-----------------
Ron="${CSI}${RED}m"
Gon="${CSI}${GREEN}m"
Yon="${CSI}${YELLOW}m"
Bon="${CSI}${BLUE}m"
Mon="${CSI}${MAG}m"
Lon="${CSI}${LBLUE}m"
Won="${CSI}${WHITE}m"
BRon="${CSI}${RED};${BOLD}m"
BGon="${CSI}${GREEN};${BOLD}m"
BYon="${CSI}${YELLOW};${BOLD}m"
BBon="${CSI}${BLUE};${BOLD}m"
BMon="${CSI}${MAG};${BOLD}m"
LBon="${CSI}${LBLUE};${BOLD}m"
BWon="${CSI}${WHITE};${BOLD}m"
RVon="${CSI}${REVERSE}m"
Boff="${CSI}${SGRoff}m"          # Bold off (reset all SGR (e.g. blink, underline)
#---[ Here setting background as well ]-----------------------------
BBonY="${CSI}${BLUE};${YBACK};${BOLD}m"
color()  # set both foreground and background color; optional bold
{
  local FG=""  # foreground
  local BG=""  # optional background
  local B=""  # optional bold (applies to both foreground/background regardless of position in sequence)
  ### Note: not using the '=~' operator here because busybox doesn't support it
  case $# in
    1 ) if expr "$1" : 3[0-7] >/dev/null; then FG="$1"; else E_message "Invalid color argument, $# given"; exit 1; fi ;;
    2 ) if expr "$1" : 3[0-7] >/dev/null && expr "$2" : [01] >/dev/null; then FG="$1"; B=";$2";
      elif expr "$1" : 3[0-7] >/dev/null && expr "$2" : 4[0-7] >/dev/null; then FG="$1"; BG=";$2";
      else E_message "Invalid color arguments, $# given"; exit 1; fi ;;
    3 ) if expr "$1" : 3[0-7] >/dev/null && expr "$2" : [01] >/dev/null && expr "$3" : 4[0-7] >/dev/null; then FG="$1"; B=";$2"; BG=";$3";
      elif expr "$1" : 3[0-7] >/dev/null && expr "$2" : 4[0-7] >/dev/null && expr "$3" : [01] >/dev/null; then FG="$1"; BG=";$2"; B=";$3";
      else E_message "Invalid color arguments, $# given"; exit 1; fi ;;
    * ) E_message "Invalid color arguments"; exit 1
  esac
#  echo "case $#: \$1=[$1]   \$3=[$3]   \$2=[$2]   \$4=[$4]"
#  echo "case $#: FG=[$FG]   BG=[$BG]   B=[$B]"
#  echo -e "${CSI}${FG}${BG}${B}m"   #don't use -e here -- embed the function in an echo that does
  echo "${CSI}${FG}${BG}${B}m"
}

#---[ Box Drawing escape sequence stuff ]--------------------------
#  See: https://en.wikipedia.org/wiki/Box-drawing_character
ESCon='\e(0'
ESCoff='\e(B'
H_wall='\x71'
V_wall='\x78'
UL_wall='\x6C'
UR_wall='\x6B'
LL_wall='\x6D'
LR_wall='\x6A'
# we can also use unicode characters, which do not require the esc seq intro
uH_wall='\u2500'
uV_wall='\u2502'
uUL_wall='\u250C'
uUR_wall='\u2510'
uLL_wall='\u2514'
uLR_wall='\u2518'
uD_H_wall='\u2550'
uD_V_wall='\u2551'
uD_UL_wall='\u2554'
uD_UR_wall='\u2557'
uD_LL_wall='\u255A'
uD_LR_wall='\u255D'

#---[ Cursor Movement Commands ]-----------------------------------
SCP()    # save the current cursor position
{ echo -en "${CSI}s" && return 0 || return 1; }
RCP()    # restore the cursor to the saved position
{ echo -en "${CSI}u" && return 0 || return 1; }
HCU()    # Hide the cursor (Note: the trailing character is lowercase L)
{ echo -en "${CSI}?25l" && return 0 || return 1; }
SCU()    # Show the cursor
{ echo -en "${CSI}?25h" && return 0 || return 1; }
HVP()    # move cursor to position row=$1, col=$2 (both default to 1 if omitted)
{
  local row col
  [ ! -z "$1" ] && row=$1 || row=1
  [ ! -z "$2" ] && col=$2 || col=1
  echo -en "${CSI}${row};${col}f" && return 0 || return 1
}
CUP()    # move cursor to position row=$1, col=$2 (both default to 1 if omitted)
{
  local row col
  [ ! -z "$1" ] && row=$1 || row=1
  [ ! -z "$2" ] && col=$2 || col=1
  echo -en "${CSI}${row};${col}H" && return 0 || return 1
}
CLR()    # Clear the screen
{ echo -en "${CSI}2J" && return 0 || return 1; }
CUU()    # Move the cursor up ($1 cells)
{ [ ! -z "$1" ] && reps=$1 || reps=1; echo -en "${CSI}"$(( ${reps} + 1 ))"A" && return 0 || return 1; }
CUD()    # Move the cursor down ($1 cells)
{ [ ! -z "$1" ] && reps=$1 || reps=1; echo -en "${CSI}"$(( ${reps} - 1 ))"B" && return 0 || return 1; }
CUF()    # Move the cursor forward ($1 cells)
{ [ ! -z "$1" ] && reps=$1 || reps=1; echo -en "${CSI}"$(( ${reps} ))"C" && return 0 || return 1; }
CUB()    # Move the cursor back ($1 cells)
{ [ ! -z "$1" ] && reps=$1 || reps=1; echo -en "${CSI}"$(( ${reps} ))"D" && return 0 || return 1; }
CPR()    # Report the current position (row, col) of the cursor [tip: hit return again]
{ perl -e '$/ = "R";' -e 'print "\033[6n";my $x=<STDIN>;my($n, $m)=$x=~m/(\d+)\;(\d+)/;print "Col: $m, Row: $n\n";'; }

# ---[ common function blocks ]------------------------------------------

isnumber()      # test if $1 is a decimal number; return true/false
{ re='^[0-9]+$'; if echo "$1" | egrep -q "$re"; then return $TRUE; else return $FALSE; fi ; }

ishex()         # test if $1 is a hexadecimal number; return true/false
{ re='^[0-9a-fA-F]+$'; if echo "$1" | egrep -q "$re"; then return $TRUE; else return $FALSE; fi ; }

checkroot()     # Run as root, of course.
{ if [ "$UID" -ne "$ROOT_UID" ]; then E_message "${E_NOTROOT}"; echo; exit 1; else return 0; fi; }

checknotroot()  # Run as not root, of course.
{ if [ "$UID" -eq "$ROOT_UID" ]; then E_message "${E_ROOT}"; echo; exit 1; else return 0; fi; }

checkboot()     # check to see if the /boot partition is properly mounted (look for grub)
{ machine=$(uname -m); case ${machine} in
  "x86_64"|"x86"     ) result="$(find /boot/ -iname grub -type d)" ;;
  "aarch64"|"armv7l" ) result="$(find /boot/ -iname *.dtb)" ;;
  * ) E_message "${BRon}Error: machine ${machine} checkboot not supported" ; return 1;;  esac
  if [[ "${result}" ]] ; then return 0 ; else E_message "${BRon}/boot not mounted${Boff}" ;
    return 1 ; fi ; }

checkshell()    # reset colors if this shell is not interactive
{ [[ ! -t 0 && ! -t 1 ]] && source ${non_interactive_header}; }

message()       # echo a simply formatted message (arg $1) to the screen
{ echo -e " ${BGon}*${Boff} ${1}" && return 0 || return 1; }

message_n()     # echo -n a simply formatted message (arg $1) to the screen
{ echo -en " ${BGon}*${Boff} ${1}" && return 0 || return 1; }

E_message()     # echo a simply formatted error message (arg $1) to the screen
{ echo -e " ${BRon}*${Boff} ${1}" && return 0 || return 1; }

E_message_n()   # echo -n a simply formatted error message (arg $1) to the screen
{ echo -en " ${BRon}*${Boff} ${1}" && return 0 || return 1; }

d_message()     # pass argument $1 to message() if "external" boolean VERBOSE tests true
{ [[ $VERBOSE && $2 -le $verbosity ]] && message "$1"; }

d_message_n()   # pass argument $1 to message_n() if "external" boolean VERBOSE tests true
{ [[ $VERBOSE && $2 -le $verbosity ]] && message_n "$1"; }

dE_message()    # pass argument $1 to E_message() if "external" boolean VERBOSE tests true
{ [[ $VERBOSE && $2 -le $verbosity ]] && E_message "$1"; }

dE_message_n()  # pass argument $1 to E_message() if "external" boolean VERBOSE tests true
{ [[ $VERBOSE && $2 -le $verbosity ]] && E_message_n "$1"; }

d_echo()        # echo all but last (level) argument if $VERBOSE && verbosity -ge $level
{ input="$@"; set $input; level=$(echo $@ | cut -d' ' -f$#); if ! isnumber $level ; then \
  E_message "final arg must be decimal verbosity level"; elif [[ $VERBOSE ]] && \
  [[ $verbosity -ge $level ]] ; then [[ $# -eq 1 ]] && echo || echo $@ | cut -d' ' -f1-$(($# - 1)); fi ; }

de_echo()       # echo -e all but last (level) argument if $VERBOSE && verbosity -ge $level
{ input="$@"; set $input; level=$(echo $@ | cut -d' ' -f$#); if ! isnumber $level ; then \
  E_message "final arg must be decimal verbosity level"; elif [[ $VERBOSE ]] && \
  [[ $verbosity -ge $level ]] ; then [[ $# -eq 1 ]] && echo || echo -e $@ | cut -d' ' -f1-$(($# - 1)); fi ; }

status_color()  # emit to stdout the escape seq for color based on arg $1 (T/F Y/N 1/0)
{ case $1 in "1"|[yY]*|[tT]*|"up"|$TRUE   ) echo -en ${BGon};;
             "0"|[nN]*|[fF]*|"down"|$FALSE) echo -en ${BRon};; *) echo -en ${BYon};; esac ; }

TrueFalse()     # echo to stdout "True" or "False", depending on truth of arg $1
{  [[ $1 ]] && echo -en "True" || echo -en "False" ; }

prompt()        # set external variable $answer based on reponse to prompt $1
{ ps=$1; echo; echo; CUU; SCP; message_n "$ps [Y/n]: " && read answer; # '=~' not in busybox
while ! expr "${answer:0:1}" : [yYnN] >/dev/null;  # answer not a regex match
do RCP; echo -en "$(repeat ' ' $(termwidth))";  ## blank the line
RCP; message_n "$ps [Y/n]: " && read answer; done; }

old_prompt()    # set external variable $answer based on reponse to prompt $1
{ ps=$1; SCP; echo -en "$ps [Y/n]: "   ### Not using '=~' because it's not in busybox
  while read answer && ! expr "${answer:0:1}" : [yYnN] >/dev/null;  # answer not a regex match
    do case ${answer:0:1} in [yY1]|"$TRUE") answer="n";; [nN0]|"$FALSE") answer="x";; esac
  RCP; echo -en "$(repeat ' ' $(termwidth))"; RCP; message_n "$ps [Y/n]: " ; done; }

alpha_words()   # alphabetize the words in a quoted input string
{ echo $(for x in $@; do echo $x; done | sort -db ) ; }

pur()           # ping ip address $1 until it is ready (0% loss of 3 packets)
{ SCP; count=1; hits=0; status=""; hit_color="${Boff}"; while [[ $hits -lt 3 ]];
  do status=$(ping -c1 -i1 -t2 $1 2>/dev/null |  grep transmitted | awk '{print $6}' | sed 's/\%$//');
  [[ "$status" == "0" ]] && let "hits+=1" || let "hits=0";
  case $hits in [01]) hit_color=${BRon};; 2) hit_color=${BYon};; 3) hit_color=${BGon};; esac;
  RCP; echo -en "not ready -- try: [${count}], hits: [${hit_color}${hits}${Boff}]"; let "count+=1"; sleep 1;
  done; echo; echo OK - ready now ; }

sap()           # ssh after pause
{ pur $1 && echo "pausing to allow $1 to start sshd..." && sh_countdown 20 && ssh $1; }

swr()           # ssh when ready (pur(), then ssh after nmap shows port)
{ pur $1 && \
  message "pausing to allow $1 to start sshd..." && \
  while [ ! $(nmap -p ssh $1 | grep 'ssh' | cut -d' ' -f2) == "open" ]; do sleep 1; done && \
  ssh $1 ; }

vercomp()       # compare two version numbers return [0:equal|1:greaterthan|2:lessthan]
{ if [[ "$1" == "$2" ]]; then return 0; else first=$(echo -en "$1\n$2" | sort -V | head -n1);
  [[ "$first" == "$2" ]] && return 1 || return 2; fi }

show_result()   # show the result of vercomp comparison, in english
{ case $1 in 1) echo "${LBon}>${Boff}";; 2) echo "${BRon}<${Boff}";; \
             0) echo "${BGon}=${Boff}";; *) echo "${BYon}*** Error ***${Boff}";; esac }

my_date()       # echo a simply formatted date string (DDD MM dd hh:mm:ss AP TZ yyyy)
{ day=$(date +%a); month=$(date +%b); monthday=$(date +%d); year=$(date +%Y)
  timeofday=$(date +%X); timezone=$(date +%Z)
  echo "$day $month $monthday $timeofday $timezone $year" ; }

my_short_date() # echo a short formatted date string (yyyymmdd)
{ month=$(date +%b); monthday=$(date +%d); year=$(date +%Y); timehack=$(date +%H:%M:%S);
  echo "${monthday}${month}${year}-${timehack}" ; }

loggit()        # send a job completion status message to the cron logger
{ [[ $# -gt 2 ]] && E_message "invalid loggit arguments" && exit 1
  [[ -z $2 ]] && EXIT_STATUS=0 || EXIT_STATUS="$2"
  [[ -z $1 ]] && PROGRAM=Unspecified || PROGRAM="$1"
  case $EXIT_STATUS in
    0 ) PRIORITY="notice" && MESSAGE="succeeded.";;
    * ) PRIORITY="err" && MESSAGE="failed with exit status ${EXIT_STATUS}";;
  esac
  /usr/bin/logger -p cron.$PRIORITY "$PROGRAM $MESSAGE" ; }

repeat()        # output a repeated string of character (arg $1) of length (arg $2)
{ local i thing limit
  thing="$1"; limit=$2; out_str=""; i=0
  while [ $i -lt $limit ]; do out_str="${out_str}${thing}"; let "i++"; done
  echo -en "$out_str" && return 0 || return 1 ; }

termwidth()     # calculate and output the width of the terminal
{ echo -n $(stty size | sed 's/[0-9]* *//') && return 0 || return 1; }

termheight()    # calculate and output the height of the terminal
{ echo -n $(stty size | cut -d' ' -f1) && return 0 || return 1; }

separator()     # draw a horizontal line with a simple title (arg $1) and preface (arg $2)
{ # to facilitate separation of portions of the output of various scripts
  # include a title preface (arg $2 or $(hostname) if $2 is not provided
  local msg preface msg_len
  [ ! -z "$2" ] && preface="$2" || preface=$(hostname)
  msg="${BYon}---[${BRon} $preface ${LBon}$1 ${BYon}]"
  msg_len=$(( ${#msg} - $(( ${#BYon} + ${#BRon} + ${#BBon} + ${#BYon} + ${#Boff} )) ))
  echo -en "$msg" && \
  echo -n $(repeat "-" $(( $(termwidth) - $(( $msg_len + ${#Boff} )) )) ) && echo -e ${Boff} && \
  return 0 || return 1 ; }

get_longest()    # return via echo to stdout the length of longest string in input $@
{ ans=0; for x in $@; do [ ${#x} -gt $ans ] && ans=${#x}; done ; echo $ans ; }

display_vars()   # show aligned values for vars in $@; incl bool. lv. ; $1=longest
{
  if ! isnumber $1 ; then
    E_message "Error: arg \$1 must be numeric longest expected input var name"
    exit
  fi
  if [ $# -le 1 ] ; then set $@ "<empty>"; fi  # insert placeholder "<empty>" as $2
  maxlen=$(($1 + 2))
  shift
  for var_name in $@
  do
    if echo $var_name | grep -q "\."; then
      # display by type
      type="$(echo $var_name | awk -F \. '{print $1}')"
      var="$(echo $var_name | awk -F \. '{print $2}')"
      case ${type:0:1} in
        [bB] )
          eval "key=\$${var}"
          pad="$(repeat '.' $(( ${maxlen} - ${#var})) )"
          message "${LBon}${var}${pad}: [ $(status_color ${key})$(TrueFalse ${key}) ${LBon}]${Boff}"
        ;;
        [yY]   )
          eval "key=\$${var}"
          pad="$(repeat '.' $(( ${maxlen} - ${#var})) )"
          message "${LBon}${var}${pad}: [ $(status_color ${key})${key} ${LBon}]${Boff}"
        ;;
        [lL]   )
          eval "key=\$${var}"
          pad="$(repeat '.' $(( ${maxlen} - ${#var})) )"
          message_n "${LBon}${var}${pad}: [ ${Boff}"
          echo_n_long ${maxlen} ${key}; echo -e " ${LBon}]${Boff}"
        ;;
        *      )
          # invalid variable type
          E_message "  (${type}) invalid variable type [${type}] for variable [${var_name}]"
          exit
        ;;
      esac
    elif [[ "$var_name" == "BREAK" ]] ; then
      echo
    else
      # untyped
      type=""
      var="$var_name"
      eval "key=\$${var}"
      pad="$(repeat '.' $(( ${maxlen} - ${#var})) )"
      message "${LBon}${var}${pad}: [ ${Boff}${key} ${LBon}]${Boff}"
    fi
  done
}

initialize_vars()   # initialize values for vars in $@; incl bool. lv.
{
  [ $# -lt 1 ] && return
  parmlist=$(echo $@ | sed 's|verbosity||' | sed 's|bool.VERBOSE||')
  d_message "initializing vars: $parmlist" 5
  for var_name in $parmlist
  do
    if echo $var_name | grep -q "\."; then
      # initialize by type
      type="$(echo $var_name | awk -F \. '{print $1}')"
      var="$(echo $var_name | awk -F \. '{print $2}')"
      case ${type:0:1} in
        [bB] )
          # boolean convention: parameter is "bool.${var}" where ${var} is e.g. "VERBOSE"
          # initialize booleans $FALSE
          d_message_n "  (${type}) initializing ${var} FALSE ..." 2
          eval "${var}=\$FALSE" ; d_right_status $? 2
        ;;
        [yY]   )
          # yes/no convention: parameter is "yn.${var}" where ${var} is e.g. "EIX"
          # initialize yes/no to "no"
          d_message_n "  (${type}) initializing ${var} (no) ..." 2
          eval "${var}=''" ; d_right_status $? 2
        ;;
        [lL]   )
          # lonstring convention: parameter is "lv.${var}" where ${var} is e.g. "CMDLINE"
          # initialize longstring to null string
          d_message_n "  (${type}) initializing ${var} NULL ..." 2
          eval "${var}=''" ; d_right_status $? 2
        ;;
        *      )
          # invalid variable type
          E_message "  (${type}) invalid variable type [${type}] for variable [${var_name}]"
          exit
        ;;
      esac
    elif [[ "$var_name" == "BREAK" ]] ; then
      # ignore BREAK
      type=""
      d_message_n "  ignoring BREAK ..." 2
      d_right_status $TRUE 2
    else
      # untyped - initialize null
      type=""
      var="$var_name"
      d_message_n "  (${type}) initializing ${var} NULL ..." 2
      eval "${var}=''" ; d_right_status $? 2
    fi
    d_message "about to initialize $var_name of type: [ $type ]" 4
  done
}

echo_n_long()    #  spread a long string over several lines, if needed.  $1=start
{
  if ! isnumber $1 ; then E_message "Error: arg \$1 must be numeric starting caracter position"; exit; fi
  if [ $# -le 1 ] ; then set $@ "<empty>"; fi
  left=" * "; right=": [ "
  start=$(( $1 + ${#left} + ${#right} )); shift; input="$@"; tw=$(termwidth); newline=""
  for x in $input
  do
    d_echo "start: $start  #newline: ${#newline}   #x: ${#x}  tw: $tw   sum: $(( ${start} + ${#newline} + ${#x} + 1))" 6
    if [[  $(( ${start} + ${#newline} + ${#x} + 1)) -le ${tw} ]] ; then
      [[ ${#newline} -eq 0 ]] && newline="${x}" || newline="${newline} ${x}"
    else
      echo "${newline}"
      start=0   # since next will be a new line
      newline="${x}"
    fi
  done
  echo -n "${newline}"
}

right_status()   # output 8 char [ ok/fail ] status at the right margin
{ # test message_n "good_test" ; right_status $?
  #      E_message_n "fail_test" && cat unexistent 2>/dev/null; right_status $?
  local msg status=$1
  [[ $status -eq 0 ]] && msg="${BBon}[ ${BGon}Ok ${BBon}]${Boff}" || msg="${BBon}[ ${BRon}!! ${BBon}]${Boff}"
  # go to start of line, *then* move fwd to 7 chars from the right margin ("[ xx ]" is 6)
  echo -en "\r" && CUF $(( $(termwidth) - 7 )) && echo -e "$msg" && return 0 || return 1 ; }

d_right_status() # output 8 char [ ok/fail ] status at the right margin, if $VERBOSE
{ # test with v=((verbosity+1)) and v=(($verbosity-1))
  # d_message_n "good_test" $v; d_right_status $? $v
  #      dE_message_n "fail_test" $v && cat unexistent 2>/dev/null; d_right_status $? $v
  local status=$1
  [[ $VERBOSE && $2 -le $verbosity ]] && right_status $status && return 0 || return 1 ; }

sh_countdown()   # count-down seconds (arg $1)
{ # special note: bb sh cannot use base#number notation with prefix 10# to ensure interpretation as base 10
  if [[ ! -z $1 ]]
  then rem_time="${1}" ;
  else
    message "no argument given, defaulting to 30 seconds"
    rem_time=30
  fi
  # execute countdown
  while [[ "${rem_time}" -gt "0" ]]
  do
    [[ "$rem_time" -lt "10" ]] && r_time="0"${rem_time} || r_time=${rem_time}
    echo -en "\r${BGon}*${Boff} Pausing. [ ${BGon}${r_time}${Boff} ] seconds remaining..."
    sleep 1
    let "rem_time--"
  done
  [[ "$rem_time" -lt "10" ]] && r_time="0"${rem_time} || r_time=${rem_time}
  echo -en "\r${BGon}*${Boff} Pausing. [ ${BGon}${r_time}${Boff} ] seconds remaining..."
  echo
  return 0
}

progress()       # display an arrow depicting progress (visualize $1 of $2 steps complete)
{
  [ $# -ne 2 ] && E_message "${BRon}Error - two arguments required (${BYon}step ${BRon}and ${BYon}number_of_steps${BRon})${Boff}"
  step=$1; number_of_steps=$2
  #---[ user configurable variables ]---------------------------------------------------------------------------------------------
  margin=10; marker="-"
  #---[ analytically determined variables ]---------------------------------------------------------------------------------------
  range=$(( $(termwidth) - 3 - $(( $margin * 2 )) ))   # the -3 accounts for the two brackets (|) and the arrow head (>)
  myprogress=$(( $range * $step / $number_of_steps ))    # this is how many $marker to draw to represent a single step of progress
  start=$(($margin + 1)); end=$(( $(termwidth) - $margin -1 ))
  myrow=$(termheight)
  startofline=$(($start +1))
  [ $step -lt $number_of_steps ] && endofline=$(($startofline + $myprogress)) || endofline=$(($end - 2))
  lengthofline=$(($endofline - $startofline + 1))
  percent=$((100 * $step / $number_of_steps))
  middlestart=$(( $(( $(termwidth) / 2 )) - $(( ${#percent} / 2 )) - 4 ))
  if [ $percent -ge 90 ]; then pct_color=${BGon}; else
  if [ $percent -lt 70 ]; then pct_color=${BRon}; else pct_color=${BYon}; fi; fi
  #---/ action: move to start, draw "|", draw line and ">", move to end and draw "|",
  #     move middle, show percent, return to original position /------------------------------------------------------------------
  SCP; CUP $myrow $start; echo -en "|"
  repeat $marker $lengthofline; echo -en ">"
  CUP $myrow $end; echo -en "|"
  CUP $myrow $middlestart; echo -en "( ${pct_color}$percent%${Boff} )"; RCP
}

fe()             # find ebuild files matching filter "*$1*"
{ echo "looking for ebuild(s) matching filter: $1"; find / -iname "*$1*.ebuild" -type f -print 2>/dev/null; }

summarize_me()   # list contents of this script header (employ me with "source" or ".")
{
  echo
  separator "script_header_brendlefly-$BUILD | content summary" && \
  message "This script header defines some ${BYon}common variables${Boff} for" && \
  message "  use in various scripts, it provides pre-formatted ${BYon}easy-to-use${Boff}" && \
  message "  ${BYon}ANSI Escape sequences${Boff} to facilitate the use of ${BMon}color${Boff} and" && \
  message "  ${BYon}cursor${Boff} movement in my scripts, and it provides a number of" && \
  message "  useful ${BGon}functions${Boff}, for some routine tasks, as described below\n" && \
  grep "()" /usr/local/sbin/script_header_brendlefly | grep -v "grep" && echo && \
  msg="${BGon}* ${Boff}  ${BYon}About to run:\n        ${BBon}message${Boff}" && \
  msg="${msg}  ${BYon}\""'${BYon}VERBOSE is currently ' && \
  msg="${msg}${BGon}\$(${BBon}status_color \\\"${BRon}\$VERBOSE${BBon}\\\"${BGon})${Boff}" && \
  msg="${msg}${BGon}\$(${BBon}TrueFalse \\\"${BRon}\$VERBOSE${BBon}\\\"" && \
  msg="${msg}${BGon})${BYon}\"${BGon}; ${BBon}echo${Boff}" && echo -e "${msg}" && \
  echo && \
  message "  ${BYon}VERBOSE is currently "$(status_color "$VERBOSE")$(TrueFalse "$VERBOSE") && echo && \
  message_n "${BYon}Compare version number ${BWon}1 ${BYon}to${BWon} 1${Boff}  " && \
  vercomp 1 1; echo -e "$(show_result $?)" && \
  message_n "${BYon}Compare version number ${BWon}2 ${BYon}to${BWon} 1${Boff}  " && \
  vercomp 2 1; echo -e "$(show_result $?)" && \
  message_n "${BYon}Compare version number ${BWon}1 ${BYon}to${BWon} 2${Boff}  " && \
  vercomp 1 2; echo -e "$(show_result $?)" && \
  message_n "${BYon}Compare version number ${BWon}1.2.0 ${BYon}to${BWon} 1.2.1${Boff}  " && \
  vercomp 1.2.0 1.2.1; echo -e "$(show_result $?)" && \
  message_n "${BYon}Compare version number ${BWon}1.2.0-r1 ${BYon}to${BWon} 1.2.0${Boff}  " && \
  vercomp 1.2.0-r1 1.2.0; echo -e "$(show_result $?)" && \
  message_n "${BYon}Compare version number ${BWon}1..1 ${BYon}to${BWon} 1.2${Boff}  " && \
  vercomp 1..1 1.2; echo -e "$(show_result $?)" && \
  message_n "${BYon}Compare version number ${BWon}1.0 ${BYon}to${BWon} 1.0-r10${Boff}  " && \
  vercomp 1.0 1.0-r10; echo -e "$(show_result $?)" && \
  message_n "${BYon}Compare version number ${BWon}3.4 ${BYon}to${BWon} 3.4-r2${Boff}  " && \
  vercomp 3.4 3.4-r2; echo -e "$(show_result $?)" && echo && \
  message "  ${BYon}About to run:\n        ${BBon}sh_countdown ${Boff}6 ${BGon}&& \\ ${Boff}" && \
  echo -e "        ${BBon}message_n${Boff} "'"\\nFinishing with status of summarization --->" '"${BGon}; ${BBon}right_status ${BRon}"'$?'"${BGon}; ${BBon}echo${Boff}" && \
  echo && \
  sh_countdown 6 && \
  message_n "\nFinishing with status of summarization --->" ; right_status $?; echo

  return 0
}
