#! /bin/bash

# /usr/local/sbin/ipdeny
# based on ipdeny by BoneKracker Rev. 11 October 2012
# Modified by Joe Brendler Rev 21 Feb 2015 - ipset setlist size bugfix
# Rev 17 Feb 2022 - further adapted to refer to ipsets separately loaded for ALL countries

# Purpose: Use sets of ip networks registered in a country pre-loaded into a country-coded ipset
#   to load that ipset name into a setlist containing several such ipsets, while this setlist is
#   being used in a running firewall.
#
# Notes: Call this from crontab. Feed updated about 05:07 and 15:07 daily.
#
# Usage: 'ipdeny <TLD>' (where TLD is top-level national domain, such as "us")

source /usr/local/sbin/script_header_brendlefly

#-----[ variable initialization ]----------------------------------
[ -n "$1" ] && firewall_ipset="$1" || exit 1

#-----[ functions ]-------------------------------------------------

# function to get modification time of the file in log-friendly format
get_timestamp() {
    date -r $1 +%m/%d' '%R
}

#-----[ main script ]------------------------------------------------
checkroot
separator "ipset_countrycode_load-$BUILD" "$(hostname)"

timestamp=$(my_date)

# if the setlist does not exist, create it
ipset create -exist ipdeny list:set --size 256

# if the ipset is not already in the setlist, add it
ipset add -exist ipdeny ${firewall_ipset}

# log the file modification time for use in minimizing lag in cron schedule
msg="ipdeny setlist updated for [${firewall_ipset}] (as of: ${timestamp})."
message "Logging --> ${msg}"
logger -p cron.notice ${msg}
