#!/bin/bash
# mkhotspot -- joe brendler, 18 April 2018

IFNAME=wlan1
PASSWORD=joejoejoe
SSID=PoisonBerry
CON=Hotspot
CONFIG_PATH=/etc/NetworkManager/system-connections/
# create a random mac address
#MAC=$(perl -e 'printf "%02X:%02X:%02X:%02X:%02X:%02X\n", rand 0xFF, rand 0xFF, rand 0xFF, rand 0xFF, rand 0xFF, rand 0xFF')
# sorry: have to use actual interface mac
MAC=$(nmcli d show wlan1 | grep -i hwaddr | sed 's/ //g' | cut -d':' -f2-)

source /usr/local/sbin/script_header_brendlefly
source /usr/local/sbin/script_header_brendlefly_extended
separator "mkhotspot"

message_n "removing old configs for ${CON}"
nmcli c delete ${CON}; right_status "$?"

message_n "adding wifi [${LBon}${IFNAME}${Boff}] connection [${LBon}${CON}${Boff}] with ssid [${LBon}${SSID}${Boff}]\n"
nmcli c add type wifi ifname ${IFNAME} con-name ${CON} ssid ${SSID}; right_status "$?"
message_n "setting autoconnect to yes"
nmcli c modify ${CON} autoconnect yes; right_status "$?"
message_n "setting mode to ap"
nmcli c modify ${CON} 802-11-wireless.mode ap; right_status "$?"
message_n "setting band to bg"
nmcli c modify ${CON} 802-11-wireless.band bg; right_status "$?"
message_n "setting hidden to no"
nmcli c modify ${CON} 802-11-wireless.hidden no; right_status "$?"
message_n "setting mac-address to ${LBon}${MAC}${boff}"
nmcli c modify ${CON} 802-11-wireless.mac-address ${MAC}; right_status "$?"
message_n "setting ipv4 method to shared, ipv6 method to auto"
nmcli c modify ${CON} ipv4.method shared ipv6.method auto; right_status "$?"
message_n "setting key-mgmt to wpa-psk"
nmcli c modify ${CON} wifi-sec.key-mgmt wpa-psk; right_status "$?"
message_n "setting group to ccmp, pairwise to ccmp"
nmcli c modify ${CON} wifi-sec.group ccmp wifi-sec.pairwise ccmp; right_status "$?"
message_n "setting mode password"
nmcli c modify ${CON} wifi-sec.psk ${PASSWORD}; right_status "$?"
message_n "setting proto to rsn"
nmcli c modify ${CON} wifi-sec.proto rsn; right_status "$?"
echo
#message "Here is the resultant config file:"
#cat ${CONFIG_PATH}${CON}
#echo
message_n "attempting to start the hotspot now..."
nmcli c up ${CON} ifname ${IFNAME}; right_status "$?"
echo

message "to start the hotspot run:"
echo "nmcli c up ${CON} ifname ${IFNAME}"
echo
message "to verify the hotspot is up, run:"
echo "nmcli dev wifi list"
echo
message "to view the existing connections, run:"
echo "nmcli c"
echo
message "to view all settings for connection [${LBon}${CON}${Boff}], run:"
echo "nmcli c show ${CON}"
echo
message "to view all settings for device [${LBon}${IFNAME}${Boff}], run:"
echo "nmcli d show ${IFNAME}"
