#!/bin/bash

source /usr/local/sbin/script_header_brendlefly
nslookup_target=""
nslookup_server=""
nslookup_names=()
nslookup_addresses=()

#-----[ functions ]-----------------------------------
useage() {
  E_message "Useage: nslookuptest <target_name>"
  exit 1
}

process_line() {
  # ignore server address w "#"53; ignore (non-)authoritative "answer" line
  line=$(echo "$1" | grep -v "#" | grep -v "answer")
  # ignore blank lines
  [ -z "${line}" ] && return
  # capture server address
  [ "${line:0:6}" == "Server" ] && \
     nslookup_server="$(echo ${line:7})"
  # capture each name and corresponding address
  [ "${line:0:4}" == "Name" ] && \
     nslookup_names+=("$(echo ${line:6})")
  [ "${line:0:7}" == "Address" ] && \
     nslookup_addresses+=("$(echo ${line:9})")

}
#-----[ main script ]-----------------------------------
[ $# -ne 1 ] && useage

# capture target
nslookup_target=$1
separator "${nslookup_target}" "nslookuptest"

while read oneline
do
  process_line "${oneline}"
# read from nslookup output
done <<< $(nslookup ${nslookup_target})

message "Target: ${nslookup_target}"
message "Server: ${nslookup_server}"
# there should be the same number in each array, but just in case...
[ ${#nslookup_names[@]} -gt ${#nslookup_addresses[@]} ] && \
  count=${#nslookup_names[@]} || \
  count=${#nslookup_addresses[@]}
message "# Answers: ${count}"
  message "  (#) \tName \tAddress"
for ((i=0; i< ${count}; i++))
do
  message "  ($i) \t${nslookup_names[i]} \t${nslookup_addresses[i]}"
done
