#!/bin/bash
[ ! $# -eq 1 ] && echo "search term argument required (e.g. imx8mq)" && exit 1

# assume bcm2712 is in every file we want to add $1 to (create list of those)
#TARGET_LIST=$(grep -iR bcm2712 ./ | cut -d':' -f1 | sort -u)
# assume meson-gxl is in every file we want to add $1 to (create list of those)
TARGET_LIST=$(grep -iR meson-gxl ./ | cut -d':' -f1 | sort -u)

for TARGET in $TARGET_LIST ; do
    ! grep -q $1 $TARGET && echo "  ${TARGET}"
done
