#!/bin/bash
# works on the cmdline; not sure why not in script
source /usr/sbin/script_header_joetoo
inputfile=$1
target_char1="{"
target_char2="}"
lp_count=0 ; rp_count=0 ; running_left=0; running_right=0
[ $# -eq 0 ] || [ ! -f $inputfile ] && exit
n=1; while read line; do \
  lp_count=$(echo "$line" | tr -d -c "$target_char1" | wc -c)
  rp_count=$(echo "$line" | tr -d -c "$target_char2" | wc -c)
  let running_left+=lp_count
  let running_right+=rp_count
  if [ $lp_count -ne $rp_count ] ; then
    echo -en "$n: $line"
    if [ $lp_count -gt 0 ] || [ $rp_count -gt 0 ] ; then
      echo "<<<==== diff count"
      echo "$n: lp_count: ${lp_count}    rp_count: ${rp_count}"
      echo "$n: running_left: ${running_left}    running_right: ${running_right}"
    else
      echo
    fi
  fi
  lp_count=0 ; rp_count=0
  let n++; \
done < ${inputfile}
