#!/bin/bash
source /usr/sbin/script_header_joetoo
for x in init validated_functions_header testing_functions_header
do
    separator "$x" "listing functions in"
    grep '()' ../$x | sed 's|^[[:space:]]*||' | grep -v '^#'
done
