#!/bin/bash
# collect-system-files_new (c) Joe Brendler 2026-7789
#
script_header_installed_dir="/usr/sbin"
#script_header_installed_dir=/home/joe/myUtilities/dev-util/script_header_joetoo
header="${script_header_installed_dir%/}/script_header_joetoo"
echo "header: $header"

# source script_header
# shellcheck source="/usr/sbin/script_header_joetoo"
if [ -f "$header" ]; then
  # source it if it isn't already sourced
  # (redundant since it should also make this same check at its top section)
  if [ "$JOETOO_ENVIRONMENT_ALREADY_SOURCED" ]; then
    source_finding="was already sourced"
  else
    . "$header"
    source_finding="sourced"
  fi
else
  printf '%s' "failed to source header; cannot continue"
  exit 1
fi
# verify sourced script_header
printf '%s' "Checking for header commands to confirm sourcing"
if command -v toc >/dev/null 2>&1 && command -v run_sequence >/dev/null 2>&1 ; then
  printf '%s\n' " success; header ${source_finding}"
else
  printf '%s\n' " Failed; header not sourced; cannot continue"; exit 1
fi

#-----[ variables ]----------------------------------------------------

# NOTE: varlist variables are initialized by app_configure() and displayed by show_config();
# the basic set of varlist variables is defined in script_header_joetoo and can be extended
# either in the using script or in its .conf files.
# An example is provided in the joetoo_cli_example script and in the template joetoo_cli_example.conf
#
# BREAK tells display_vars to add a newline spacer in its output
# $LOCALIZED exemplifies use of the joetoo pseudo-boolean data type for POSIX scripts
# $EXAMPLE and $DEFAULTS are pseudo-booleans defined in joetoo_cli_example_local.cmdline_arg_handler
# $INITIALIZED_ME and $SOURCED_ME exemplify use of the joetoo yn data type
# Note how each is named and how these types are prefixed in the varlist, to inform initialize_vars
# and display_vars how to handle them.
# $longone is a long string defined in script_header_joetoo to test and illustrate smart wrapping
# by the smart_wrap_n() function. its name is prefixed "lv." in this localized extension of varlist
# to indicate (long variable), so display_vars will use smart_wrap_n() to display the content of
# $longone (which is long-one btw, not long-gone)
#
# CAVEAT: varlist is instantiated when script_header_joetoo is sourced (above), so it IS safe to add
# variable names to it in a "variables" section at the top of your main script, but note that
# the standard joetoo cli script layout calls app_configure() after that --
# so anything you add to varlist before app_configure will be over-written when app_configure
# calls initialize_var. which sets all bool. to $FALSE, all yn. to "no" and all others to ""
#
# Bottom line: you can append variable names to varlist at the top of your script, but if you do, you
# ALSO need to reassign them AFTER app_configure runs. Thus it is "easier" to just append
# variable names to varlist in the .conf file, which app_configure() loads AFTER it calls
# initialize_vars, but be sure to also assign them, b/c they will not be initialized otherwise
LOCALIZED=$FALSE; INITIALIZED_ME="no"
varlist="${varlist} BREAK bool.LOCALIZED yn.INITIALIZED_ME"

#-----[ functions ]----------------------------------------------------

initialize_command_sequence() # (POSIX) initialize command sequence for joetoo cli framework
{ ics_ret=0
  _ics_FLAGGED=$FALSE
  j_msg -${info} -n -m "creating tempfile for command sequnce"
  cmd_seq_file=$(mktemp /tmp/${PN}.XXXXXX)
  handle_result $? "$cmd_seq_file" '' "$info" || _ics_FLAGGED=$TRUE

  j_msg -${info} -n -p "setting trap to remove tempfile on EXIT"
  trap 'rm -f "$cmd_seq_file"' EXIT
  handle_result $? "trap set" '' "$info" || _ics_FLAGGED=$TRUE

  j_msg -n -p "initializing command sequence"
  num_cmds=0   # global variable holding the length of the sequence
# heredoc needs to be on the left edge; no leading whitespace
# initialize/clear the command sequence file
# format for each line of heredoc content is:
#   command_string${US}description_string
#   where: command_string is POSIX executable
#   and:   ${US} is teletype era unit separator char \037 pre-cooked with printf
#   and:   description_string is a human-readable description of the command
while IFS= read -r _ics_entry; do
      [ -z "$_ics_entry" ] && continue
      # write directly to the file instead of using  ' set -- "$@" '
      printf '%s\n' "$_ics_entry" >> "$cmd_seq_file"
      num_cmds=$(( num_cmds + 1 ))
done <<EOF
start_ssh_agent $SSH_KEY${US}start ssh agent
maybe_create_collection_directory${US}maybe create collection_directory
copy_dirs${US}copy directories
copy_files${US}copy files
show_tree${US}report results as filesystem tree
load_key${US}load ssh key
transfer_results${US}transfer results
unload_key${US}unload ssh key
stop_ssh_agent${US}stop ssh agent
EOF
  handle_result $? "num_cmds: $num_cmds" '' || _ics_FLAGGED=$TRUE

  j_msg -${info} -n -m "initailizing starting_step"
  starting_step=1
  handle_result $? "$starting_step" '' $info || _ics_FLAGGED=$TRUE

  j_msg -${info} -n -m "initializing stopping step"
  stopping_step="$num_cmds"
  handle_result $? "$stopping_step" '' $info || _ics_FLAGGED=$TRUE

  [ "$_ics_FLAGGED" ] && ics_ret=1
  export num_cmds
  export cmd_seq_file
  unset -v _ics_entry _ics_FLAGGED _ics_result
  return $ics_ret
}
# @usage initialize_command_sequence || die "failed to initialize_command_sequence"
# @vars sets global num_cmds, cmd_seq_file
# @vars initializes global starting_step=1, stopping_step=$num_cmds
# @rule creates a temporary file for command execution and sets an EXIT trap for cleanup
# @rule command sequency entry format 'command_string${US}description_string'
# @cont where: command_string is POSIX executable
# @cont and:   ${US} is teletype era unit separator char \037 pre-cooked with printf
# @cont and:   description_string is a human-readable description of the command
# @ret 0 on success; 1 on failure

#-----[ Demonstration Sub-function Stubs ]---------------------------------------------------------------------

# shellcheck disable=SC2329
# shellcheck disable=SC2086

maybe_mkdir() {
  # don't flag; die over error
  _mm_dir="$1"
  _mm_path="/home/${user}/${collection_directory%/}/${_mm_dir}"
  j_msg -${notice} -M $idx_axe -p -n "maybe making directory [${_mm_dir}]"
  if [ ! -d "${_mm_path}" ] ; then
    mkdir -p "${_mm_path}" &>/dev/null ; _mm_result=$?
    handle_result $_mm_result "created" "" ${notice} || \
      die "failed to mkdir -p ${_mm_path}" "$_mm_result"
  else
    handle_result 0 "exists" "" ${notice}
  fi
  unset -v _mm_dir _mm_path _mm_result
  return 0
}

copy_dirs() {
  # flag, but don't die over error
  for ((i=0; i<${#source_dirs[@]}; i++)); do
    _src="${source_dirs[$i]}"
    _z="$(printf '%s' "$_src" | sed 's|^/||')"
    _dst="/home/${user}/${collection_directory%/}/${_z%/}"

    maybe_mkdir "${_z}"

    j_msg -${notice} -M $idx_tree_deciduous -p -n \
      "copying ${BMon}dir${BYon} ${_src}${Boff} content"
    # To copy all files, including those with and without a leading '.',
    # from a source directory (source_dir) to a destination directory (destination_dir)
    # using cp -a, you can use one of the following methods
    #   cp -a source_dir/. destination_dir
    #   cp -a source_dir/{.,}* destination_dir   # didn't work here
    if [ "${verbosity}" -gt "${notice}" ] ; then
      j_msg -${notice} -mp ""   # newline so verbose cp output starts cleanly
      cp -a -v "${_src%/}/." "${_dst}"
    else
      cp -a "${_src%/}/." "${_dst}"
    fi
    _result=$?
    right_status $_result ${notice} || FLAGGED=$TRUE
    # unset loop-local variables for each iteration
    unset -v _src _z _dst _result
  done
  return 0
}

copy_files() {
  # flag, but don't die over error
  # note: ${source_files[@]} entries can include wildcards like '/etc/dir/fn*.txt'
  #   so these must be treated as patterns, not literal filenames. Therefor,
  #   leave ${source_files[@]} unquoted in the for loop top line to ensure the
  #   wildcard expansion is allowed to "word-split" so each file is an iteration
  for source_file in ${source_files[@]}; do
    # use -- (end of opts) to ensure any - in filename isnt interpreted as an option
    _z=$(dirname -- "${source_file}" | sed 's|^/||')
    _dst="/home/${user}/${collection_directory%/}/${_z%/}"
    maybe_mkdir "${_z}"
    j_msg -${notice} -M $idx_fluttering_leaf -p -n \
      "copying ${BCon}file${Boff} [${source_file}]"
    if [ "${verbosity}" -gt "${notice}" ] ; then
      j_msg -${notice} -mp ""   # newline so verbose cp output starts cleanly
      cp -a -v -- "${source_file}" "${_dst}/"
    else
      cp -a -- "${source_file}" "${_dst}/"
    fi
    _result=$?
    right_status $_result ${notice} || FLAGGED=$TRUE
    # unset loop-local variables for each iteration
    unset -v _z _dst _result
  done
  return 0
}

maybe_create_collection_directory() {
  # don't flag; die over error
  j_msg -${notice} -M $idx_axe -p "maybe creating collection directory"
  j_msg -${notice} -M $idx_hammer -p -n "  collection directory: [${collection_directory}]"
  _mc_cd="/home/${user}/${collection_directory}"
  if [ ! -d "${_mc_cd}" ] ; then
    # -- (end of opts) protects against dirnames beginning w -
    mkdir -- "${_mc_cd}" && _mc_result=$?
    handle_result $_mc_result "created" "" ${notice} || \
      die "failed to mkdir ${_mc_cd}" $_mc_result
  else
    handle_result 0 "exists" "" ${notice}
  fi
  unset -v _mc_cd _mc_result
  return 0
}


show_tree() {
  _st_cd="/home/${user}/${collection_directory}"
  j_msg -${notice} -M $idx_splatter -p "please inspect results in [${_st_cd}] ..."
  # -- (end of opts) protects against dirnames beginning w -
  tree -a -- "$_st_cd"
  j_msg -${notice} -mp ""  # severity-aware newline
  unset -v _st_cd
  if [ "$FLAGGED" ]; then return 1; else return 0; fi
}

transfer_results() {
    # sudo -E rsync to access files as root and pass the environment containing SSH_AUTH_SOCK, etc
    # since rsync destination is ${user}@${remotehost}:... it runs as user (who can authenticate)
    local _tr_msg=""
#    local AGENT_ENV_FILE="/root/.ssh_agent_env"  ## shouldnt need to assign - it is in script_header_joetoo_ssh

    # source environment variables to guarantee persistence
    if [ -f "${AGENT_ENV_FILE}" ]; then
        j_msg -${notice} -p -n "sourcing AGENT_ENV_FILE..."
        source "${AGENT_ENV_FILE}"
        right_status $? ${notice} || die "failed to source AGENT_ENV_FILE" 1
    else
        j_msg -${err} "AGENT_ENV_FILE not found"
        return 2
    fi

    for remotehost in "${remotehosts[@]}"; do
        _tr_msg="[ ${bin_rocket} ] ${BYon}Transfer to ${BCon}${remotehost}?${Boff}"
        response=""  # re-initialize yns_prompt global
        yns_prompt "$_tr_msg"
        case "${response:0:1}" in
            [nN]) j_msg -${err} "aborting as instructed"; return 1 ;;
            [sS]) j_msg -${notice} -p "skipping transfer to ${remotehost}, as instructed" ;;
            [yY])
                j_msg -${notice} -p "Validating availability of environment variables:"
                env | grep SSH ; _tr_result=$?
                j_msg -${notice} -p -n "done validating availability of environment variables; result:"
                right_status $_tr_result ${notice}

                j_msg -${notice} -p "Validating accessibility of SSH_AUTH_SOCK"
                ls -l "$SSH_AUTH_SOCK" 2>/dev/null ; _tr_result=$?
                handle_result $_tr_result "confirmed" "" ${notice} || \
                  die "No access to SSH_AUTH_SOCK, or variable is empty" 2

                j_msg -${notice} -p "Validation complete"
                # execute rsync as ROOT (to read root-owned 0600 files)
                # script runs as root, so sudo -E is not needed
                # --rsync-path="sudo rsync" ensures the remote side runs rsync as root
                # Destination "${user}@${remotehost}..." guarantees SSH environment for authentication as ${user}
                # user, remotehosts, sync_root, and collection_directory are assigned in .conf
                rsync -avzhe ssh -A --rsync-path="sudo rsync" \
                  "${sync_root%/}/${collection_directory%/}" "${user}@${remotehost}:${sync_root%/}/"
                _tr_result=$?
                j_msg -${notice} -p -n "rsync command complete; result:"
                handle_result $_tr_result "${bin_face_beam} success" "${bin_explosion} failed" ${notice} || return 1
                ;;
            *    ) j_msg -${err}  "invalid case [${response}] in ${FUNCNAME[0]}"; return 2 ;;
        esac
    done # next remotehost
}
# Note: this transfer_results function is one of the most complex pieces in my joetoo ecosystem, to date
# It coordinates SSH agent persistence, environment validation, interactive prompting, and rsync execution
# under mixed privilege contexts, and error‑aware reporting

#-----[ main script ]----------------------------------------------------
checkroot
separator "$(hostname)" "${PN}-${BUILD}"

message "my PID: $$"

app_configure || die "failed to app_configure"

# re-assign varlist variables appended at the top of the script and thus
# over-written by app_configure
j_msg -${info} -n -m "(re)assigning LOCALIZED"
LOCALIZED=$TRUE
handle_result $? "$(TrueFalse $LOCALIZED)" "failed to reassign LOCALIZED"  ${info}
j_msg -${info} -n -m "(re)assigning INITIALIZED_ME"
INITIALIZED_ME="yes"
handle_result $? "$INITIALIZED_ME" "failed to reassign INITIALIZED_ME" ${info}


d_do show_config ${info}  # show config prior to processing cmdline only at info/debug verbosity
j_msg -${debug} -p "(BEFORE process_cmdline)"

process_cmdline "$@" || die "failed to process_cmdline"

show_config
j_msg -${debug} -p "(AFTER process_cmdline)"

run_sequence "$status_file" "$starting_step" "$stopping_step"
result=$?
separator "$PN-$BUILD" "(Done)"
j_msg -${notice} -m -n "$PN complete. Results:"
handle_result $result "" "" ${notice}
exit $result
