#!/bin/bash
source /usr/sbin/script_header_joetoo
testfiles=$@
#for x in ../init ../validated_functions_header ../testing_functions_header
for x in $testfiles
do
    separator "$x" "checking logical tests in"
#    message_n "[^[ ]: "; grep -n '^\[ ' $x  | ./strip_d_lines.sh; echo
#    message_n "[ [ ]: "; grep -n ' \[ ' $x  | ./strip_d_lines.sh; echo
#    message_n "[ ] ]: "; grep -n ' \] ' $x  | ./strip_d_lines.sh; echo
#    message_n "[ ]$]: "; grep -n ' \]$' $x  | ./strip_d_lines.sh; echo
    message "[^[ ]: "; grep -n '^\[ ' $x
    message "[ [ ]: "; grep -n ' \[ ' $x
    message "[ ] ]: "; grep -n ' \] ' $x
    message "[ ]$]: "; grep -n ' \]$' $x
done
