#!/bin/bash
# Standardized Joetoo Update Sequence (jus), implemented as interactive
#   script with "resume" functionality
# Author: Joe Brendler 14 October 2020
#   20260212 - migrated to joetoo cli framework
# see version_history in ebuild's filesdir

# to do list:
# (1) sort out getbinpkg override of per-package env (don't want gentoo-kernel binpkg for example)
# (2) doesn't use run_sequence - has phase_seq arrays instead...

script_header_installed_dir="/usr/sbin"
header="${script_header_installed_dir%/}/script_header_joetoo"
echo "header: $header"
if [ -f "$header" ]; then . "$header"; else printf '%s' "failed to source header; cannot continue"; exit 1; fi
header2="${script_header_installed_dir%/}/script_header_joetoo_extended"
echo "header2: $header2"
if [ -f "$header2" ]; then . "$header2"; else printf '%s' "failed to source header2; cannot continue"; exit 1; fi
printf '%s' "Checking for header commands (toc, run_sequence) to confirm sourcing"
if command -v toc >/dev/null 2>&1 && command -v run_sequence >/dev/null 2>&1 ; then
handle_result $? "" "" ${notice} ; else printf '%s\n' "Failed; header not sourced; cannot continue"; exit 1; fi
printf '%s' "Checking for headers commands (bs, isfloat_regex) to confirm sourcing"
if command -v bs >/dev/null 2>&1 && command -v isfloat_regex >/dev/null 2>&1 ; then
handle_result $? "" "" ${notice}  ; else printf '%s\n' "Failed; header2 not sourced; cannot continue"; exit 1; fi

# if /usr/share/config/ doesn't exist, fix that
j_msg -${notice} -p -n "looking for /usr/share/config"
[ -d /usr/share/config ]; result=$?
handle_result $result "found" "not found" ${notice}
if [ ! "$result" -eq 0 ]; then
  j_msg -${notice} -p -n "making directory /usr/share/config/"
  mkdir -p /usr/share/config/
  handle_result $? "created" "" ${notice} || die "failed to mkdir -p /usr/share/config/"
fi

#-----[ variables ]----------------------------------------------------

# NOTE: varlist variables are initialized by app_configure() and displayed by show_config();
# the basic set of varlist variables is defined in script_header_joetoo and can be extended
# either in the using script or in its .conf files.
# An example is provided in the joetoo_cli_example script and in the template joetoo_cli_example.conf
#
# BREAK tells display_vars to add a newline spacer in its output
# $LOCALIZED exemplifies use of the joetoo pseudo-boolean data type for POSIX scripts
# $EXAMPLE and $DEFAULTS are pseudo-booleans defined in joetoo_cli_example_local.cmdline_arg_handler
# $INITIALIZED_ME and $SOURCED_ME exemplify use of the joetoo yn data type
# Note how each is named and how these types are prefixed in the varlist, to inform initialize_vars
# and display_vars how to handle them.
# $longone is a long string defined in script_header_joetoo to test and illustrate smart wrapping
# by the smart_wrap_n() function. its name is prefixed "lv." in this localized extension of varlist
# to indicate (long variable), so display_vars will use smart_wrap_n() to display the content of
# $longone (which is long-one btw, not long-gone)
#
# CAVEAT: varlist is instantiated when script_header_joetoo is sourced (above), so it IS safe to add
# variable names to it in a "variables" section at the top of your main script, but note that
# the standard joetoo cli script layout calls app_configure() after that --
# so anything you add to varlist before app_configure will be over-written when app_configure
# calls initialize_var. which sets all bool. to $FALSE, all yn. to "no" and all others to ""
#
# Bottom line: you can append variable names to varlist at the top of your script, but if you do, you
# ALSO need to reassign them AFTER app_configure runs. Thus it is "easier" to just append
# variable names to varlist in the .conf file, which app_configure() loads AFTER it calls
# initialize_vars, but be sure to also assign them, b/c they will not be initialized otherwise
#LOCALIZED="$FALSE"; INITIALIZED_ME="no"
#varlist="${varlist} BREAK bool.LOCALIZED yn.INITIALIZED_ME"
# all jus varlist extension is in jus.conf

#-----[ functions ]----------------------------------------------------

initialize_command_sequence() # (POSIX) initialize command sequence for joetoo cli framework
{ ics_ret=0
  _ics_FLAGGED="$FALSE"
  j_msg -${info} -m -n "creating tempfile for command sequnce"
  cmd_seq_file=$(mktemp /tmp/${PN}.XXXXXX)
  handle_result $? "$cmd_seq_file" '' ${info} || _ics_FLAGGED="$TRUE"

  j_msg -${info} -m -n "setting trap to remove tempfile on EXIT"
  trap 'rm -f "$cmd_seq_file"' EXIT
  handle_result $? "trap set" '' ${info}  || _ics_FLAGGED="$TRUE"

  j_msg -${notice} -p -n "initializing command sequence"
  num_cmds=0   # global variable holding the length of the sequence
# heredoc needs to be on the left edge; no leading whitespace
# initialize/clear the command sequence file
# format for each line of heredoc content is:
#   command_string${US}description_string
#   where: command_string is POSIX executable
#   and:   ${US} is teletype era unit separator char \037 pre-cooked with printf
#   and:   description_string is a human-readable description of the command
while IFS= read -r _ics_entry; do
      [ -z "$_ics_entry" ] && continue
      # write directly to the file instead of using  ' set -- "$@" '
      printf '%s\n' "$_ics_entry" >> "$cmd_seq_file"
      num_cmds=$(( num_cmds + 1 ))
done <<EOF
emerge_sync${US}Sync
update_check${US}Update-Check
emerge_updates${US}Emerge Updates
show_news; maintain_config_files${US}Review news and Maintain Config Files
showelogs${US}Review elogs
handle_dependencies${US}Handle Dependencies
final_phases${US}Final steps
EOF
  handle_result $? "num_cmds: $num_cmds" '' ${notice} || _ics_FLAGGED="$TRUE"

  j_msg -${info} -m -n "initailizing starting_step"
  starting_step=1
  handle_result $? "$starting_step" '' ${info} || _ics_FLAGGED="$TRUE"

  j_msg -${info} -m -n "initializing stopping step"
  stopping_step="$num_cmds"
  handle_result $? "$stopping_step" '' ${info} || _ics_FLAGGED="$TRUE"

  [ "$_ics_FLAGGED" ] && ics_ret=1
  export num_cmds
  export cmd_seq_file
  unset -v _ics_entry _ics_FLAGGED _ics_result
  return $ics_ret
}
# @usage initialize_command_sequence || die "failed to initialize_command_sequence"
# @vars sets global num_cmds, cmd_seq_file
# @vars initializes global starting_step=1, stopping_step=$num_cmds
# @rule creates a temporary file for command execution and sets an EXIT trap for cleanup
# @rule command sequency entry format 'command_string${US}description_string'
# @cont where: command_string is POSIX executable
# @cont and:   ${US} is teletype era unit separator char \037 pre-cooked with printf
# @cont and:   description_string is a human-readable description of the command
# @ret 0 on success; 1 on failure

initialize_jus_variables()
{ ijv_ret=0; _ijv_FLAGGED="$FALSE"

  # source make.conf b/c we can't grep for just parts for systems that set
  #    e.g. PORTDIR="${ROOT}var/db/repos/gentoo"
  for x in PORTDIR PKGDIR DISTDIR PORTAGE_LOGDIR; do
    j_msg -${notice} -p -n "sourcing make.conf in a subshell to set $x"
    eval "$x=$(source /etc/portage/make.conf; eval "printf '%s' \$$x")"
    # use bash indirect expansion ${!x} to get the value of the variable named by $x
    handle_result $? "${!x}" "" ${notice} || _ijv_FLAGGED="$TRUE"
  done

  j_msg -${notice} -p -n "assigning ELOG_DIR"
  ELOG_DIR="${PORTAGE_LOGDIR:-/var/log/portage}/elog/"
  handle_result $? "$ELOG_DIR" "" ${notice} || _ijv_FLAGGED="$TRUE"

  # Set these to defaults, override later with config file
  j_msg -${notice} -p -n "setting starting_step"
  starting_step=1; right_status $? ${notice} || _ijv_FLAGGED="$TRUE"

  j_msg -${notice} -p -n "setting stopping_step"
  stopping_step="$num_cmds"; right_status $? ${notice} || _ijv_FLAGGED="$TRUE"

  j_msg -${notice} -p -n "setting default NOBINFEATURES ..."
  # turn off getbinpkg userpriv and distcc --> override make.conf or package.env
  NOBINFEATURES='MAKEOPTS="-j1 -l1" FEATURES=" -getbinpkg -userpriv -distcc"'
  right_status $? ${notice} || _ijv_FLAGGED="$TRUE"

  j_msg -${notice} -p -n "setting default yes/no variables ..."
  EIX="yes" && DISTCC="yes" && SELINUX_RELABEL="no" && PERL_CLEANER="no" && \
  HASKELL_UPDATER="no" && REGEN_OVERLAY_METADATA="yes" && EIX_UPDATE="no" && \
  NEWUSE="yes" && CHANGEDUSE="no" && \
  PYTHON_UPDATER="yes" && MODULE_REBUILD="no" && \
  X11_MODULE_REBUILD="no" && RKHUNTER="no" && GLSA_CHECK="yes" && EMAINT_CHECK="yes" && \
  continue="y" && RESUME="no" && SYNC="no" && EXCLUDE="" && UPDATE_CHECK="no" && GO_AHEAD="no" && \
  KEEPGOING="yes" && USEPKG="no" && USEPKGONLY="no" && GETBINPKG="no" && GETBINPKGONLY="no" && \
  WITH_BDEPS_Y="yes"
  right_status $? ${notice} || _ijv_FLAGGED="$TRUE"

  j_msg -${notice} -p -n "setting default sync data ..."
  SYNC_TS="${PORTDIR:-var/db/repos/gentoo}/metadata/timestamp.chk" && \
  SYNC_CMD="EIX_SYNC" && MAX_AGE=24
  right_status $? ${notice} || _ijv_FLAGGED="$TRUE"

  j_msg -${notice} -p -n "assigning world file"
  worldfile="/var/lib/portage/world"
  handle_result $? "$worldfile" "" ${notice} || _ijv_FLAGGED="$TRUE"

  j_msg -${notice} -p -n "Setting defaults for non-displayed variables ..."
  KP_FOUND="$FALSE" && updateables=""
  right_status $? ${notice} || _ijv_FLAGGED="$TRUE"

  [ "$_ijv_FLAGGED" ] && ijv_ret=1
  unset -v _ijv_FLAGGED
  return $ijv_ret
}

sanity_check()
{
# veryfy the sanity of the combination of arguments on the command line
if [ "$SYNC" == "yes" ] && [ "$RESUME" ]; then
   j_msg -${err} "Nonsensical option combination: sync and resume"
   useage
   die "correct options and try again"
fi

if [ "$SYNC" == "yes" ] && [ ! "$INTERACTIVE" ]; then
   j_msg -${err} "Dangerous option combination: SYNC and not INTERACTIVE"
   j_msg -${err} "(you should never merge packages blindly, please check first)"
   useage
   die "correct options and try again"
fi

# if both remote/local and local-only are set local-only should over-ride
[ "$GETBINPKG" == "yes" ] && [ "$GETBINPKGONLY" == "yes" ] && GETBINPKG="no"
[ "$USEPKG" == "yes" ] && [ "$USEPKGONLY" == "yes" ] && USEPKG="no"
}

display_config()
{
  j_msg -${notice} -p "${BWon}Using configuration data below: ${Boff}"
  # display standard joetoo varlist
  show_config
  # now package jus config data, by phase
  longest=$(get_longest ${conf_varlist} ${p0_varlist} ${p1_varlist} ${p2_varlist} ${p6_varlist})
  j_msg -${notice} -mp "${BYon}Global Congiguration${Boff}"
  display_vars ${longest} ${conf_varlist}
  j_msg -${notice} -mp "${BYon}Options for Phase 1 - $(_get_entry 1 1)${Boff}"   ## phase 1 - Sync
  display_vars ${longest} ${p0_varlist}
  j_msg -${notice} -mp "${BYon}Options for Phase 2 - $(_get_entry 2 1)${Boff}"   ## phase 2 - Update Check
  display_vars ${longest} ${p1_varlist}
  j_msg -${notice} -mp "${BYon}Options for Phase 3 - $(_get_entry 3 1)${Boff}"   ## phase 3 - Emerge Updates
  display_vars ${longest} ${p2_varlist}
  j_msg -${notice} -mp "${BYon}Options for Phase 4 - $(_get_entry 4 1)${Boff}"   ## phase 4 - Review news and Maintain Configs
  j_msg -${notice} -mp "${BYon}Options for Phase 5 - $(_get_entry 5 1)${Boff}"   ## phase 5 - Review elogs
  j_msg -${notice} -mp "${BYon}Options for Phase 6 - $(_get_entry 6 1)${Boff}"   ## phase 6 - Handle Dependencies
  j_msg -${notice} -mp "${BYon}Options for Phase 7 - $(_get_entry 7 1)${Boff}"   ## phase 7 - Final Steps
  display_vars ${longest} ${p6_varlist}
}


check_timestamp()
{
    # compute age in hours of timestamp on file passed as argument
    # set $SYNC flag to "yes" if timestamp is older than $MAX_AGE allows
    SPM=60   # seconds per minute
    MPH=60   # minutes per hour
    agehours=$(( $(( $(date -u +%s) - $(date -u -r $1 +%s))) / $SPM / $MPH ))
    #if it's old, set SYNC flag
    j_msg -${notice} -p "Portage tree last sync'd $agehours hours ago"
    [ "$SYNC" == "yes" ] && \
        j_msg -${notice} -p "option: sync set by command line" || \
        j_msg -${notice} -p "option: sync not set by command line"
    if [ "$agehours" -gt "$MAX_AGE" ]
    then
        if [ "$GO_AHEAD" == "yes" ]
        then
            # sanity-check: unwise to go-ahead immediately after sync
            #  without checking what will be merged
            j_msg -${err} "You selected option: go-ahead " && \
            j_msg -${err} "but you also set MAX_AGE: $MAX_AGE hours in jus.conf" && \
            j_msg -${err} "The latter would cause this program to sync and then auto-emerge non-interactively" && \
            j_msg -${err} "(you should never merge packages blindly, please check first)" && \
            useage && exit 1
        else
            SYNC="yes" && \
            j_msg -${notice} -p "portage tree sync required by MAX_AGE ($MAX_AGE hours) set in jus.conf"
        fi
    else
        j_msg -${notice} -p "portage tree sync not required by MAX_AGE ($MAX_AGE hours) set in jus.conf"
    fi
}


emerge_sync()
{
    # check to see if portage tree is up to date
    # if timestamp of last emerge --sync is old, do a new one
    check_timestamp "$SYNC_TS"
    if [ "$SYNC" == "yes" ]
    then
        fixpackages   # Perform package move updates for all packages
        case "${SYNC_CMD}" in
            "WEBRSYNC" ) j_msg -${notice} -p "Running emerge-webrsync... " && emerge-webrsync ;;
            "SYNC"     ) j_msg -${notice} -p "Running emerge --sync... " && emerge --sync ;;
            "EIX_SYNC" ) j_msg -${notice} -p "Running eix-sync..." && eix-sync ;;
            *          ) j_msg -${err} "Error: invalid sync option [ $SYNC_CMD ]" ; return 1 ;;
        esac
        [ "${REGEN_OVERLAY_METADATA}" == "yes" ] && j_msg -${notice} -p "Running emerge --regen ..." && emerge --regen
    else
        j_msg -${notice} -p "Not running a sync for portage tree."
    fi
    return 0
}

update_check()
{
  # Beginning with ver 6, just check for major upgrades in key packages
  # (linux-headers, glibc, binutils, libtool, gcc) and branch to full rebuild
#    'sys-devel/libtool'

  key_packages=(
    'sys-kernel/linux-headers'
    'sys-libs/glibc'
    'sys-devel/binutils'
    'sys-devel/gcc-config'
    'dev-build/libtool'
    'sys-devel/gcc'
    )
  KP_FOUND="${FALSE}"

  # first populate the updateables list (note, calling script has already run emerge_sync()
  if [ "$EIX" == "yes" ]
  then
    if [[ "$SYNC_CMD" != "EIX_SYNC" ]]
    then
      ### make sure the index is current
      j_msg -${notice} -p "${BMon}running eix-update to ensure index is up to date${Boff}"
      eix-update
    else
      j_msg -${notice} -p "${BMon}eix-update not needed -- eix-sync should have already done it -- continuing...${Boff}"
    fi
    j_msg -${info} -m "EIX=[$EIX]; assiging updateables with \"eix -u\""
    updateables=($(eix -u#))
  else
    j_msg -${info} -m "EIX=[$EIX]; assigning updateables with \"emerge -puDN world | grep ...\" please wait..."
    updateables=($(for x in $(emerge -puDN world | grep '\[ebuild' | cut -c18- | cut -d' ' -f1); do qatom -F %{CATEGORY}/%{PN} $x; done))
  fi

  # now determine if any key packages are in the updatables list
  updateablecount=${#updateables[@]}
  j_msg -${notice} -p "${BWon}There are $updateablecount ${LBon}updateable installed${BWon} packages:${Boff}"
  for ((i=0; i<${updateablecount}; i++))
  do
    pkg_color="${BGon}"
    # determine if this is a key package using bs() tool in script_header_joetoo_extended
    # note: bs() is "noisy" so quiet it down here
    if [ "$verbosity" -lt "$debug" ] && [ ! "$DEBUG" ]; then
      # do it in a subshell to isolate verbosity setting VERBOSE is for bs legacy code
      ( depth=0; VERBOSE="$FALSE" verbosity=0 bs "${updateables[i]}" 0 "${#key_packages[@]}" "${key_packages[@]}" )
    else
echo "looking for bs"
command -v bs
ls -al /usr/sbin/script_header_joetoo_extended
      ( depth=0; VERBOSE="$TRUE" verbosity=7 bs "${updateables[i]}" 0 "${#key_packages[@]}" "${key_packages[@]}" )
    fi
    if [[ "${result}" -gt 0 ]] ; then KP_FOUND="${TRUE}" ; pkg_color="${BRon}"; fi
    j_msg -${notice} -mp -n "   "; j_msg -${notice} -p "${i}: ${pkg_color}${updateables[i]}${Boff} result: [${Mon}$result${Boff}]"
    if [[ "${result}" -gt 0 ]] ; then j_msg -${notice} -mp -n "       " ; eix -uc "${updateables[i]}" ; fi
  done
  if [[ "${KP_FOUND}" ]]
  then
    j_msg -${notice} -mp ""

    update_message="${BRon}  **  ${BYon}There is a key package to update\n" \
    update_message+="  --> ${BRon}if this is a major version upgrade, ${BWon}exit ${BRon}and run a ${BWon}rebuild ${BRon}sequence ${BYon}(rus)${Boff}\n" \
    update_message+="  --> ${BMon}if binary package server is updated, ${BWon}rebuild toolchain${BMon} and then run ${BGon}emerge -avbgke world --keep-going${Boff}"
  else
    update_message="${BGon}  **  ${BYon}There are no key pakages to update\n" \
    update_message+="  --> ${BGon}ok to continue update sequence${Boff}"
  fi
  j_msg -${notice} -p "${update_message}"
  j_msg -${notice} -p "done with update_check. returning with answer = [ $answer ]"
  return 0
}

emerge_updates()
{
    # assemble the emerge option string and message with baseline options (note --oneshot prevents jus
    #   from just adding all updateable packages to the world favorites file)
    OPTS1="uvD"
    OPTS2=""
    MSG="emerging updates"
    if [ ! "${GO_AHEAD}" == "yes" ]
    then
        OPTS1="a${OPTS1}"
        MSG+=" interactively"
    else
        MSG+=" non-interactively"
    fi
    [ "${NEWUSE}" == "yes" ] && OPTS1+="N"
    [ "${CHANGEDUSE}" == "yes" ] && OPTS1+="U"
    [ "${USEPKG}" == "yes" ] && OPTS1+="k"
    [ "${USEPKGONLY}" == "yes" ] && OPTS1+="K"
    [ "${GETBINPKG}" == "yes" ] && OPTS1+="g"
    [ "${GETBINPKGONLY}" == "yes" ] && OPTS1+="G"
    [ "${KEEPGOING}" == "yes" ] && OPTS2+=" --keep-going"
    [ "${WITH_BDEPS_Y}" == "yes" ] && OPTS2+=" --with-bdeps=y"

    # add --binpkg-respect-use=y and --binpkg-changed-deps=y universally (for now anyway)
    OPTS2+=" --binpkg-respect-use=y --binpkg-changed-deps=y"

    # if verbose, use --verbose-conflicts
    [ "$verbosity" -ge "$notice" ] && OPTS2+=" --verbose-conflicts"

    # if we have an exclude, put it on the end of the command line
    [ ! -z "${EXCLUDE}" ] && OPTS2+=" --exclude ${EXCLUDE}"

    j_msg -${notice} -p "${MSG}"
    # turn on distcc feature, but don't override setting in make.conf or package.env
    if [[ "$DISTCC" == "yes" ]]; then
        MyCMD='FEATURES="distcc ${FEATURES}" '
    else
        MyCMD=""
    fi
    MyCMD+="emerge -${OPTS1} @world${OPTS2}" && \
    j_msg -${notice} -p "${BWon}About to run - [ ${BRon}${MyCMD}${BWon} ]${Boff}" && \
    eval "${MyCMD}" || return 1
    return 0
}

show_news()
{
    # display any news...
    j_msg -${notice} -p "The following news has been generated:"
    eselect news read new
    j_msg -${notice} -mp ""
}

maintain_config_files()
{
    # run dispatch-conf to maintain configs, if this is necessary
    # if the optional go-ahead flag is set, skip this (remind user later)
    if $( [[ -z "$(find /etc/ -iname '*._cfg***')" ]] && \
       [[ -z "$(find /usr/share/config/ -iname '*._mrg***')" ]] )
    then
        j_msg -${notice} -p "No config files need maintenance."
    else
        if [ "$INTERACTIVE" ]     # note: use of the --noninteractive option will cause this phase to be skipped
        then
            j_msg -${notice} -p "Launching dispatch-conf to maintain the following config files:"
            j_msg -${notice} -mp $(find /etc/ -iname '*._cfg***')
            dispatch-conf
        fi  # not go_ahead
    fi  # find/not-find
    j_msg -${notice} -mp ""
    return 0
}

showelogs()
{
    # run show-elogs script to apply important phases from emerge notes
    # if the optional go-ahead flag is set, skip this (remind user later)
    j_msg -${notice} -p "Running show-elogs -l | less ..." && [ "$GO_AHEAD" == "no" ] && show-elogs -l | less && return 0 || return 1
}

handle_dependencies()
{
    j_msg -${notice} -p "\nRunning emerge -av --depclean ..." && emerge -av --depclean
    j_msg -${notice} -p "\nRunning emerge @preserved-rebuild ..." && eval "${NOBINFEATURES} emerge @preserved-rebuild"
    j_msg -${notice} -p "\nRunning revdep-rebuild -p ..." && eval "${NOBINFEATURES} revdep-rebuild -p"
    # recommend you run revdep-rebuild again if it had to
    #   emerge something to fix dependencies
    # TO DO: check if that is the case and ask this only if so
    if [ "$INTERACTIVE" ] ; then
        j_msg -${notice} -mp -n "${BYon}would you like to run revdep-rebuild again, for action? (y/n) ${Boff}"
        read rerun && j_msg -${notice} -mp ""
    else
        rerun="y"
    fi
    case "$rerun" in
        "y") eval "${NOBINFEATURES} revdep-rebuild" ;;
        *) ;; # do nothing
    esac
    j_msg -${notice} -p "\nDouble-checking configuration files now ..."
    maintain_config_files
    return 0
}

final_phases()
{
    # as indicated by option flags, perform additional phases
    if [ "${EIX_UPDATE}" == "yes" ] && [ "${SYNC_CMD}" != "EIX_SYNC" ] ; then
        j_msg -${notice} -p "Running eix-update ..."
        eix-update
    fi

    if [ "${PERL_CLEANER}" == "yes" ]; then
        j_msg -${notice} -p "Running ${BGon}perl-cleaner --all${Boff} ..."
        eval "${NOBINFEATURES} perl-cleaner --all"
    fi

    if [ "${HASKELL_UPDATER}" == "yes" ]; then
        j_msg -${notice} -p "Running ${BGon}haskell-updater${Boff} ..."
        eval "${NOBINFEATURES} haskell-updater"
    fi

    if [ "${PYTHON_UPDATER}" == "yes" ]; then
        j_msg -${notice} -p "Running ${BGon}eselect python update${Boff} ..."
        eselect python update
        eselect python cleanup
    fi

    if [ "${MODULE_REBUILD}" == "yes" ]; then
        j_msg -${notice} -p "Running ${BGon}emerge @module-rebuild${Boff} ..."
        eval "${NOBINFEATURES} emerge @module-rebuild"
    fi

    if [ "${X11_MODULE_REBUILD}" == "yes" ]; then
        j_msg -${notice} -p "Running ${BGon}emerge @x11-module-rebuild${Boff} ..."
        eval "${NOBINFEATURES} emerge @x11-module-rebuild"
    fi

    if [ "${SELINUX_RELABEL}" == "yes" ]; then
        j_msg -${notice} -p "Running ${BGon}rlpkg -a -r${Boff} ..."
        rlpkg -a -r
    fi

    if [ "${RKHUNTER}" == "yes" ]; then
        j_msg -${notice} -p "Running ${BGon}rkhunter --propupd${Boff} ..."
        rkhunter --propupd
    fi

    if [ "${GLSA_CHECK}" == "yes" ]; then
        j_msg -${notice} -p "Running ${BGon}glsa-check -vp affected${Boff} ..."
        glsa-check -vp affected
    fi

    if [ "${EMAINT_CHECK}" == "yes" ]; then
        j_msg -${notice} -p "Running ${BGon}emaint --check all${Boff} ..."
        emaint --check all
    fi

    # clean un-needed package and distribution files, run localepurge
    if [ -d "${PKGDIR}" ]; then
        j_msg -${notice} -p "Running ${BGon}eclean-pkg${Boff} ..."
        eclean-pkg
    fi
    j_msg -${notice} -p "Running ${BGon}eclean-dist -d${Boff} ..."
    eclean-dist -d
    j_msg -${notice} -p "Running ${BGon}hash -r${Boff} for current shell ..."
    hash -r
    j_msg -${notice} -p "Running ${BGon}source /etc/profile${Boff} for current shell..."
    . /etc/profile
    return 0
}

wrapup_reminders()
{ # if not INTERACTIVE, remind user and check for new configs and elogs
  if [ ! "$INTERACTIVE" ]; then
    # remind user
    j_msg -${notice} -p "You ran update sequence with option flag: --noninteractive"
    # check for new config files
    if [[ ! -z "$(find /etc/ -iname '*._cfg***')" ]] || \
       [[ ! -z "$(find /usr/share/config/ -iname '*._mrg***')" ]]
    then
        j_msg -${notice} -p 'You have updated config files pending. You should run "dispatch-conf"'
        j_msg -${notice} -p "Found the following pending config file updates:"
        find /etc/ -iname '*._cfg***' | sed 's|^|    |'
    fi # found new configs
    # check for elogs generated today - start by identifying the most recent
    find_cmd='find "$ELOG_DIR" -maxdepth 1 -type f '       # files in $ELOG_DIR, no subdirectories
    find_cmd+='-printf "%T@ %p\n" | '                      # prepend timestamp
    find_cmd+='sort -n | tail -n 1 | '                     # sort numeric, keep only the last (latest)
    find_cmd+='cut -d" " -f2-'                             # drop the timestamp
    x=$(eval "$find_cmd")                                       # x is the full path name of the most recent file
    x_date=$(stat "$x" | grep "Modify" | awk '{print $2}') # used stat to get the modification date
    y_date=$(date -u +%Y-%m-%d)                            # e.g. 2026-02-12
    z_date=$(date -u +%Y%m%d)                              # e.g. 20260212

    # if the lates file has a modification date of today, consider it new and recommend reviewing elogs
    if [ "$x_date" == "$y_date" ] ; then
        j_msg -${notice} -p "there are new elogs for today ($z_date).  Recommend you run \"echo $z_date | show-elogs | less\""
    fi  # new elogs?
  fi  # go_ahead
  j_msg -${notice} -mp;  j_msg -${notice} -p "Don't forget rebuild modules if needed\n\temerge @[x11-]module-rebuild\n"
}
#-----[ main script ]----------------------------------------------------

app_configure || die "failed to app_configure"

# re-assign varlist variables appended at the top of the script and thus
# over-written by app_configure
#j_msg -${info} -m -n "(re)assigning LOCALIZED"
#LOCALIZED="$TRUE"
#handle_result $? "$(TrueFalse $LOCALIZED)" "failed to reassign LOCALIZED"
#j_msg -${info} -m -n "(re)assigning INITIALIZED_ME"
#INITIALIZED_ME="yes"
#handle_result $? "$INITIALIZED_ME" "failed to reassign INITIALIZED_ME" "$notice"

j_msg -${info} -m -n "main script checking to verify handle_local_arg was loaded"
command -v handle_local_arg >/dev/null 2>&1
handle_result $? '' '' ${info}

initialize_jus_variables || die "failed to initialize_jus_variables"

#d_do show_config "$info"  # show config prior to processing cmdline only at info/debug verbosity
d_do display_config "$info"  # show config prior to processing cmdline only at info/debug verbosity
j_msg -${info} -m "(BEFORE process_cmdline)"

process_cmdline "$@" || die "failed to process_cmdline"

#show_config
display_config
j_msg -${info} -m "(AFTER process_cmdline)"

j_msg -${debug} -p "status_file: $status_file"
j_msg -${debug} -p "starting_step: $starting_step"
j_msg -${debug} -p "stopping_step: $stopping_step"

run_sequence "$status_file" "$starting_step" "$stopping_step"; result=$?
j_msg -${notice} -p -n "$PN run_sequence complete. Results:"
handle_result $result "" "" ${notice}
separator "$PN-$BUILD" "(wrap-up)"
wrapup_reminders
separator "$PN-$BUILD" "(Done)"

exit $result
