#!/bin/bash
# mypatch-config - joe brendler - 4 Dec 2016
# use sdiff to patch my custom config file ($1) in /etc/ (like dispatch-conf)

source /usr/local/sbin/script_header_brendlefly
checkroot

[ $# -ne 1 ] && E_message "Error: mypatch-config requires one argument (configfile)" && exit ${E_BAD_ARGS}

configfile=$1

[ ! -f ${configfile} ] && E_message "Error: configfile [ ${configfile} ] not found" && exit ${E_BAD_ARGS}

sdiff /etc/${configfile} /usr/local/sbin/${configfile} -o /etc/mrg_${configfile}

mv -v /etc/mrg_${configfile} /etc/${configfile}
