#!/bin/bash
/usr/bin/rsync /usr/armv7a-hardfloat-linux-gnueabi/usr/portage/packages/ \
   rsync://thuvia.brendler/armv7a-hardfloat-linux-gnueabi-packages \
   -uaz  --progress --verbose  --exclude "Packages *.html "
