#!/bin/bash
#
# rigorously test whether packages in package.env actually fail to build with distcc
#

for pkg in $(awk '{print $1}' /home/joe/myUtilities/joetoo-base/joetoo-per-package-env/package.env); do
    echo "Testing $pkg"
    emerge -1av --keep-going=y $pkg \
        --config-root=/tmp/joetoo-testroot \
        --root=/tmp/joetoo-testroot \
        --usepkg=n \
        --getbinpkg=n \
        --with-bdeps=y \
        --jobs=1 \
        --quiet-build=n \
        --accept-properties=-interactive \
        --accept-restrict=-fetch \
        --env=test-distcc.conf
done
